### ISSUE TITLE
Running Governance UI Fails With "Cant Resolve ./RegisterGovernance"

### ISSUE THREAD

**Issue by bonedaddy** [solana-labs/oyster#116]
Attempting to run the governance app with `yarn start governance` fails to load the web page as the following error is presented on load

```
./src/views/realm/RealmView.tsx
Module not found: Can't resolve './RegisterGovernance' in '/media/solidity/DATA1/Code/oyster/packages/governance/src/views/realm'
```

**Comment by SebastianBor** [comment]
It looks like an old issue with capitalisation of the file name. I can't reproduce it any longer so I'm crossing this issue.
