### ISSUE TITLE
withdrew RenBTC from solana to ETH but only got Wormhole Wrapped Token, How do I send it back?

### ISSUE THREAD

**Issue by misterbaka** [solana-labs/oyster#142]
Hi,

I bought some renbtc on solana and used wormhole to send it over to ETH. I didnt expect to get a wormhole wrapped token which is useless on ETH. I want to send it back but I dont see a way to bring up that token on the wormhole UI.

token: https://etherscan.io/token/0x18b6b94f185ccf3ca721432a1e9ebf28bb8472c3

Can someone please help?

Thanks!

**Comment by pepip** [comment]
I join with same issue. Help pls

**Comment by pepip** [comment]
interface dont see wrapped erc20 tokens

**Comment by yamijuan** [comment]
@misterbaka we have a fix going to be deployed soon. After that you should be able to see your RenBTC Balance in the ETH Side and be able to transfer back

**Comment by yamijuan** [comment]
@misterbaka the fix is up

**Comment by yamijuan** [comment]
@misterbaka were you able to send back the tokens? if so, could you please close the issue

**Comment by misterbaka** [comment]
yes i was able to send it back, will close.
