### ISSUE TITLE
wMEDIA is not displayed on wormholebridge.com

### ISSUE THREAD

**Issue by DMan326159** [solana-labs/oyster#143]
I sent MEDIA tokens using Wormhole (SOL -> ETH):
https://explorer.solana.com/address/51aeR7a5HJ6Hza4cXgAKnZpBvUhb3LQHwtoYRs8Toms4

Got the tokens wrapped:
https://etherscan.io/tx/0x26319c9fe7b236aaa6e3f71076864478c236180d81f2e2deaa44789c7375ec7a

I want to send them back using Wormhole (ETH ->SOL), but my wMEDIA token balance shows as zero on the website. I have tried both MetaMask and WalletConnect, but the balance still shows as zero.

In reality, the tokens are present in the wallet:
https://etherscan.io/token/0xcb65d3c25e724e36609f9f7921c418af07fac6a1?a=0x6a435e3fd842b76b266208ccbf96febf143d39ed

![image](https://user-images.githubusercontent.com/9461734/127005586-438864f1-ccbb-46b3-ae6b-7f79d4a38e7c.png)

**Comment by bartosz-lipinski** [comment]
I will investigate tomorrow and see what we can do, the balance should show correctly.

**Comment by DMan326159** [comment]
> I will investigate tomorrow and see what we can do, the balance should show correctly.

Thank you! I'm looking forward to it.

**Comment by yamijuan** [comment]
@DMan326159  we have a fix going to be deployed soon. After that, you should be able to see your MEDIA Balance on the ETH Side and be able to transfer it back

**Comment by yamijuan** [comment]
@DMan326159 the fix is up
