### ISSUE TITLE
Wormhole Transfer Lost

### ISSUE THREAD

**Issue by phannypharkle** [solana-labs/oyster#144]
Attempting to send Wormhole RenBTC from Solana to Ethereum. Was able to approve and submit the tx on Solana and then it failed somewhere. I don't see my RenBTC balance on Solana or Ethereum now

https://explorer.solana.com/tx/2eRAzfqkwss2PSvS9mmAAtUD8aHyHAsvTPV2Jkrp9PKCqCSPPn6aduFdGT7FqirvpqpWZRgrGkEVp96BHeNF4XJy

https://explorer.solana.com/tx/5rFXZWyoKGbJzUNyqHg4SmSYS57yUQ4SRCtRF8Y17egs5b9fy2jxukqq9NvPNAS6LNkd3n6Ev2P3bmhxJfHxKwPp

**Comment by bartosz-lipinski** [comment]
We are investigating, looks like for this one transaction: https://explorer.solana.com/tx/2eRAzfqkwss2PSvS9mmAAtUD8aHyHAsvTPV2Jkrp9PKCqCSPPn6aduFdGT7FqirvpqpWZRgrGkEVp96BHeNF4XJy was successful and you might just need to retrigger metamask to ask for redeem from the contract on the eth side. Tomorrow I will post little tutorial how to do that.

**Comment by phannypharkle** [comment]
Thank you! Ill keep an eye out for the tutorial.

**Comment by iamlonga** [comment]
> We are investigating, looks like for this one transaction: https://explorer.solana.com/tx/2eRAzfqkwss2PSvS9mmAAtUD8aHyHAsvTPV2Jkrp9PKCqCSPPn6aduFdGT7FqirvpqpWZRgrGkEVp96BHeNF4XJy was successful and you might just need to retrigger metamask to ask for redeem from the contract on the eth side. Tomorrow I will post little tutorial how to do that.

Hello, I have the same issue with reLuna tokens sent from Sol to Eth. Received some WWT tokens that I can't move back and even see in wormhole UI

**Comment by phannypharkle** [comment]
@bartosz-lipinski Is there a contract that I can just call on Ethereum to redeem from the contract?

**Comment by yamijuan** [comment]
make sure you don't receive some WWT tokens instead @phannypharkle. if that's the case, you can transfer them back

**Comment by phannypharkle** [comment]
@yamijuan I transfer renBTC from Ethereum to Solana, receiving renBTC (Wormhole). I attempted to transfer that renBTC (Wormhole) back to Ethereum but the transaction failed somewhere. I was told in the Solana discord that I should be getting renBTC back and not WWT token. Can you please confirm if this is the case?

**Comment by yamijuan** [comment]
First, look in the UI if the balance is display on the ETH side. Choose the same renBTC token with both of your wallets connected. If you see the balance in the UI but not in your eth wallet, that means you got WWT tokens. After you confirmed that or not we can see what we can do next. @phannypharkle

**Comment by phannypharkle** [comment]
@yamijuan when I was bridging back from Solana, I was able to process all the transactions on Solana but was not prompted to do any transactions on Ethereum. I have 0 balance on Solana and on Ethereum and did not receive any incoming ERC-20 txs for WWT

**Comment by phannypharkle** [comment]
issue resolved
