### ISSUE TITLE
pBTC balance not displaying in Wormhole Bridge

### ISSUE THREAD

**Issue by tomquirk84** [solana-labs/oyster#145]
I believe this is a bridge issue not a wallet issue as I have used two different wallets.

Used the wormhole bridge to send pBTC (ptokens Bitcoin) from Ethereum to Solana

I now have the new pBTC in my Solana wallet - address DCXCyQpqDmedRyi6iF3Ra7V6WiFNFwHftGYeWEdtkCLY
Transaction ID - https://explorer.solana.com/tx/4fdj36EaQsrLwKvMuoufFHb523R3sUbiCbytZ22FU1jXkzvj3CyWniFBXEdVgugo2mRtAA7ekwyNV2PgMqY4tYcu

I wanted to deposit these into the Saber protocol, but realised the pBTC there is actually 'Parrot' BTC, so wanted to bridge them back to Ethereum.

I connected my Sollet wallet with the correct address and noticed that my balance shows as zero in the Wormhole bridge UI

I thought it might be a wallet issue, so I downloaded Phantom wallet, restored from an existing seed phrase and connected this with the same Solana address that the new pBTC tokens were, but the balance still shows as zero.

I believe many others having same issue but with other tokens.
Thank you

**Comment by bartosz-lipinski** [comment]
I will investigate tomorrow whats happening here.

**Comment by tomquirk84** [comment]
Thank you, much appreciated.

**Comment by jason801102** [comment]
I have the same problem!!!
Please help.

I use the wormhole bridge to send pBTC (ptokens Bitcoin) from Ethereum to Solana

I have the new pBTC in my Solana wallet - address 3oD7PhZstGGxcpLfxsZW8iGby8DQjSB3SJy74NPVHhgT

but I can't use the bridge send this new pBTC back to the eth

**Comment by bartosz-lipinski** [comment]
please refresh the page and try again. We fixed one issue with balance for tokens with large decimals that were not defined in Solana token-list.

**Comment by tomquirk84** [comment]
Thank you very much for this.  The balance is now appearing

Can you please confirm once the transfer back to ETH is complete I will have actual pBTC tokens in my ETH wallet?

I’ve been reading a few things about people receiving a wormhole version of ETH tokens which aren’t tradeable.

Thanks



Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by tomquirk84** [comment]
It's all good i sent a small amount first as a test and it's fine.

Thanks very much for this.
