### ISSUE TITLE
pBTC(Ptoken btc) balance not displaying in Wormhole Bridge but displaying pbtc(parrot btc) balance

### ISSUE THREAD

**Issue by jason801102** [solana-labs/oyster#150]
I use the wormhole bridge to send pBTC (ptokens Bitcoin) from Ethereum to Solana  and want to deposit in the saber
I thought it is the same with the pbtc(parrot btc) in the saber  but it isn't 
I now have the pBTC(Ptoken btc) in my  wallet - 

Token Address: 3oD7PhZstGGxcpLfxsZW8iGby8DQjSB3SJy74NPVHhgT
Associated Token Metadata: 9WWoKQbHBTQK3f4cMKEwJxQgpewX9ked8Qk7oepqxXN1

Create Associated Account 
Transaction ID 
https://solscan.io/tx/49CJ9sChERuefffbnwg9o3yReWXpVwQ8USBC35CvTZ19Hqv8EiiHsxsHV7Pg19YWpGrgewGRzQVVKmjmHGzJ7XLh

Signature
49CJ9sChERuefffbnwg9o3yReWXpVwQ8USBC35CvTZ19Hqv8EiiHsxsHV7Pg19YWpGrgewGRzQVVKmjmHGzJ7XLh

Transaction ID https://solscan.io/tx/Zxcm2PGdVfVkd3uAHPM6ang1tzT2qS7tzB4D3oMhqUZZcC63cqthEn28Cov84tzZbfFkuj7JmnfaEUetXS7TSo3

Signature - Zxcm2PGdVfVkd3uAHPM6ang1tzT2qS7tzB4D3oMhqUZZcC63cqthEn28Cov84tzZbfFkuj7JmnfaEUetXS7TSo3

and I had one "fail" Transaction ID 
https://solscan.io/tx/fpQbabBKrUKegR82uxrs9DXqHN2hp9oaDt3obw1u2mf28mUK8dV2n3QNyZrrBvYKLHLzBBg6aVbF2yvgvRQkkEd

Signature
fpQbabBKrUKegR82uxrs9DXqHN2hp9oaDt3obw1u2mf28mUK8dV2n3QNyZrrBvYKLHLzBBg6aVbF2yvgvRQkkEdicon

------------------------------------------------------------------------------------------------------------------------------------------
I wanted to send pbtc(ptoken btc) back to the eth but wormhole cannot get my pbtc(ptoken btc) balance but get pbtc(parrot btc) balance 
so I cannot send it back to the eth 
wormhole should add ptoken btc in the solona site and parrot btc in the eth site.
wormhole think parrot btc = ptokenbtc  cause this error.

plz help me to send my ptokenbtc back to eth thx!

**Comment by bartosz-lipinski** [comment]
please refresh the page and try again. We fixed one issue with balance for tokens with large decimals that were not defined in Solana token-list.

**Comment by jason801102** [comment]
Thanks you very much
It works!

B ***@***.***> 於 2021年7月29日 週四 11:03 寫道：
