### ISSUE TITLE
Received WWT tokens after transferring renLuna from Solana to Eth using Wormhole

### ISSUE THREAD

**Issue by iamlonga** [solana-labs/oyster#153]
Hi, I used Wormhole to transfer renLuna tokens back from Solana to Ethereum but received WWT tokens instead of Luna. Is it some sort of wrapped token i need to unwrap to receive Luna on eth? No Luna arrived to my MM wallet.

Tx - https://explorer.solana.com/address/9Ho9MMdST6zwfNdNpKFSyJA4g1dhgiB5AYmG4bAGrm4C
Screenshot from Debank transactions history - https://gyazo.com/67f71ed6f67e23ee7c4d600a387529f4
WWT deposit - https://etherscan.io/tx/0x280df2e65be8a5950b2848064e65d9dba245bac90e0e63cf82d756785e616d4b

**Comment by bartosz-lipinski** [comment]
Wormhole bridge wraps tokens when they are moved since Luna exists on both chains. Please move your tokens back and use one of the centralized exchanges.

**Comment by iamlonga** [comment]
> Wormhole bridge wraps tokens when they are moved since Luna exists on both chains. Please move your tokens back and use one of the centralized exchanges.

Thanks but how do I do that? UI doesn't show any WWT tokens in my Eth wallet
Screenshot - https://gyazo.com/e3f19dbd6bdf351e0328bf4fd26fa5ea
