### ISSUE TITLE
wLUNA lost when transferred from Ethereum to Solana via Wormhall

### ISSUE THREAD

**Issue by albertjpn** [solana-labs/oyster#154]
After the successful two transfers of wLUNA from Ethereum to Solana via WormholeSolanaBridge, I tried the third transfer of wLUNA from Ethereum to Solana. However, although the transaction at Ethereum succeeded and my wLuna disappeared from my Metamask, wLUNA does not arrive at Phantom Wallet.

Eth tx: https://etherscan.io/tx/0xb62301b4042b7a00f908d9b1021c4665e708840dfd6e4c24e3671510275fa492
My eth wallet: 0x312C3F85a5b73B63583Cf1b7b45b5646A2812C4A
My solana wallet: 6iSLNqHhP3yAJ38Z4g5c6rWpjadyvfGMp326A5QD7qvz

The affected asset is currently worth 63,000USD, which is most of my entire assets of my life and I cannot live without it.

Please help me as a matter of urgency.

**Comment by albertjpn** [comment]
For your information, wLUNA token address of my solana wallet is as follows:
https://explorer.solana.com/address/CR1ktcmr469if8cTDE69tjzDAdF63nnLYjuv4arXTbLB

**Comment by albertjpn** [comment]
Happy to provide screenshots you guys may require.

**Comment by yamijuan** [comment]
@albertjpn were you able to solve this?
