### ISSUE TITLE
Wormhole Transfer Lost

### ISSUE THREAD

**Issue by tosunra** [solana-labs/oyster#155]
Hello , i transfer hbtc from Solana to Eth( wormhole) , i refresh the page, and the hbtc was sent, but i can not get them in my eth wallet. It just show In Process, how can i do now? Please help.

https://explorer.solana.com/tx/2TKPJtV7SGfAZdfXSuaa3zVMKNLo3Kjv1F1w87MBk4nHhQuRTZf7hVXFxSGkzxFYZtFdb76wSUk9KuARmBCFHrQk

**Comment by yamijuan** [comment]
Hi @tosunra according to that tx and this https://explorer.solana.com/tx/3EiKCKsHZTYgNPUT9WwemMEfs1XuLM4KdeTJ97WUq9ccAULyZquyzEdZmdCgDNTUjHC9yXzNszrZUqWoYGKAdqf1  it was successful. Could you check again in the wormhole UI and verify if the balance is shown up?

**Comment by KemarTiti** [comment]
Hey 
Thanks for the feedback - indeed i also got an error message
Can you try with this https://solscan.io/tx/Bq7dRJgSSRuyzszKP5kEFEPLLuaPiSc87CU6fWCCqShXiPbCacPM4G5cAfBnpJbHMUNMTqnCXGGy7e2h6n55Cw2
It just worked on my side

**Comment by leoluk** [comment]
This still open?
