### ISSUE TITLE
USDK from ETH to SOL ("Sign Claim" cancelled manually on ETH)

### ISSUE THREAD

**Issue by Deswiffer** [solana-labs/oyster#158]
Hello, 

I initiated a transfer from solana to ethereum with USDK token. I actually wanted to revert the transfer so I cancelled the claim on ETH side thinking it would revert and give me back the token on solana. However the transfer is still pending and the  UI of Wormhole is telling me to sign the claim (that I already cancelled). How can I claim back my token?

Edit : I found a way, I just refreshed the page of wormhole and could access to my recent transactions, there I clicked on the refresh sign next to the transaction that failed and it worked. Hope this will be useful for other people in the same situation as me.

Best regards,

Deswiffer

**Comment by yamijuan** [comment]
@Deswiffer glad you were able to solve it. Could you close this issue, please?
