### ISSUE TITLE
Wormhole renBTC transfer lost

### ISSUE THREAD

**Issue by bellabartok** [solana-labs/oyster#161]
After making a test tx from ETH to SOL using the wormhole bridge, which showed up in my phantom wallet as "unknown token," I sent renBTC to the same address. The tx is 0xc2a5858925a4184baa3abba4a6ddea28221335ba06b7d2176d9e2f15fe2050eb. I watched it go through all the steps but then it kind of got stuck on the second to last step. After a while I lost Internet and had to refresh the page, but renBTC never made it to my phantom wallet.

Solana discord mod referred me to make a ticket on the certusone page, but they weren't able to help. They said that somehow the bridge either sent or wants to send the coins to a different address. I know for 100% that I used the same address as the test tx. So they suggested I open a ticket here to help gain access to the address the bridge sent the coins to. This is obviously a huge amount and I am incredibly distressed about the matter. Please help!

**Comment by bartosz-lipinski** [comment]
Investigating

**Comment by leoluk** [comment]
@bartosz-lipinski Any update here? Could you perhaps add a one-off page that creates the `FPV4RvtUvShnGAp1ADLPdZfEspj9szobBr64ekYMX4RY` token account using the user's wallet? We can handle everything else.

**Comment by bartosz-lipinski** [comment]
yes, we will have a debug page like that. @bellabartok can we hop on the call tomorrow and debug this together, here is my calendar: https://calendly.com/d/wkch-xdjx/30-minute-meeting

**Comment by bellabartok** [comment]
I'm connected.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by bartosz-lipinski** [comment]
@leoluk, `FPV4RvtUvShnGAp1ADLPdZfEspj9szobBr64ekYMX4RY ` exists now, can you run postVAA again?

**Comment by leoluk** [comment]
That worked!

:tada: https://explorer.solana.com/tx/ygzwLNMNFoV4aGhrSEquXg4cy2jLyCEyt4QxqALW5ddD4CtJVbS55QFqEg3aLNwYzeuyYTU7iAANJuWYNdXFm3N

**Comment by bellabartok** [comment]
What a huge HUGE relief... THANK YOU for following through and helping me recover the coins.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by yamijuan** [comment]
Nice! :tada:

**Comment by yamijuan** [comment]
Hi @bellabartok . could you close this issue? Thanks!.

**Comment by bellabartok** [comment]
Done, thank you.

**Comment by bellabartok** [comment]
Hi guys,

It happened again, though this time when bridging wbtc from SOL to ETH. The tx got stuck at "waiting for guardian" step and I never got the coins in my ETH wallet. I want to participate in the SOL ecosystem but this is just so frustrating. Could you please help me with this one too?

Tx: https://explorer.solana.com/tx/3hYMSQNXcHZjb4rSZCPtTX16qmiL63RdBCTYh3Vk1UiKek2XUKM1Q6uz87yp4oqkPYR9jVYEzJkdQQ9nxbQGEsMf

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by yamijuan** [comment]
Hey, welcome back haha. Reload the page, connect both wallets, select that same token, and look at the bottom table for failed transactions. And click retry

**Comment by bellabartok** [comment]
Thanks, it worked!

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
