### ISSUE TITLE
95 renLuna stuck as WWT on ETH from SOL

### ISSUE THREAD

**Issue by anonintern** [solana-labs/oyster#177]
sent renLuna from sol to ETH and it just shows as WWT and i cant unwrap or do anything with it. any reasons ?

**Comment by yamijuan** [comment]
renLuna is a wrapped token and the wormhole can't unwrap it, you need to send that back and maybe contact solana support to see if there is a workaround

**Comment by anonintern** [comment]
got a fix from the solana discord thanks guys closing this issue!

**Comment by yamijuan** [comment]
@anonintern I'm glad it is fix. Btw i'm the same guy as the discord one

**Comment by blinzi** [comment]
> 
> 
> renLuna is a wrapped token and the wormhole can't unwrap it, you need to send that back and maybe contact solana support to see if there is a workaround

how do you send a WWT token back to phantom?
