### ISSUE TITLE
Luna SOL > ETH not received

### ISSUE THREAD

**Issue by KemarTiti** [solana-labs/oyster#185]
Hey!

I tried sending my wLuna last week from SOL - Eqii6WJ4bLZTvGQYGJnvdoWEMngY87socUiQfQutPvmz - to ETH - 0xBce338B553195f9EF224F7854e89D4aA75c8B83A - but have not received anything.

TX 
https://solscan.io/tx/Bq7dRJgSSRuyzszKP5kEFEPLLuaPiSc87CU6fWCCqShXiPbCacPM4G5cAfBnpJbHMUNMTqnCXGGy7e2h6n55Cw2npJbHMUNMTqnCXGGy7e2h6n55Cw2

Checking metamask it seems i dont have any activity at all relating to this tx...

Thanks in advance for the guidance!

**Comment by leoluk** [comment]
The Solana tx hash is invalid

**Comment by KemarTiti** [comment]
Hey
Thanks for the feedback - indeed i also got an error message
Can you try with this https://solscan.io/tx/Bq7dRJgSSRuyzszKP5kEFEPLLuaPiSc87CU6fWCCqShXiPbCacPM4G5cAfBnpJbHMUNMTqnCXGGy7e2h6n55Cw2
It just worked on my side

**Comment by leoluk** [comment]
Wormhole itself successfully processed the transfer: https://explorer.solana.com/tx/37P26Ba6EpVfjdH7nuAyiyvLuMKLRVywZcvZBCssNGQW7nTY2jUvDdJAJC7GFouwaLiKkdt6KJfXQkfz1kUfXBc4

You likely have to retry the Eth transaction submission via wormholebridge.com

**Comment by yamijuan** [comment]
@KemarTiti do you get any retry button in the table at the bottom of the bridge page? you need to connect and select the token for the table to populate

**Comment by KemarTiti** [comment]
I did not see - will check again today!
Thanks for the info
Will report when tried

**Comment by KemarTiti** [comment]
All good! Indeed ot was showing failed at the bottom
Ty very much!
