### ISSUE TITLE
wWBTC roundtrip

### ISSUE THREAD

**Issue by Zzzoz** [solana-labs/oyster#186]
I did sent over some WBTC from ETH to SOL blockchain.I Received wWBTC on the Solana side.
However I can't do anything with it as there are no swaps supporting the asset as far as I know.
So the best solution seems to sending it back to ETH.
I just can't do that cause also at the wormhole bridge there is no support for the wWBTC.
I received this token:
https://explorer.solana.com/address/qfnqNqs3nCAHjnyCgLRDbBtq4p2MtHZxw8YjSyYhPoL

**Comment by leoluk** [comment]
This doesn't work?

https://i.imgur.com/npumDxJ.png

**Comment by Zzzoz** [comment]
Hey Leo,Indeed,it's totally working now,it recognizing the wwbtc.thx for it:)!It did not worked before,or I totally missed it.Anyway my problem solved:)

**Comment by leoluk** [comment]
Perfect!
