### ISSUE TITLE
Can't get transaction through on v1 wormhole bridge to transfer ibBTC from Ethereum to Solana

### ISSUE THREAD

**Issue by posselts** [solana-labs/oyster#189]
I have been approved for sending ibBTC to Solana(confirmed on Etherscan) but then this pops up and I cannot proceed any further:
Approve assets
✅ Already approved on ETH!
Lock assets
🪓 Waiting for MetaMask transfer approval
❌ Transfer failed!

Is there something different I should be doing on my Metamask or maybe try using a different browser(I am on Brave right now)?

**Comment by leoluk** [comment]
You need to provide more details, like a transaction hash

**Comment by posselts** [comment]
Thanks Leo. It was solved by updating Ledger Live prior to using metamask. This allowed my hardware wallet to sign the approval to proceed. I also used slightly less than my full amount of ibBTC when transferring over to Solana. Not sure if that helped, but some anecdotal advice was provided on Discord. Appreciate your help!
