### ISSUE TITLE
Stuck transaction

### ISSUE THREAD

**Issue by lempire123** [solana-labs/oyster#190]
Hi, I recently tried transferring renBtc via the wormhole. The Ethereum tx has been confirmed, and on phantom as well. however, in the step that says finalizing it got stuck for several hours. not sure what to do.
tx hash: 0x3c8d7c8a228961a5d6b23e13c132ad0c80003ce593f16e1a473fe07fad280bef

**Comment by leoluk** [comment]
This was resolved by resubmitting the VAA to Solana
