### ISSUE TITLE
sending renbtc from sol > Ethereum

### ISSUE THREAD

**Issue by lempire123** [solana-labs/oyster#191]
Hi, tried sending renBTC from sol to ethereum, but it seems to be stuck on : awaiting guardian confirmation.
Here is the tx id: 3HZ6K1DSsstTT9C1DySruEY9dzRrV9NFaFSwnEXbmPHFBieTohQfvSuqjm35pWc7uXr5SJRMN3E5RZsj2QWNvDQn

**Comment by leoluk** [comment]
Account: 4FQAzmq9vpvKww8MBsjS4cvQmVMepfZ2jGuYwjvWBoAC

Digest: 494bb29f9adfb22a84fc67404c6dab0209d601415c0c4a80bbaec4717f92326b

Signed VAA:

> 01000000010d008df59e18e3e67fd32f30bd9e932d7e3fbc4bfa68aff90e7347946f77479e86ac3af799ca4f1be95497c4e25d10ec570d58708d886b9a9e3e5359f063b9a7125a0001e03805ae1d3d37bf5133999d8dda9782f83eb78f6b51bf32d3ceb7ee7c4dafff1f967d2908f24964bc507e166385b7564e3c4241fa5416d96433c778e73b244700025da95fff8091b5b7cdebad3db011c80ee89f4fb0dc8d40641c18ac19932793ea36d5521b291bb87f3ac6feb82107326af5578fd340b82fa221c9fc474e029b7a00033937ad5cb125f07dc4369c12a1500c904bf3f7bd640ef4953cc5d91ed5e24e177cac4f6c521a0ab09a57aae80505ca7b8637a0be47756d1385c640acc4ab9290010539f60041dbd2c0a94d3738c5a93093949abd0b1b9f95bb78305c2fb93ea1db8031e5ef85b3647b25850d1aacfd241a829791fa3c6853202b9a092936bf8d815b01067228b87a9c1312e983a805aa7b8182f01c9fae887d50e3060f72f2cb2a0f4e7a3be5cc687fc9cfa243d343853c3ced816ad4ab557db73577dd4b01b02cb2a937000786ef6a4794c8c54f20e974ef11048879d180981a3b8ca20c9ec835a6e79876821247f7b24ec0af3ddd124742d44aaff121268969a33ad4ac15f41a14c2eb81bf0108116aa93de40ceebe7a1eb758bafa75a8cb2c3c0c3da31fbdf6f468d5e789d2f8590a6eede41d1e99e0eb8df43bcef8d6049a2007f2c010353cd0c6e0a4bdbf56010ab878e9ca6e7d57c50901ba74fca2bbc18dee6bfeb4ab6cff6dad16c91ecf87282a702aa6739b26931540af03c1483b9e35defe548b8587f4e9a9e991fab30970010b86f2dbb94d7cc414c02d599eb626eb92b7b7d04030947b1a132e45fb9ceda52e61c5d556e71e32b87b1c1bedcd89a4fbbed2a4e16e6bdabac44b4908ab3ca02e000da4ac35b5988df21d62d4c41a5bb8e78ed8660c5f7180516ceb4fab10121b61df7c155545920198668e8483eecf9d1223db94dec4e8462d8784215f06370f448400116fe413d68f9ebe2e351b01493a0f46190a1637aced5def0d2e4bdbaef2751b7d30a4d50fa634819786bc9a50830c5125ad0a13d30d4f98b2b2483d695cca3e130012a67216ee097bf230bfb82123e97f633780c7a56ab6d84766a134b90ad022ab477276857e32d46726241dc8c40953fe7302a74377be5862a569a21becaf4a0e1100611dfb291000005793010240be2c90193f9328a5b69b8440baa877108c3e527a30110e41f7275c9c4ff908000000000000000000000000308040f38ed1141c24f93b4d4a16f9f26f70a2f002000000000000000000000000eb4c2781e4eba804ce9a9803c67d0893436bb27d0800000000000000000000000000000000000000000000000000000000040aff9c

**Comment by leoluk** [comment]
Solved by explaining how to manually submit the tx :)

The UI bug still needs fixing @bartosz-lipinski
