### ISSUE TITLE
wBUSD --> ETH Bridge Failure + Lost Tokens

### ISSUE THREAD

**Issue by GoonTrades** [solana-labs/oyster#198]
Hello I was bridging wBUSD from SOL to an ETH wallet. I didn't have any gas in the wallet so I declined the transaction on the ETH side.

I didn't receive my wBUSD back in my SOL wallet - nor did it make it my ETH wallet (canceled TX). Looking at this TX it seems my wBUSD is in a wormhole contract. I have tried checking my balance on multiple DEX's/tools with no luck.

Can someone help me understand what happened. This is the TX where I interacted with wormhole and sent wBUSD.
[https://explorer.solana.com/tx/4FnxxiCkJxR2yJyHBxewMP3btziGJS3a3DzUN9CtWsDB1qAodN9oq9at4TWu76bTbSvQ3YH77Qs2bPPpcUCHLtkE]

**Comment by leoluk** [comment]
Due to its cross-chain nature, it's not possible to cancel a Wormhole transfer - you need to complete it on the Eth side. Try completing your transfer on wormholebridge.com

**Comment by leoluk** [comment]
No response - assuming this is solved
