### ISSUE TITLE
Assets stuck, SOL -> ETH

### ISSUE THREAD

**Issue by jhkk2010** [solana-labs/oyster#199]
Hi, I got wbtc and renbtc stuck after trying SOL -> ETH
Account - https://explorer.solana.com/address/hNMTSgasiZjoanUGpBrzkQN6XoecXR9YqMnj4gzUEGC
The hashes are
https://explorer.solana.com/tx/2s6uSiYr8cLfCXCCRZQWYBgi6PcbuDQ6M3JzEhjsCUhEZsP7bpv5uMHt1fdRA9dBCrDxBRXon2hBzWG5dZjf5grz
https://explorer.solana.com/tx/3Nxmc2YYZ9HLRuHzG5iTKYKpBGXJaedhZSFENiRt66A3HGRVnH7gBcCajfrPiExUEAzkeAXo4Cx2Dh4SD7Qumihr

I think the account were not created

**Comment by leoluk** [comment]
Both transactions were properly processed by the Wormhole network - sounds like client-side submission of the Eth transaction failed.

Try clearing your cache and reloading wormholebridge.com to see if you can retry them in your list of recent transactions.

If that doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

> 3Nxmc2YYZ9HLRuHzG5iTKYKpBGXJaedhZSFENiRt66A3HGRVnH7gBcCajfrPiExUEAzkeAXo4Cx2Dh4SD7Qumihr

Digest: 0266eed2784fd79407466ad41693f51438dc3c83b6e1186b70b3ea46d1d31025

Signed VAA bytes:
> 01000000010d008e648baa71bb7ad5ccf677bb9185eabaff106ddbc245f4326b2d771dc5f2ecd71ad0d9e61dec3af922cc673b7f1694a2d74dcb45c71eb7ae148ab8e9d1d3dd800102e5dbba7bbce3a9b70bbf0225eac96bb34c4cd8ae52f1dda59b9c500813be62b83a379ec4768befe9dcf68e113391bda2c3d5ba1cb03fc68cce66f03178f940e401036eab09e2f44b3e6bee9ecb6ff53f4a887b03b4cd69341507381bc3773f90229b1b447f521b6a5e67be4df76b0823c424d72935db247a70c569c6d6ff6ebf35300104c5035ee575fb296e97892b6ae7a8b61cc9e14c2b246fb920a54c3c38a734f98f53923c6fd8f5dbe9767126c05285b6b53eb018e42e9b3d577ac580dc1ab246da00050922238719cb6efb10dd20343461f228cb2fad415e7f9b6afa4ecddb99598270058176af3dbec40a6763a647715e13511d33b51bf143802d3875fa7fba3d2f7500065763eee1ffc53fe5fc83507fd192e9c0679fbc51fff0f1c57a4e0bea64eda2661701d2d1343154bb1bc12c28aa4583f5da1eacc98a3363adbf693b74c40401bc0107a0dc9cb28f87845ffee21e3857ec16c2839d23688c01084235eec57867a7f6cd3d88bad75febad53ca8a86255b87038a912c32dd56094956d23d8afc07ed433f01082696b0e81b03596fe13d7dabfb16152730608c06b6bd78a2d24a10edfffe77736eb09c19aeb4b0a9258c558eac69660bbe712f865da9d9fafa8f5a7d78ba4ab3010a9ab3625361cdfa3a0055f9e42d5babcea46b305539220daf16116c514e75b75f6949cfe0bed96fc7608add24739c2b32e4bc3027a6fc5cf1794eb90020b256af010bdcc19cd43bb0f69723cc135973a4417ea6d97b320f9476dd4e751d0cf0ef254621429e03978aad737c812d9fd71344fc916b698f9596745936b50f2fa3a4d270010d897bfcd04169ba4c71558d80bb7445a34b2d1239c30aaf61fa673b4ff43cda1423103d5cc0c3bbd3836cb3eedf4b41e5192bccc76abeaed2ec35b0d4e3ec0f01011038db6f837c492650d6ce79e55b5976a5fbb331073a954ba17cd480e4d483c6eb3871572c02727c1aa49b1e0d39f726ed8171d410ac8fc4d167f4715534c86d5e00120960d1860bdb494d279ed49719667c580684084f569d0d430a65459dda9938114aba71db326658d486e228f7b4b9fd333581e02f9ca3471954dff81c6f871be001612254ef10000179590102f00e537f42b4823a5e03f2b43a3f140ae0e5989704d5b6a674ddb678dc0a010c0000000000000000000000003971df12b1f77a9f8b377e55403eee555f44f343020000000000000000000000002260fac5e5542a773aa44fbcfedf7c193bc2c599080000000000000000000000000000000000000000000000000000000000eb4ad6

---

> 2s6uSiYr8cLfCXCCRZQWYBgi6PcbuDQ6M3JzEhjsCUhEZsP7bpv5uMHt1fdRA9dBCrDxBRXon2hBzWG5dZjf5grz

Digest: 4db3f654689fc33cdb675a618b863a30cd4984bed0e4b73f3599d3c38a3c43b7

Signed VAA bytes:

> 01000000010d00de551fcebbcc65d18243638f4edd11a1c5c65484d3bbf230e422e4497253f45f00e4f682e5b4eb20827ff848984d1d7b9766128b683acf355654eb0e39f2b261000340a88e30f9db69dba38df6f7ecc8c51ac7d7bc4321ed3d2a0a4685ee5b32f5546fdcf17eae40843a2e2e6127c2e38d6671f3783f39c8d9a2dd83da998ceec4da00042f256007b7b468ceda38db57b236a93ec9cc7411456639393c8676e8568017eb77ddc0785c83b6aab383dd5876f062c918392ae1fb8f6d5f6c6bfba3325f88490005f8c07cd5c971496f73d841e27b57d57b9ce98d9ad486015227c76b1f6a4f34576ba171afb4d80561859560989bced05696d0401965aaaf5b228697b99ff3f58b0106e398de1b379fc43a71ecd19a5d69d9c77c8fda2f5c59e06a86c2f0192ee42abd7d1200ff0287c06d0ab9165090fec14de8c460d19d9fb12b964faffe5f37ed72000734d5c037800f8384300d117cc22866d4ca7422faf0d7413fc0926476175d9149194ff7536b1032637168a3e3539ad1dbf638741d8bf6c0c8e38e26a1611d261c000890617fa93b56e1d97991aa241d42f148888b2c4b60d34e12f3b0bd246088b9fc07d860e173479e5826f34af70bf94d9ac01fd93795fb9af722f03eaf7287776a010a6820dbc426f87992c8f7748d6d1cff8a5c2fd55abebe733f46dde50d7f7fd2df441f90847662c835b9c726686d7fc96b52a53135d5c406eed49e97cad3d069aa000b55783b56308566e48e65d0475f3ee82f9b5898083e21f3e191bc5d00189a2e607bc382f20776994c53cf4d838e405c24976013b059094d044a3daa3d3e4fa6dc010dc1be45d28832350f55c4acae803951f15327eb630464ca15fcb5f0385f14967953332c1fbe0b812389f25175dc6006b041e741a3231fd9aada71f8a9bb0137e4011071ce64af1bd8d321c278b41b6185670b555735c1421fdb712e992f403308e397533e31828bf95e3d6e1698d67b1cae2e61b773a9bad363be126ea15d859268810111458a24d9ba9d6a0f5821036495822c992de768476bbe1b5faf409add4c009d83253c7da8c3d5a5576099a1a9f3318c06a76194150aec475f1d9ca7bc98c0b3ef00123f48e43efe89236cc14ca21f19e0c74726a6436288ec228edae61274ca9a54bc38bfa0ab21287f141edaaa752fff255bce050387e5f9cb9ae8c015354fea87f90061225a9110000016d301021b17d7a929da5143fe1bdbdc2e838d714b39c43a8b0d88ad0c9e297e7425e4fc0000000000000000000000003971df12b1f77a9f8b377e55403eee555f44f34302000000000000000000000000eb4c2781e4eba804ce9a9803c67d0893436bb27d0800000000000000000000000000000000000000000000000000000000000f4240
