### ISSUE TITLE
BTC lost to Wormhole

### ISSUE THREAD

**Issue by maxitimes** [solana-labs/oyster#201]
Could some one please assist with lost Bitcoin? 

I transferred some BTC from Ethereum to Solana with Wormhole and it is not recognized as BTC on Solana?

tx is here : https://solscan.io/token/3UeKTABxz9XexDtyKq646rSQvx8GVpKNwfMoKKfxsTsF#holders

Token is : 3UeKTABxz9XexDtyKq646rSQvx8GVpKNwfMoKKfxsTsF
Binance Wrapped BTC (Wormhole) (wBBTC)

Can i please have help transferring this back to Ethereum, please add to Solana Side of drop down so i can transfer it back.

Thank you

**Comment by maxitimes** [comment]
Can someone please respond on this issue, The BTC I transferred has appeared in my wallet but is not useable on Solana.  There is nowhere i can see to convert it from wrapped BTC to Solana BTC on Solana and if you see attached, when i try and transferrer it back to Ethereum it doesn't recognise it on the wormhole it came from? My wallet shows Qty but wormhole doesn't see it? ?
![Can-Not-Send-BBTC-Back-to-eth](https://user-images.githubusercontent.com/13531192/131204657-46ad8f5d-8749-4c99-b855-7f2e7b1e07bb.PNG)

**Comment by bartosz-lipinski** [comment]
we are investigating.

**Comment by yamijuan** [comment]
does this still happen if you connect both wallets? @maxitimes

**Comment by maxitimes** [comment]
That worked, when both wallets are connected.  Thank you.

We need an easier way to move assets from Binance Smart Chain to Solana.  Going via Ethereum is not a good experience and has ridiculous Gas fees STILL!

**Comment by leoluk** [comment]
:tada: 

> We need an easier way to move assets from Binance Smart Chain to Solana. Going via Ethereum is not a good experience and has ridiculous Gas fees STILL!

Good news - Wormhole v2 is connected to BSC and Terra in addition to Eth and Solana!
