### ISSUE TITLE
Lost Serum

### ISSUE THREAD

**Issue by adroFPV** [solana-labs/oyster#202]
Hi, 

Can someone support with some lost SRM in the wormhole bridge. 

See previous comments here: 
https://github.com/certusone/wormhole/discussions/338

I have access to my wallet again now, and i tried to run the bridge again but it didnt do anything...

Please help,

Thanks
Adrian

**Comment by leoluk** [comment]
Did you manually submit the VAA as suggested in the other thread?

**Comment by adroFPV** [comment]
No, because I have no idea how or what that is.

Is there a guide?

**Comment by leoluk** [comment]
You need to connect your wallet on https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract, paste the "Signed VAA bytes" from the other thread and execute the contract call:

https://i.imgur.com/gFsSbKR.png

You tried clearing the cache and checking the list of past transactions on wormholebridge.com, right?

**Comment by adroFPV** [comment]
Yeah I cleared cache and tried again but there was no tokens available in
either wallet.

**Comment by adroFPV** [comment]
I get the following error when pasting the VAA:

![SS](https://user-images.githubusercontent.com/69713889/131224275-225b05d0-f2f3-4aa4-8e13-ba97e8e8cc31.jpg)

**Comment by leoluk** [comment]
Try prepending 0x in front of the byte string

**Comment by adroFPV** [comment]
Get a new error now

![SS 2](https://user-images.githubusercontent.com/69713889/131225216-c569a192-cd45-4e15-b021-198ea7c292cb.jpg)

**Comment by leoluk** [comment]
Are you sure Metamask is connected to Ethereum mainnet rather than BSC or another EVM chain?

**Comment by leoluk** [comment]
Please re-open if you still need help
