### ISSUE TITLE
ETH send stuck on SOL side

### ISSUE THREAD

**Issue by skypher** [solana-labs/oyster#203]
https://solscan.io/tx/22617fNDZ4Y3RBKZnAPbGDzjvNE777Z2W7Lmu2zsyZQXVPH7g993zVTwgLdQPWtZ1p9XkB6kiWAgYRFp6XGofhYp

**Comment by leoluk** [comment]
This transaction is using the Sollet bridge rather than Wormhole: https://explorer.solana.com/tx/22617fNDZ4Y3RBKZnAPbGDzjvNE777Z2W7Lmu2zsyZQXVPH7g993zVTwgLdQPWtZ1p9XkB6kiWAgYRFp6XGofhYp
