### ISSUE TITLE
Bridging WETH from SOL to ETH, assets sent from SOL but not receiving on ETH

### ISSUE THREAD

**Issue by bthh** [solana-labs/oyster#204]
Account - https://explorer.solana.com/address/HNTN2ciKwmuYZCrT1rcXbSLbAPbUP8EcJ1xoUd89sF7h
Hash - https://explorer.solana.com/tx/4LV7UngmMdY7DBGf6b5qKqFpNWePo7RnnJBPc3vxosqi5ZDUBkF4TQHyas9kTKQGWLCyx1zVJA4XKxt3tNzjXr7Y

Still nothing showing on ETH, also wondering how long this is supposed to take? Since it was so quick to bridge from ETH to SOL I figured something went wrong. Any help appreciated, thanks!

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the wallet you're using may not have properly sent the Eth transaction. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest: 43165290109b05e49adafbcf928ec84d22e002f473b125477d0f3ffbdf99b757

Signed VAA bytes: 

> 01000000010d001d3697442871d68d14f9e782a49f0408951dad5f6bbe5e136757e825c299031667b957705855527d5298d0e692c7a4de9e79e171d9a4c927e963bc144994784900016cbc83acb53d8567b9b15809483bc14dc0162e0d9ecfc469062f3aa928ba0632783c69c9d820642920b09e2b3c73da7b90f9a37e38621ed36e57847bec39231a0002d7d4196f321f1de9a304c19aee0d10e6d88b1694571cc3024a01fd4d721e9dfa637fd96b53cf00ec7dc982e1ca8ffb2b60f7f9ea22990b8df37628eea8e6c2e500048cb389f1fe011984fd15ed740bac69623476d43020439db361460586d7b4a89951ee30bab6b638395c5e717f835fc2c93556e68163b66b1412e30949cebdf8ca01051371acd9975fb106e4168bbbbbc5e59c1f103f771a2a0baa8c08e269270be75513f9db57eeabd0c7c555766336281a7b3f633bc264feade2c7293c005ea7e49e010606cf5a099d315f33bf8d0149e280dfa97fa415c4e7e7aaa7d1e887cfaa9b0ecb34e9b40bd1190ec68e41f237e396594926bdf1924a4d28901859f1d38d24372501088d815933d06f5b21354797baf453c8240aa73b0a0a84f5ed4890d1d41b4b064022b247648acd44459814446ec3687b47e07408f2dc9bfaffcf625aa8e5684dac010aee3f90df84a420b55e6be5c0a744e88a5d7c4ae1fa7e9427487cb86af7773fd5259c33ddb743292f81990434de21e90e7ad50224963cdedac979c2ee0a7620b3010dc4dd6b3fd04374741570145f2f1390f85afa05c1561488ad8f1a5c4c4832f54410e27134cebfa8d548ac04722fe74b46de358a3cf6744319a7e714c85df16b00010f25e420945737c8cf76afeafd79bee6f871295c49308b704c4d1f83d50756cea72014d158272e9a9fe3b6d0efaf37abdafb61581a3df6529be63e4effc123f48b01105df333cdf56692a627aca6ae15ec74719dce7a48cc5e263d9c851f896889f98d04017d26c9d93731d3f77e3b375ae5826c65f54a3b8283427c074d1771ad82c00011a572dfa7c0da89268327b4cc8a160c4e1d9468401a27c2f36f3679b816125c72692045bd45d85f9262589690da447d4a5c727ce239f8cbc621d4636d840e0ad200129002503710da2f4b46940d38461e9b13a979d1a451043290d9d07148511b1ee322574e181a4ee3fc7257746d03d0bd919f0317ac2eaf6f27515a80fbcc1e2d6901612a31601000000a290201000000000000000000000000d164ff4c786d851a0e2d2fc1bf78370dc9cc1d80e3469f00b6cfacfe65f61496e9681afaa16294259b2c5a5d1735d43eb691e56d02000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2090000000000000000000000000000000000000000000000000000000005f5e100

**Comment by bthh** [comment]
I copied and pasted the signed VAA bytes to the "Write Contract" > "sumbitVAA" but getting an error when I click write:  " Cannot read property 'methods' of undefined"

Do I need to fill in all of the fields in the first 2 tabs as well?

**Comment by bthh** [comment]
asset (address)
0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
amount (uint256)
0.318129
recipient (bytes32)
0xf5813365e84D9391678b0Aa9a97376D157125157
target_chain (uint8)
4dpEcgqFor2TJw9uWSjx2JpjkNmTic2UjJAK1j9fRtcTUoRu
nonce (uint32)
  nonce (uint32) - Not sure about this one
refund_dust (bool)
  refund_dust (bool) - Not sure about this one
lockETH
0.318129
recipient (bytes32)
0xf5813365e84D9391678b0Aa9a97376D157125157
target_chain (uint8)
4dpEcgqFor2TJw9uWSjx2JpjkNmTic2UjJAK1j9fRtcTUoRu
nonce (uint32)
  nonce (uint32) Not sure about this one
vaa (bytes)
01000000010d00e3f02c25f2b8f2835c8cd0273e882fa2b6efd7d8a45ab4bf6182c9804fe2220c036afe75a7c13f362a4210d5e103707b90e70768bcb616aec0f8de414567c0690101e5f38f3202408b394664c59ebbdd0480adc5ed7d4327d634dea86a24242b48fc22d7b16d904d27c402372ce51cc643f0f62343cc170e296eda4d8decd6c58e9b010219fe7218234c22a4dbd6a47734d1662c889f6e442dc3e1dbaf8858c42474330306314b5857aeae0c4da94c83cf5a86608b154c90b9e1ee05e15226fb2a96831a0003899a8a30426ec5d5122cedff5e67852ab8956450ceb3ec24b39928a4c98397922c88c8bde71b440e262a396593ab2eb552152f03c84e2280fe84ac4ed6cc85d5010595ecf7384849f4c9066914d96fe0c7c60d6cef017881d67fec3d2e6086af25a43d48f808e28141832c1ab7e4bcd4640fa0c94e7eb70d110cd1ab8606d7f158ba00060f1a2eac4cfe6228e6e0a5dd9a06e75a23151b6e98ac7c1079d4a1b4dd97c384549593a8563d1b2fdd7abc5db32c82a2572126cfdb85ca2f72994a80cf7885730008950cb712cdc85e5e53815fbc9a92728f623ca7fa41b8861b18c51fb3283ea5967e3de9e217e88be6f48819b7054535722bcd7070bebdb92d2faf1d15f3f3d43900099c054cdb558ea8ce7a2d555ebcb7a1c032e22a13e866976761de4eeed95a67ec3a3248fa472ab64ea19315643a36f2809027be265a380981064780bb6e782139010a97931da0fde8940fcb75d352d4d3876e5fc551d6bcf98e1b292e695a9ccd1ddb1d23351ff4a3d080b54165d661339193b46003e399bd549519fa5ffdf241bf13010d5d7ded89f7038cc5c3fd4bda23a15e31b3c96a8731bf03441e392377fee713184566350986d48fa7aad98db9844aa2fb5ae7c9df2bb32ffb8a521196a21aa6bd011041bc52f86693bcd3dfd700a8c546ee7a0f016d0a5448dcc16de1b8ac46bb26ee1140587818ab174704970f08207253d5af6f81476a89add74fd1be432deda09300118062075d604fe0187702fed90afac3eacd113513084e3a493d8342d962c086a26f5c2fa21714b259b8987db4f7d55389a5da855a1cc5832d536912d2f4a22ae100126a61413316802aee14dbe450822617041eeb85a726608beda1dc7a57f66ff97c3a11b2cc5e4946198a907ddee9e85bef790c745d44fa14eba04caaf3cc828c4b01612a202e1000005f760102d4df50120a293d28a1844aead91c40e7440161b8b9c260952d639e664866a80c000000000000000000000000f5813365e84d9391678b0aa9a97376d15712515702000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2090000000000000000000000000000000000000000000000000000000012f64368
 Cannot read property 'methods' of undefined

**Comment by leoluk** [comment]
No, just submitVAA - single field.

**Comment by leoluk** [comment]
Please re-open if you still need help
