### ISSUE TITLE
WETH/SOL to WETH/ETH Not Showing in Wallet

### ISSUE THREAD

**Issue by andrew4490** [solana-labs/oyster#205]
Sent wWETH from my SOL wallet back to my ETH wallet. Transaction shows success in Phantom, but not seeing transaction on MetaMask for the ETH side.  

https://explorer.solana.com/tx/4mtFDvV1p1SqM3qh416CrFMrrhQ3w3nqhJUb5WaYYL8mtbQvhQEoyD4AybAfxez1AtfVP4qKg3A563N7E9eoP99g

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the wallet you're using may not have properly sent the Eth transaction. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest: 43165290109b05e49adafbcf928ec84d22e002f473b125477d0f3ffbdf99b757

Signed VAA bytes:

> 01000000010d001d3697442871d68d14f9e782a49f0408951dad5f6bbe5e136757e825c299031667b957705855527d5298d0e692c7a4de9e79e171d9a4c927e963bc144994784900016cbc83acb53d8567b9b15809483bc14dc0162e0d9ecfc469062f3aa928ba0632783c69c9d820642920b09e2b3c73da7b90f9a37e38621ed36e57847bec39231a0002d7d4196f321f1de9a304c19aee0d10e6d88b1694571cc3024a01fd4d721e9dfa637fd96b53cf00ec7dc982e1ca8ffb2b60f7f9ea22990b8df37628eea8e6c2e500048cb389f1fe011984fd15ed740bac69623476d43020439db361460586d7b4a89951ee30bab6b638395c5e717f835fc2c93556e68163b66b1412e30949cebdf8ca01051371acd9975fb106e4168bbbbbc5e59c1f103f771a2a0baa8c08e269270be75513f9db57eeabd0c7c555766336281a7b3f633bc264feade2c7293c005ea7e49e010606cf5a099d315f33bf8d0149e280dfa97fa415c4e7e7aaa7d1e887cfaa9b0ecb34e9b40bd1190ec68e41f237e396594926bdf1924a4d28901859f1d38d24372501088d815933d06f5b21354797baf453c8240aa73b0a0a84f5ed4890d1d41b4b064022b247648acd44459814446ec3687b47e07408f2dc9bfaffcf625aa8e5684dac010aee3f90df84a420b55e6be5c0a744e88a5d7c4ae1fa7e9427487cb86af7773fd5259c33ddb743292f81990434de21e90e7ad50224963cdedac979c2ee0a7620b3010dc4dd6b3fd04374741570145f2f1390f85afa05c1561488ad8f1a5c4c4832f54410e27134cebfa8d548ac04722fe74b46de358a3cf6744319a7e714c85df16b00010f25e420945737c8cf76afeafd79bee6f871295c49308b704c4d1f83d50756cea72014d158272e9a9fe3b6d0efaf37abdafb61581a3df6529be63e4effc123f48b01105df333cdf56692a627aca6ae15ec74719dce7a48cc5e263d9c851f896889f98d04017d26c9d93731d3f77e3b375ae5826c65f54a3b8283427c074d1771ad82c00011a572dfa7c0da89268327b4cc8a160c4e1d9468401a27c2f36f3679b816125c72692045bd45d85f9262589690da447d4a5c727ce239f8cbc621d4636d840e0ad200129002503710da2f4b46940d38461e9b13a979d1a451043290d9d07148511b1ee322574e181a4ee3fc7257746d03d0bd919f0317ac2eaf6f27515a80fbcc1e2d6901612a31601000000a290201000000000000000000000000d164ff4c786d851a0e2d2fc1bf78370dc9cc1d80e3469f00b6cfacfe65f61496e9681afaa16294259b2c5a5d1735d43eb691e56d02000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2090000000000000000000000000000000000000000000000000000000005f5e100

**Comment by ssollaa** [comment]
I had the same issue. I never saw anything arrive back on Eth. Was bridging Wweth from Sol to Eth. Approved on Sol side and then I never saw my weth again. I think this is the transaction. Thanks
https://explorer.solana.com/tx/2MGNJ756juGjtNsdyNYC6oMvxxSpbMytViqxkQ7n3nxst25SsuLy7ifwSkvXNLHFycvJTVhNzXZGNe3pZGQvEoma

**Comment by leoluk** [comment]
@ssollaa please don't hijack existing issues - I created a new issue for you

**Comment by andrew4490** [comment]
> The transaction was successfully processed by the Wormhole network, but the wallet you're using may not have properly sent the Eth transaction. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there.
> 
> If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract
> 
> Digest: 43165290109b05e49adafbcf928ec84d22e002f473b125477d0f3ffbdf99b757
> 
> Signed VAA bytes:
> 
> > 01000000010d001d3697442871d68d14f9e782a49f0408951dad5f6bbe5e136757e825c299031667b957705855527d5298d0e692c7a4de9e79e171d9a4c927e963bc144994784900016cbc83acb53d8567b9b15809483bc14dc0162e0d9ecfc469062f3aa928ba0632783c69c9d820642920b09e2b3c73da7b90f9a37e38621ed36e57847bec39231a0002d7d4196f321f1de9a304c19aee0d10e6d88b1694571cc3024a01fd4d721e9dfa637fd96b53cf00ec7dc982e1ca8ffb2b60f7f9ea22990b8df37628eea8e6c2e500048cb389f1fe011984fd15ed740bac69623476d43020439db361460586d7b4a89951ee30bab6b638395c5e717f835fc2c93556e68163b66b1412e30949cebdf8ca01051371acd9975fb106e4168bbbbbc5e59c1f103f771a2a0baa8c08e269270be75513f9db57eeabd0c7c555766336281a7b3f633bc264feade2c7293c005ea7e49e010606cf5a099d315f33bf8d0149e280dfa97fa415c4e7e7aaa7d1e887cfaa9b0ecb34e9b40bd1190ec68e41f237e396594926bdf1924a4d28901859f1d38d24372501088d815933d06f5b21354797baf453c8240aa73b0a0a84f5ed4890d1d41b4b064022b247648acd44459814446ec3687b47e07408f2dc9bfaffcf625aa8e5684dac010aee3f90df84a420b55e6be5c0a744e88a5d7c4ae1fa7e9427487cb86af7773fd5259c33ddb743292f81990434de21e90e7ad50224963cdedac979c2ee0a7620b3010dc4dd6b3fd04374741570145f2f1390f85afa05c1561488ad8f1a5c4c4832f54410e27134cebfa8d548ac04722fe74b46de358a3cf6744319a7e714c85df16b00010f25e420945737c8cf76afeafd79bee6f871295c49308b704c4d1f83d50756cea72014d158272e9a9fe3b6d0efaf37abdafb61581a3df6529be63e4effc123f48b01105df333cdf56692a627aca6ae15ec74719dce7a48cc5e263d9c851f896889f98d04017d26c9d93731d3f77e3b375ae5826c65f54a3b8283427c074d1771ad82c00011a572dfa7c0da89268327b4cc8a160c4e1d9468401a27c2f36f3679b816125c72692045bd45d85f9262589690da447d4a5c727ce239f8cbc621d4636d840e0ad200129002503710da2f4b46940d38461e9b13a979d1a451043290d9d07148511b1ee322574e181a4ee3fc7257746d03d0bd919f0317ac2eaf6f27515a80fbcc1e2d6901612a31601000000a290201000000000000000000000000d164ff4c786d851a0e2d2fc1bf78370dc9cc1d80e3469f00b6cfacfe65f61496e9681afaa16294259b2c5a5d1735d43eb691e56d02000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2090000000000000000000000000000000000000000000000000000000005f5e100

I attempted to write with submitVAA and I'm getting the error: 

invalid bytes value (arg="vaa", coderType="bytes", value="01000000010d001d3697442871d68d14f9e782a49f0408951dad5f6bbe5e136757e825c299031667b957705855527d5298d0e692c7a4de9e79e171d9a4c927e963bc144994784900016cbc83acb53d8567b9b15809483bc14dc0162e0d9ecfc469062f3aa928ba0632783c69c9d820642920b09e2b3c73da7b90f9a37e38621ed36e57847bec39231a0002d7d4196f321f1de9a304c19aee0d10e6d88b1694571cc3024a01fd4d721e9dfa637fd96b53cf00ec7dc982e1ca8ffb2b60f7f9ea22990b8df37628eea8e6c2e500048cb389f1fe011984fd15ed740bac69623476d43020439db361460586d7b4a89951ee30bab6b638395c5e717f835fc2c93556e68163b66b1412e30949cebdf8ca01051371acd9975fb106e4168bbbbbc5e59c1f103f771a2a0baa8c08e269270be75513f9db57eeabd0c7c555766336281a7b3f633bc264feade2c7293c005ea7e49e010606cf5a099d315f33bf8d0149e280dfa97fa415c4e7e7aaa7d1e887cfaa9b0ecb34e9b40bd1190ec68e41f237e396594926bdf1924a4d28901859f1d38d24372501088d815933d06f5b21354797baf453c8240aa73b0a0a84f5ed4890d1d41b4b064022b247648acd44459814446ec3687b47e07408f2dc9bfaffcf625aa8e5684dac010aee3f90df84a420b55e6be5c0a744e88a5d7c4ae1fa7e9427487cb86af7773fd5259c33ddb743292f81990434de21e90e7ad50224963cdedac979c2ee0a7620b3010dc4dd6b3fd04374741570145f2f1390f85afa05c1561488ad8f1a5c4c4832f54410e27134cebfa8d548ac04722fe74b46de358a3cf6744319a7e714c85df16b00010f25e420945737c8cf76afeafd79bee6f871295c49308b704c4d1f83d50756cea72014d158272e9a9fe3b6d0efaf37abdafb61581a3df6529be63e4effc123f48b01105df333cdf56692a627aca6ae15ec74719dce7a48cc5e263d9c851f896889f98d04017d26c9d93731d3f77e3b375ae5826c65f54a3b8283427c074d1771ad82c00011a572dfa7c0da89268327b4cc8a160c4e1d9468401a27c2f36f3679b816125c72692045bd45d85f9262589690da447d4a5c727ce239f8cbc621d4636d840e0ad200129002503710da2f4b46940d38461e9b13a979d1a451043290d9d07148511b1ee322574e181a4ee3fc7257746d03d0bd919f0317ac2eaf6f27515a80fbcc1e2d6901612a31601000000a290201000000000000000000000000d164ff4c786d851a0e2d2fc1bf78370dc9cc1d80e3469f00b6cfacfe65f61496e9681afaa16294259b2c5a5d1735d43eb691e56d02000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2090000000000000000000000000000000000000000000000000000000005f5e100")

**Comment by leoluk** [comment]
Try prepending 0x to the value

**Comment by leoluk** [comment]
Please re-open if you still need help

**Comment by andrew4490** [comment]
When I try to write the contract using the submitVAA option, my MetaMask says that etherscan recommends an absurd Gas Limit (28,400,000) and gives me the message: 

This gas fee has been suggested by https://etherscan.io/. Overriding this may cause a problem with your transaction. Please reach out to https://etherscan.io/ if you have questions.

**Comment by leoluk** [comment]
That is indeed an absurd limit - try a more reasonable value like 300k

**Comment by andrew4490** [comment]
Just attempted to submit with 300K and the transaction failed

On Etherscan: Fail with error 'transfer must be incoming'

Transaction Hash 0x31f335665d6e3b31f91a0bcada4309507388a06511b1830bae58a4c83765e099

**Comment by leoluk** [comment]
Try again with this value:

> 0x01000000010d00ada694384b43d72d4219d584a9c19e7165fd29974d6af3ea250a270dea60b2e7010b1b1d978678608f7efe3dc2450025e5ee4cc8e51d986b45497e2c40948dd90101b8de7564689f371a3765f377f28a534fcb5562327212b340e8ea11018b3e146a7a8e21b060164a85034301c7f89b14e9ecd437d705de682dd0d45f9359cb1c570002ea40f55945d586addcaad5336acf192d92d7f983342f682df077ff25406ada6552cdafdea148cf388f78193b67fbc465e3467d4e5345a1eaddb0cddb2224989e0003fb81a315c6cca40e45436b64a5f1840da5385ca5b84815dae6e43544ef5e7db6545825d5e96c94cbd8ce10d953f45ec922cd2742a84b5e74bbac85360d81c12100050352aeb8711a643a02fca727112ccec0240a310cddd002736133541bcafc64d2788a4c0f3813144a7b1d09f508c2a0d6666ccb295affc34a3631ed503569bd0d00064dd640839db139729c236d22f16c0c92eeb8c80cdff568aa9bfb34afda2bf24c432c32516060b1e51c0281ec862ae7f150252ea408ba4b643d4e45036d4e735901082871bdeca06ce3d950877aa817a9ac597d0c73699c7ecc226d84cad858bb1418078f2e65af6d91eac8670723ccec1363f218b2ced12501aa154e1d5501ce6ae1000a201fda85a75d90644f1f96a4a5906f77e4cac9b1f32e0cdf5f0b1a9c78ef89fe052f8d1ccf1b1331f46d3821a72b81d329eeddb8a2ee97379ea38761fb64c5ec010d678b9b689bd2f8afad3566501686169863cbe933e246d73fd44fb2c5cfd21e8f08a758644dd3a47d0f4a0991279bac6fd26f37dcab60d450474604c0760fdab8000fd579d00f1591afa8d609abc02ffb1ffcd7a71b5e61943b0bd857ef0ff4a5914e59c31b7894bf9e93f3a9f0bbf5fc4e5b477702e8e56b5cdd0d3082ab8de95e720010afea6b580eecdbe852786fb191f1c31df119ad1a92dabe3e1f31ea338b612ae269689f65bea838cb635bb51efc8e8762b72207dc68c6dd92c4ad04e6066409b60111e0d6aafcd00401ad2bbe2cbb3b427a5f39cec4bc37544ae913742cb871932b9d7f5b425947d87c19ec756273575bd4871145b581fa25d1ab8db0016dd619ada5001284f4dd757df5267c7ef2e233abc520a4fb8c5ff0449c156b558170cec90106d01abce836dca0fe7ab451cdb4fb463b72960b75871f70ee5d857e2085e4356a5f01612a317b100000411901020bbc3c2949f78d81af9644a2c6abb132f4cc8ec000f0607caf4e8265d94c1cae0000000000000000000000008f5847bb004e110a8bbc611772886b6de9b67bde02000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2090000000000000000000000000000000000000000000000000000000003473bc0

Sorry for the inconvenience :(

**Comment by andrew4490** [comment]
Perfact, that worked. Thank you for your assistance.
