### ISSUE TITLE
Rejected Ethereum when bridging from Solana to Ethereum 

### ISSUE THREAD

**Issue by PierreMarieRiviere** [solana-labs/oyster#206]
Hi,
I failed to approve the bridging tx when bridging funds from Solana to Ethereum. 

The funds are not in my Solana wallet anymore, but didn't arrived as i did not approve the Ethereum tx in Metamask.

The table to the bottom of the UI is not showing anything (loader keeps spinning) so I can't retry the tx from there. 

How to recover my funds?

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest: 398a41f836ce5ed67468f6ea78c3e8c722412b056100bcee0c2376b117b35114

Signed VAA bytes:

> 01000000010d005d1acdf37381f00d5c02f3e0c2b7f08ac0410e814864248f7b815b126a4a79d020a9a2c5bbced25f7a3bd7bdfd7bf1c1b55d9ccfb3444a5867ade77b46b40ef8000122aa637ad26387e912aa972ac7058f83cb0f67442332b63d99fe218a5ae6b25457d148e9bdab09defa25e36c260bb5e9a9cd2045baebfb9302f8f0537a18466f0103ab4426fe5edb8470ac26edb79563cae5b00f8f91e5986fe517fca416168e0edd33938c69313d93850681b336734e38318ccf6e6e2d8dccc61b45a5ba8f310b1f0005e6892c05c2b191e747629329accbaf4a96f140e1c16ba712bf379f0c2c32300a39023d7e4198ca68b58b791232d949f9360be11f93ca86ea1bd316b7812a25410006092749ec930369fd437a88760d0671d43ed0d80b4ea3414e2c696f4b962cc9b75804496800a4904ac4a75c7e9f3069021201eb7f2590abfcda1761a8c95020050107fa7c578190a89b289baae34a6af7858981e3e828376d4cdb849a14509e8b488f64dfebfc2f409f6296d94feb99cb60f83080e55795b821c5f4a711542c89a8090008ed17e93e0109e09ec76969d989a11a1f39737032df5d54568e8f8ec57b458e5b5f599c095f602cf696d5494c79edba783d0125d6c01f6aaf85c2850a2129bfc0000a522951192e10d738eb7efea3b4d0b33174a3bb3f9f2a1c18afb8d4e633c551f24a515c71d9ebc8b4a1dd264a123982912071314174369e72e92f78b8ae7d434f000be56b936bf6b0c654081805738469980c7c39fac2a23d6d4a055d92a02e2a224a7c1d70fd0ea5b541dbfc3c5c2ac706a09f13770db465a00c1e669f3c11708f44010dd88959ff1a6ea581ba4b67b873e7b6f01cbfef3e8e7ea5400359ee2761ae319732b8c322376f6cc71235c581e2245c2921e9859257b7cb4566a6f7eec295c2d80010318aa2c894982083fce22810e35c893dcbf5817a435024190c3be66d51adb2037802447e16c7a752d45ebd6862034834f1d18efd00d9eb25703afe1a15797e16001114b6a055fdd8ce52e8979022ed9fc68598e2007b71955fe4d0a49d5f478a1a392a7f7c827b2a1dde44138c7fed5153823b716f1bbddab182e2247a666179ab1001126dd8a122700af86c3f353b0ac3d636845fdd9c39f47fe8d5ed4b0f75d052ea904a1dd87dd3bd0fbd70f114cb37da18d41fecdeea52e0c0c70377a08b8158f4c500612a8a8c100000587b0102f9d283c6eda59f293bd082203cd3989f27487eb8d0732df589afffb069c11bd60000000000000000000000002992ae1837fd3e5722495d078b599e0b9c5b2cb5020000000000000000000000005228a22e72ccc52d415ecfd199f99d0665e7733b09000000000000000000000000000000000000000000000000000000013d830e2d

**Comment by leoluk** [comment]
Solved :)
