### ISSUE TITLE
Bridging WETH from SOL to ETH, assets sent from SOL but not receiving on ETH 

### ISSUE THREAD

**Issue by LouisYipKF** [solana-labs/oyster#207]
When i using the wormhole to transferr weth from solana to ethereum, i wrongly kicked the reject bottom of my metamsk(Eth wallet). Now my weth token disapear from my solana wallet, and i dont know how to find it back.

Transaction details: https://explorer.solana.com/tx/23DEjKdmM2N4iEajfeeBMg2C2pFtEPUuHp8g8DhDStFZyxC9F9tExwvS7AD8x7mHe6khJos47KsRmgJUVgGtMkCG

**Comment by LouisYipKF** [comment]
My eth address: 0x8Cd704F7c8D94fFcc486A015dE7006aD4aCE4cfc

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest: 95a59795747b26549d57d61a570a3614e5d1fe06717c5fdb103b0f1569901249

Signed VAA bytes:

> 0x01000000010d009893094d72b07fb8d019f908e5db41b55ef1fef031a64a92794e9f67f8f2613372138d3dbe27c1a63fcbb491d493ee59509d397256d0577c94fd350bf34b6b09010199cdf77ff274341e78288f540186593e3dc6d4821758d533f21c2454695b0b94600a7b1ad5a8e4d8cf7163cee3c4377690fef0bc750ba64221143d3def88aa020102cf6ae18bf78f0c4869fb4bd1b174fea6cf2ecebd04fb6a6c5fe221776150174f0e6d4c4648d84fd003c9e303b47fde6be66160e99438a562ab029bf68df75a24000354f029241ccf49c3b0ee9fd7678eea980c806880c263ce35ed6f4455042a05356304dc836de2e329160d75d197a4d81fcefb331389cbf98eba5b25e0b1df892f01056fc40e47e2cdca7c571075290484e310638e4ff38307a1d05f399d10df59350b3209542f046e00fdcb5a9b5e64f88a001f854eaa55cc13003c74e325029bb5c90007b37acb10e12173b741be4729d45824b92cb300bdb4a5af29f45fcba381f1d6402990d4c654ae841ee69b9434d850b64588c3ea1ce5abe9d9bf60e95d4d1a828e010862a543570543db474fafc3b4e4f53a99cdcd51fb8761c3ce69fa244c35020385597b5a43d0f040c398865a7e3285d84c166d2427e4da302899d7a2bd9c91a496010aec0096e425e82d4ae706ef462da66a4d96e936d218e0383b0f52cd6520448ee3790cff2b24c662b126f66fd707fdbc77bf2bba1295a9a90a8e6f84c47c21b33e000bdd84b68141ebfe943377ca8b6dbbbc8e5f3cc725323e3187930d5cb40b2c18d5087f43be26965a7aa8c2353273be5d3c3ee0fb170c9cf8b2059cf50a06baf410000d115c99655a690b0d5f246a5d55681717bd9bab1698ce58ae506cbfa568f3292b20ae63ff3f0e220c8dc59624b8455b5ebe46519c869436cff7d60037dd222c990010fbba91b2fd0b79fd3e5dab98df646f107e76697741a942df8a6b78b755fe739c52f566980ef0e7c2f44dfc661104cb64fdbe68c4cf2998ab0204aa808234883801113a7e7ed9b60c00d0c4a69afd46a935ea5a6c8b6c0b5d6666db313245fe963ae744bbeabc81e7126ad0f0a861f0aea8a6caa2ca4ad5c07d2704ce27a5360c99950012d8f06df27177db2b6cc0e0a81a1dacb2e947d6d1d53c89504834f540bdcbfb3c2fcda324baa4517cf98058aa8f571897ab460ef1ec8e6bdf81b77dbd4f888eb301612a7a16100000f3010102fbaba74dc76b1f14f1421dea28377f8988a4bf80ad9371c50c685c30b02f6d6f0000000000000000000000008cd704f7c8d94ffcc486a015de7006ad4ace4cfc02000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2090000000000000000000000000000000000000000000000000000000077359400

**Comment by LouisYipKF** [comment]
> The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.
> 
> If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract
> 
> Digest: 95a59795747b26549d57d61a570a3614e5d1fe06717c5fdb103b0f1569901249
> 
> Signed VAA bytes:
> 
> > 0x01000000010d009893094d72b07fb8d019f908e5db41b55ef1fef031a64a92794e9f67f8f2613372138d3dbe27c1a63fcbb491d493ee59509d397256d0577c94fd350bf34b6b09010199cdf77ff274341e78288f540186593e3dc6d4821758d533f21c2454695b0b94600a7b1ad5a8e4d8cf7163cee3c4377690fef0bc750ba64221143d3def88aa020102cf6ae18bf78f0c4869fb4bd1b174fea6cf2ecebd04fb6a6c5fe221776150174f0e6d4c4648d84fd003c9e303b47fde6be66160e99438a562ab029bf68df75a24000354f029241ccf49c3b0ee9fd7678eea980c806880c263ce35ed6f4455042a05356304dc836de2e329160d75d197a4d81fcefb331389cbf98eba5b25e0b1df892f01056fc40e47e2cdca7c571075290484e310638e4ff38307a1d05f399d10df59350b3209542f046e00fdcb5a9b5e64f88a001f854eaa55cc13003c74e325029bb5c90007b37acb10e12173b741be4729d45824b92cb300bdb4a5af29f45fcba381f1d6402990d4c654ae841ee69b9434d850b64588c3ea1ce5abe9d9bf60e95d4d1a828e010862a543570543db474fafc3b4e4f53a99cdcd51fb8761c3ce69fa244c35020385597b5a43d0f040c398865a7e3285d84c166d2427e4da302899d7a2bd9c91a496010aec0096e425e82d4ae706ef462da66a4d96e936d218e0383b0f52cd6520448ee3790cff2b24c662b126f66fd707fdbc77bf2bba1295a9a90a8e6f84c47c21b33e000bdd84b68141ebfe943377ca8b6dbbbc8e5f3cc725323e3187930d5cb40b2c18d5087f43be26965a7aa8c2353273be5d3c3ee0fb170c9cf8b2059cf50a06baf410000d115c99655a690b0d5f246a5d55681717bd9bab1698ce58ae506cbfa568f3292b20ae63ff3f0e220c8dc59624b8455b5ebe46519c869436cff7d60037dd222c990010fbba91b2fd0b79fd3e5dab98df646f107e76697741a942df8a6b78b755fe739c52f566980ef0e7c2f44dfc661104cb64fdbe68c4cf2998ab0204aa808234883801113a7e7ed9b60c00d0c4a69afd46a935ea5a6c8b6c0b5d6666db313245fe963ae744bbeabc81e7126ad0f0a861f0aea8a6caa2ca4ad5c07d2704ce27a5360c99950012d8f06df27177db2b6cc0e0a81a1dacb2e947d6d1d53c89504834f540bdcbfb3c2fcda324baa4517cf98058aa8f571897ab460ef1ec8e6bdf81b77dbd4f888eb301612a7a16100000f3010102fbaba74dc76b1f14f1421dea28377f8988a4bf80ad9371c50c685c30b02f6d6f0000000000000000000000008cd704f7c8d94ffcc486a015de7006ad4ace4cfc02000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2090000000000000000000000000000000000000000000000000000000077359400

Thanks for ur help, I already got back my assets. Thank u so much!!!!

**Comment by leoluk** [comment]
:tada:
