### ISSUE TITLE
Transfer of weth to Solana

### ISSUE THREAD

**Issue by sunmer** [solana-labs/oyster#210]
Trying to transfer weth to Solana, but getting an error message:
![image](https://user-images.githubusercontent.com/1541904/131264454-5f0a9f21-7c13-4b14-bc70-3da13869d3ee.png)

Here's the Chrome debugger output:
![image](https://user-images.githubusercontent.com/1541904/131264492-4407b160-20f8-4c05-be45-22933db7d94b.png)

Does anyone know what might be wrong here?

Thanks!

**Comment by leoluk** [comment]
Do you have enough SOL in your wallet to pay fees?

**Comment by sunmer** [comment]
That was the problem, thanks for a speedy answer!
