### ISSUE TITLE
wwBTC stuck solana -> eth

### ISSUE THREAD

**Issue by nickybard** [solana-labs/oyster#211]
0.1 wwbtc failed on its way from solana -> eth.

balance did not revert in phantom; 0.1 seems to be lost / stuck.

https://explorer.solana.com/tx/u4NvBpRQEnSTMWYqowxUmTG3guYakyosfz8aTRKhyRmKBWjzAn66GMQgfSxx9zfrA3epW7jb69VkCPKHNYnpuqN

**Comment by yamijuan** [comment]
Make sure there is no failed transactions at the bottom of the page (table will render after you connect both wallets and select corresponding token)

**Comment by nickybard** [comment]
Have connected wallets + selected appropriate token. 
Cleared cache as well - the table at the bottom does not render. Stays stuck at the rotating pinwheel.

![image](https://user-images.githubusercontent.com/89751403/131272104-61a741d3-c62a-46b8-b704-8babcf0ef030.png)

**Comment by leoluk** [comment]
@nickybard Any errors in the browser console?

The tx you provided failed, it seems this is the right one: https://explorer.solana.com/tx/4kMVuBX3HxAnQjdeAKABHTjh8EKzFTVewWKpsEjMsPjWkoZxUnjF4QGrVSBSyczdVa3ubZ1UuNzreD1jThmw2p7G

The transaction was successfully processed by the Wormhole network, but the client-side transaction submission seems to have failed.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest: 4df39577fe0c74673bfbd7ff6637aa4fe4a91b818e8adb332d0955c19e3fcb73

Signed VAA bytes:

> 0x01000000010d0075f89f4cae82ad1a7c6fdc7033593c1fcd69fb1f368ba42242b4ba6bfb1ebc2264808ac1cce73ab4406b6d80b0f7b3bc43749e978e16a9d621cf1f06b84d204f00013b76d38081c6129fd273fd08a4b1d4a7e5fe9fa52f22f7fd0d8d1afa2b080af93361d3b723e01d088336d197603cc28cb2d9958dd175c07944561e8b1511522f0002b1146ae5254fb70b2db419a38c4bd4ee1ee6d502cb9319cb5863e5e7e4731e746a13e053c622f3f4549b72f05b9be51b152e7f50519a15b81344775e660ca3f00105fdf257543a7b7cd73608ec446d4c51b793f2b40bf7d2625510534e4949ace7892348954422e33fe092b6522a262e97ca15a4de53b83fa37e3e55ae7ef2d2174a0107b3100c095cf662139a9f7eb8288e23580e79961544400c3b6103858e835bef0131e99d5d0e2e0d0e5095a5788a2498d155a08bd700adcf200e6de4a691d31453010806b09db50ba5d324aff830ac9673ff52ed6275bd82590f9258c790492ea824ec679cbe773e893e43a0150a0e1bf2ee4cd4a2983e69e716d3574ea6b54668f821000956ae611cc7dde2576d47bf04274e5f48c77cbe49de3708c43b8970fc1f677e203ef619cf2b6e980551b833b759c1a1e3ec12f66f4d6fd498c1ab99e082386b21010a46ec8ef7c5f656d86240a51e127551e06fd08716460f7e1a19bdf346fc5196731fcc8727c2f519704180cddb5d415a61a5be12b80c26f5aa076187c2f61d3b64010bd0de59cbfed5e5edf4662b88db06b37882889320f6f02791b79553fffa66f8ab47b501105a360e0d1742bf474c11cd8d7e4760c48cf965503cef7d4e884e910b000d48aa4f2b4120f142d703e5d37e777a47ee4001083af17bc7d771ebd13c8488ea329fc9610b2abbddef692bd778c36532b1b94d1a2af8aa6b1e5a371f18d87bf0001071cfa098bb3cdfcb045d621e7e5662945af6c9c7e018263ee1a6ce8d9ab0d9c40ff66144d950f111d5e845c540a88ac0c8d2fa529815a39fc21f61a130d15b530011ef587d9e3d01d89a4caacb948cbee824cfded5a68024482dae28b3557f824c492a0fdcb56ebb0abd8b61cb00e6f2f7e6bb51dfd0359a704e060b5a255d3f5ffa001294b6e6ca45ed784e5721841529fac42e00b9b7f0121e357d5f04170ebde8863a57cc663d536318ea2bba6f923fc29088e61af6a0feb9898e337aba5e6e2c9df101612bf2271000016a050102430ba88e44fb0dac92e3acf829c8ba1ddc249f5157807fd00aab2252a5982e0f00000000000000000000000079ebd6ca9f685e10ec9f9e205c4f7e685dae8c73020000000000000000000000002260fac5e5542a773aa44fbcfedf7c193bc2c599080000000000000000000000000000000000000000000000000000000000989680

**Comment by nickybard** [comment]
Success - thank yoU!!!
