### ISSUE TITLE
Matic tokens stuck from Solana -> Eth

### ISSUE THREAD

**Issue by sunmer** [solana-labs/oyster#212]
I sent some Matic tokens from Ethereum to Solana without any issues, but sending them back from Solana to Ethereum seems to not have succeeded (tokens don't show up in Metamask again). 

Here's the transaction from Solana to Ethereum
https://explorer.solana.com/tx/8vZeWAHnopteBksiVt8M4MwrUHdqK7h7J8GGsjgMYyxijzMawyXdH4Q4CatXEMFW6J3C8k6qnENL4om9dPUZUHj

And here's the wallet (with no trace of the incoming Matic - only the outgoing)
https://etherscan.io/address/0x53e94c94bba3ff6366e6a745e8367685f0cd889e

**Comment by yamijuan** [comment]
Make sure there is no failed transactions at the bottom of the page (table will render after you connect both wallets and select corresponding token)

**Comment by sunmer** [comment]
I only have successful transactions according to Phantom, wallet address is 64Kd3tzSNDAeZ5X2msZTiJiTox9suhBEqAgkS8vvikCw

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest: e63c2a2c3dcb51825d176e0aa00c4145232e60c3cb0d298542c8d32d6328fde7

Signed VAA bytes:

> 0x01000000010d00ba685f696598a47d65ef92e1672b6106735aa16bfca508c42de26d43c02ad29068f760201f1b91316f67a9fdf29c9a6b3b99224694234eb586218b94540f26f601013bd7a748eea0e47be4c5a3e1b5ec13796393527f37ab3e45cf504bd60b7f49172fd79ce6b2579a667b8774c3616614682c923a11f62e96754a670f929b702b6e01028bf4bf55df26e4da66c8bb533bab08316dcfe10e193808b45b0fdd1ac0cd032748f118d4bd2afe55f1fcfc00004d28755f38a2d9d1549d6f9c26b84a527f2a7b0005b01fb3a2871dc2331aa6d81a211d906adbb470601a6e17de89d07f1146b02eb253e979160eb6ee04a6be18950e92c7cee6c7806ebcc7e5024325d562050b6fa00007b596831cfe84106f31f28a12bb18b4548276bdd4be271623cca253532ffa16323a9df84597cbdff0643848f9b648e7a2079243d0234f5ce93ae6935f1fb300a10008c8c6960715b1c2a52afe644d812461f7e2bd65a8f339960b068a0a3c83e1c887734ff7df2722893c96d9fac838a28a1344fbb879fa37d29fceee63161e78abcc01095238fbda98503d43dcb72c98621fecb09fb2044a4e8eae3ba116ebd884af5e04074a1a37bff3daa1b2304cd54919abb5f17fc4c2a16c28466b6e77a128ffd8fb010a4d3ec92913a7a680e69d8febb0676bd214d41d2a8b515a8f4ce080d0698c8c7b537bd443903b2b9fc02bb98d295e586b790170f41d5a68cd2f3a2d96e42186ac000b9caaece548261bdc6867339fb07925da76691268cdf8b7902d202b225a21c2387a404ff7a60471a9671a993bb25ad9c90ff9ce206ac3b792b988219e8f7daad7000d628bf61fcb7a5d6ca7fb93359f8cb968752f60e53dc444e2fd05dc7f61ca6a537c422488c2f06a6a25fddb207d47e0389c9f4b865fe9c02ec69320b36381fbba01108b9af9d514d8af3b23d61afb519fdb893c6ee39843af6a6f2bb835772deede1417ac4f865ba5edb22c0d9fa5a2db699cd82f37727184681d26fe7677a35c1ce00011b31d86d3f4fa2cb70db63f4c7d8a6527c0ac6e900c091dc79c223472b5ffa01510521977738a49d4610cda72305fe30f279784b3549085d7bc24b8ade021f71a0012a8d1daf928eb3de8456349163a089dba553d58d38e0239707c26e55aafe934dd5130463e168d2ae1277d40c89856b8c9d7d4fe27dafdc433b9f943e5b187f91a01612c060010000177d001024a59f07e8a0aa33e963cafe9544489053dcbe8b0785208110bbf02da29fc1d6300000000000000000000000053e94c94bba3ff6366e6a745e8367685f0cd889e020000000000000000000000007d1afa7b718fb893db30a3abc0cfc608aacfebb009000000000000000000000000000000000000000000000000000000fdc9101400

**Comment by sunmer** [comment]
Thank you, the manual submission seems to have resolved it, although I did have to pay another 59$ in transaction costs: https://etherscan.io/tx/0xde2a25a5294f095f60650b7924ab3c00b779b62c6953340c416a1661307a1b6b

Is this a systemic problem when bridging?

**Comment by leoluk** [comment]
> Is this a systemic problem when bridging?

The fees? Yes, you would've had to pay that either way - the manual transaction is the same the UI would've done.

**Comment by leoluk** [comment]
Solved :)
