### ISSUE TITLE
wBUSD sent from Sol to Eth using bridge stuck

### ISSUE THREAD

**Issue by dylanler** [solana-labs/oyster#213]
Hi,

I sent 9.96 wBUSD from Phantom wallet to Metamask but did not complete transaction on Metamask.  Is there any way I can get back my wBUSD on my Solana Phantom wallet?

Transaction:
https://explorer.solana.com/tx/WztTDxAyBYkJKdvY1e3YhLD8Gxb4xJQUTgtWqhk5WhvTNxoiHGMi9SWs4QfowJyZE6CtR3F3UYtuq9z1xNyxcvi

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest: 089b5be7c746546c4f163f14b46c033218251a95a949703ffc116c7f7676781b

Signed VAA bytes:

> 0x01000000010d00a303d1d62d145d2a080327c4f91069e7df21f450f7d47dd94cf10a02da4b17fb6144427ad20fe306933ca8b933310460a31223ff2007f1f983f64c256d843b1a000155366320796fc0fc2fa3225b4a3bfd2cc13d5205e7325fc9ea30010c65f7b8894c161cb8f9d8cbd47a306af00833b2495ef3206fa069afe0b9e963585470f04f0002b7615a1f4dea5795e5e44d1818523a2dc51cc3bc0cbbcd66eeeda57f89b992fc3331674870b2827a83a98b6a3e207960b4d49decfa787a71bb3fb7c7eae4bbeb01037861175f6d8bafef26c1471f4b74d9c3a78e93c5f506786d0e072d70ca949d542ebae243d31f4afd800a5a6078ae7729c8081697427147f5b4b1fa916269641900052401ff198f2eaa775a47a8d628f3d89ec496d3597f8ec4e5e78680907fc94ed42a7923af40d9f2b19fd49f29c4b528edfea3d9a6550c6696db6ee1ebc3d10a3d0007fc4c98011e6a6d5e207805f1c1803ef290736920f99778826ff5870d15e2db8609b40179e4b82a9e61f4011b873cb5760fd9fa0299999d4fbb134b6e6c6896d10108f18b3e33d14ea0505519765a82c48555b713c324b5b0c483f2b98146a1a4a64b30ce5b59517376b3e07bf16a6336d7381d669e698313e7d08df6f6f7ca9aab27010911ff57441e81c8f58aa37dc41883a22a814e46fc60a44b5dda29c0d7718c6e6e03d424b0246c02accaedb28341566d587c6361acbc227d1fe336167deae2ee84010a53f9fc7f50ae915687b3f1d08eabff4f6a5ec8eed9bad0984664d9ada40b95786b27b64b34ee3d0df97eda409b56ed6b9caf128f3d3b87f900c04331070c5516010bcbc6fe5f306744dc17a9f7b4d7e2c0e67b8ab5acd438d865bebdfe2116d7c22777fa8e503c36170486ccf712884cb43924edcb19e450d87f94e018013605c76c000d52de46dee212312dec0890ba6a2118498bb36384d517ae2745563f94388d17451f641eb04121fc4e5cf44ff09b6421beb32c9a276b90e1b161f1d094f6131bff0011be5d879ecf27e6ea5dd78335cee335642e492b6d96e5b90a6c67cdd7d09954cc0e11f0e689e10877572960300bc90017078882cf15b1506bc5bb4438631cddb0011224b35416fc3149c36db6352818380dc3a1f1795be465e12f94977acd050c52ef30fee5ca5642dbd9605da5cf3e5ca7bb0f077cfdd183e5983c5e85b7de88dd4300612c6cc2100000419f0102b046ea26c1b8935126664623f1d5cb4af1c423c2c2be4bb7bf3288c389f72147000000000000000000000000662c2c14713ace2fff7b147bc9c6edd645fd474a020000000000000000000000004fabb145d64652a948d72533023f6e7a623c7c5309000000000000000000000000000000000000000000000000000000023fe52748

**Comment by yamijuan** [comment]
If you manually rejected the metamask transaction, It cannot be reverted. But you can always complete it later with the UI or as mentioned above ^

**Comment by leoluk** [comment]
No response - assuming it's solved
