### ISSUE TITLE
weth stuck solana -> ethereum

### ISSUE THREAD

**Issue by RaulVolker** [solana-labs/oyster#214]
Hey,
I transferred 1 weth from solana to ethereum (https://explorer.solana.com/tx/47DJFR6C8BaUVFVvy84DKYiUZeccewCuef1a131scN5BsoKMaUMu6rZZqZR6eV5XWiyhEN4RVZNm9WVXUy2EzRWy) 2 days ago 

solana address: 9bPxZHSNc1wTsoXn8YkobXtZJcPJvGqQyuZoYq71u9Zo
erc20 address: 0x44be25318903086ee9b6a163d8c63ac6a8a22a3f

The issue was that there was not enough ETH in my erc20 address to complete the transaction and now the 1wweth is not showing anywhere.

is it possible to retrieve the funds?

help is much appreciated!

**Comment by RaulVolker** [comment]
fwiw, it is not showing under recent transactions and neither in my ethereum nor solana wallet

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest: 1a7096b788d4e788fb66cc238d246b599899d59d66d6a422553de8130ed9b7eb

Signed VAA bytes:

> 0x01000000010d005ce8861666ee3edb55ebe91b470963efbe8927dddd20ad8b8d4005322689eaf42ac51d135b96fbd693b438f7a43f1a04732efc580b2188a531333b0c7614f6650101260422afcee9a2b0d09fbb17bd8563a4699d2c14bbc5b73f2753db8d9907cd1d60f7fcf45f1c3d5faf3a29c8606ead957531bc6b33d8cef9f040b0bb4471f9de0002f708f56ef759a2c23e13fbb5f7b1fa5e8563a3cf62c1669d15dafe2881935799670f142f492c0c84801e958347e9eed121449d010028fdaf6a2b8e21b4385973010380ce3941510cce65bbc0b549f86bc0453f8654167498c77bb471bd59c869074627d52b660514546f406dc16fe3c3a256d0cf88053d28f0d1f30b556ac540a84900058d015f7c21e368fb1f660cffd32a050098ec97985c3e0ad07587f0f18b9ee9c601bc37522ae2c3a674f5f1d6c457a02c536d605f5d1794b98d9fd15450d2cf71000691650d136b3cc440b1bd2c3bddf84d71c2a230871ee5d73c8b453b6b4454d3651e098275bd3ae5c6bca42a412a75dd3f9ea020b16b5194351c151edbf70a345c0108fba5e0fec5045de24479e72cba44ca8cbb1d5d2f2733cdd7055e50d580d67548165cbe18c36c41d8b79bf7898252848dec4b2c51e3af75983ed4dcc0902c9e5501099e0b0e6afebfc02f3b495ad40f554d4972a94fbfc347a7be715dacc906fbd7f62cc8d5599e553cbf4274de53800125b687f32d9e146fca655a004f0d0987c37f000a151c1584c3dc8a91666d4b5255c148a74174dbf9ecdc44e25a9591639cbedd8c1b0b07a62cee6a474c1ed214ed3aa1c4771ae2bca328e8d770089ece33d9aaf8010dc628b986ade738a59700dce40d9f2d0c0b000644e80a73cf87909521cd60c08909d99616723cc7972c984bc732aeaebc5ebb56ae34e82e1069945d45a60f7fb90010ceccc8e44beeb9a5abb1f38fa4650ce4639ea709c9ebbb62f723c2dd76195afc053667a76230e27be5c26348a88879dbcd4127d2529b9bf097c0af88baad0fcb0011f3c173509e996569a616f08a2ff577028c2203431b210b6a0898eb9a1b5d9f157f4281e701e68811243589062bf26a7d59712383fda45de2b00478faa58eecbf00120eb93e5c30d75dd5de87c727dcffe0e4c9f5e59d6ae025f5f02d993d570cf2bb1023b6454600cf639cec8b444d4856262278b6eff66a733ddc50eb5297ce7140006129fe0a10000027d50102afef81747941f0b320743192b0c36cc62ea434048c384a91cbb410c1cbb7d18800000000000000000000000044be25318903086ee9b6a163d8c63ac6a8a22a3f02000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc209000000000000000000000000000000000000000000000000000000003b9aca00

**Comment by RaulVolker** [comment]
the funds don't appear on wormholebridge

on the contract (ive never done something like this), i just write contract, dont fill anything into lock assets / locketh and just copy paste what you put here into submitVAA? what confuses me is that if i paste your text there, it cuts the last parts off. and where do i put the "digest"? i have really no idea how to do this :/

**Comment by leoluk** [comment]
Yes, just the "submitVAA" bytes:

https://i.imgur.com/3gCiGH0.png

The digest is just for reference in case anyone else works on this ticket - it's the unique identifier that can be used to pull the signed VAA from the chain or guardian node log files.

**Comment by RaulVolker** [comment]
https://etherscan.io/tx/0x1f2edc66e261b824f3fe8cc4cde

i dont know how, but apparently it worked, tyvm!

the weird thing is that i didn't try it around that time at all, i tried it 4hours before and i always got failed transactions. but apparently it eventually worked and i got the funds now. thanks!

**Comment by leoluk** [comment]
:pray:
