### ISSUE TITLE
wbusd stuck sol -> eth

### ISSUE THREAD

**Issue by ptnebel** [solana-labs/oyster#215]
I submitted a request for 9992 wBUSD from solana to ETH but then did not have enough gas to approve the ETH side transaction. Funds appear to be stuck now.  I have attempted to resubmit the transaction, but that did not approve.  

Addresses:
ETH - 0x1D2226d37529729EB4c36c14F91cec723e5582b6
SOL - 6CavMETv51AFpZFpXKhmiLjUp5H8MYWptV4BGNBHCYJh

Recent transactions (the most likely failed bridge one on the top)
4ewPnjkzzzo2Z8MBZSqmhupMuu8dQxnBrJ5zwkaVLKdjDiRUs7Zs9J257F8kKn2YVBBWjfS2uty4K8UWg4GukRTn
2eBsG3R1RL874nWuweJpy4dgooLSj1PN2zttndGfzhatdZmQ7pkQmumNxfZmfjwpMw9Fiq4wr1o2qnHbJHpanX4c
4jc2cBiWxP53asvmyJoATi9yQs4UcR7KoDAdrBgP1YB5caAjsFGpnJTppiZbQvKmene9p38FwJEnQNyEjLZhnowC

Can you please help me recover my funds?

**Comment by leoluk** [comment]
You should be able to retry the transaction via the "recent transactions" list on wormholebridge.com. Reload the page and make sure both wallets are connected.

**Comment by ptnebel** [comment]
the recent transactions come up empty.

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network. If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest: ef83a4fc39a1980888a67a0c868d9c4a5f5df332d396c055f60a093e116dad52

Signed VAA bytes:

> 0x01000000010d00a80313de671baa2a7a1c95b5539fe1a49d06e877661970e5c389e0a3e740ec651c4a58dddfb222e6e869eb63a1db51fcc68e737075e4299cf3a4a306b83be1f2000175a97d9248402ab2a6c33c06eb5dda0aa9f7f791f312c26965896dc9a592d21f70030d3e5ef874362630854745b5b5a84b904314f64faa112864db06337d4e1f010245b745692114542357dfb3f906f01b671af0a8c757a5d00b5dc73ab0af5af4054e2f6d48c62723b1192cf509adb0494be9b926c6e63f14e846504bd53398048900049d2bffb69a7a8ae4c6796b49e548116e74850b604346c14f7ae187f338a9b5f728cb4694f95b1369ca0506839403003b53cd4f44564ffb074a4ea31ae7b5d7770105c82498dc073fef4dce7836945a0f56d01700f86a6e2a11ab5389f3133132f3b917be9e0951f5e302073558c74754129adc722b07f4fb552a6819754dfc620b1d00060b70bbb76035aaeaa9d1385dcf559857e0fa0af64e6982e20b07bbcbafec719d6be5f39e1891e082e9022bc0f1ee87f3a7da3aa5c0020b86306bbfe770e14f4100071e093db82a514a10d896cc0ca9df3fbf8fe20be4301e1bacac4a0a359755ce9430d9b45421eaffa2114e20729003d779444063133db2769ca27881c1ca1173460008c53b4bdc65493c21ddb8f1762d230cee681175023b671a09214a8c68aa2cecf138f94cc8a88b5fbc7adf2c4d6553efc3fb79517225e94b17f6efcc7b434d7af4000abb686ea4c36c32914b7cc4e9afb240b3738ce2d2c5739e0f5f398f554e7f0d015574abfd2b9d0b2ec31ffa18122bfcf87636af7265459ee1a50b865cb6802675000d45a384c010ee982c99d4ed0c14f3552f4e0180b0e9b9ae29e4e96c7118b7290d2a8170c62f408e63a959ea0db4d2ef06a7bcdd9aa10b228334e6e0af079791ef01109e98ff4c10eb7a5712e51ef4d86a735722a94c4693457f667dc5f446359bb21b0b93ac195cea3b587350499c985b518d0eee03e0fca64724917540af03a5cbad01116b95aef42055bb2677deda5ac59ca2d3247f475dc644f04a7d6c5c7777d8acfe5486e63df608f57296ec8305c8bde94626a6cc6a7dc0c7a805f83b7717cd0a6e0112b45b1e5865dafb6fec7bbcb876852b99a7bb3d263e5cc4cab79b4b26a3a212c5610579377d1b6316b1b516e0875ba994f28b02f11e232bb394fe1f99825bf52900612d23b510000042060102083bbfc4dd25146f3d82086686362d5e4d6853059c4c6f36642df76d3f26594f0000000000000000000000001d2226d37529729eb4c36c14f91cec723e5582b6020000000000000000000000004fabb145d64652a948d72533023f6e7a623c7c530900000000000000000000000000000000000000000000000000000916719c5000

**Comment by ptnebel** [comment]
thank you, that resolved it.

**Comment by leoluk** [comment]
:tada:
