### ISSUE TITLE
wSPI sent to Metamask, I rejected the gas fee by mistake and now the tokens have vanished.

### ISSUE THREAD

**Issue by oirman** [solana-labs/oyster#216]
Hey there,

So I was testing out the Wormhole in a bid to escape high gas fees, realised I was in a bottle neck and tried to move them back.  I rejected the gas fees and now the SPI is nowhere to be seen even though the transaction was successful.

Any help very much appreciated!!!!

Solana Wallet:
HBaZTYaAjMDcGoqg91VreCniLXXXitjLrdGGMhosS9Fe

Metamask Wallet:
0x11D82b9F5d79B8288f0410d101a6Dc3AA7af054f

https://explorer.solana.com/tx/53bVeJ3ZsD1tTSL6SeSPivfXnwUnG7QbQYwxQuvZgKsgTE9q6Mf2h21vaseviM8DrpffFHwvLEzghEey1kA21DNk

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest: 9a106fa1968854cdfd49da6cda7c05683e0d0866354d198f3dcdd1579d8048f2

Signed VAA bytes:

> 0x01000000010d0001fe031b7c0b5e801f0bcd25e540f62455e906092ee6a8694412423dc7e2c10c7ebcee7eee573e3e7d9151fa7eaffa87e8841b666a573765a488c50b5b1b58e20001ee0313e7504e781d47195b2f16481421d3b6f23ecbf6a84af0b768fa1c51ddd70226cafdd5067c458e4b430e38b910c0de190910f8ec3720cb7388d44ed84aa20102ce45ae3b710e7c710c6a891bb2da0a2af12cc0aae13fe50b6ff956b8302e725b3cea3568b3b5560f14d0699ccc5af38de22a7ef1c35428ce2e6a7937564c5716000451ea6557bee5d5b72ddb2bfa473f0e45aa01be7cfa751f2ad490e6a4942edf2c698a5ca8a2cfeb89af11686d0eee75955fe95610a067fb5c673e0d33515641b500051297777e3ee43ee624f32d0e8f2b291d51b4b2c05abed8c13866f9174bb975964c18f1742ac441769c19a91e00921a9868e2a13dd94cbd92ad80f23e4643e7640107936a36f98b45d34901733a5007dbe56dc383a0ca0761bbc47a1c7dfdecd71e2c5aad04f109aa252372a038d2f60d036cad565293c266930a413b91dcb7417c440008e657a80fd2cc6f3e453b72ade737122f530b41812cc75a4207c74a8d2ca75efc0c1d1aa99e73cb598763801ef786222a99ca99fd1b496965acb1bf73e3cca2e4010acedf3fa47d4cc973e7ed4022cb5122828c866ca5521c0299b55df3edf56b27ca0feaefa7cdf3b446f5367d2b7f31dbcb5a928c40922937634c57dcea06251ad6010bc5e3a7698d0e3f47eaf2ee3afb5167f285870d3358527f7e4e0269c7835e443d0060535c374bc272d698e6ed273f54f650b8c3415a78681bc301f3ec5ee130fd000d156356ba5f930391c0d5be6e4b42b166ee0f648bddfab0d84c635fd2cf33663a45ffca1b19315e1636922fca1cfeda8113e29c3505c1aba2fbf944df6fe5701f01109ea39559b96b22de54e333823acaf6f4d39bfd46267eac27825cf3a71905c368384a227acec71c667a4089b164869b2b2a6f0c55e65d63cf8e3ee5fdd7fd13420011674b2ff927aa5d4662ba0f197ada7c3d3987d48553e884aeb72334963eddfaa03eb6b4d3709d11ab5baf16b94196f3cd20df92365697508cb766d3312fb9c7fe011216246fab2464f7ebcf6c82f46ddaf71cf469ae5188eeeb9b70008c02cf388bd021d53fec3b0de392c670b6d769b6f07ed9b51208aaf34a76386329c75fcdd14001612d441310000106a40102c81b379533bbf5e23d2ec0ab293b1fa878ff9d83e1801923dc4777c19989fb5f00000000000000000000000011d82b9f5d79b8288f0410d101a6dc3aa7af054f020000000000000000000000009b02dd390a603add5c07f9fd9175b7dabe8d63b70900000000000000000000000000000000000000000000000000000026e1f9c600

**Comment by leoluk** [comment]
No need, glad to help
