### ISSUE TITLE
wdai stuck sol -> eth

### ISSUE THREAD

**Issue by rickydavila** [solana-labs/oyster#217]
Hi I have some wdai stuck that succeeded through solana but failed to create a client side transaction to submit in metamask.

I have tried clearing cache and checking recent transactions in the wormhole ui but nothing shows up. This is my transaction [https://explorer.solana.com/tx/AHrKFch6tuHZMat837WBKU34gesu735wxNKfz1gs2m7HwRvdE3JgAtpxkqvTxwypiThxk7ERNVEUyheiuWeG74x](url)

Would love a VAA code to resubmit transaction but unsure how to find this. Thank you so much

**Comment by dentalflossman** [comment]
I have the same issue and would like help finding my vaa code

**Comment by leoluk** [comment]
Sure thing - call the submitVAA method on this contract with the signed VAA bytes below: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest: c4b19f227cc2c2a38bd091214b831dd12eb6e989b39bd079f6eca364bfea7822

Signed VAA bytes:

> 0x01000000010d006939991ccfd9f6c5c5635db52e0715e429f90697abab727c4233fc053f947b3645c9f6fa91d329f7dd8e7d327f33cc95157e6c7d7aead5beb39ae9a1917b840b0101fc80032f57d2fe2966170fd4d8b5412749b9c7537b16d1430d1e67c6809cc44003e8c3db7d9537fbc9e0b52b0540408e542d09c7afe250f015192a5f50a9d87f0002ca994fe5408266cff10228e6bd615858049966711483f718765933204de36166378e812640caf269a4651f53d13f6da1c5b44b6e9719546a070dd6a3fafef5e40003c8252eeeaf6a0e0cfd471c1d72c7d4a5e9ee1591d4b3546b2f1af9efa01c04143687bacf74bf83d3e9586190326f0639b96955421221be9ee77cdfc91ea24e8101046a51124176767c225e56a7a1230f6771f2007cd75c7a87fc5f79d4ee14527996179f426ac0ea45e3386390ed5bcce45014c2baf32dd27e86ae908586a95ea9f90105e126423b605bc2b7e2490dbbd15d5ed16cf0c0205006abac886604e180e81f522f4915b56c42ec6c71e4d7347ea11d5f683762cdd171e57dba601f5a8e79aa8e01061a8d0503ca3313998db40317facd53ba8b0f988c95dbf05dc624491c4b0396595cc4666f5365c003058dfe5351783f60493b0652b46e7fe047b370fcc7861b570007b8a1c06952023f09c676995011defd11b1f718b6f7338b3cb0ffd9e4e490b6441fbfdddd363ffd363d82a0631214a609cf5f466dc912d19b6313a4ebaa17000b000a6ed1ed367796bcdadd8a0e0e5c20993810e863ad06c2f06f0d2867263d8b20f05d787c0b16b09506e0ef73b304c7e2e8b67951a4856c361662759259a87dd26b000b12637084d755c85494e722c09db2e8ded0763ffa3b8cc78099b8d16827d635454457c2becb50f22dd2bbc07b4bdf2c45e16b7c8ff7f0c55f65da6f7b5d031d3f000d841da289d65c000d05e28ddcd0fc37bb4d22a8a10b02ea7100b7293598a4bd8038d2bac5d3e94c6c000cd4109cc18cc235afa4b3e07e87dd5fe37f281b01f8780110ea1f78043cdab075aa2a6e861b8e8432ca7c7fcb3bf5d8778b8294d655ab71eb65d6d533697cb45b9d6d9729da71ca5bfa232ded449948027f67c69da2e777b50011e38a23dabccae79f7f682925c033d94369f11f2d5e3ae5ac6faeb385fea74e2d38fe5d0aee4b1cca505f73cd79f5fc894c3ef9595e34135426b4c019a9b8ed0801612d4a2510000129bb010272fd07e908ced4443c0a1341b6b083c7e47d7130da81bb534285ce7483c87e68000000000000000000000000748b3183382e1123fc70ff8bd99daa96d71e15c5020000000000000000000000006b175474e89094c44da98b954eedeac495271d0f09000000000000000000000000000000000000000000000000000098350c3adda5

**Comment by leoluk** [comment]
No response - assuming it's solved

**Comment by rickydavila** [comment]
Yes VAA code worked thank you so much leo!
