### ISSUE TITLE
Stuck Weth sol -> erc

### ISSUE THREAD

**Issue by dentalflossman** [solana-labs/oyster#218]
Hi, so my transaction failed and I need help finding my signed vaa code to submit manually through the conctract. Here's the transaction hash.

https://explorer.solana.com/tx/4U3s4qrgmP6tJGqoUi1aCVTRwwtUkj44omZ8xqmTkz2KeJ7v29MXFpYRukxR9DUmm8siuo4ZAg3Axon6V8SBrfXw

No recent transaction come up in wormhole. Thanks.

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest: c21cc5cdc7c5397da579bc4b5e557db7f0aa9f3a59b5af247f8209286f8fab8f

Signed VAA bytes:

> 0x01000000010d00a51956ffbf30bf18a81b384e4be3d525fc02000a60ee70300f1df2eaaa788d9758a6c72873ba029b8266e4ebffedf0376c5b273fce28d7947d62cca60101339b010144c84ce6a5e50a1aa0e880b82ba46be2437cf84690986efc118d5a989d902dec528388dd0fbf8ef27d0d2359596f0522c13175c696bf50e16f69b894ff816094000276dd532702ccea491277535ffaae9d772d30040206ba1ad77773bd555dc8b0da7c8efa252e3d0b6d56beda66955b399944ce9bb616b6b374656f103c40899277010412961276d97fc6d10db9ad2a493e1d4e262c172b963ec831b74739e53c8da43e58408c2b677a8d21c9841e2030887798b3c4e429a7e345c776e06394790495e501051cd595623cb7f04772675862affebd9f47a31e9af02cedb743808b3d9a6aca0e05dc212123c85e88f71f649c7a41a07db24c3ab199ae4fcd01dda0192ab90beb0006ff17b2e099fc43089d979d55693e908dfd3298028355619f40c4df02e88244e96f0ffa8a18e45f535286af9ef1675fcd669b7ab9de9e470a962786006f5f884c0107ff3e0ee39cd6ce78c66b3f84c0a2602ae1595e6ad494c38fc0537dd6dbf634573c11f1d7ad3475a2d5ea2d4ef1ef602d3835d4a887b36ee7869cf45ad9f259fd01084e0732fd1813bceee455eacc8c8f37ba0a0b3edf07e826f06c9f5c4586f8057017de3844ee4f91012bee039c5953c80ac8108ac36944185d577f3b40dcde17be010ae60953da1223c37e648de87df2c64cbc1129e2fafa527ca4ba29d8010ae5ad6d7dd0887429c22d799e2b8796fa75f63cfda9ea112054e3ff4c02887e741d0639000b93add067cde89587e5a1e6a6398b54e5010ea3a03d0e642c8227712bac8be96f4db25182f1b35024b0e6ac7df7a844f9ee3b3655af733733bcbef45bdf622c59000db14ae5e05b6e16d8611c01bf3ce55803be3eb57e055631186b2e317e9ccc88507451dad6a9dfc5fd645c179903a6064722dac85e6ea71bb293d184647f10aed8011053d4484a0bbfeb4f67968fe8202e8b2a6d894bb4339f2832c9b5be7cb85a7c9031461d5151f7a908e4bbae3ef38501d9e196b81ff8f048cb985fddde414f39c500126b378e9a527ecce53d39e05207d373827c8c5bbadd8f87b457519f22096f21c4323c3161a8470dc63b580b22f38e9476d834f3316fe62c3503d70d6cbbf92bf600612d2e891000010a7901023017ebedf1c6e28d46e881294516b59e6fde6492d23121c17f5e24f5fa220d0800000000000000000000000046910af2ead8ae10ad2787cf197909126c3864f602000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20900000000000000000000000000000000000000000000000000000000d6ccbf8e

**Comment by dentalflossman** [comment]
worked! thanks!
