### ISSUE TITLE
Wormhole does not send tx to metamask, stuck after clicking "approve" in phantom wallet

### ISSUE THREAD

**Issue by GHowlett** [solana-labs/oyster#219]
When I click "transfer" to move weth from ethereum to solana, the process gets stuck after I click "approve" in phantom wallet. Details seen in screenshot below. I do have $300 of SOL in the wallet.

Testing on:

Brave Version 1.25.72 Chromium: 91.0.4472.101 (Official Build) (x86_64)
Latest Phantom wallet

Wallets connected:

<img width="988" alt="Screen Shot 2021-08-30 at 6 12 09 PM" src="https://user-images.githubusercontent.com/1733920/131425668-9a5abeb2-051e-4f83-9d44-8409bfd5138c.png">

Click approve in phantom:

<img width="351" alt="Screen Shot 2021-08-30 at 6 12 32 PM" src="https://user-images.githubusercontent.com/1733920/131425666-e136fb4e-c117-4361-85b8-a59926a5f936.png">

Console log:

<img width="1069" alt="Screen Shot 2021-08-30 at 6 13 01 PM" src="https://user-images.githubusercontent.com/1733920/131425662-a1e77ef2-3b32-4b4d-a999-5ea3f6f8391d.png">

Error in UI:
<img width="506" alt="Screen Shot 2021-08-30 at 6 53 47 PM" src="https://user-images.githubusercontent.com/1733920/131428905-e1a676fc-93eb-4649-97c6-4df59c5e96f1.png">

**Comment by leoluk** [comment]
Looks like wormholebridge.com might be running into RPC rate limits

**Comment by leoluk** [comment]
For reference, this is the transaction in the screenshot: https://explorer.solana.com/tx/45TyEH4mX62pWxL9B6UM2cL45E6BGUpKaNbnNosemf5LjVcTRCbPR2wLie6V8CbyVir2BvT2pP2g5QNpzDdMDimk

It doesn't exist on-chain, so it probably never got sent.

**Comment by leoluk** [comment]
To my understanding, this was solved by increasing RPC rate limits. Please try again and comment if it doesn't work.

Note that mainnet-beta is a little overloaded right now regardless of Wormhole.
