### ISSUE TITLE
stuck from wUNI > UNI (ERC20)

### ISSUE THREAD

**Issue by isoz** [solana-labs/oyster#220]
Last message it showed was "Sign the claim..." but nothing popped up, missing tokens on both sides, tx shows an error as well.

TX: https://explorer.solana.com/tx/AGZYbVVtUqXd25FZjvWYkCkK2UrWHByXmK7iwRcAEZSV697NPDbRhXAjwbq5NdX5jSCFjmHWnCCWn5XrvyDcqwN

SS: https://imgur.com/MgkrbHo

tyvm

**Comment by leoluk** [comment]
You provided the wrong tx, but I went through your tx history and I think that's the right one: https://explorer.solana.com/tx/4bj9PVNfZRTSUmmzEvsY5Vm3UfAYdeU21KYUK4ZTvQoRJMEe6HC5BgvyHhLKnrwBcQ93LuLhLzGx8RChH1kenyT7

The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest: 3e01962614fa8f89e52ca81c22c140cdba308d109bd9ddd969610f6dc951874a

Signed VAA bytes:

> 0x01000000010d00d367ad6204fb32db56244aa9c2fb4c280cceb47dc39cb6b9661ce3339f89c3187df01136128ba8db85be88ce4c3a893caf47e59fe1785c0fb7457d25637fbda8010164e17ca5a4a9409e3e6c2075d48076a53cae541b5dd0c6d882d069099b92894b528029e48b4ae6f76c9340867a88071ae146bb710340374ae0fadea213e327340004b9cdb7263fdf2b16b62d8cbf2bf8ec6ae0820de4b36fde34c5cc82df9a10c72d2f8ac93ea39a0570c1c75cbf4142bd342b2db0d16d977b408f507df93c2cc65b00054bbf4d747752268c90e49854f2c471a0efa26d73ffe5f6f52d16c6983f5975352f4c79520b9f4dbd00ef730cdf6c430d83ef8c272c09c56e0b8c891492c282320007b9150e229d9f28cb5a1069d0c2d5f25330783cca689e9e1f988a8fffe17505697979df90021cd3e88d049f404b1a4bd8582cd7ffdff36cb47449bd309f5a695901089eec1524fe7e0e9aff75185043ad25333a838ca3c7685aef09c47df24ea5ad942d7ece4d8023cfd708ca183eef9d59a93fa388cee9bf32f6b69c299d5d6a1cce0109520440c0b39cd902d74db38c9c9fead20c0a6d4ca54e0159d60432d1c679f1282a18e40e3ca73cbdd0d1e1478ed8ea8f7586621630bcbf08c98c524856e1dfbc000ab64ecc6f613be3a08930620ffa0c588c66c2069091cefd5b7d356e0c44ade7fa58b8259209fbf3110d8e0801e674bd75b0e9966024661a9cf1894c163ba3af8b000b0ada02d0d068558ac92b70fde85da027894d3f559533cacef3fa31b91eeb53531f0085d48972e2f9afd9646b8eec7798917cf1eae75ceb96b57122abb98293f0000d227c2cbe335568af937049379016f5e3f72b5c36cf8f5c113dcce7bdc74e67f34ce0ac894e8e1dc73517f8ceae02c11a14968076fa2f2b3e8ba96b6ff9d62771001068bbdca23e6b4fa2da70f7b84038b21d13c5dea947da8969a1e13b63b444628f0f74bdd2bed51226cb6cd305dfcc12351a99a3bad1e98b7243e9211125cd47ae00111f5c2a1022022786da67920415351474a34a93d01306266e38fe517f6e1f14843fc81913ee0424220c22c3c432e247ad261a2b8741e8d9df16db099838ac04d8011216338d46ce823b8879bd1d0a01648cf314a55fbd9ba83cbb3d277a8f4c2855b60bd22e75460a7b663cbc1c4dcda6f47abef6e8c8264eb9683996a781716000b600612e23ae100000da9e0102887b913fa84a88d40774c85f1b2b6885e4ad49693a595a95ce942987e7d718f90000000000000000000000007149976d0cf5b71ec11ebc37b9e24854c705402e020000000000000000000000001f9840a85d5af5bf1d1762f925bdaddc4201f984090000000000000000000000000000000000000000000000000000002c787cb600

**Comment by isoz** [comment]
Seems like I received it now, you must have done something, thank you!!!
