### ISSUE TITLE
srm bridged from erc20 not recognized on sollet wallet

### ISSUE THREAD

**Issue by specialfx74** [solana-labs/oyster#221]
i hope you can help out
https://solscan.io/tx/2E4H6XtAAduGntYAKdbaqqZ2MKmP4tDpfPDciTdH95KqQYB591s1Szg1SJUZpt3mc9NApB9XJVxrgr9513WWZbpq

this should be the transaction id.   as i sayed. within the bridge the SRM show.  but within my wallet
only the amount + funny number.  unrecognized

regards. specialfx

**Comment by specialfx74** [comment]
tried to bridge back 
https://solscan.io/account/CPhXkK5nXRN2NfXcc3MHpFkKgDG3LDft3DSax4GYK1BS

reduced the unknown token but never showed up in my erc20 wallet

**Comment by leoluk** [comment]
As for the second question about bridging back to Eth:

The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: 1https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 0b3292a571e63bd4df8d7e0225bc8a4a06b8a580baf3c59fbb99302e6306a1ee

Signed VAA bytes to submit to the contract:

> 0x01000000010d00b879b454de326e6daa8c2816c6f8eed2c0d2905a665f08b33b1158bf3170cf934ca40e275c08f2bb4e9a1eb7f890fd7fed3be8bec786cbe0380c831e4eaf884c0101bed5ff449d3bb6e3911430e915b8228447d24989c51de89d77463b9e36ea8b24087c3f0e00b146b8b5bda8fb372468ab9d8836f2ad5c8d7613309a2d696515f30005f1f2493bcf76aa3059ef1ca2331438e14c3ce65e9108117d648be2e62153a63b758f385e4ebc104ec9a850e4a24a712b0979362bb5f596960fe1a0453c6311ff00060244655b5b523666e1ef4a9ef9f820ed4170f4947a51fa0fc3d565197a76d391054b7787d4242f27e9941a8a827f0d9c1c88af6fc1a59b6aa2ee24bc7190dd1501074d776c4123ebc36673ac1f5ce859b017dcb3d8cc20765933fe5755dd0097cf48067a87b2e3f80f0a6f72a95d666a1b2e1a893b6b5cab2a5fc81594a5cc7854ca0008c994e73ca3c0aa51761c77942e948844a81c1030ffe6dcaab78668920e4209e23912aae46e16016b60184d43cc2f2ebe3e4bd33065af7cfd3efff797373d09b90109421d6d9ba0e5c5be83e251a1a786493aa2c53414fa1d2e79e02a6a12ff80af38512c84ade80dc050a4452b21fe23e6052c6561dfd126504153f0a262b00fd53d010a7d069fdca94696d5683b682277ae12cf27504a941fe0fbccfb70776bd201a21767de7ed02f854328e198b4aa6100da25ac3dff000328198b6c9d6ac1dc830cb2010ba6d050e75601f3036e04e4817d7706923e276f7d479dea3734713775b87fc6221e38190807a7ba8f870daa5e3786b17683daf4b96e9a4f6d3c70fc1884d7c26e010db8e98051b31b3cf0940f267ba9ecee18911eb1db2910efa58bc097b7cbfdaf91592d93a1c9480e6bc0a8ae959da1e34ffabc5bb2e7078b27bafe9a45d7e91f7f00109975deacc5c49346407840c3f5e11b42166b985b2bfd2f33ffca02d0e3907d071ec76988fb7a08dd8e909245d2a16e495dbbc311850f9584bc42b2cc8549586e0011961ad38550f1fb9aeda4f8a7ae3de6e1c4b1a11eb87b75f7d99b6348ac3282522720d172ca5208bfcbb34438767a0f2b8cf147641040bd09492a95c94e4687780012437a9bdd7eb9dc849fec77af66d633df5fae54acec8df9cfff6c3b1219a6bdfc6e35824a95bc67307b3defedced50b572c50797a27a753cbb2a4ce7f9bdc8ef200612e2eec10000071810102a941295a9313ff39bb710df30aca1f098292fb6df8ca002df53a0b36df6ae1bd000000000000000000000000f47f42b1fbf477e89cb8f08815da073d287b973b02000000000000000000000000476c5e26a75bd202a9683ffd34359c0cc15be0ff060000000000000000000000000000000000000000000000000000000012571c7d

**Comment by specialfx74** [comment]
cage clearing didnt helpt. but the write contract worked.   one more question.   how can i find out this signed vaa bytes manually ?  can i see them somewhere or do i always need to contact a dev member ?

many thanks again :)

**Comment by leoluk** [comment]
> one more question. how can i find out this signed vaa bytes manually ? can i see them somewhere or do i always need to contact a dev member ?

Right now, it's a manual process since it needs access to guardian node logs - any of the 19 node operators can do it. It shouldn't happen this frequently in the first place, might be related to mainnet RPC instability due to the large amount of new Solana users.
