### ISSUE TITLE
Lost renBTC sent through the wormhole

### ISSUE THREAD

**Issue by ShepStax** [solana-labs/oyster#222]
Last night, I tried sending renBTC from Solana to Ethereum. I have done this one before with no problem. This time, I did not have enough ethereum in my metamask wallet so I rejected the contract in metamask thinking that my renBTC would still be in my solflare wallet. Unfortunately, it is not. I am including my transaction hash below. Please let me know if there is any additional information needed.

2kC7KHVQKsCKd7yHqqfGqpQ9CkzCueaZKm8Js8CALAWCREn8BhT4mcaVuUMC1Gfb76zJ5cfnbK55L8wijZ1d9LXD

**Comment by yamijuan** [comment]
Go to the bottom of the screen and look at the recent transactions table, make sure your tx shows up there and can be retried with the button at the end of the row.

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network,
but the client-side transaction submission may have failed. Try 
clearing your cache and reloading wormholebridge.com to see if the
transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed
VAA bytes below to the submitVAA method on the Wormhole contract:
https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 743afebf65fa18b7cb7185351ad0a4fc15a21b29b8c242ed038e0bb285488f83

Signed VAA bytes to submit to the contract:

> 0x01000000010d00600c3293a6ddddf92498d5131bfca60eda6d70969ccfa230af4f7f4526e9acc50d00e36b2d0e7cffd213f04e3351b019729a7fce375cb6917791e0b24452e42500031190ccc94ff92257dc9140817d2f6cb80a1cde1cbd9a809b2c37f4d28058b537329436f9410e1d94ecd66c5d718999221f1407dbb78569590666b3dd62bb16fc01046ba4c81925ca35a239801214d4d01f1b9f94e2c5d9ccd96cf37d06de185787220d2d6303b35851d06c7ffb8a6124cbc656a7756230c9e571327116aad28cd62f000568fa166006730d05c8f4772e0b098d25b95203588d3d326116212537720305fa3f714c739219e191dffefe8c34cf73365cc9d51412dc2f9a32b67e07b2e1c7cd000680b921a0980094502651c56089443b4925313a21fba7bc4f4d4ef9d72d6554c030b9520c7b58d5f253cb3a21aa6e19d319858bfb6c3cc88d619ebaebcdbc45e700077dcc714a9c7d6a654a1bdf7f427a6c81df867f146bbdb041c3a5c96c24f6d6c86e722d274a3ae1972ab1da4af27402eacdd55751bdbb75efea7dc269db5b3b5b0008cd31cd6611d92142754f92ef218c5b2547b2d45ef31f6f4bd9df7e7609d1e5b54ea3b67c56b1fdb41b68ed941a5ee05aefed9487b7f9f1f45f87e7a8c53295800109d8861efc2c5795328fd3e0de206315cd60ab46edfd41886023b987a69b6fc267015776994c1fc2493b25212f90ad189cf964b48c840b7754681e08ab660dbea1000a8c826989672c5dd1450945052c1070e9b3f55ca0ca145ba00100612fc2610b982ca8191ab8cf0ed0eb6d81bcc7be83864b10a69dd397535ec67e9e5f53dcc2e5000b3cec0166b71985bb4a5a3a270ed199e15474022403590cc7f7363f8c943e31bb18aec65543403dfac138279fd622507eeb312a47bcba3f2259bdeebc548922b6000dc3e6ef2eeef7bd309e7276529cb7f2eb7f85c0fd6c5bd33adf803f65bc8072c01d328b846e93f33f5dce2579e9eb3586f13722fc35b74a55c4b6dda8850134db0010eb9cd5982467da94c670604f7df060482ae81a3c66a0e1ab2e7b5f48ca7664705d4151461d96f6813c3acf4bdb52413a4e0dac357a2efe601f2a5c3ce3807142001115e252f9aada82bfe83caa3a58dd34e1f8e4763f2fd51b90af7cecb5ae6b03010a03292030fe5a055576242ecdbc76b28c66f1432f32e28259846de9e84d7a8b01612d94fa1000016a0b0102957fc3c5ea0c5dd7cf7dfc1745ba93bcbcb800ab6d6340c2db83e9aec1cc750d000000000000000000000000f2a7fe69ac4a6398e58c2d66950f285058d81f8b02000000000000000000000000eb4c2781e4eba804ce9a9803c67d0893436bb27d08000000000000000000000000000000000000000000000000000000000255754f

**Comment by ShepStax** [comment]
I don’t see any transaction history at the bottom of the screen.  This is what I see. Sent from Mail for Windows From: Juan Diego GarcíaSent: Tuesday, August 31, 2021 10:51 AMTo: solana-labs/oysterCc: ShepStax; AuthorSubject: Re: [solana-labs/oyster] Lost renBTC sent through the wormhole (#222) Go to the bottom of the screen and look at the recent transactions table, make sure your tx shows up there and can be retried with the button at the end of the row.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yamijuan** [comment]
your message is badly formatted. Also, make sure both wallets are connected and the corresponding token is selected

**Comment by ShepStax** [comment]
I went ahead and manually submitted the VAA bites to the wormhole bridge.
