### ISSUE TITLE
lost eth on wweth (solana) -> eth (eth)

### ISSUE THREAD

**Issue by imprincesspeach** [solana-labs/oyster#223]
<img width="382" alt="Screen Shot 2021-08-31 at 11 18 17 PM" src="https://user-images.githubusercontent.com/89858910/131529711-ed50dada-2e66-4466-b778-d32d2af75ccb.png">

I can't sign the claim on ethereum.
this is the transaction on solana:
https://explorer.solana.com/tx/3CmaamvodFvhMKvDo97jjMW6taZ6ehZLBELdezZuGjyiagAK9iNEVJzaMynndx93qaB8xPZcGDq6qsgx3JDxLb5x

there's no transaction on eth because the "sign the transaction" was rejected by me.

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest: 9c2c04bcce5ef034af130bddf2a6a2618beebc5a8dbd8b6a7b003e7f4d7c1f28

Signed VAA bytes:

> 0x01000000010d00fb8d795ebf0561932508d0bde72f4f35c2d8a889ae4e594a38902de528dd5e1579f0dfb5b9b6b501fe288f13262185ea12ed9d5583adbfb05c5109b4c62ebf620101fa8c92dcb0d2c34232787bb277ab759553ac2998a403b6b9434ac7f23bee869c528142eae1d8d8b3beba7beed48b19b04a846f7d1bd9b73f3e83f5e15b256ff7010245f84d3d4dd433b4264f2377fd969ce69549db7dd0448c6f2427d14bf8f1216218435f79b056115188cf7fd0eadfc342140025e7a9931325b951b5fb395d996e00054c5f3075cc47bd3247e76e2eede40a5bec2e7a7bb2aff2aa54ae4c453dd1a9ba1d4f515f703be2d2d46e99dff959ef2e1de87cc1bc19240aacb2fbd7f6226950000637cc3f379fa75804cb6a6584c6feb5cbc841d06250e1ac07018ef1062e6b31a70f0e3f95b1b28ab3943fe7a4e97a0feb179ca76e6ad615170e363c4ada7843320007536de4fe2cd4d255494413640fcbe76334c888c2b130bc1e4dd1d488ae5e183220c96dacf185915015b6eaee8a1558ff0b6c3184358615e4bdf5319a4f99abcd0108ceb73b52edf7d7b72281d55deee9ec37a4879a8949c94fd88c3fc728fa14b3070613d9da759b5d47b40596c68329497f194c1768b766804fe526537127ca15890109f4ed268b85f0d61a6be7f1cc4ab99c4d29497b6cd3b24b5a5effbabc1558688d6257f8e433ba3d5132af19eabc16f1580bb2e595b4d94da897680b9f6d1ea2a8010ac0f4eb36fe5fab3df9e12f4b5bd8587c0aefc78969f2028c995fdfd92069f6c2706fa66b29c84277397f7c5dc7f2538792867fdf19b714873ac57148d6394f84000b45bbc8de552bf69688b833645c2f637e38a3bb8dc6761558ea64a7bf642f617411b825346e22b29bbf97a66590d324aec1272bc846732f62a7c6f5f22c530ad4000db91620549936de12764a991bd2c8f5c84cc0e51d875ae1f94e57cab975c3d1463f192151a520ea99fcf9aca2e1a79418a556e4562e4c121963fe857e1b0337620110c093589f8480b8fa7ea2996dc7170273d44dbbbd27901cc1c99f3e1ef5b371732d99659881288d025c0d2a7317cdb55491e65ec948d55ed258d267c1f5d1967a01123699dd8cf7f108ad6a0a5fc87f04f79a061ac54efe0ffa73dc38011cd4e0e3877c04e984f6e5b473f33e59600f3c1b6d294e81c0935cac5e497bc13bff10313701612e3e3e10000137f60102dd30fa190970afdab263b101df4c1cbdc9ff8dbdc688716e797548b5decc7b5a000000000000000000000000097db74a73419a3f60f465bf71c9baca36a6690102000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20900000000000000000000000000000000000000000000000000000001d6e06f00

**Comment by yamijuan** [comment]
Go to the bottom of the screen and look at the recent transactions table, make sure your tx shows up there and can be retried with the button at the end of the row. You can also do it manually as explained above.

**Comment by imprincesspeach** [comment]
perfect. thank you. Just out of curiosity, how do you find the VAA?

also, the txns don't show on FE in recent transactions. Seems like quite a few requests here could have been resolved if it were showing on the FE.

**Comment by leoluk** [comment]
I'm retrieving the signed VAAs from the log of the guardian node Certus is operating, but it's also possible to retrieve them on-chain (that's how the UI does it). However, there's no standalone tool to do this.

**Comment by leoluk** [comment]
(this is how I'm doing the manual retrieval - any of the 19 guardian node operators could do it: https://forge.certus.one/plugins/gitiles/wormhole/+/refs/changes/65/1265/5/node/cmd/debug/lookup.go)
