### ISSUE TITLE
Stuck UST from Solana to Ethereum

### ISSUE THREAD

**Issue by MihirJoshi** [solana-labs/oyster#224]
Hi I have some wUST stuck that succeeded through Solana but failed to create a client side transaction to submit in Metamask.

I have tried clearing cache and checking recent transactions in the wormhole ui but nothing shows up. 

This is my transaction https://explorer.solana.com/tx/kbLuoGnuQbgkiWP6dSctryi4EBaBAG6DAKAgaRQwFo62ZfgSjy3LciK6NohP7NnkThDn5BoxdNGUjmpwvdmA9gm

Would love a VAA code to resubmit transaction but unsure how to find this. Thank you so much

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest: 9d0965a1e2047a97cd9589427834f4d0f7feb6b62acfa12b00178dc409ef4b58

Signed VAA bytes:

> 0x01000000010d00adfde1ffa61166708d6c24f862239635b1b34156d490c4bbe4c04a3fde07125145aad30807ac8c96864763517e744cc08eca574ab2c68fd1945d81d7cc9158ef000198a24617f72344d4b4b9278022574ed0968b4a22c158e594cab767b8c2d4152f6e833038a2fcd6d3e7c84a90a7fccc652f66aa198c32797c54739cb1d6d39aa700025b55f4e43e2f8832920553cd50cd40c8f89c0fe95154fe53ee3d63cd8c4cda7844290826f842cbbca68213b23363c491f94f8c9caa5585855188787c2fc70acc0003aea008911c68f599c2135c5aea84d1decdb906b8bfc102658d94b91c422e85f67bbbeccb519527308e8438b4a93aba978a8bc6d5d43242c8e3eb9b3e85ee9d7800059724875e45752f665f4605cbfdbbbe2657bf36100868613d7b1ae7043c260d707d8fa7a81eb89d92526f6ed72e6a25094a62ca05b097fc04993394ea82b5b56f0107326a4fa532fd8a5522260911e6d91973131784e71ac74df710d4eeed052e1ae404d8de34c39e1f7e26f483ec19841d6a9ab098c6be06acf8c9455a9b6ddf32520008971a8abb655d81f5aaeeeaa20bf2f340d5e901be998e857ce8e0e04216a9281773f409f049cc201fb5143ab54f7e0f59198a51803bc39d1889da14d4cf706dff010946aece93b6d1ca42863952bb4039982c00fba61de741eb85676ce17b1b27b3cf22f43fffbe8c1cb8999265de1bc5974cf5719ca7ee52403268b9cef93a876462010a825f9ad8e0d2ae1f3d77bb0e5c79107971bb57229c44bd464a2ae50667edc3f47cff3629228d2a021cd75e099f15bcef130c6acaa3ce351d8be8c4c0b7ca36bb010dd86f19173882e60cc788738677c5de760aa03348599a7238e82dedfd8a484c40421445f45b6fcb1731a5869ad2d55b76c15387ab188f43cff995d48f851609c90010787e1df247adbaed61a13cbf820e4cdc4f97c5b0a1829e911b6ec226071ba714134c34dda8f4096558cce31d8656bafc6e3829dde0b96bc485c8202d87c95cd80011ea60e68534cb56f3a3e87d59e5c9906f8d017a5833d1b2845bfa747612c508b612c2dfb56ee95b43390fc97d970a355ca4e4cd53b76853ff8d5845f2781391eb011291b0debc6ab7027eb7c9d60a684f3f8f23a23467d0dcaee7dc3e1e2c0b03b8d74fcc1a7e224548b8b613e4b6230b7e8ca0692ad8e87edcf1e5329d43d708c31e00612e43881000010bf3010269b836a909b26b0c8b92e366c850f55664ad1f770bc00b4d2d047668722fc8ee000000000000000000000000b8a6b2a4c492eb20686ac1706bc5a2548a9e400002000000000000000000000000476c5e26a75bd202a9683ffd34359c0cc15be0ff060000000000000000000000000000000000000000000000000000000010366400

**Comment by MihirJoshi** [comment]
Hi,

I submitted that VAA but it looks like another address got 272 Serum - https://etherscan.io/tx/0x172e11fce83337e54593e003d45d97c9720d1f639e583039ad65c1f7a66cbdc4

Was that the right VAA?

**Comment by MihirJoshi** [comment]
I'm looking to get UST back as this is the transaction that is stuck - https://explorer.solana.com/tx/kbLuoGnuQbgkiWP6dSctryi4EBaBAG6DAKAgaRQwFo62ZfgSjy3LciK6NohP7NnkThDn5BoxdNGUjmpwvdmA9gm

**Comment by leoluk** [comment]
D'oh. Here's the right one:

Digest: 3e01962614fa8f89e52ca81c22c140cdba308d109bd9ddd969610f6dc951874a

Signed VAA bytes:

> 0x01000000010d00d367ad6204fb32db56244aa9c2fb4c280cceb47dc39cb6b9661ce3339f89c3187df01136128ba8db85be88ce4c3a893caf47e59fe1785c0fb7457d25637fbda8010164e17ca5a4a9409e3e6c2075d48076a53cae541b5dd0c6d882d069099b92894b528029e48b4ae6f76c9340867a88071ae146bb710340374ae0fadea213e327340004b9cdb7263fdf2b16b62d8cbf2bf8ec6ae0820de4b36fde34c5cc82df9a10c72d2f8ac93ea39a0570c1c75cbf4142bd342b2db0d16d977b408f507df93c2cc65b00054bbf4d747752268c90e49854f2c471a0efa26d73ffe5f6f52d16c6983f5975352f4c79520b9f4dbd00ef730cdf6c430d83ef8c272c09c56e0b8c891492c282320007b9150e229d9f28cb5a1069d0c2d5f25330783cca689e9e1f988a8fffe17505697979df90021cd3e88d049f404b1a4bd8582cd7ffdff36cb47449bd309f5a695901089eec1524fe7e0e9aff75185043ad25333a838ca3c7685aef09c47df24ea5ad942d7ece4d8023cfd708ca183eef9d59a93fa388cee9bf32f6b69c299d5d6a1cce0109520440c0b39cd902d74db38c9c9fead20c0a6d4ca54e0159d60432d1c679f1282a18e40e3ca73cbdd0d1e1478ed8ea8f7586621630bcbf08c98c524856e1dfbc000ab64ecc6f613be3a08930620ffa0c588c66c2069091cefd5b7d356e0c44ade7fa58b8259209fbf3110d8e0801e674bd75b0e9966024661a9cf1894c163ba3af8b000b0ada02d0d068558ac92b70fde85da027894d3f559533cacef3fa31b91eeb53531f0085d48972e2f9afd9646b8eec7798917cf1eae75ceb96b57122abb98293f0000d227c2cbe335568af937049379016f5e3f72b5c36cf8f5c113dcce7bdc74e67f34ce0ac894e8e1dc73517f8ceae02c11a14968076fa2f2b3e8ba96b6ff9d62771001068bbdca23e6b4fa2da70f7b84038b21d13c5dea947da8969a1e13b63b444628f0f74bdd2bed51226cb6cd305dfcc12351a99a3bad1e98b7243e9211125cd47ae00111f5c2a1022022786da67920415351474a34a93d01306266e38fe517f6e1f14843fc81913ee0424220c22c3c432e247ad261a2b8741e8d9df16db099838ac04d8011216338d46ce823b8879bd1d0a01648cf314a55fbd9ba83cbb3d277a8f4c2855b60bd22e75460a7b663cbc1c4dcda6f47abef6e8c8264eb9683996a781716000b600612e23ae100000da9e0102887b913fa84a88d40774c85f1b2b6885e4ad49693a595a95ce942987e7d718f90000000000000000000000007149976d0cf5b71ec11ebc37b9e24854c705402e020000000000000000000000001f9840a85d5af5bf1d1762f925bdaddc4201f984090000000000000000000000000000000000000000000000000000002c787cb600

**Comment by MihirJoshi** [comment]
Sorry about this, it's still not the right one. 

UNI tokens were sent out this time - https://etherscan.io/tx/0xd72d7cff8b23555c5e6f48858b486dafdc6438c78b7fbdb3bc5f258b9d39d31c

**Comment by leoluk** [comment]
> 01000000010d00a1409b26d34fb89f7b918e23ac593e0a1a3bf3f19559f746662496aa1ee1bfbc1a543d165c9971351b5ab2792f5f6d93fc407fcb69d4d81da80b4274899114ee0101933e240649e436802fd134dade44a8e5d122d68d877b4db147d490d4bc014a655a7c991fd38ecb85bf4ebff6808dbaf4b3f93863547dc61511be31c2570ecfff0102cc5bd78cb8091d0445757d83ecc4f11a51e63e95314a369adf31ffd7c759b8fc53fa5205bac5914b2150f2649bc275f630f316b4850a6b2572db20a483765a8f0105ca26de085eeeefb4a4070c1616ec423c561379246d9e4d76f287070e098503dc1e5156881a03e53411af985a7d9516e590a38ffaab57f0eb96d3160bc7b4eab9000641692b38997d296ca3a61eafadbcb8df45e81e1d50352000596ef5d8db5cbf2316dc8c1b208a0c556040a0ca8a118ad24469867500a7b1557ea8c0fe96977c000007eab416e8dc6a8091bbfac190486f36e3dafdcb4795e66a83502854c45d3dc37e319e291a5c32082d6dd8796977afb7751f5e530cee889eefdc564fdc2efc33ec000813b800d16f0194afd090a8c9dc85a45fa18fd8975f247c058fba86f7130eb7475737c529c5483a2726db91b8f74f02c594e031a958df2e11e73e3b365c353cf00009f68436085fda1f28e2ae0cee3b9e5c04dce451a00dd09dc9a307802022ce09815a4a34bfd8f4762e46d4e34e49e0c5a09bf15e5d22273b338e92d27d957c6b89000a68ba5a05279db35ae3fbd5fc4c10cbef9bf936cc77ce4df9f5c75c161b12a0570542f2bd4556475cf8f8011e719864ebb3da45900c4a4a635c5c0b1e843b8aa0000d51d9a0082f74138fe4cf4a200b736bdc45c67dc49ad6592f9495076cd058defc7e048d907a920d1a55e382f477f203b5e2d2d836f0eedccdc409ac3ce754e56500100201f133a08883886911dfab990b7f2479907c4f750067cf80bd3456ba325beb5868808163e479266a97246b6e9c13c399a9da2ce0f886242e205801163f8ba300118230e8c6544608dd683a6c84f7de9ed4881687a36f32b5f863f5fcfdc74af38448d8201fdda6eac664a6e87d3590ac7634308dddf15ab6fb24ebe8affc4e0d3d0012591e23b72be51673982d28891e899f8c76e88e40503f00d4b69aa5b9a8a398cf14915e41a430d1c62bc3e6e5b149085d378464be696c01952403f3b64de9af4c00612e468210000070b201026c75f971d1eb470f289e4c76d91753adcfe01cefde345aa15c1504bf4008da690000000000000000000000002326d4fb2737666dda96bd6314e3d4418246cfe802000000000000000000000000a47c8bf37f92abed4a126bda807a7b7498661acd090000000000000000000000000000000000000000000000000000b5a243028979

**Comment by MihirJoshi** [comment]
It works now, thank you for your help!

**Comment by leoluk** [comment]
:tada:
