### ISSUE TITLE
Wormhole Weth Transfer Stuck

### ISSUE THREAD

**Issue by bobbywol** [solana-labs/oyster#225]
Hey there, I'm trying to transfer my wormhole weth from solana back to eth, but the transaction got stuck, this is the transaction that went through on the sol side https://explorer.solana.com/tx/57damNnnCEk6KUhqP5MN6kesg6EZzFyppPAvX9DHhspfaJExh7sUUBDScvHjAVyFskyBahTG4LN5KbGJjbKsibDz

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest: d05085528cece660d4caf6d6c31fdbbfc536d48ebb5167935ba7f481da8c2f03

Signed VAA bytes:

> 0x01000000010d005bd24322f4e1142cdf9c66732ae97fc4c7a532ed33a7c9c7e0cd1c5b7700cd1b198f6bef9bed62f4a65fdadf6b4ba84b09f2b42c2b9be14e83ae4595b93ab1b0000162f4c46f37af17d99e609bcb46424901527d999f322d91a226a54e9dda5796e928fb8a31d3866dcaedd18b04e1ce26456ce3418ca5b9ee1e69e26babca99da290002e3e59dfba067c31a3b77b6aa65dc513ffe0a51173eb5a611e0e4dcb543a234f94a1bf4a087adcbad92abbdf0426868f811e6d1305d812cf6712c5d3acbdd90f601053764934dbc94963ea34dd86c485598251fb5cb8f7e721b18380ef251d4e65ee94afc65f4329fa5529b6c6463524c5ba7f4e81a9747a8c291ab0f3cdb222d95920006a3bf9da8c7f623e3603cd39f42d6f7f7c6d6faf50ffbef400a85462a275218892274ff97128d703c39472f00e55fa8858013d492d1fa56adcad79b23bca72c040107e385cf71e2c92821943a1158c33bbae07d2884d7b94b3f9366787ea04194b1ca790f1fb8c543efb52dd62a9da7d929a74abafc2cb47bf266c7ff7bb3642fdadb010899e936958a42f302402f260b50ee00d1402f45e589d11356b5767b37cfb7ac97073f6eb9a4563c0bf07f6d9eb199ee5bebeb5fab4a58e6edabe71ea4f5a15eb4000ac38ed5c8c3183e5f0dc9c24404bee1daa88388526b5848886f1face96c837b4c2d71c244107e25db7e192e6cae00ec0d44c85ab4f4643c73653b0a8648baa40d010bcfb853c4354fd29893ae8073b5a561a28303123717dfd4e0a6c93db10e1e196d25ccad2577a78e46e874f077be1ea63741a4b93b5b30413a8cd0013ed18d08f1000d52e8b6dd415eeea68c3d06dea10ef8fa1396e6d84a7eecdadfa9d2145a8fa5ee101773b19a5dfc3fbbf4096b800d4311c74ceb4dd7a15739014c5642347170270010c0d6e440b83641b819771ef0e101229312c84319e7ab7884e459c85fc249d7ea78a1762de3f8b7c34dc7ee104c2365afd3397c43b240d238f9ce99fea262f3df00115f50dc9e974fa65d81b83b2149f721db303ac7877137fb821131ca20833766154c0ccc17790fb7f1f6c64fa8f81438ae5e3ed430194f351fa50f54584bf2f3460112a6a529a3bdc0c011ed01064ca21b23ece74d7905480465ac0af1df0a05461df96e97d2ec3b838d44886e38b08ea77c8ce5b4704f0658caeeeaa6fd1a6b0a2d3500612e507f1000013aac01027abba3510879c85b404f562f131b21e402ad51452f4b6c71da3859118bdb86ee000000000000000000000000c05bc25eaa52a23476e113b9a139a66e7473b36402000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2090000000000000000000000000000000000000000000000000000000059682f00

**Comment by bobbywol** [comment]
I used the VAA method, but got an error when trying to sign my transaction with metamask, it says: Transport Error: invalid channel
I think it might be because I'm using a ledger hardware wallet, maybe your contract doesn't support it or something?

**Comment by bobbywol** [comment]
It worked, thank you!

**Comment by leoluk** [comment]
:tada:
