### ISSUE TITLE
WWT stuck from ETH-> Solana

### ISSUE THREAD

**Issue by m4t123** [solana-labs/oyster#226]
Hey there ! i was using the wormhole bridge of wwt/ccai to solana , worked fine before, made a test transaction and all, but the one a few seconds later failed. Looks like it arrived in the wormhole, but the transaction from the wormhole to my wallet didnt went through, so i can not give that transaction.

eth transaction which arrived on solana: https://etherscan.io/tx/0x934a2d9b51e7fd4423f5817b5fe76b4f50527e22937215252504fae196daf9a2
eth transaction that didnt arrive on solana:
https://etherscan.io/tx/0x0b4f05ab3336fc9d6b728189864efb53df8214323aca1968ee8ad6924df80eba

if you need further information, i will gladly give it ! 

greetings

**Comment by leoluk** [comment]
There you go: https://explorer.solana.com/tx/P7F5Yhbv1SZZeXZg3E2jp6mTvHrCn2f1E7qSVxzQPbRnNXXWqV9M6mWcFVJJk1djbRvbBi9gRTrR2wpsHAu5xkE
