### ISSUE TITLE
Lost wWBTC from SOL network to wBTC ETH network

### ISSUE THREAD

**Issue by andbark** [solana-labs/oyster#228]
Hi ,
 
I used the wormhole today to transfer wWBTC from SOL network to wBTC ETH network and funds never arrived.

Screen appeared to get stuck on attached photo but looks like transaction was processed via transaction hash (also attached) 

https://explorer.solana.com/tx/487nUbYPKCfYz6ersarehRWT8dBPcb84qY7qN8fm4c3yMp1kcpvoqueuUNnYWADMxP4fV8fufQP7FtP8aDap1LQU

After quick digging:
Funds appeared at this address: https://explorer.solana.com/address/qfnqNqs3nCAHjnyCgLRDbBtq4p2MtHZxw8YjSyYhPoL

![65212138006__79E0705F-803F-4BC5-A409-1E8D5CD25D30](https://user-images.githubusercontent.com/89865399/131548963-23ed10ae-5b79-4331-bcec-b0362e2708ce.jpg)

**Comment by yamijuan** [comment]
Looks like the SOL part was completed and it's just waiting for you to sign in Metamask side. Go to the bottom of the screen and look at the recent transactions table, make sure your tx shows up there and can be retried with the button at the end of the row.

**Comment by leoluk** [comment]
If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: 1https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 68979a704b5b834dcfbc7d932d984341628df2a4d869c56d2bddee91286f4638

Signed VAA bytes to submit to the contract:

> 0x01000000010d00d86aa10085dee6c47c9d7481a9d15b4296f35d836bbae64bfe2304b4c2957abf2a3a225408901eb3278ac3c38cafe0e9f178a3e8d00357924e48d30a06876f9f010124cc2459a79c6cdd1ed01f1bd52111506855c20174773f894c040dd41af21ef31435c3dc7f292bee193f453d51f46269bf584457700ca47d09705d3969e622b20002e38f5c77436de89b1cdf7f024e9cf788af6e4c88f998cfe17fa30d791fd2f02d3eaa51ac82527b49b6088fdcd78313aa69540c66573d0eac1ab67fa8a7a1b11d010311dd7c9998ea2a6f4c2077d1e8aa72bc76cdbfa179c5faddc4d5160856ee7b7f3accd49b01d051cc13ed47903bf9ca5b5c69ea08f2b0746797151992628a6f5401058c6c4bb1dc189505c6ee0ca9e38eb21cdc71c9381d387b6a1139d30e72ba0663600ac8ad8e80a561392ad066295ef16412b3b07b47d50e3a70aef52726d4325c010716c29d47a6336973217f2924604ac76cd56fb8a52a24614af05a1b3af99d236b0853e45f93d9d21c1bfefd72f22388946a568ddfaa2d514312020d75d0e2200c010821f7162d8631a18833bf40d0d0734bd54ac8bf6a38748a737fce610315f6e4f7224940464b417b985f6ead16de4d169e050f17d754811fa1f0ffd3f9bcfeccb40109498817510a120b324b574f205dc730410a0eb7fdb6e286d5bb0adde8376e9361542bc8c9373305fbc81e77edd12b5431eb7480bd5c71b83c3d8218af616e5480010a80417ec47e7a862cbf4d155dcab59dabaecbbea543b26989800029260fa1240a15664d002b59257a48d389e268818350f5d707418b7642992df0025cf178cf14000bb6d98bba5ee993e6ccc0ada9680a423677ed43f75f892461de7966086219c46a5ca113b3f520f3e7e1bc2d4b8a6dbf702e1bcec522aa10c7a35080c42a204971000d63e81c8eb51eab1632048609a26095d28fa65ab26a3cdd2a6af3cdb9efb4b0d74e60078e7fda6dde8fbcf5eda4e9e17542855b4937c2d4679cd2e6af5566f734001044418f3dfc38b240a356324d30907cd32463174c35156d3566d6c545dfa6efa572fee418e4847d09d01a68f1198a0f1f505eb59d4625fa231eaf1ddcbb3ca1ea0112a84a20dffe5de01ff9bb2c9c074376006b1e86bb44fd41ab7e04098b27d506b419c4702907e071332ab633fe3a7b07c8d0c1056131c8456a6b89dc21a071d3c100612e59481000013177010266d5c7c1e7ddd43ac97c366b3fc15fbdff28c44b246667a2d27644fa7ff7b57a00000000000000000000000009dd3e7798311ad25584c93ed4f4110b309ac46f020000000000000000000000002260fac5e5542a773aa44fbcfedf7c193bc2c59908000000000000000000000000000000000000000000000000000000000007a120

**Comment by andbark** [comment]
What screen do I need to be on/

**Comment by andbark** [comment]
Thanks for the help.. Before I do this, does it make sense to pay $150 gas for a 0.005 WBTC transfer?

**Comment by andbark** [comment]
And where do you find the VAA bytes for future reference... I have much more to bridge

**Comment by leoluk** [comment]
> Thanks for the help.. Before I do this, does it make sense to pay $150 gas for a 0.005 WBTC transfer?

Probably doesn't make sense... I got the VAAs from our guardian node's logfile. Any Wormhole validator can do it using this script: https://forge.certus.one/c/wormhole/+/1265

**Comment by andbark** [comment]
Do you suggest I wait and send the rest of my wBTC (approx .51 BTC) , and is there an estimate on Gas that I would need? Thanks so much for the help.

**Comment by leoluk** [comment]
The gas amount is the same regardless of transaction size. No need to wait, if it does get stuck just create another issue!

**Comment by andbark** [comment]
Ok.. I just tried moving the .51 and got an error 

https://explorer.solana.com/tx/5iS6FCuN478hrbrQvMNMFsRBesUQKyZViTCEfmJBn76AGinp2Ue2PEFP2dyVefsP5pTiEtFAa7JpLtj3SmGVT8LH

**Comment by yamijuan** [comment]
I think the UI is rounding up somehow, you have  0.51016154 wWBTC but it tried to bridge 0.51016200 wWBTC , slight difference
