### ISSUE TITLE
Lost wLUNA from SOL network to wLUNA ETH network

### ISSUE THREAD

**Issue by Bobby10009** [solana-labs/oyster#230]
Hi,

I used the wormhole two days ago to transfer wLUNA from SOL network to wLUNA ETH network and funds never arrived.

See for tx: https://explorer.solana.com/tx/5FfeSFxngjEKhxH6QAyqTAPhC6pHyUmqwz4t5KcvNJ6G9nHv2PvwSW5cmE8KHRS41jwScRANzsTfbWK26d5BuDjD

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: 1https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 172647b3fd921a02b76bc688b3ee438288d37c32984b9e1e5a5d8e95919fadb8

Signed VAA bytes to submit to the contract:

> 0x01000000010d0045ceb3e4d6c2d1d2a816705f5ad402a085cc918e594733c0e850f99a380fa7a726f941545e7a35ba7612d506d4d884e18173a5298ca6d03e181cc6b16a50cc7501013c947f82aea3d1b95b9fd4ca60434ce7be4e8fb9a957dfb569b53c4d15ff966303a31f8091bd67af566ad1ebebf0087613e9c1e679363e627a1d67a724266202000453072e77642ce48158e85da3c5c39359c3f3221ac660c50ad8bbe67c2ab9575f2def16f0df52762c98f47128540cdc287258d67442d7c56b9a283d2dbe96cd5001055e8c09502524e32cb86a04dc5054fb83f076861af0aef32dc185ba67d4f3b5c04fc9e59d018b0d0462889e905128d238f39a7e537b78e2858e2432c16fa7b5af010775d7d7d31a26353ade941692e04940357b99bf2fc26afdaabdf0f50d722a18d501a3ce3ccd07e6cf473e62c184f8cbbbc71488ded19404a547656bf7a5b80f4d0108fbf0b8cc0290408036348ac44f1a1bb20a55f3fcd0bf43c648e2b00c982a705e4ae722565841c2c68143e4bc86f93ac8fff18de77525610a7d0ca5087d00165a00093d6331b82eec94056ff6a8915ffe84341ead2d2cc158ec46bcf3938dd5c7e25f445e57bac4ad4cd9a3c7fe34339f9895a84617a453524c52aae584b63c381614010a5bae0a5e7ebe90e785f3e521946304cd0ef93aeef2c659448e5c1ee1a9d4137d348d0eb32e979cb26c69328ac75db31592b6c26dba170a93443ff132471ab716010b1ace58a49cf8bd25d9eac0c98031be793e0f9c3674cb9938ea5a5895d9cf77670477ffe3b14dd40fdc6985d3ed9666ceb6f2bb696d7eb005fd9c7354570da972000d98adda12bcda17d6669f234cec907b9315a6a406f26e423b25ef67477132f7fb3282cfa47f15272bacd145255bb6b62f353f645f601185aa95a88304f39d26140010db9218f705b239b677d02c3d086c1edb83dc94572cc943daf35432ffb7f9b9ad70ef4bf5c5f332760088ebb4623b75466147f759781b75c69fd34d6a7891bf3201116c62d9f23f98c0fb72ca32e7f43a243aeb02789528c6c5f60bbd09a9c818fe9e60160b8238a100694dbeaf7987bb5744381f0267a3bd5b82cc8689f9d2770a930012dd5763f40ce407095488bebccd7ca34a5c4c1df67dae351e193c60eeace67da12efe8785563ef8e841c6bf01c9db7c6e4363c93a2a06cc2a67a4798a10b8400c01612d5daa10000079670102745a1597345fff9d9686c4eec00ebba8b8a4dfbf9b0e66096a966f308f62c267000000000000000000000000c3df4005290a4f01e99e8aa7927566b26977a15502000000000000000000000000d2877702675e6ceb975b4a1dff9fb7baf4c91ea9090000000000000000000000000000000000000000000000000000000bcc52334b

**Comment by leoluk** [comment]
Assuming it's solved
