### ISSUE TITLE
LOST HUSD transfering from SOL back to ETH 

### ISSUE THREAD

**Issue by ShotguncharlieXBT** [solana-labs/oyster#232]
Hello, I have lost my HUSD whilst transferring from SOL to ETH 
Cache has been cleared and recent transactions checked. Still no sign of my tokens.

Would like to request my VAA code to submit 

My TX Hash: 2uuGxBVJaaZiMxEwxmT7yA6hL8AiDkbjBc37ASAfiFcBp86Bsf3cjnhGo65S2oqogt8V2W9zKBXEc3pgkAvBELpi

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: 1https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 8c5cf2566f4ac062f059832ff55f24d5a97a76f51ad2b8ec104076aee7720e92

Signed VAA bytes to submit to the contract:

> 0x01000000010d00f3bcddf3bb6cce964f6f9c25ed4833989f4869352ba684450896d92a150b3f0c230c8ec9a303aa13f79dc30e40603b93595422854aeefb2f09adb0c1ed8aa16601013a57fd7dd604c2576f606cbe673bbc578abde673f6252704074b8f3461a2a02f16514862f92854d1804a84256afcdecff0e11a262790c151771283658f9c5abf0102bb6fc09f2e1d655e43045501462db914443bd850167c23a6cb9f11097c1adf015d77dd04aad7464f13406bddaa156598308ba9c58c290ee08c4c53a55c45c2870003c46f17b0c8658b6a6c2e3b814929eb13045ded6c8ac502d5b8f4b5c5bf5970870b792e99f369ebd40b916a8bdc8a817b756178b7c9fc4be4b5ce0bff8350b30d0105efcdebd8900ed134cf8f843a778c984884c140c5fbaf41c1711cc1f27c640fb904dd088f983517338db2786f9eabfeabe51d3670d0a958898ff484edb95edefb00078bd2745f9a44922d7d3cc97e9f6837a2ad03703266335c5d77f116728c8b70e82cfca5b0362bf3c7c8fa95a4461d5bc97d8f3739275119ae48ee7e96b9f261ae0008e469d72a13b8209e8ae7562b959db3d7844760e5af949c6b1ccee9ff708f0dd0216f497511039f7170068c6432d4a339afaca3bd71d5f2c755ae8ac003e8d1a30009943df0806d28777fa2f89ddaf4b004c4d17ef89be4ee85eb44010b18255afb59551ff17d2eb538f2ea3e1ac6fd8d38b1fb0e4e7705bd58f8f2fcdae658883410000a7effbafcffc62e83ef159bf482b8caadf0a9f5b15b1390882eb27bd08270366612f427ccae32f2ebcc56775ab3130791a437bae2d0a6ed227d41539aeda49a1c010ba24cfb05f11dce96bee82f7b86970251b9de4a39d50dd90b32b3ff15e04d92e57e3daf9e0aaa0a4a80f8da6378134453c6942e993a6c0c7a46ef8b4a32c43d97010d2a8d64ef46e34b4b1bc55202f11c7880abf2886030cf1b6dc705e59e08553c9c43290befa04e171e4f400f05c7311a31ef2accfdd408d05ad97cf2c9dabb69ca01114f016b4c1a7d624f5a3fe9b22a49f11c0d963f60da4a8f306a1f2cbbc63a5fa6205573ff33d01bf2aca487af0e74148a7b1ac10f9401ce23beddf3ac4c525b310112033c0fe16df5c5c6e98087b29d5ff15d906f5df66ac98ff7d0e27ac69767240a076e00859e7188eea7aa69e39ea101f4eb2cdc9ce3bd0e69defd8bdc039b94c201612eedba10000064b50102a704a5a71322b0b9c37ddd409cf191290aac12b87c50b3f7cf73780c5c4d9acc00000000000000000000000099b02491fd1a9a7a97a31d046767c08d5ccc9a1d02000000000000000000000000df574c24545e5ffecb9a659c229253d4111d87e10800000000000000000000000000000000000000000000000000002fcca68cfc20

**Comment by Steven1T** [comment]
I know how to call the submit VAA contract on ETH but how do I sign with that specific VAA bytes?

**Comment by ShotguncharlieXBT** [comment]
Another issue  

HUSD again..

Tx Hash: 3dbJeJdWR1wrudKnhHyFkt7tKNjdgnJx6M63PDo5zVcBcojkqic3TR4n7HXMMRFK4eWU12mpskceVZcvb32HjNsB

**Comment by leoluk** [comment]
> Ey es hat irgendwie wieder nicht funktioniert. Wie kann das sein?
> 
> Mein HUSD wieder. Hilfe
> 
> Tx Hash: 3dbJeJdWR1wrudKnhHyFkt7tKNjdgnJx6M63PDo5zVcBcojkqic3TR4n7HXMMRFK4eWU12mpskceVZcvb32HjNsB

No duplicate posts, please

**Comment by leoluk** [comment]
Assuming it's solved
