### ISSUE TITLE
Lost HUSD from SOL to ETH 

### ISSUE THREAD

**Issue by Steven1T** [solana-labs/oyster#233]
Also on the webpage, it can't load "My Recent Transactions" even after clearing cache.
Keep loading while not showing anything.

Txid: https://solscan.io/tx/Mz8BTe77gf7ji5XZJYwyH4oRSPUzeheNVER1CiZpuXsiQFX2tVKAAKQyMc1XRDDBzYnytTkF7VS28sRPnZBeYgk

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: 1https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 437b5b55a2ee2320e1f67666a102d1f3f269b0fd71de3eea19f74ef76112c031

Signed VAA bytes to submit to the contract:

> 0x01000000010d00d04d2c50dcd538b6bda1281dfb5e672db2f0ce3e92a5f1f2599e1cb3bf0dce4d459cf5dead1fb86f5c71d53432cd794817aa79022b8549bd993b38c924678a2a0001b65c5cf9196286890facfd3cead7965b4b03d2fbe63921f877862135512980e03a0e6387d834dace24aeec9d99c95f879ff17ece288998982b5b338c7587a290000358b34e5332d8b0c88deca743137170a702382e296b1411573bc3296c0b6900786f90240dac530620bfd072a8d5cc79c7947649ff5445b59ccf8e0ab289e58b1f0105994c8cd15c7ac23b9af8b69e6982a85987f5ad57118e49038e9b53689d38dfc12f9e12da82c2f4dca597e46c886bb85c99350fd74ab9b61989f3e089b7e759d000074ff153bd0489bf93335623265f1b1da66cf778d86f32a5c1f9f1247f23c014783a27bb8402c286803fb301f850670c5df851ac0b94099b050e0ab802dce3f2c4010870bdf6b305ff1ad98d05fd1041b27be0a4e8f14e681a62be4d574adf592223f4546bdcf632dceca1d438c3f0420125f90d5507a2363f802f2e3d26c30c5e8e360009da086e8cde52dadf51ee49bcfebb51d4bb1db9205cb020fd68ca21e5a800308d4f48dc87a1f3589c36918f3b9dcb85ad12b85f27de50f33b4696a3a7fa35c273010a558a2bee5af3255cb8234f249a9dce6bf6cd77738caf48f5bf0b02a5342614022482866e0e9282f29405d1512f87dadaad98ff8376b43217c0d39a3b9906e746010bcdb9d120cb3fb79422f3ed9b660b30b12cba0170908049ff04cc4fd8c2f955d70a2b0693b3cf9061731d54e116021612830764cb23492da30d2718de44940d0a010d5ebb4f1e8df6fdd40fdd3f57a544e5100146bf52505e301258060a5dedbfbb760275837c66318df26e29ac065b8281b03723b30ca65f421c9254aad3811c354100109f0d46ada69ebe17fe263e032c2f3e8e4ff901a87dd49f11826d4ec9d0732f2418c7da186e5c51d0c6db5cbc79032394ba71cc1d97711df65d41640da003060d0111c4e28dc9e6b33a2e7caef6cddbe7fd6ce8cd41a64911beb1ae569d45055a83685e77d8c6acbdf8b6e5fdc5c273cdd8f0122eac0177ddac28accce792981234b00112492a377de536cc7313a78a6d523f4330ee9ab919c94519d53f5c6cb6545427a764c5ef7268bcf523f9032cc540081909d121e178261c2a9683e95b384d5ad55501612f7eba1000007c99010221ecd8638d72695fa606482717bdaeb432b243f5e82e9528e4643f16141a979000000000000000000000000046ccb9b24baa3fb761934f566e1613339e2afc9202000000000000000000000000df574c24545e5ffecb9a659c229253d4111d87e10800000000000000000000000000000000000000000000000000001d329b56643c

**Comment by Steven1T** [comment]
I know how to call the submit VAA contract on ETH but how do I sign with that specific VAA bytes?
