### ISSUE TITLE
WBTC did not arrive in Ethereum from Solana

### ISSUE THREAD

**Issue by takuarc** [solana-labs/oyster#234]
I bridged some WBTC from Solana to Ethereum via the wormhole but although it settled from the Solana side, MetaMask did not pop up to let me approve the claim from Eth side. Is there any way to manually do a claim from Ethereum or can you help send it back to my Solana wallet?

Transaction hash: https://explorer.solana.com/tx/2fsA75AD7xtKrof2zaUG6paY5QAhnUdhMWREtiDV64LxB9J4GfrBNpXCMYnWB6t8edRdYF41qddRN7yWea8ok4Sw

**Comment by yamijuan** [comment]
Connect both wallets, select the token and look at the bottom table for failed transactions. Those can be retried from the table

**Comment by leoluk** [comment]
If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: 1https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): c58e91a1833b4dc91c30946d50dca72e052d1a246ab7ff7b8987f7d8951a14af

Signed VAA bytes to submit to the contract:

> 0x01000000010d005ac55d2e138a16cb7d837cc9ac8fd20de1675d54749c266bdb1df3d0e303de1c0d78e745e2626086c7fe1d36ea67b2fea7426b8cbee11bf515e86e65b41feeec000155e23f8d48a131ff3b47e5904063aca3e20e87c641d1180021e608dfc1e10d4439f91e8b4cbceef420af3d403dc632e75c1feac6dd697d6d69740900a8378f8d0102da96878b51715d28392db983517dda5a0dda5afb9ee95287313e26548d37e9453fccabba234fcb887478aa560b95f5d9e520c6076c30d9b891c369c3f35626120003e83e8e2526407a8704088be352f02edf595defb5efb06f109bf0be9c8ed625bf551f99cc36223e3dcc03e9f13987e77a17ce31e3c8cd0ed4f9e3b882f670fc740105a5f440176ca9604db45c6733d21801d0e154c898cf5eec236dcef5d5a81c58ff75795235c7beb43ef0590d33691e0e5a8fc502e6211376282ccfa5f4cb3baa690106551e5308d48d28a475816042ed121b8ac9618974618d220c5b948636db635955793523196b2ba60fb5313401ee108d952c4442db322675e16cc258e8bd2207f20107398f8f386730f863750d6acc5a6593cfc215f223431deedaa0b6640f620bb9aa7283f24ae06a2bccc386b59c39144959fd8d4176963590b12668dc80e46fdf4301083d0716b648091b3aba3000703804c2d28508431d19848808fe50435b1ad07d5c5d797864398dc3115ea4f7a90e77db021d78c6f9661ce52b676004d0892d5c510009b87c02da2a2b314e82fc6954b7a9624090f40b10aef23f490b7606456af454b670473af8b901890b1833f5226e7ac94b3818733315fded176eda7d445fe22759000a5e1115de82863053dd7a097e046cea97c12cf6d30615a3e6e1f94f763865cd64211b87dc5e7d678a854dc9a363943311d56c69b9d15b4265513aaff92659cd3d000df9004495b404e8284128c5030a05ca81e2a48e83bd2636ef3ec4de3cf778574447d850da81f88e608b0d8a785b409f567e907cb557a6cc497bc11ca09f58674f0110eb5342b4623f5cd3823cd130984c86f807a7331334c2e682decae50d90a3f92d4e5f42d2c5ee646ea73c4c831492be0d9c5009648d227dcaf6d91983ab39860e0012b809876686f3d2e8d27effbe49aa15f281a3308fc69bfe534b9f1868fa81ff05387794fdef5fe6c59cf5341909cc61f1eb9de660ca3443e28fc89b2d451d458900612f041e10000093aa0102ec9e09533d012a6127d51391c0b3816d3c4f773f4e68d90070fa4b871f365343000000000000000000000000403fe0fe2bcdb829999f7de9bdf2502debf3a50b020000000000000000000000002260fac5e5542a773aa44fbcfedf7c193bc2c599080000000000000000000000000000000000000000000000000000000001592a82

**Comment by takuarc** [comment]
VAA method worked! Thanks!
