### ISSUE TITLE
Stuck funds again from Sol -> Eth

### ISSUE THREAD

**Issue by m4t123** [solana-labs/oyster#235]
Hey , sorry its me again and funds are again stuck, so i would like to request the VAA code :/ 
This is the signature of the transaction: 2drvqazLsP5SkdeLjSZt81VNRzx9smeqngDiLWomLUEuLBxUQYwnPnNuHyGzZpb685VRmfEkrRDn13a5bG1ntd7D

I guess i will wait a while now or/and try to do something with my cache or test different kind of stuff with dummy amounts. I dont want to bother you a few times every day.

Have a good evening!
Mat

**Comment by leoluk** [comment]
There you go:

https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 06b4fd60cd536eb8deffda4da51cb787d4619ba3a0426e47f64ff5c188a6519c

Signed VAA bytes to submit to the contract:

> 0x01000000010d008f19d61dcdf37b87fbdfc27b606c772fc5472d541d6e112e2d0efa269e7ba11c7fa0d98b6f10f8ab61be68fc86139aa606602e69076c614d3672ae1254fcc36d0001b31759723479f064bafb6bf0a1425ad6b77d25ff5357a32dc880a728d1d7dad35a83201bce46a185b425aea590c158e56940f427bb9627fa581657105b297dce00020455142a10c2794e8d01b39a26f8a1f72fb0dc94d911734d271f594837c86e6c2ad03aac94c72b7517d2a4c8d66ca757131ae81c574d2288099aa43df4b6c4af0105ca7076ffc0ec1b0e32e70e5e7c11f77219a33e2cf89afcc825578ee43f804c652002a01fdb0a3f66090a142e9580d0a20d30a72685f2c284fd00b2c2488353630006b224e73890a39b70af11c37ffcf82eecc059f2db8f4b0be01e6335af980a16090a55ad32cb02d18e61b7e51a309d893e6d58361953f9fcfd0c829e4b5cbbf1fc01074baec8bc47f4ecbaf5c072e3a811eb9511d06080688bac9b6cf009447bb0729e4e2a59b3a547265a03be4321d793c6dfdda70fe2bbc0bae380505223fa71d4b601085110cb872ec17000a1d9469f15cb6ccd62846fda669bc952d573e2e6f4552be207a5352df196d73e67ca656edbe2224168fe4a7f20647ba7f4730a97fc152895010aac0562d72c55b61bbe663429bafca711924fe1622ad714fbb86786cd44030ebc4d1ff3a78300faa0bf912f3e06a6decf6ef002fadb0ef3cae8b89546a3d921dc000baf7404b6cba5a3bd6a3abb18d64f3a14f58ecf11ea5d0b1a86a96f073f776f626223056ffe31d9112e978831a74b66aff4e094755ed3209760d738f027568022010d102aa6474c98c0cf5b532b2081a5d45478220cd02df8d71b1862fa41155c63c67d28902f406c4e33255dd90cab03219541eb939d09167ceae50fd8380f465ee601106642f152908146769d01aa9648a5d043f3ff6420dee123d1f34daedb2c99f6f86a80f7d65de338db606ed3958cc5dd92222286fb9996cc4b70d708c0332fbda901111e4926f96cbd24ed1db3a2cf250125f3120ecde7ba776341832da13d8da9908800238da6c263473ab21d2beb63fca386a4dd609f4ed7cc0a0e1d0037ba36bb4000122c8ec512bdc07bf922177f147d2e2e8a5c990e3a83cc912f94d5988834786f0d6d2694218cbc4e4d8d5799fda06f89d61c9813f18956b416a3ad2934f4fe5f4e0061301b5b1000007196010249c36d3d422f0d4485c42e252d9128e1f7a5cf57b896e8a77de479e45be64404000000000000000000000000e7207afc5cd57625b88e2ddbc4fe9de794a76b0f01c261d86cf5cf877128ba1f5652e5f3dda599270c1556a15bc0a9aacf8063e56309000000000000000000000000000000000000000000000000000000e8d4a51000
