### ISSUE TITLE
wormhole erc-20 serum stuck in solana- token doesn’t appear

### ISSUE THREAD

**Issue by Cryptoradio** [solana-labs/oyster#236]
5Ed1aPF8dUcyqaVXG4dnoES4iZgAYHgX6giyLg97zRCapDDa3zTyTEPJq7h1skrsmm25u4io2vHxvznYTm8uddbA
transaction HASH… 

> 

Tried to transfer my erc20 SRM - from ETH (metamask) to phantom (solana) -
There was SOL… in the phantom 
The Ethereum side went well but there was am error in solana part….
Serum token didn’t appear… instead a “unknown token” amount ZERO…

![27B05E3F-9C86-4AB2-87D8-816AD1F62424](https://user-images.githubusercontent.com/89953321/131768174-9bb23bb3-538e-4f17-a59b-135884aeb58c.jpeg)
![CF38CC95-617C-44D8-987B-0A603821563E](https://user-images.githubusercontent.com/89953321/131768184-385d5ec3-6edb-49a2-9268-df37a6be2b7c.jpeg)
![C7171EC7-F2DE-4D6C-AB0E-8EAE14A4F3EB](https://user-images.githubusercontent.com/89953321/131768185-b16c6100-e91e-4ecb-a3d5-a2ec5702ea2b.jpeg)
![77FC36D4-49CC-4BD6-9CEB-FF390724F30D](https://user-images.githubusercontent.com/89953321/131768188-eadfc117-c8f5-415e-8aec-a2fbeaf32577.jpeg)
![A776C6B1-639E-43B9-84A7-144EEEE34510](https://user-images.githubusercontent.com/89953321/131768193-f19a272f-873d-4fd4-915e-aeb65ec139e5.jpeg)

**Comment by leoluk** [comment]
Does https://app.saber.so recognize the token? It may simple be missing metadata in Phantom.

**Comment by leoluk** [comment]
`2jXy799YnEcRXneFo2GEAB6SDRsAa767HpWmktRr1DaP` is the correct token mint for Wormhole-wrapped SRM, and it is listed Saber.

It appears you already sent the tokens back to Ethereum: https://explorer.solana.com/tx/3fQ1pFppwr66LE3NA5jw2kyGYNwFAjVSD4tppgvCPj2mMPhG4SygwC17mchhxoTU1qhaZRttDfxMCA16egqyCCmA

**Comment by Cryptoradio** [comment]
Yeah . I tried to. But the token doesn’t appear on my metamask.
0x2bdfd0C77ecAc63fAbACB225FDE5e3E078A4eaE3
here is my address on Ethereum. ZERO SERUM.
Can u check this?

**Comment by Cryptoradio** [comment]
I mean. If there is a token in my metamask wallet…. Its not definitely serum….
I could be another token..? Wrapped? I don don’t know…. 
![FA38C966-1343-4DAD-8E2B-8DAD4C91ABE5](https://user-images.githubusercontent.com/89953321/131840788-cb10a37a-f002-4763-88c5-fdf28d7367cc.png)

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: 1https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 7fdccdda9f8d2255dbc13236e674c7739c4afc21968c6ffee260ae77c080df17

Signed VAA bytes to submit to the contract:

> 0x01000000010d0056a02fd7045a2ff2e5b9d73bdd8b39ccd9055c10c5efe65e84efe37d19748907041362ab2213b75ecfc1d12e826015a66c32290415f4bfed29400e3ec03df4970001606cf548db5b94aa19291146f6cff0112e859a8872e22b62e53c076819bb6b280cafdce1f47a325bff383c4b5969962cf01be65538c806562df099207c2ef2530002dfac462421b90b8c27cda46b560cab219f582af0bfda222214bb62882b1a085216f0119deff186612a13a319ec088372560b1e9b813018df0b89df074d33f6450005aead4cba27ec5460ef01ad335cdf8c185030d9e1805dc83228ebe6debe8abf161d16387affe647d406706c58427a0b850d9ffbb3a43a94257d042c1252e0326901061bf017c3aec04541c5268ec905eab418bfe93caf80dbe966636e446f32b64baf62f3530d9393b73ba05f419b3cfd70cebbe83229a2cb7ad08fdfc219de40835e0107799326d4528513ee31fb5bbcc1f615274d5483cbb4d4ddd2d073bea31a0d4a220dff0cbcbf02fec5872b8a0bf603d6fee6e8498469c55a8378cb49fe0f38af27000862d74ce85a0f6388b5bd89115af1de2947974cf1088a47504aabc616ba0538a617ca77df6f402d6f8b52ae66e0c48c37579d75847fecd272dd5ad0d8dfe9477e000a21df37ecb64243f24d63e60d6ae85301233414da9d2b210e4826c0a4feaee202247c860052923ea027dd96f37c69d8105dc8f9a2952b6e2e641dffd7d5f6a293000bc7d685f48840614703cdc8815d770bc73cacd2436bee4e19d1e730cef2b73ba450fd5820d6c92bbc1348790aafa85f7ac8f7ff0e97be218871c4163873913ce3010d5645f4d0b0c5a716a4fee04c1c94d4c62aa234b1f1b767cefcdc5451a79788a60cc42cb6d6a555e47c126b44770db48f53773134216f3e23ba3304afa1a7bbc50110fb71e794415a24a01855b3c0c95296b8120b860c076fde05c5da743f53c2a8e14ca777517639b705e69f194d1ecaf0fadb4be48b6a21d99b85c2790aee226dd40111a1709563dda4707a58495533a99899bf89f333c66cde970d28c4fc25ee313f46138644b954f332c5444b888edec47c38dc7cc9b2511ddcba300165ff07c30ae401128c4d89b88bbcc958b44eaa5a7983765cc350173a8c30aeb35ebdac146e0b34322652fd763beaba7df572ce6dc82959d992605653deeae2469a987ca27edc7cdf01612ecaa0100000db1a01028fc946fead9571aadf36ccbff3a3a9344fb7f7471067eb0912d7f9465ddf34410000000000000000000000002bdfd0c77ecac63fabacb225fde5e3e078a4eae302000000000000000000000000476c5e26a75bd202a9683ffd34359c0cc15be0ff06000000000000000000000000000000000000000000000000000000000aa36f38

**Comment by Cryptoradio** [comment]
Let me see if i got this…. 
i will go at https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract
And then….
Copy this…..
![B16E2564-576B-48D9-8C8D-08DF06CF2070](https://user-images.githubusercontent.com/89953321/131843819-cc9681b7-e8f2-40af-bf53-c35705bed13e.jpeg)
 And paste in here? 
 
![Uploading 037A1B78-09B0-439E-BA32-4EA3B3916F31.jpeg…]()

**Comment by leoluk** [comment]
Like that: https://imgur.com/3gCiGH0

**Comment by Cryptoradio** [comment]
Yeah! It worked….
I had spent almost 250 USD…. In gas …..
Ethereum is being very busy….
I think this issue in wormhole is very serious…. Next time i will transfer my serum to a centralized exchange….. and then….. transfer in solana network to my wallet….. this hole process sucks….. and its very expensive

**Comment by Cryptoradio** [comment]
Any suggestions? How to “bridge” my serum Erc-20 to solana ?

**Comment by leoluk** [comment]
I don't know what the issue was - the `2jXy799YnEcRXneFo2GEAB6SDRsAa767HpWmktRr1DaP` you got were the correct mint. Saber confirmed this. You should've been able to swap them on Saber.

Note that Wormhole is only the bridge and has no control over how its tokens are used or accepted in the ecosystem.
