### ISSUE TITLE
Lost HUSD again! Sol to eth transfer 

### ISSUE THREAD

**Issue by ShotguncharlieXBT** [solana-labs/oyster#237]
HUSD lost again   
Please send VAA bytes 

tx hash: 3dbJeJdWR1wrudKnhHyFkt7tKNjdgnJx6M63PDo5zVcBcojkqic3TR4n7HXMMRFK4eWU12mpskceVZcvb32HjNsB

**Comment by leoluk** [comment]
https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 7d9f923762b6b474a3b6c5815aa774665ab24d6022f8e4fd854b61c297e8c0b2

Signed VAA bytes to submit to the contract:

> 0x01000000010d001402251e900ed43e79c5228e1b66c8c23020c9be4f48aae6b61596c1f7da36a670caeb885c3d3889c5d45888bb6b1392d2e2251f3ad79e5852709dd8af62b20100016ef8e979eee55c75805661263d28d89c2ce4bfbfeba337ebb8df2a3c37b9039b6c2858d109d9865e106af35c2e1e7675f1163e552cc92b5ca5d7039e16c0e27c0003d656b5b10d9e24dcfdc2eb31b9d2c8dd4c4845aa8f5f651d6509deb117c59aaf1ba2b40c38490bd5d1944239441777caad4208885bb8a556c4de7d51aebaac520105667498e48af163f217c53b1571f7e234df15982244cb34dd7ac4d9b9455081453c3388a0c4b092084d691baa4b7d49ab889f18aac899e068a912bd2bacbf7a6d0106de0d1b593715d390700df31c581d6b06cabecea1db6d3c5f4c40e379f82a756c10acd8694f85cfa30febcd92803d3ce93fd7c7fe0f636d1d94e4cc8daa7772af0107ce9d1a90dc9e23bc31c31d6442ca13a4c5276dd09c9c01832e9a5b4e00ea779b71080392f30df6ee2c0b5db7163cdfd004076c38b30e8e4491b3091fd6ce0cc301083e3a812c1f2aae953666f59c94af3c0b424683843acaa453d2340cc6b0cb735936a615f505809ad8cce959960185712a7ca14c870adae647c43222349377e289000a20a22cf882ca3d7d6a44ab5d3566ce76883a032859935c365f4c434771f1c74a142577707e561ea837d461d803d7293183cb2bc9dd3094bdaaa121cda75c4f34010b1a209a49b9484935f056d8fd3925b4380c17098ec7d774180ebdd9a53fb732d15cd548fbd2c55a8933de0cc7fe7cfa7db64bffdf0db5f187b16eaa3613124c3d010d88c884db86b1377e2b1b2aeacd2c73ac50c45da29727187bd92ef96ab4f51961543d7adf4cce5ab4be04b130a1025bc98d46005c7456593d91841a818db413df0010117b6bb78d64e3ce2fa616bcf1399f57fe4656b96d867e8e525d4fc11916147833f9cacdea3bb1c768ddf62b4048b4546d33806add985073d1f017ead650f3e0001172cadcd64cbc257d252b358d4edc3fb8e5181f79d19bd02b288607aacd4b47861df454813182356927a6ea4c92a70a0206944a1e60f6e11995b394625964423f011292f95c98cfa43cc318385cc4f79207ded40638c328290c9292bc765885fcb7f64f4e9f50804b1c036106d8fd78f47f376c987fb99bce7b6a6ba0b6e2968c12260061302f62100000a54a0102a704a5a71322b0b9c37ddd409cf191290aac12b87c50b3f7cf73780c5c4d9acc000000000000000000000000c19169b42660e3e96f889e08e761d8c217beced002000000000000000000000000df574c24545e5ffecb9a659c229253d4111d87e10800000000000000000000000000000000000000000000000000005f7ee744fcc7
