### ISSUE TITLE
Tried using wormhole to convert SRM tokens- arrived to Phantom wallet as "Unknown Tokens"

### ISSUE THREAD

**Issue by Molecularity** [solana-labs/oyster#238]
Hello! I would be so grateful if someone here could help me with an issue. I used Wormhole Bridge to convert some Serum (SRM) ERC-20 tokens in my MetaMask wallet into SPL tokens in my Phantom wallet. The Wormhole bridge conversion of the token from ERC to SPL transaction was successful, but when the coins arrived to my Phantom wallet, they showed up as an Unknown Token. The quantity of tokens was correct, but Phantom does not recognize the tokens as SRM. 
Phantom provides the option to "edit the token metadata".. I wonder if doing this might help resolve the issue, and allow Phantom to recognize the token as SRM?

The Mint Address currently listed in the metadata is: 2jXy799YnEcRXneFo2GEAB6SDRsAa767HpWmktRr1DaP
The "Name" and "Symbol" fields are currently blank.

Here the tokens/ transaction is shown on Solana block explorer: https://explorer.solana.com/address/9MRwLJVfs3gtu3bvygMDUoFBmSNqC49vy3RdiTcT2T7b
https://explorer.solana.com/tx/2m566KL6x7PQZF16cFBC4JRfRUhbu2KMk5TWiJjrgzdLp7pbVeQnmQkuPTh1gPjuaCifiBbYd8V8sBCSWVEYQw6j
<img width="344" alt="Screen Shot 2021-09-02 at 12 27 13 AM" src="https://user-images.githubusercontent.com/89968203/131807015-27214b65-a147-4e1a-b741-5e348f14fc41.png">

Any help would be greatly appreciated!

**Comment by leoluk** [comment]
This seems like a Phantom UI issue, which doesn't recognize Wormhole-wrapped SRM (likely because it's not in https://github.com/solana-labs/token-list).

Does https://app.saber.so recognize your wSRM?

**Comment by yamijuan** [comment]
According to saber: https://explorer.solana.com/address/2jXy799YnEcRXneFo2GEAB6SDRsAa767HpWmktRr1DaP?cluster=mainnet-beta this is wSRM as leo mentioned.

**Comment by Molecularity** [comment]
Thank you very much for the quick responses! Yes you are right, it appears that Saber recognizes it as wSRM. Correct me if I'm wrong, but it seems like I can use saber now to swap my wSRM for SRM?
