### ISSUE TITLE
I tried to change weth (spl) to weth (Etherium Network). However, the gas bill on the way was high, so when I canceled it, weth was sent somewhere and it disappeared.

### ISSUE THREAD

**Issue by pepebancho** [solana-labs/oyster#239]
txID : 2Ae5aZ3aee63HN95fS62xgAHxLNNtiKYVQ1SBhuKD2ieT1LqqPYiNN7hxaBviWR42USyQJvz3kRZ6cMPBTQMHZt

**Comment by pepebancho** [comment]
https://explorer.solana.com/tx/2Ae5aZ3aee63HN95fS62xgAHxLNNtiKYVQ1SBhuKD2ieT1LqqPYiNN7hxaBviWR42USyQJvz3kRZ6cMPBTQMHZt

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: 1https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 33a670b8f84afee06d92b8a71a1b49479f043bb185a38e3b518508c1e73e3481

Signed VAA bytes to submit to the contract:

> 0x01000000010d0098e55ce64c24935f8982166525e561547091400c561e1c82335ff81d3daf0e955daef87d4e9dcc0f7d5bcc8b1013e54a6ccf72568f37976d39b1b6565abca62601016bbbbeb563456a1abd097ca77df19101f935974bf76013e8a2855dd1653098875787ba45fdfa44936123c2707bd0e508d8ec37e5ac69f447c5cde440aeb1a7ad0003ed492bc12e68b49cc5eec8bd1b1b1444855e2bfbae4cf18949fc7febc142cf414ef65df993fdb476c6b080eb62742f0ad997393cc1c0738717d2ddcdab5269360104caca43dfb3d851cf70813b4a6808d7a69bcb3ffcc93b984541e8ee257ab2992d15b513c45d2fb2825bb412953f855c4d37856c1f388d2dd06b660e322aa8beed01058a31d2a43c9d185eb8baa0d968ac7a28fdb66f601b2a6e2b2ef1bfbaa5fc8f4111360e52952329835fdec9e957e8df5f44676ff1736ee1e026092a20eebe148d0006a75e838c3439845d818d6d20d54939be459154b4dc74661870df34ed39bc46593bc4afe6ade6196bc13a8e30910492fdab1b7a50bb6219a0b6807259c31cee3e00079cf37f2ecdd2d90d9a0988da415cb1646d6c4cb07d00a046e58210a30441d36c553c664707076ac38b80881a36214fd2a9fd571a307a1dc18c0e5666008aed6f0008c0fa9ddfc5cd0d4dca2baed54cd2a037aa21cd9dc945c2c508160a33f83e49b44909929608950d27f60bed135df3f6d54512477d491b647f2a54c6635903978c000af31beba0b93f7c5b1c92f15333802d8016563f078ff75d35f6c367621da8d012158e8883cf2bcfda4d0bb1547735bc193bbdec428bed1f7655bccbe46ba4e597000b19094fe3c5678c33b9968348dbb36de801303a0b641c07f03563d9fe508ab2be61477e9626221f9e164f508a91941d4629300ec671d2f638763d981b7d0cf8e9010d205ef566fb95d5a3cf2652b8f2137d4f0de7b4e1f48fe81ad78f04c8bd2aa1623c53ab98fe0bab86b5a74e461b9163ae8ebec13386b960115814729d7836b5fc001064adc1ba31bd255871a6253ffabaf8b46977b1d588ec1a7801293718d29eb252584974f627bdf9694b51a628a4db0123a9606a3925725fee8bd07d02fc22f0af00123ab9e200bce6e77fe8963155678942b2b49685aa163d005ae2064d61265b2ac033956391d0a03a5125c00d9d70c5b47103ddece888c2545cb261d4f1a5b3ad69016130c31e1000013dbe01024736384bbbef3e62a4e013073e417fa07c275d63e52e5c09d7cc46a90e06f84a000000000000000000000000d8048c86d30daf69ce8418e135d91f604c4f242c02000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2090000000000000000000000000000000000000000000000000000000005c8e948

**Comment by pepebancho** [comment]
![キャプチャ](https://user-images.githubusercontent.com/89984730/131909690-30a9586f-3eaf-471f-bc6a-ba99564cdb0e.PNG)
![キャプチャ2](https://user-images.githubusercontent.com/89984730/131909698-e57875d7-9bbb-4711-8938-08b6e806070d.PNG)

gas fee is too high

**Comment by leoluk** [comment]
Set a more reasonable gas limit (300k). Looks like a bug in Etherscan.
