### ISSUE TITLE
Lost wETH from ethereum ntwrk to wETH to solana ntwrk

### ISSUE THREAD

**Issue by ciggu** [solana-labs/oyster#240]
Hi, I was trying to send WETH from my metamask to my phantom wallet using Wormholebridge. The transaction succedeed but I have 0 weth in the end.
the transaction hash on etherscan
0x470973f394bd0c2a76e12d8cf128a67de3ad60a6ab0381f169f1859f19d58467

and on solscan:
JSt6YVtXY3SRTPMog7vkVbCNHhrru5Rpp96zesfypb1dvfRpohtXF9aZchyT4pFa9QNJwpQxouha91g3DN5EteR

Can somebody help please? Thank you!

**Comment by ciggu** [comment]
Just made another transaction, the same exact way, but with a lesser amount of money and it worked. I can see the result of this one, but still nothing from the one above.

**Comment by leoluk** [comment]
https://explorer.solana.com/tx/4Bq7Qzp1XYgC7AEd9f4PDZFnHEUD8nPWasg5yvjc2JYSvaAkicPqsu2JkHFAbHS2Z31WXHWNabTdYdzS7m3garFV
