### ISSUE TITLE
I have transferred Wweth from Solana to Eth, but it has not arrived

### ISSUE THREAD

**Issue by traianus1** [solana-labs/oyster#242]
https://explorer.solana.com/tx/24B4bwwCF7FL3pjHJfWKV4nXVrDs5BRoaqSGS6SvoUFerRYmJcYRj7q3kHhAh3wAaaZjWoyy2Mwx3EF2e7KGNNos
I have transferred Wweth from Solana to Eth, but it has not arrived

**Comment by traianus1** [comment]
My account of eth: 0xE3666187c7Fbd30ea514a00747f27BeF2Df27d69

**Comment by traianus1** [comment]
I transfered 0.2 wWETH

**Comment by yamijuan** [comment]
have you checked the bottom table? you need to connect both wallets and select the correct token so the transactions show up

**Comment by traianus1** [comment]
Hola Juan, perdona que no te pudiera esperar ayer, soy español, el tema es que pase weth por el wormhole y me dieron wWeth, pero no puede hacer swap en ninguna pool, entonces pasé los wweth por wormhole otra vez pero para la red eth, y es cuando no me han llegado a metamask, abajo en el historial sale no data

**Comment by traianus1** [comment]
![load](https://user-images.githubusercontent.com/89991663/131990318-f4014d08-7b11-48b7-8c20-78ef334cee9d.png)

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 3fcea92ff77a3b6cf8ee081de8a493e2919a3603d53a4608b0c708abd069f240

Signed VAA bytes to submit to the contract:

> 0x01000000010d00a90f1d5506a47f88c591335cbf263bde1ef9471064d35ff368734db16497a1564578b5a93e184d8bfdfd083cd857b417a7226b425cf32580a08312eccb5a0e0401018a8a40d8ca0b0d032953d8be5336995764e579231b5835e5e3fd1a1dc584f1f5604599404a8541163e7c65230f23e4f2f4666b1b4912237a8f0dcb40c007cbb70103f6741414d9e667c7c4e9a8aa2a6de961e3eff21e1778e0d6f13dc5dcef695e261cf1dd201152308907d83ae2b6028725ff28384448701d8e410d0a58cef2fbc30004fa8e454c0e3501d6fa13dfe2f4fec62340b14a3e28d00ebf314576c9390ab26a1902cb5a0cc899ec6fab3aa7272855658f49eddd27b3cc25dac6475dc6f03f6001055da6ab22b6dd5f867b8e1d9ad9a8d28523f03cf6ca7785e2e38c4e35aaa028521c2ed2fc5f8cde32a90d1f8fa8a2dca7017658d528fe2a94625b35f447e9243100079063bc1b854d4c275cc77d567623a93fadc412fc9333c83b3a1e15d34777819e49e740c9e56e43a9ff14b5ab4bad811969d1880ac456d06bd20bde4af10d4f770108c61bc00a468f42e33df7b9c2d67a16ce71d5f3f5328cf279cd1450f96c746d1a0d111d12fca3d0caf4f88531513ede6c085e7ae60038d722bbe73985d360b01f00099bf01e74139b752cf38b4f1914028c7ac51d77e5edc3ba063db22c52792e75aa4d176b60bb3c118d380b27a50ecb97367dea9fca52383e2c1caa7313a82461c9010a9512db81c6dbe8f15132552a99342466750a14d4e48c7d46552a271e5d89fce77d64d4305ade710cfae0a0c83b30d05d1df394ef443515d431fa44711705e6e7000bcfdebca010a0ed4e5b6678dc982fce485cdbe17c5b742d61de5b9bff145b28d418a8ebd8fc148be480e3251863191a19012d0cc98f851292f3b8854b32ddd1bb000d42ac9953a5bdfbdb93b1b1626f5cd0fb349e601dd36cb854778aec917448fffa5108feb6998f49ab8545c33d23a1c3cbf438449fe0986983bf3e2a1111e6da1f00101e2fc98df6c1a07920936eae3b79a6a8c22a7f07e94c17764be471272cb713971e908beaef70fdcde7a3a4631fff32f3ce1492dc49fd7ed3bcb3e5f98f73d1eb0011a4f5f5394b92e29b6c4422c909c421afc6d777aab9705457f2cfd68cd2ab236c7fd45cb6496a9df863f40f78f66e32cb1985049e479b2d3761e61bca4acf020b006130d6b7100001440a0102a8440201f407e0456fa0247ba42dfdd779dac402b5afeda387134c2f54ddc3a4000000000000000000000000e3666187c7fbd30ea514a00747f27bef2df27d6902000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc209000000000000000000000000000000000000000000000000000000000bebc200

**Comment by traianus1** [comment]
I am traianus in the discord, all right, it has worked, thank you very much!
