### ISSUE TITLE
wwbtc(solana) -> wbtc(eth) wormhole error, I need Signed VAA bytes

### ISSUE THREAD

**Issue by bitcoin1000k** [solana-labs/oyster#243]
I have sent wwbtc from solana to eth through wormhole but it doesn't come in.

I've seen a lot of people have this problem. https://github.com/solana-labs/oyster/issues/228, https://github.com/solana-labs/oyster/issues/211

How can I find Signed VAA bytes?

https://solscan.io/tx/3Mefek4Ue3BL6B94dRYahvkeEYjt8dEBD8Yi6Jf3mZ7ix3VvqH1tFSmXoCZn4dCFsrVJMb8FWh1VramxyYMSkhT4

![이미지 4](https://user-images.githubusercontent.com/55371640/131880403-74eb9fa4-5e9e-4a31-8006-7864e7f46e85.png)

Cleared cache but still no tx showing up.

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 76123af992a98501fca79567f062354da6de5bd2b8584cde53066650d91a150d

Signed VAA bytes to submit to the contract:

> 0x01000000010d006c2546faed4ca06c0a55ae8e2327df1a1381b213120868e26d9018d7ffe3088e0a351d1af13156b234c0d2053bd828f42d84c5e325a2277e29f2cb800da4116400013c65aa5feceb07d4264d02fff3a7008d15823d78915666240ed4f14d61b821a060fcc72d0149452e334ce16c3697d582024543707cc7a1d0fdc7e1df41b7545400026e8171df6efd49c2530b9476f7705c45d686de6e1dd9a034bb349b1b6ebac258550dacae45f2da5eb165166915f7f3253789a23759eea5745c045917f5744c0a01043378118a66e739b7d6ece32496dbaeb59a25f8f4943950ee20b56aa12f67ed581387b4555269f8e74a479045cb857c9b5920c8d03214f8d948b939eabec897d5000575469e3520322f6739669a525c14fed1fd2c07a2cb031c0950c11634e24be7c47d8a9f826ac3cbdb624ddef8fba0810721ad9e0082a407623969ea77857717f501073206cbb05b8433cae9dc87b1d32f22a2175cb7b96e9941aa6798fa6f65df7aed60b511dcb75260d0b3eb514319313a0b9594b59903cec6688b6c6558cd58fe550108da7b4934523c0011b86c579f2ff01eb31cda6d756140c2d76ffaee51f765bb615a2cd10c7bd6bc3b5ee63161b30d3a57c73c3fd2d7de5f004bdd346187f2fa1e010a16d11bc39d74d0db574995a7c1b5fae4930a888bedc79693495d17ace87cb2c1422017f6cb4cd539a9584f1efecbec57745a00b07d702704fa02a42b30ab2037000bca85a15bd21f733240fba5d1e3df47beb4ee6a68510355dfea784a0a72470a7604cc1c5f95ec21c2637452a2730423ff2419f78e37cc35f1bcda444e80c4f59c010d5de7c285de644d35d2a0426f212f00dc05eba08e30b0c3dd1900c06609767a2f46e8e07291c3e88943be958bf8821753719521969127310ef5672e00263ca738011079cc94dcf637189db6b9545047ed605aabe25b580cb0280ad99e597180249c044a817a2ef494475703ab648363037a2b7b5a88baf9043cb15568fe6c48fce2b601110b753b421db7c9c9fca6f8108190989937d8013e78010bf5739d2abf56fe7e2b2dc4d94d9c2d49ed371ad71921f6b4abcba5cf6c863c93c55b4f79838e86486c00127a5a00866f458723f1bda1505aa22fdadcc41963baaf9fe9bacd9d4b0c6f5a9e54af1cc9d4dbf7f259447d1e6d84c0e372cf161b34e6e7667ce18f7c60c019a8006130e681100000b9c20102d936adcc271bddb5ac7799939de3b71231b5e0c747d94a9e460d604d968f1bd900000000000000000000000082dc92b01c7ff54911842956083795f60f6f64f4020000000000000000000000002260fac5e5542a773aa44fbcfedf7c193bc2c599080000000000000000000000000000000000000000000000000000000017d2b588

**Comment by bitcoin1000k** [comment]
Thanks for your hard work 👍👍👍
