### ISSUE TITLE
renBTC stuck on the way back to Ethereum 

### ISSUE THREAD

**Issue by cmx250** [solana-labs/oyster#244]
accidentaly closed metamask tx back to ethereum for a renbtc transfer from solana

the tx table doesnt load - it just does the forever spinning thing, so i cant manually fix this on my side

![image](https://user-images.githubusercontent.com/90019448/131947198-c5cea39d-6d52-49ee-a399-5b168f73d788.png)

the transaction i sent to worm hole from solana is here:
https://explorer.solana.com/tx/CKCVRCDZgqQ9nVT4TwQX1FMGetyZwNt6GdLZXQmM82um9rqrnGDLLe12EEYzkn9edx9iLJUwGRPU1dMfYykFQPs

let me know what i can do, thanks!

**Comment by leoluk** [comment]
The transaction you provided is not a Wormhole transfer.
