### ISSUE TITLE
Accidentally declined my metamask sign in

### ISSUE THREAD

**Issue by JAYJAY8866** [solana-labs/oyster#245]
![image](https://user-images.githubusercontent.com/90021928/131952228-df639c84-00e5-4002-a56a-a8445a8b8a7b.png)
my transfer from sol BUSD to ETH was taking forever and i accidentally declined the sign in on my metamask, now the balance is gone and i cannot find it in both wallets. please help. 

https://explorer.solana.com/tx/s3mAK6BUSUXoqVJZ9TEcWC1BJoWWSTyf4iZ4x2w4FZbBErrh5SxsGfh83yWvMPja2vc9YVYz6QBEReStqEM4dCX

please let me know what i can do

**Comment by leoluk** [comment]
You provided the wrong transaction, my guess is that this is the right one: https://explorer.solana.com/tx/3AYfQr2dhHuiy4jyH8yttpmaqE3dKnBMwbrroLBNQaC8x6iWwPsbGR5FExYNVkTvke3L7cRM71Kg32YXznt7dD4D

The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 789d44175bf57eabbc85e834930ed1dfc73c72a9b20fa711e6825bd037c83743

Signed VAA bytes to submit to the contract:

> 0x01000000010d001482341eaf19fc9db15ec810be4cacc39e1b93310fd7ee14de4c72c4e46fa61e4dfda04865d6631daa043b69c41440e03d711ace955b437379b8cc4b46cf425c010154f861124249b3002e6dc4c623ef5b28f82a0b11ce4c33ed9081c6bdb2264af2004a823b0611e5dd29b71d33407ff8d597d237b20608368c5d6eed372fbc8e3e0003b66dbd185dc016d0c113850bc049015a0822256422459a223f487e00efa4f9945a89984c18ed4f20615b24a3e0fea842e198c18b6863c3f712f7704ae45155bb0105806dcd911cf4bf5d4894e4a2e35c4e9bb2539e8a203fecd84f0a23f768803ed9392d53725ae58b2ed56b767409510bfe17e52843c7a493ff569eb0659648d66501073ab6d3ed0e2ddd93e22a5f131db0755acb013edb05594e24546ac0df1f5708234c09f3455f73e878446d65088902aed5fb3c2791834e132026cad3f45de4cfad0108824dd69c18d2c110399f5601c333c2a862c7d2b5e451e91889c5e896517253792fcc4359138f8f63a2e942cca0b7fa1c055716ed245c2bc4397326503f43b4350009da3c3bee9847f99ba6b3baa8f29cd20c5ba6b80d24bcd7854fd4eda190e4328060175efb30e44d946165f62866c76fe4af45ca5734fa1ef6a0f171a6f89c0e5c000a642cad7fd2d68fb34e97f2752378fe1ca1db4c6eceeccde9ec94326285608b917b1e7adefc9bcb8e7ad6ddd2b7cf7de5d1dd4f70a06b73e715bf37a3fc56b52e000b1e26c7bbda0d3aab7690c650408adc11c576c6a94203180032af515ea6c17fc12abc90c429ddfe37a6f6dc2b72f1a193c873dc9da3622c01ff102c181a4d5f72000d55fa614930d9ba72681a1566e505e858c7e6e5262feb92342083619abe30633b60ee43a7340fb9b5716c10af01b92e4781d5d1e888c7cb0e94d8beb3c11caf2b00100e47b90d01cb6e4a1b3cf13c460aac4ac46bb6efc474bb33943786ab4436eded3ea83ef01965f771fb748d77ae6c837a1a351e4caff927813fb844aa95c74964011107b83dc9b531524412b283e84ff80cc6430738df976cb70347a39b08041ef41023431bb58bbfac7444791d7a4a2482376bd4bd18d11f4bd2a3d4fbec5acce6d001120d2e6e0943423d4f5d8d6b8709718c3ac8373599a72a42005f02c755a56f767a53d262c2a8205ab2bccccf4ba3106484d4aae48a2bdd54f74e357eae010f9719006131a5241000017ee20102da71156367dbbfa0e02bca6248f638e399b720b8906b3177593a03fa529932840000000000000000000000009da513f0656d5130a59593f8a27401c4d7962d53020000000000000000000000004fabb145d64652a948d72533023f6e7a623c7c5309000000000000000000000000000000000000000000000000000003d4befee057
