### ISSUE TITLE
need vaa bytes

### ISSUE THREAD

**Issue by tannishmango** [solana-labs/oyster#246]
tx hash: [https://explorer.solana.com/tx/3DiT6PcEt8pyXKEUdHkFDqc4v76fJVQqjGLtnuuYA1kua3i8P6bSSDNYqEjZyDWcXiCNhrejHzNJ3RDXDeumtWC3
](url)

Please let me know what the vaa bytes are.

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): ab2add86196cfa3dd9b2fec8f6d2614d2ece2f163a451dd31e707abf56c955db

Signed VAA bytes to submit to the contract:

> 0x01000000010d00308fcd5617c246e34d03e40df815ffcbb2d05127a04b54795d0548290f2b8e656e6eb1ac33eba31ea1b341b67cec94884bf330ad206805551a76a0759ce6847e010126ba0e8f6b51dd4697d81f5eba7f203e3e8392c4df1f417143bbacf853f8b60d7e8f1b3a831b9ad425eea255c73b6144651374db6d008388decbba2efb979a76010208bec32b3fe2bb2848b9009a3148d698ecc58f9c295c3cd24213749ddec6a2af5f115238559243836d1a3eb4f084f330a7fa0788ebb4c82eaaccc9456309899a00055b8e26dc20725099a85612dade373efed88844913a8c5b62dcecd478d1b661845a4a1de8725e70b970d050ffec747af268e8ee89704ea7a019d968e4e69b8d780006b3d70253727494032048bb6cafb20f20d2ee3fe9fe070d29e00a0354833a8b4d19309e7707f15fbf4aad5852a5f0a7f5091fa0d5144556abe40c49d46bf5af6a000743b1b05c74fd6a30fbd7527bead499e42fcd0fcfd2c74c2e2be85be1535971e73c5b6f58d94778c715fc72b1b6a6e31ac723a9bdf889ea837cbfa588412a8d2b0008418a799a9fcb3f0b83fcc99fd41fb5ecc896747f8dbdc5d1203f879a7470bec332683326a93f71c59b785539c8bc7d91e0d62346d7844e0318c4ff19a529b9640109809061c51d68d21c6e344796daa1cde34a193a689b8e686a9ed475a5222575af684564a36de1a2b232ec3012882fe9aec359edf5c693414960bf452672e65a3a010ac618e54fd69247a008c4f8ff57f67149ce06aeba63c7a65ca39a07f031590b2449cd4956795add9c6717e96aa60afe1e06285098683533ddfc2a0caa87ee74f4000bdd67be37be3c1d73f59a73a37b11e513c5b91893261c52e9048cefacb146ec0e3307a2ecf4088443a7e75cfce766321823a119064d5da73422d6b952e6102856010d77e384783b6366b5860d743b7fc8a75cb61f632504138c46fa3f097e6670e5f0320a94887d2f832eebab1eab93fd5590c6a53128593352f554865b256b87859c0110c6e1c449e8e7726031d86067fc2ae4b68794964b8c2f8020b5008309d667476a7904d4df50f94c3341566c8a7a1926136d15e03310528f53572fb630adac05960012e05ebbec71ce27b18b4e0bf1f4e97c245e7a11d1fed5bf5307bbf085bf22f68b41ac8930df4f2bbad1f2cc63595e7f1455a9899e973eca739598e3728f425681016131950c10000167150102d1f0f486dc932b220dd6f9d0d04f53f77045904c7c174ecd603a31f3cbd1fc8700000000000000000000000060b4f4a50cecef7a3a09270a4585107f7ac8cf1602000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc209000000000000000000000000000000000000000000000000000000002887fa00
