### ISSUE TITLE
wWETH from SOL to ETH (using Wormhole) Left Phantom Successfully but Never Arrived in MM

### ISSUE THREAD

**Issue by vb5549** [solana-labs/oyster#247]
Yesterday I tried moving wWETH from SOL to ETH networks via Phantom to MM wallets. Mid-transaction I lost my internet connection and the page refreshed (during a signing period of the transaction I believe? I'm still fairly new to the process.)

I'm new to this so I'm not sure what I need to supply to resolve the issue. Here is the[ page](https://explorer.solana.com/tx/4AZCcj1Li3WMEnRto25SDuV1WYdG82VC284czBaCiKd7MQ5heqYDZwjMrSbox7fmmq6qGWoz6yZXq1ZswoboaWU9) from the explorer in SOL.

MM didn't register the transaction at all.

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 75cb03d533c4a733137bf24f98dcbf0d72f8293262ddd05c262bee22987f2916

Signed VAA bytes to submit to the contract:

> 0x01000000010d00ca03678f00d3ac40343ea06249a51f248d1b04b94241aaf72b30044dc0ec1f1f21d5226b1f31506af9d05b9af0354ffd9fa6ee498b10e31e0e396a96ec7848800102b8a2955bae724bc644b6b57d22341de0ccea874a555596b35d594daaf6d658400e2860ce3acb422a9e6b76911e5fa22e60b6c48bbd903c77e8990a67e043dab5010376f351058f5ddbd5364202ef46bb30f5ae5b4cf7ecc9c2f1bb64091177e2ce60044af6ad4614fc86b5f3d2780b10132f8f1349065af30d16e08e92e8b294ff780004b64c1e3496c8c86bbfedb10bca9b380db3570db6da87de8aa7283e865f41960527960f31a5081b2fc75cea2d371b326116f70868985cd3d57a8796f6b0bec48600056b1c7f2781de751dcb7d1bb9e817d04ab75d91172d14536db296d7c349ae24fd6c7d00a969c44148f148cc8f322f794026d00c0bc6dcaf1c11b01c2f8d06fad301079f89d8b62dcdca5ad5ed5dfbf7cdc61e9417e417c8b40d930629ad190f752f9017e497a2e486fa1cc70cc85c5419d0b23341f6558241c916c097afecba174cbf0008544b41a2cec10f2070d889b105369b2acdda1f1fe9ccd734b9f6ffa6c892ba735effc28e0e67ea4570445668512b723a22a15c97110df8ff60a4b5e90f512f5d010a5cddd253519018815e9d650c700473e8321c9f9eb2d9886311e3a9e38d76a2e36cc827517a1034f37ec3cf67577735d1ce581238cb8db41af59bc4eda9e2da04000b17fa342eb6afe203c24d08c648781530fa117ab5c7460107e24ef9329a63de624f29d213d6c8fdc1b76057abb691a8539e46cf0b0223852d1e3c8f5c7df44040010d9849c743dfd137a2b61ff0c188798494686db78340245425947dc480597d65ba31eeec7d7032b55fc7e82da4953b9c862287861e22b0f0abc80a4664d3a49c8c0010205746c44173aaa156f5a3f0f7daee3c8e8186df76ca7d1b248d0bb09d56da775b7b39786ef00af0517f37c4110601c14f548b29d1f62ce9640d0e1b1cb5eab30111181ac5742b885892dbe544082eb8c13f4479641e3d18c326ce09f872cc0bb59c254c2a80c8e8fbf273e25108dd9bf38afbc7a743c06fcbc7d09e99e55518cf8c011220eb56b953d8d48d80c40f0c90b0ebcae4dc18e33655f3705627a77cb5f9f9d22e9f11b071c0218a5dba5df4214fb035966d03b39d8b60f60cec31c7cc28b1c401613194a0100001233801023254e1ff1c8a0c07e76199d5e411d292dff0a2ecd5bdbb3468cd14f2a9ec76a40000000000000000000000007b95632223964b73853322e0a24f1e224007424802000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc209000000000000000000000000000000000000000000000000000000001dcd6500

**Comment by vb5549** [comment]
Thanks for the help! Unfortunately clearing the cache didn't work :( 

I'll submit the signed VAA bytes. That's what you've provided here, correct? I'll *carefully* copy/paste if so.

**Comment by tseitz** [comment]
Hey, sorry for the noob question but I think I've got a transaction stuck in the same way. Do I submit those same VAA bytes to the contract or would mind be different?

Transaction for reference [here](https://explorer.solana.com/tx/5GEyPDCAuawwBWg2PjGY6qvqnPhiivWHn7BVDo7G3PLBAKbNzUMXyUpoX8VSSrcaUEeKpM72gZTMLZvBg7A52ivy)

**Comment by leoluk** [comment]
@tseitz create a new issue please

**Comment by leoluk** [comment]
> I'll submit the signed VAA bytes. That's what you've provided here, correct? I'll carefully copy/paste if so.

yep!
