### ISSUE TITLE
wbtc stuck on the way back from ethereum

### ISSUE THREAD

**Issue by caulinez** [solana-labs/oyster#249]
I bridged some wbtc to solana and got WBTC(Wormhole) which cannot be used for yield farming. I tried bridging it back from solana back to ethereum but the 2nd tx where i needed to pay eth gas did not pop up and now my wbtc(Wormhole) is stuck and removed from my wallet

**Comment by caulinez** [comment]
I read through how previous people got their VAA and was able to retrieve their assets. Could I get the VAA as well as the etherscan link ?

**Comment by pseudoanonymous-eth** [comment]
I have a similar problem -- what's this VAA solution? LMK if you figure it out! 

and yeah, .48 wbtc! That's a lot!

**Comment by caulinez** [comment]
closed as i got the vaa bytes
