### ISSUE TITLE
.2 YFI stuck in Solana --> ETH bridge

### ISSUE THREAD

**Issue by pseudoanonymous-eth** [solana-labs/oyster#250]
I sent the YFI to Solana via the bridge last night, but couldn't figure out how to swap it (Raydium wouldn't recognize it as YFI), so decided to send it back over the bridge. 

The transaction appears to be stuck - I don't have wormhole YFI in either my solana wallet OR my ETH wallet. 

This is the transaction ID but i'm not that good at reading the solana block explorer so you probably have a better idea of what's going on if you click forward a couple transactions (note I also bought a tiny amount of YFI on Radium so that is still in my wallet)

https://explorer.solana.com/tx/4aaKUwDjEVSKQgFFb5uhQvqL36bRSQjwJCv8WAuAwU6HZV8VmByvvR9HypCm12mgaiCwNuNVBPcqnkKNZDodSYpc

Thanks

**Comment by pseudoanonymous-eth** [comment]
Here's the token account, paints a cleaner picture - https://solscan.io/account/BmRW7LTCKdu7qL6GSJvriYbS1kv7Wg4en8V9tJsJ4hgR

**Comment by pseudoanonymous-eth** [comment]
okay it appears that the Submit VAA transaction never got initiated on Ethereum... and I assume this was probably an issue with wormholebridge.com. Can someone tell me how do I manually generate the bytes for submitVAA so I can call submitVAA from etherscan? 

https://etherscan.io/tx/0x4c80c86caebf269c4262803f11435353351210d57bc657c961c4f15bf0dc17ef

**Comment by hx8888979** [comment]
I find a way to find back VAA, and write a script to do so, you can try it at https://www.interstellar.tk/ source can be found in GitHub

**Comment by pseudoanonymous-eth** [comment]
hell yes! thank you so much! sent a 1% tip, hopefully his helps other people out as well. thanks again!
