### ISSUE TITLE
SRM stuck in wormhole - plz advise

### ISSUE THREAD

**Issue by joeschmo54** [solana-labs/oyster#251]
hi there - I was using the wormhole to transfer SRM (eth) to SRM (sol) and appear to have minted an unrecognized token. is there a way to reverse the wormhole transaction? im not sure what I did wrong - any info would be greatly appreciated. associated txs below:

https://etherscan.io/tx/0x57fddf57554ff29638388d3f7fcd7d7f75e4b5dcf7c26f10b5f68fa674b82fbf

https://explorer.solana.com/tx/fQ8QZ3G9qbrXAUg2QboJ6gacFszy3PUXP5EyiWSa6mnx3tUPafXgFWW6HW2AM3XFca2extUMvdr8ZMMQHLxhymg

https://explorer.solana.com/tx/32Rjpsid9GCTPpmn4LAGYQhGweiYWN7MCpfrbWdoPCn2NXEyGFsfHzcosek72okswi2644XeaUfu8JZBDEqdTCDt

https://explorer.solana.com/tx/489sBfMK3xbx1DYQxGbEvDJeaTHg3M1j7NHvLSTXxFGfijVVN47akiwdyuYe8aqHHmadK31xz9ZXSob1piMhV1Xa

https://explorer.solana.com/address/Brkcsib9s8ZpTDNVTvMK1exH24RfS7MFUPszJhvf5saQ

**Comment by yamijuan** [comment]
you might have gotten wSRM (wrapped wormhole serum). It is not recognized cuz is not on the token list. Try on saber APP and see if it shows you balance under wSRM. https://app.saber.so/

**Comment by joeschmo54** [comment]
thx for the quick reply - you are correct, I can see the wSRM on saber - can I now change it to SRM (sol)? if so, what is the easiest way to do that?

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by joeschmo54** [comment]
i got it!! thanks so much!!

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
