### ISSUE TITLE
wWETH burned in the wormhole when trying to birdge back

### ISSUE THREAD

**Issue by johnp412** [solana-labs/oyster#252]
Hello, can someone help me figure out why my weth was burned when I tried to send it back to the ethereum network from solana through the wormhole? I approved the solana transaction, but then rejected the eth transaction because it was too expensive and now my weth appears to be burned. Transaction hash on etherscan: 0x438162ac938d57b98b3082fd76250fadf28c6ea2a43e15360ba27d0ac4a41560
signature on solscan: TCWpH2JLdBSkHZVmAELNCnhtZarpWx1mTiT5CRB92rgxJ7VmHsbWoaJW7VAgkFvmzLoiH3JAsSdwdpv53TE778V

Appreciate any help, please let me know if people need more information. Thanks

**Comment by pseudoanonymous-eth** [comment]
I am in a similar situation -- approved the solana transaction but didn't make the ETH transaction. 

i've gotten as far to realize I need to submit some data via "submitVAA" (you can do this on Etherscan), but I don't know how to make the right input https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

LMK if you figure it out (or if someone who knows what they're taking about here can give us instructions!)

**Comment by curiousgamer** [comment]
yea similar for me, https://explorer.solana.com/tx/Hm8SHxyUQWjyznSL3zxo79zgJSTHpKqYaiGyBcXfproce8Vry7hdLQCW21EJwB7Q97ee6FgudnAp6ia1rRYkeXd

never arrived into my eth wallet

**Comment by leoluk** [comment]
@pseudoanonymous-eth @curiousgamer please create new issues

**Comment by pseudoanonymous-eth** [comment]
The issue is you need to call "Submit VAA" from your ETH address with the proper byte code
this person @hx8888979 wrote a script to generate that byte code based on your solana TX. try it https://www.interstellar.tk/
I was able to use it no problem, so am sharing it to others with this issue
they put the option to tip fyi, if it all works well for you

**Comment by leoluk** [comment]
> Hello, can someone help me figure out why my weth was burned when I tried to send it back to the ethereum network from solana through the wormhole? I approved the solana transaction, but then rejected the eth transaction because it was too expensive and now my weth appears to be burned. Transaction hash on etherscan: 0x438162ac938d57b98b3082fd76250fadf28c6ea2a43e15360ba27d0ac4a41560
> signature on solscan: TCWpH2JLdBSkHZVmAELNCnhtZarpWx1mTiT5CRB92rgxJ7VmHsbWoaJW7VAgkFvmzLoiH3JAsSdwdpv53TE778V
> 
> Appreciate any help, please let me know if people need more information. Thanks

Please provide the correct transaction which burnt the tokens 
- this one failed with "insufficent funds"
