### ISSUE TITLE
Dai stuck in worm hole - please help

### ISSUE THREAD

**Issue by hx8888979** [solana-labs/oyster#253]
hi there - I was using the wormhole to transfer DAI from SOL to eth. and failed when mint, is there any way to find VAA bytes?
POST VAA:
https://explorer.solana.com/tx/2wv7LruAjLpgRbLVWyPuz1T6xiptASXsmoaBCEbSyTVKXLd54cE9aX8SFCFgKXHVpxXPHNyEP8uL1wpfNuHFsYLu

original TX:
https://explorer.solana.com/tx/5ZKgYnRiJ9waydmwYpsNcX7RuhGVCy44x2pw9bfoFctKgDQQJrXrcUWPv1hgNU5MwLBZAMnrrbsbh9VjmkXxmbBg

thanks in advance

**Comment by pseudoanonymous-eth** [comment]
I'm pretty sure we need to figure out what bytes go into the submitVAA call on ETH here https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract. -- but don't know how to figure that out. LMK if you figure it out I'm in the same boat

**Comment by hx8888979** [comment]
I already fix it by myself, and write a script to do so, try it https://www.interstellar.tk/

> I'm pretty sure we need to figure out what bytes go into the submitVAA call on ETH here https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract. -- but don't know how to figure that out. LMK if you figure it out I'm in the same boat

**Comment by leoluk** [comment]
Cool - thanks for building that!
