### ISSUE TITLE
0.17 wBTC stuck in wormhole. 

### ISSUE THREAD

**Issue by naturaldeflections** [solana-labs/oyster#254]
Hello,

I used the wormhole to send 0.17 wBTC from Solana network to Eth network. The transaction was confirmed on Solana side, here it is: https://explorer.solana.com/tx/48vvsedVSZrmUPaqpysDJ8qx8cZg4ywESoeDHEeCWPYNJonEtsjQTxozEerD4XvVW7MuLLiNU2gf1gSTZoQeN7to

However, I accidentally rejected the signature request in my metamask and I don't know where the 0.17 wBTC is. Very grateful for any help so that I can get this 0.17 wBTC back.

**Comment by pseudoanonymous-eth** [comment]
Wow EVERYONE is having this problem, including me! I'm pretty sure we need to figure out how to call the transaction again from the ETH side, here's the contract. Not sure what to put into "Submit VAA" though https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

**Comment by naturaldeflections** [comment]
this was solved by using : https://www.interstellar.tk/ !
