### ISSUE TITLE
0.39 weth stuck 

### ISSUE THREAD

**Issue by ciggu** [solana-labs/oyster#255]
Hi, I have an issue with 0.39 weth which I was trying to send to my eth wallet from phantom. I couldn't finish the transaction on metamask due to fees, but the weth from phantom were already taken. Can you help please? Thank you very much.
 Transaction: 3q5tixhG6jKd2z5KFyTnTnvzHC3gxL7vLNQFQVPPoZsQYTP9fSSCxF2Wiaai2t1Yg5XAcmaRjTQRwrAbXJKih9MD

**Comment by pseudoanonymous-eth** [comment]
The issue is you need to call "Submit VAA" from your ETH address with the proper byte code
this guy @hx8888979 wrote a script to generate that byte code based on your solana TX. try it https://www.interstellar.tk/
I was able to use it no problem, so am sharing it to others with this problem
he put the option to tip fyi, if it all works well for you

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): a496e3c39bb528a4245574cdf144dcdd244d84779ce6b54aba9be0bb448bc134

Signed VAA bytes to submit to the contract:

> 0x01000000010d00544f1b44bfbc0fa8726a20291d7aff8772fd6ed1ec7aac3cc57bb114e06f71e55316d9386f32b861a58760b1458994df4303a7b3f177686cbfc17ddc0b0c14f8000144d40e98a785376406398d5b155f0e7c7c46cf8ae98b50209241a9ff8f9f77415b7ea47602e7cb2a67a156f3caab80f5562f9338a4eed0839f54587ee5384e7400022471e37bbff6594f6fd9b6f10e8a990c8946916817ab922c6bbc727ecfd4aa3e286cdf3db21775e030312ee62668e090d3d7bd3f4cf817427fa92f2f8c2c30760004ffbd2c8329379c910d59c92b5b0107e2a9af20a75961fc4b5ab92d2b1713b3822c3e73760da2b622cdb3587f685aa735662b3c6be6f17da6b35ff4599b42ffed000521c765113bf651af8954499ba19101834320d1a6602d054fea5f2cd286b7ab3b6585aa0e01419f3b9d3e6a8a3e39420236f4360dc7ae9fa606d34a626c409a460106918c4a0f3ac68d547fd1879f84388b5b9ae0caa93379e5a76bcc18863d5a6d4629eb4adbea860c6704eeb0b9a609aafab7eb88d2a890ae5257fc62e8490a9af30107dc825ebe1bdfd61c9d83ef088defaa45106e7f3b94534dae833df3d2b6eaa1853661d3dfbfe3a81f0175077859f3dee7500a5c768727bbc7c0f35538ef3b04d100084584d8e8285cfa17edc3de18a9627691d7f2d8f177c5c5e4a55ff778b9f62ffd3ab7773a0f7465e9bb9522c2a78780d2bfac61e7748444f6203c114d35b3671b010ac679245d12f75debbc2e64f6ab1a4c9589ac824b5d5f688185d0d51ba4b7dc7530c4812cdd9f4fbc3eb56024237b72566922a07e45fad15809228635b2b53cc8010b55df112ba42f5fd6ebc912dbe2cebd77e6b3d0c2058cc315a922773a7ad75311315defe702ba9663518a0edc0f0fcd7aa0a8478ba5770c652b963ca800a0aad6010d85d41fcb720db1d7d096f40c5b440768a628e09989bfcec8e0316d1085743b47714661f348b08460ba5e000e8026e01aa8ea2be5916a00fcd9904eda60fd688b001110b7d2aa5fe83e4081f56ed407f8b44fee8a4c2e571da1f31429c4ef427691664b13264433967e7fb857f64ba5f25b363ca3fbdfa4a8ad44ac76784800248b0c001226717a3ec9cf5077a80dfff2f2f4d1c45120995ad458450dfc84a23312349ca147ae458413998e3f03af4bd7b270bf1a18f957cca6fe71b2f3ed0e25c5b5519101613478f41000004f430102523e3d293286096d6a6a98a80eaf81a2369a0aa0cecfd0ddd808c1369a69baf2000000000000000000000000ccf726bc9309f126f8ca06160e718bfa73420f4e02000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20900000000000000000000000000000000000000000000000000000000173eed80
