### ISSUE TITLE
lost 0.3 wweth 

### ISSUE THREAD

**Issue by yodolph** [solana-labs/oyster#259]
Hello.  I was trying to transfer 0.3 wweth from sol back to my metamask wallet.  i never received a notifacation to accept the transfer on metamask.  seems based on research i need to submit the vaa manually?  Could someone help me with this?

Here is the transaction. 

https://explorer.solana.com/tx/3zWEw25VrSzvCVgGKwFDLnWSgoY7UUAZcZJTWS4Jp3KyCoAvjzNx8dkVnNaTTHpUNNCsX6r1Mr5egzS85FD54XTs

Thanks a lot

**Comment by yodolph** [comment]
also i tried using this the interstellar.pk tool mentioned in several posts and I kept getting this error..  

9/6/2021, 2:53:57 AM - Transfer Amount: 0.3
9/6/2021, 2:53:57 AM - Target Network: Ethereum
9/6/2021, 2:53:57 AM - Target Address: 0X29380AE327DAD64C5B87F2672076EF00210C5A
9/6/2021, 2:53:57 AM - The target address doesn't match connected wallet, abort

seems like for some reason the target address is missing two zeroes after the X as just above the error it shows the address as.

0x0029380Ae327dad64c5B87f2672076eF00210c5a connected

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): c528960505784bcc303ba32dbe9281c767069fc325895917db84e2a37d34f6d2

Signed VAA bytes to submit to the contract:

> 0x01000000010d00cff05d0153b1aaa3bf90550c521065274e9bea01967398ba0b22d043489f60b25727c93daa8f74337ff4e3f73cc55207acb6a121e32a0da40bec9b073c38bf4801013ca1aae46cfcf4fd1c2b1596b46922d60e2cbd7fa98d382b90b9fc29d03fd00c1e981d5d044456d2e3a34fe52ab994f990e5ce957b43f7a69014492fb29dc0e20102b954004b392800d0e84008fe804da7d8329d6e1171090a7c742f32468e9c922b1c1f667ddf4223775faaf14af68626b0856eb2eb822d5ab6f7665a45caeae34a01035eb2e0caae8da6c434b84b28a090a031b5f16d23f5237a5dd41b177c800ec324113fdc590ed1ccd9953549abfbce13a7d73214dde9247d733fc1bd5ec359523c000428eb230d5edd158c436d284d74694f9a5486ceb2cebe02b402de5cde96f3ea32383ff3c3bbfac4fbc457bc0362cc4a1501065d5b171031fffd90f9a8e7c9dc4e01050abae02dc85a7b599b56a7def88143f3209ca82c81baf7ff5cebed34466d6c2a2cde9ddd36e0bd3e871c06743347acd7f1b0c8c990330ebffb7a31627b9dc89d0007336e7deb7433c7f0fa17fe762153a97e658d65cbabaaa6d42d94d63f61d2fe6a5ae7ed85cceef4d209dffd60128921141dcada112949e1eb52268992c3c2ef810108d1bba22a43af428463c398b89b7d99ab104e0a2f0fe22e81e7a389b2f1af54b65e2955986bbb8c8cc4dee3296e96342cfa231c6225e08aa622f958226b272445000a5cb5a62d59456f840b870e2445fd9ae0163aa2ff55e3eb87a954846483bb581177b568995bf6db5f272374b5692926edab7bb6e1cc977096de2a035b4dda6024010b64b9b67e3fe20d1c93f280995eaa3bad18c12e9829a9084eb4af734c10bd8a194d5d8874b75b42fac15c1fbc29fac9831aaf6e5553d9c6a6d6c10bb7d84ca274010d40e211932b4192a29a5139c5de1546368b862785756c28bece571ddd063f191e522fbeaa512859d0660696ab5a7dec0d1a20ab1598c5dbd3d7195ec95e2e5e580111b8119bd8e8bbeb4ff83cd98491a08fe0aea4e2e9256982fa2d70abb6e07e5bd403970c60b2cd7b4812d6b7c417c6c6ebf5e194273b6c45e00d304f05aea16539011206fb4099ed306b2a3016a1417d404d991ea01ed81991d34e2ac7a86fa53b385b4a049b0b5f593be9f89b25114517d4473cb46d081f1d499652dc64d7fc567f130161356c1210000068ef010209fb04c8b420fe29d4796c2dd512cf0dcf

**Comment by yodolph** [comment]
thanks @leoluk  but metamask is telling me its going to cost 100k to do this transaction haha.  when i try adjusting the gas fees the contract throws an error saying insufficient gas.  
![Capture](https://user-images.githubusercontent.com/31747024/132258498-1fec65e4-eddf-42ee-8059-58866abb4e51.PNG)
