### ISSUE TITLE
coins stuck in wormhole bridge from SOL to ETH

### ISSUE THREAD

**Issue by d0llarbill** [solana-labs/oyster#260]
Hello,

I Bridged TUSD from SOL to ETH using the wormhole connected to phantom wallet on SOL and metamask on ETH mainnet. I did not have enough for gas on metamask to complete the bridge and closed the gas page. After this ocurred the coin balance disappeared. I can't find the transaction in SOL under recent transactions in order retry. Something is trying to load and won't appear.  Phantom wallet transaction: https://explorer.solana.com/tx/2rku2ffeS97SWfETYy2WrMDfCua9o4fomrAuvN7DAeE3seiVHfEYYvU8wQhFyfbVh5V94KccKuxV8aL6xoV8wLm3

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): e5798a8199c4aa5c1cdd9aabea99009d1f95db5b2bb6312d5aa94b95b2b10443

Signed VAA bytes to submit to the contract:

> 0x01000000010d00ec63054b3f555783089b8ba5c2e4793acf4a1e574ccc7850291eeddfe9aee54a3e06e0785c08b9284b39b0dea139902b08db171d3c96e6a682c288d79a24313a0101a28623b1f0d4d02432ce259d29b82adc7bae4eed92c06bc7286f74509aa2c6bb25010e60865812c9dd35d5bc67ac4e64d7c1943f160dc6e99ab27ddb91c65a04010255f3965ea70a5fe21d840cabab0bd67ea73dba0ba3891241273c04f13fcb45b2460b49436cc89e8a0ab048603e22f813b043f68876d29d99b9156e29a9f1749c0004a885b92f7ea480f65e193a6e2e827fe506f605781f3fc64a1941d2afd1665969772ed07e23de808d8361a57834afa9dc83e34e1bc7e7e78140e0e589cf7b330701054da4afd3d8855001a54f0175f0b6934fa0794773fd3f4cbb833ff5e1583a296b7210c09656b8db260c8b84f6b5c7ad792fedf44296defb4896041f3a79af7a980106443cdf5e54f5d6cb56823f657477f951f6612856888d7422ed5c61aab8d0dc060c125cfaf59b6c9fa146ffe13191b5b6c59e3c53bf5085448485f3acbd4eb56e00072de1df6ebb2111fbac8b0b57d0958473af8dbd6c0092e8f23ad9d9faf35bb1067614dd1fea012ecc45d8dc09ae517fe8a3e1872f44d0e076c7b7a41bdfc986d001085685d16a5a21d58a56fc75284bf1d63f3b3405419cf6e11c07cc25a48ff33a1126d80b63481da9ad2c2dc17c1222cefc3fdc5a532ecacee3ea85bb8931ee2064010ab5d55d979c89cf9c90e730d7914e1c1de522dd1fd11b45aa063d122ec3efc2cb6019ed6eeb635a2e2c68436ca14f692cca754b90b836a6e874f76162757c4f12010b34a54432ea4de71a7104a338f9946d5952f4b9333c97dca964eb7d95efa986bf50906cdfa5f75cec715b2ac17172aa52cf758c1d7e32fe086224aa1e18df1038010d34667c6fe14899fcbc1b47569714afab85473815bdc40f7281dfec7e52d8c6ac271315cfe8d5bf5958959d5c4e0e42d1d05b4f23eaf7cc2c7c6e64323b967d2900111ce98d6ef8130319eb9bed8d1b9fa6bdc63f316f70136afed6a18e4fca01faf85d2de762604e339fc989167c6939f92e2a9281c42280301b6be56ad707dfb232001208b916819ec0d9bf3f4131a995f0d9cfb4a1a8527962e964af41b1bdea7f6c7f377b1e303a16a721ecd1cb61277a3fdcefd2c678ff8733851523cbf165af781d006133cf11100000c4ce0102ed6d3a683a61ce72523ed0f729e4c7c35949089f60c8943b91865f993fbbe083000000000000000000000000de7541b306b0edb337bf47895962cce43a34964c020000000000000000000000000000000000085d4780b73119b644ae5ecd22b37609000000000000000000000000000000000000000000000000000000fff0259d38

**Comment by d0llarbill** [comment]
It worked out, thank you
