### ISSUE TITLE
Sent WWETH to ETH - transaction rejected, wwETH gone.

### ISSUE THREAD

**Issue by j0bbyteam** [solana-labs/oyster#261]
Hi there,

I used Wormholebridge to send wETH to SOL. It went through but I ended up with wweth (wrapped wormhole eth). I decided to send it back to Eth to just change it to SOL and send it to my SOL wallet. The transaction rejected due to me not having enough eth in the wallet I selected. However, instead of it just failing, the wweth is gone. 0.75 worth.

Any help to recover the funds would be greatly, greatly appreciated.

TNX: 46B1fM7fFXNBtbN99LnmML6bbWq47dwmxVUM3whBZZJ6Ag9P5chp58pwxY3ynt7hnu4MoD3ZKmfhicAEFVJidCak

Thanks!

**Comment by leoluk** [comment]
It's not gone, just waiting ;)

The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 13c4d6b7728ff4a44f07e7d65daf1de9010a5809d6834357b8dd180e72191eeb

Signed VAA bytes to submit to the contract:

> 0x01000000010d00a0c63ad6655be93f039b0fed530efce159c17f652928be90c6681505cd9e0e894ba401b7e5799cc1a0f15addba57e82850bead61144988d3d5fd49d934c4039500014174cd6d3fb6a6f7f4b7d31424590b97f9a7ffa33cce0396a479fc7b4dd4ba080ff2c1ed9606305b1f3247719d1fb1241cab568ddb463c59b1b372750a898ecb0002ea74d4946f16f3a00192082c12c6545e07049b2ed0ecda3848e5233278b1536d4a77ba4cebbcf7bad1f1bb29506c97dfc6dd4a757d05d51b2053f2a4ce104edb0104b6fd16cdcb791ef8ebb530b9b6461823533f587a568d69a9aa4078f2823d679639842aee74bc9b18ae1b7e9cb894c696c0d0d1b643829bc40b2f10feade4acdb010591201df07dcb4af136513f086851419b1f0d1c01c214f0e5dcba7755fcb7a3f12f38e451f84023d68004821c6fcfc991f4a763697e19fac9f4b80c20f5b0bd6601068f73d082192f413e415a221ae836df32ff8491e3f16ad28f454f284dbac0467e1f71df9959c8ec5fc15ea2a50d5153eba4c2264761bbc559f8640843290891360107616c2b57a27260a4be036ea01041a8c7e50c927059c67a74ee39d1ac9c563e263723bf5a599e5bf8c7cf2b2e1de140d8bc219faacaed15ce6b937e65c2366300000883d21027db0a34815d141f4d19d5cf236d51f79605d59750fc5c11cae6175c975b10c389db5c9d933edbe37ca0b694a6e5852ce4f416a3fc0ecc9672f5bb7ec0000ae181ad82e593418a1fff49cd5de929012f73a6a7e36e82d389ad06da5e13c20516b7291b8e83962e233b9cc14725ba8cf91ec1fdda2d65ae5300fea8e1ff66e0010b3744930b4d156c25f4c5cc329ebfa04f83479b1b64f3815043bf6a3575bb66943d89d01b352ae1fc99ead4463405d70fb3c4586d0aa81806e098179536bcce54000d7e86dd5c417c92bdfc3ed29cbf1c6d8b88438755ac43cd88c515cb7c66474cb279f3e5dafb24f42efe37de892534614864c3691605178092097c55ee420243d10011f9c4103f4448cfc676c712166c8b7e53125caf2fe8a57ecd376a73c0b157516957bbdd11a00f35ed2270a52fcb1bfc5040bc85fe084ed4bcc3da753790bc3013001284d4f50dd4c6534459c304cb0bbbb0a60ea9b44c29170e67136ee3ee82c0b8665574ae5ee567f5b3cd1c08dd3c1d0cb2d3fec6957b2b0553275467c3954820740161363d9c100000f283010232d77b2660f0f9663a78475e7b2edc4ef9bd55969f466ccb3c5df9b264427a8e000000000000000000000000fb3478ff46bf36659f3801580bf026c700a07e2902000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc209000000000000000000000000000000000000000000000000000000002cb41780
