### ISSUE TITLE
Cannot bridge MM token in Solana to MM token in ETH

### ISSUE THREAD

**Issue by beartuna** [solana-labs/oyster#262]
Using https://www.wormholebridge.com/, I put in MM in SOL (ByjsSVF1FLHrMDVR1tw8tpMwSjR9hnW9YBHjzwGPbjhx) to bridge to
MM in ETH (https://etherscan.io/token/0x6b4c7a5e3f0b99fcd83e9c089bddd6c7fce5c611).

However, I received an error in the Program Log:  `Unknown` instruction error

https://explorer.solana.com/tx/2LmbCcncLz8kF5u69wA5bsxGgcgV5Gmb69bv6LsK8MBpytdDBav9CC3eoa4vtmJhnmBJ4z8qE1EtsoayhjVUUHgG

**Comment by leoluk** [comment]
You need at least 0.09 SOL to pay rent for accounts that are created
