### ISSUE TITLE
AUDIO Tokens Stuck

### ISSUE THREAD

**Issue by tseitz** [solana-labs/oyster#264]
Hello, like others I have had a glitch with the UI where 150 AUDIO got stuck. [Here](https://explorer.solana.com/tx/5GEyPDCAuawwBWg2PjGY6qvqnPhiivWHn7BVDo7G3PLBAKbNzUMXyUpoX8VSSrcaUEeKpM72gZTMLZvBg7A52ivy) is my transaction. Just want to confirm the VAA bytes before submitting. Thanks!

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): f10669012a51c5defa8e003495e3cbbf321631fe52ad602cb43802a2a6e6966f

Signed VAA bytes to submit to the contract:

> 0x01000000010d0035cf249440a813216fb51083b0b207b0e9eba17f039f43e841d18ce6c095ea00523fc328be81a7e47c5ff13c417fe38bb952e9eebe60bfa1627b0085df6d1592000113e2b5ded3d62720cca0176708141980512d20a144931062f0e4d1f908d44ecf1565b487298f1263750ee8f41b8b7c1377af34f3458a0169b51805e5ef23147a0102cc0094f20495bca979f5662e330f907a8af7ed0ee93310ea698cba92a9138c4277668b37ffa28054c0a4d43a2a9abbcecb9f6800554d20055ee5a892f2c132710004159d73b55d88aaf2b5d7b832a58382245eb4c3d4b4cfeafbce5c0ead38023c0a1e3d4ff7c05259038b42e016de89f7d117fff592ffbcb7aa2a9e70c5d51368d40105f23e52a1181b573c5d9b0bc56e11e300721202f4c2daec39fe1183a4469a857f4546b3a1d69fb1d62561301a2f2f9fdb0545ccdf1bf1f6cfdbfa8db2e6f258220107b5f3a357300bce7c82e03a674c5e0e2fe68fb918dfa719fb3c5adbb3afdfe255301624492777f5b8e4369deca761d4067888e0ff7b4b4ad3b7c426a2aa29cf3400083891757252d79f5e3f32d86cabfa6a6282b31dbad43704e80918736ad9702a664566dded90c9090abccbc1cfc78bff921eef2c1a8826a65f5ce0b880c230d5ef0009c47474a7883f719ad5b54319dd12ab9464787a7a337b518850af5a4dff1796854de677c1845c25966d0ffdd3094e2ac67da1d5e7cb228595a3bd8152782131fc000a7c7ef9fd1fb632e475c9e2510ca1a65f619a53b298a8d3ddb8c759a0d41a16b971882460b3375ac9b67996359922370bf53ca17a4e89160b0fc21e99d5c153ef000bd277a0b2aca738ae644a82b691e237aefe1237d3cbeb02d40c9bfe204e5b8c726fc01ca61d8795bb8175b0947a0d0884c3ac35ce8d235ab8403dd35ef491182c000d36ae71ad01fc4b8c0a5f11e5f4d4ea53e6f889fdce4ec709692c420cabf2021a079aadad23a4b05140686b921bc600831aa72101bb1f49eb44409bfbe04f23890111684f70db4ac06ec21c62ec6ba1d58b7dc11bc7a5432f968a88faa088389905bb514453be381f12e5817be808c51c9f1529f1bfa830bd63e973ad66c3a22f54f801129591e099beedc4cdfca85d7e3c62c3166a47c1e81f0dfc097652e099916ce21e1fe74255fdef1893037790f78e43a38473a3616f9cc4cc558d102021b17ba82f00613283f91000011eb801024454ab84039737d128d38c433f7b3141339a72203f2c5df14cc8dbf9cf725047000000000000000000000000266d6bc2262cc2690ef5c0313e7330995c15eedb0200000000000000000000000018aaa7115705e8be94bffebde57af9bfc265b998090000000000000000000000000000000000000000000000000000001d1a94a200
