### ISSUE TITLE
Tokens stuck in wormhole

### ISSUE THREAD

**Issue by KFCColonelSanders** [solana-labs/oyster#266]
Hi.

I tried test sending 2 WLUNA from Solana to Ethereum via Wormhole. Here is the tx ID below:

https://solscan.io/tx/2eJ5PiguE1JpXDaaJCpSFhq4cBK5NEwQZFWsdYd7gkYyefkYF76Jrv4bbSxezeRMYQTCc93B7LKJUf19297AR1GH

I approved the transaction with Sollet on the Solana side, but I misclicked Deny on Metamask. Susu on Solana Discord Support-Wormhole channel suggested I do this:

"Hey, Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected."

I tried that and I didn't have any success with that. Are these coins stuck forever?

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 0a3f7b56da417f97c47658ec3ed0dbe128105c5427a08749372d6dabe0a93d91

Signed VAA bytes to submit to the contract:

> 0x01000000010d002cf7f3a8c0b1df8f76c5ee194e7e1eadbffa1c62e644b6bb5775d8410a5b8f8f4eeca1dbe88dad9584cc6d46c03a9c532749f64a85e65844020b66b612df06d8000107f1be975cde398cead73c9d7a63551ddc5d82704b3912bc49121d0aeb698b1566dd26e36742ce8e0a9f05e256447d018920876b03510be8085d308e46b089750102068346db6bd78a719e8879467903667b68a12a8c042eab351e9f0dd45867de740d96175933dbb36e6580e353bca6ce5616084817154b10dbacc2b871fd283e7d000469885b079875c7d066d923c6042db923a7f5e444f9f263363b1c4c0848e909f5370c2a2b029e59a6cfc26013418edacc4feceff5b7560f0e9b693d56292bbb33000539cae2ca3f874093c76cf8158a19da9b0bc9e0f5e2d02c11eb1cf82d6b1c8ca529cc1b8076e2b30ce7e9cff4365c7744f0db87c89e9e675791901f27f64a7f180106ae8027b7221738bf743efe859f17b29a7bceca9650ec5896fd0b58453a1c9ad93357eb407c713b274ea58359d5519a7b6959c4a4248db523f05ba73eee18516b01072b1ef49f31841b2d9d8389c1523691b4e5c534fab95c5cc55cfcca93a46e5e79784788678e639b2dd0bfc2508e4da7fc3368dd9a0ed3f16d688bed4b8e5c9da50108e232827f3ddf8ed28db6e592af813e76b5b6d9bfc71d5633f4516d743ba657504ed7c808f4f8328a45c50a7475e8c150c08dc6c7bb062e9d7f5688da2cea49a4000a96fd12608b520f3b236eb6022bd89f5972921635ae0a68706d5493d34b57a81a3e3e6ff39dc2a56ece5b2f2012201ec2238e436cf46b7f7821b5e0e06433185e000d03e9a504412f30d738276ca183659453f81dcd6a96b1c10f1fec6e5ceb6cec461e7114d3a00e2f45726ee409196f9ae1e20ffa0549afe0b3e1b59685a5656095000f6ba9cc61f3d8178b76b809e268ab69aa8f8438fd06067fe80cf102ddad195f67354223314d96fe40b2371aa7b1187b325df6c571f0259043428e74b4dc57c6eb0011c52d3da7882f06ec17ec2e6814f15bf5b6396589c642eaf31f3b6ce5115beca86f1905f794d02bea93e13de40487e0a63d829ce2b633e93ba0e5a4237c49b7f601126783780a3d85a6d0b38560f53403dc2a0ae3bdf3c3f8c744fc71ee66f1526e271a51a8226a040774aeb3194de7804ba7c68fd7c9a99f177449300c7ebe0300c8006136c80210000047fa01027b5e129cfccf5a794c7525b0073001ee5e2cc22ec7d91c28521cbbc3c0b52711000000000000000000000000fc8614e425bf5d7d36ff3fe27bde99071c7afc6402000000000000000000000000d2877702675e6ceb975b4a1dff9fb7baf4c91ea9090000000000000000000000000000000000000000000000000000000077359400
