### ISSUE TITLE
Unable to receive 0.1 ETH back through Solana Wormhole

### ISSUE THREAD

**Issue by joshuad31** [solana-labs/oyster#267]
In this transaction here:
https://explorer.solana.com/tx/43oKWBp4wjcZNyQBqjF4qYYrVDL2zPBm9WR9EUKrdpxoNr8Txq7B29ZXSCchkRZmZe21CvheftrNoffcu88DEADZ
I sent 0.1 ETH through the solana wormhole:
![2021-09-07 00_59_43-Wormhole Solana Bridge](https://user-images.githubusercontent.com/5976059/132292446-1a366191-a126-475c-a33d-3feef893c380.png)
I then has to use my metamask wallet to sign a transaction enabling the smart contract to work:
![2021-09-07 01_00_11-](https://user-images.githubusercontent.com/5976059/132292514-35b6c4d6-9486-4ec7-ba04-01a855494dc6.png)
Unfortunately my funds are stuck and I cannot get them back.  Please help.

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 4b1ac08ae32676dfc6994081f7acdaa0d5ebf5f4eec20d362c94387baa5220c5

Signed VAA bytes to submit to the contract:

> 0x01000000010d00a4ee5e3c046b7b90fc18cda426e4cd3b92bb2930c8d005f79192f409e119f6656f5ae31ebf3ad3d58b160c1cb8c1123b1e295ebf5b1158823295203d8d4c868a00014b41e7e5c14a952d0e2108dac6c3b61494f5f9a576b090888749f808d2400c9838e756d6bec21df66c55048b318f00c92251eb639d04ee4ef7fe7fc37d05940b0002024c872aa03dae99ce223fac69351e382f3c8920990b2c92cd0ee22ae512712062277e3f616aeb86feaeebbaf4848b0fa977335174a57897badfe415d246717201049026b633896637a471714d08ab65a43f9bd2d2f8f305ed08a0f5d0d745092c793435e4bd9fbccd871599e11141fffa9e537f462808bc7ebb324e0e7a89bfb2aa0105a2b8d6ca1f45dc7c3277b2fd10a8a9adff0fee6fc5b5c8db4e9ca430e4985f4a5495a4fdaa51ed05d5043db7aa2d859e728273662a59c4b3574e28842e08dc890006c557452fe20638fc8a56ccc386b26689689f84938c8c9469f47489986bfef54e73d7f3c39b86eabd78b7bbfc47f3dc8156ffba2b2618c85c329c5ee9b8540d85000736e589b9422404871a3677dc9be95a7ea4380450dfa3e9b1b04d6fdaa8b9c029547bca065b7664d7fb0a9e04a390777a180beb22918b28462fec099c55b72fe8000864f9b34eea821e860636fe2179ef3cc8d7308eee296b7181d3c804dc1dad739920fd4bd5735ed7309669f0b1a3c7d39669fcd9a7cca6f21200baa98201d24490010abdf8da031c15d6e2278ead51fa131dc0a031b720a9b21c7269369c057f0ca2776e0524ee7670fac7c8bfef0c56cb067492a1842977598a64206308519cea23fa000b614c6bc2c52380a4db2337c1ccd869944fb2b627b41c730c463cd486d86c58dc02ae5e4317e7417c65266c51747893259b0fde388945e2e62cd421abbea031db000d0f786d6d54598c97468c54d83e53a53fc592329ff8e38beb690aac51ee9ea68f32d101b6c5a13de3e9192b80caafb288bb43ed0a9f3668f7115bbeb55624ec53011140604b8ac8b07237da45c436d13e93bd4b4f528f516dea0bd1d59a16bf57ccb9299eedcfbb61b16bc1e7550c207a3c7c9cb1f20b2532b68acc819ac269f1f78a0012e0679622156bf33ba1356f3d09e08a671ac2563c70cbcee7f73b407214172c17665d7d23f6c0c8205cd4dcd86c4d219252ac5fdb4af057f52851c377ec40edaf016136fd9c10000092db0102772a873e689ca08706b59116d7c3fbdbeedd1b3cd627f0decd645fbe44dd052b0000000000000000000000009ad67cdce4baafb154e0ab3db17a8eaa27a1f07302000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2090000000000000000000000000000000000000000000000000000000005f5e100
