### ISSUE TITLE
lost .013 wweth

### ISSUE THREAD

**Issue by akslipped** [solana-labs/oyster#268]
i know its not allot but its allot to me and I was moving from phantom back to metamask with wormhole after figuing out i cant buy anything with it i was trying to buy sol now my weth are just gone is there anything i can do to fix this and recover my eth i cant afford this.  
https://explorer.solana.com/tx/348SRzCzbzZfpdTR5voUpgEJb92t4iXnTCJb77okAt1ueBF9ZhwjnGuPsQaZh6pvJ8aLvKZHfGWU4q56xLcfyPay

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 9c767ab3528092e6df67af7eab104d700bf3c10aca5b960fc91c01ec17e57951

Signed VAA bytes to submit to the contract:

> 0x01000000010d00896e2596cbf808492c518476d59511d97705dbcdc0a6977a60ca9fb6ff1aeb0b05eeba72ba97cf8da3cd4cf9879850568f84dea148bf34f2deb02cdb50f05c6f010154b3c0ea2c48b91f3288f658f846f126e066c1233dcc2e3f709a2a526453b903000120f2a7b31e91506635017f38eec0fe338f29d8d9d6473eb16f2d5f5339b10102adfbde3488d54c09e5de005626bc8e50eac1fdc1378dc38b19109aca42ce0deb4ad5c47444d49ff782150e20323465799e7a29c5057a0d84fd905c065db5d32e000351f4f077478709b9d385d596747721ffd549d8a9a4f01d95ebb67ebdb4871d4b07cc5279e137c7aa94e3ac63f77e4a6d20aec38012400ac913adb6be5ecc722701048682478af1925d37526e2446900db338407927a92f3a9cb81c7a50d1774e4f87763db80e9bb7b9f8a330f79d2fa056d8bac6811fa0d84b5d6d7ce9d5e02e5cf101055a158872ab0d69beb54b55a34cdc8fbfb5911fd93afa37b2e43709bd982e216f2d115cbb4431d5c4bfd4c7f4c719f64abc019779150a98373665818bd888fbb90007cf52643bbc1337b3c01db0dad53ce66b00814be638c017c1d8b79f922335271a3519691f00bdf80c71c0838e0a5b81e6e4ab1e163dad549758b19aa993bc62e00108d0e58efd1dd384a533c654abc85f1da73fdc91dc5a5e3cf2059c841c6d2738b64cd510a4f46f3960313c5efcb4c537e0c21bbc66bbdcdb58c589f52693002c52010a71d827880486a76538eb2e0a4877e2e7f155809d886e03701bba0ebc62c0b9e273d41298eb033847c10cf82aabaf1059b4c90b3f29585dbe4e51756906be4323010b26a6a5faa133080546419312dacd724ce5ba25cf3b1d3464ead8bf1ce8dc8f2f6f70ffcbb9d0375c6f9d4e9afbfa15882d942db492694fbc3898686a564e05ff010d5ed109fa47a965ec5a781f51c2b9e43f06b126b266696858c5d2f822d0482bb513de41a27b82be55f935e1e73d719bbd3dc8fcc2bb908619a96283c4a794fe600011ae7f75a4424f7dca84cf0b604caf41c3f5031a770786f0e67eb357a8c8a2994f5561c61df171832a4a60a3253641385ee9c50a88a80bb8b6a6d5e6f9d2ca7190001241f5b13c41a40dec3771aa487e059533db5df9315e524d2c19c82c38c56891cb71a51b92ede5669a93df642b0cc5ec77ddc51acd8c60d81095237ba1645417ea01613711991000005b6301022905b42c69b6ebdff71487a8fbf0f9f5f0a8e38774787c8b1f12f170e3bc5c6d000000000000000000000000e1665e0bb115cd3ffb258bbca7aa546b0c72e94702000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2090000000000000000000000000000000000000000000000000000000007bfa480
