### ISSUE TITLE
weth dont get back in my metamask wallet after trying to send back tru wormhole.

### ISSUE THREAD

**Issue by cryptoelite1** [solana-labs/oyster#270]
Hi 
I sent weth from metamask to phantom true wormhole. this went fine. i found out that it was no use for weth in wallet so i sent it back. first i signed the transaction in phantom but when i saw how high the gas price was i declined the transaction in my metamask. the funds are no were to be see. pls help, i am new to the sol nettwork.

4tfefKh8nN1iQYkFamRixwF8LZzLdWFssbgtb2GfNJUmeXZojpdCrjf2LxL8g2RSLwq6DvvJgnbLscwnZbTM3GRs

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 12c0d7c739979345b7e4f9eab51d35919a1b9ca284113b9e8e69aef0c2ec60f1

Signed VAA bytes to submit to the contract:

> 0x01000000010d0083e0cd42ad2b9229325c2a2bc35eb1693666cb92705edbfaa504d306b4f93d3d1b00c016abb279ba2ee8a706bddf9d042b492b69de216e7879b127053309f5540001a4f9087bf97e5af4b4fd384c0bdecc211c4c35a3e35f6ff51fc52366918d539a665ffeda2ca70b672930b3e1030663148936411569485382738b6ab169f4a48a00024b4ef464f9d3d3b5bc6de445d899ae93886a166482901bae460c0850c8b1b24d7f19f545ffcec0297ae5049be6838d9cb182ed2001a33904a7d0792fa585209b01034ed52d26e2ed4ed94af404486f6d95c062523d78fab5a182ae85eca8e377d6ac7506ec7a0afb0f2af0882601bc2726c504cdc251f13fdad1aa22286edf14472d010534fa5f65c706d213105e638c17f0bd54e4f9053ba553b863809a2c0b3fa770c92101fc8161edf1c2bf5942d3f4bdbd316361018ea0dd62bdb15da55868ce5f0900069c1988f019e32433f02b0bb04cbc0fe0203cb0dbc99514080ac9f5bed292120b6da946a9f3108cadadc87ec0511e3456714e558d59c2fad7add3cfe25e4f08210107fac8eb7922d4eda850369ca4e3b5a90b75d85aba49f2fecb9cc46cef6f40823f5d5c7be8fb398d8cd0e5850de2f532daf58e7d544273bfc949157d04e7729f41000848a1038e7188aff7bd77b6ba94db0128a844845c0887d87f224cdfc9316c3b6679ed285800baa7aa905a5b41f3da6fc7b4e6c689ee6bf02ff079905ca9e3ff360009fba8334f0065ef7b1c83453aaeacb1e39133123a58a04e0e943acd7e4a96807438754cf5de49264cce4692b66b99fc4a2390b623f5ac357ec4a7746f008baff9000a79ade860e05dfe05204422553200ce43a0e7173cdf20699086a44f4d2da70ba052e24c2cee7d1a4de031051ed61776244f8a3f71bf53cfc0174a91c1917400fb010d9b8926e03dcfec1a0d0022a47d74908188b57f0321a31fbe5965a040562fc17c7747184902aca089ad580188a038267b5e9ccef5dbab9660b51ff6b2d189234a011139a847d2761121f757ac1f2eaecd525fe930a4b34a7d9888d110814f8c9d13293ea7326375d66f10be573ba806a9b4909faef7e95a8b4e8180c12d1f8050ffa7001287533345beb71d8aef631b51fa52f0c5ae5704e573511d23e0fab828b134c3dc02a6a103126323895a56bbbf0c3cf69a3e150d99397389153b893d83b79ce42401613775c010000132580102c276efd37cca2427abbb74323b3ea3ea8f13f57d0294f41a267a8536dce4c15f000000000000000000000000d70b5230571ba9c99e9d4e1545dafd5ccbd07bd402000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc209000000000000000000000000000000000000000000000000000000012a05f200

**Comment by cryptoelite1** [comment]
Thank you so much. I got back all my weth.
