### ISSUE TITLE
1 BTC lost down the wormhole...

### ISSUE THREAD

**Issue by KryptoKingz** [solana-labs/oyster#271]
Had a transaction pending in my Metemask for over an hour. Checked on etherscan and it said the transaction had an existing nonce which it didn't. I thought overwriting the nonce with a new transaction would spit the 1wbtc back to solana and I could transact once more but alas it didn't and its literally stuck in a wormhole.

I don't have the etherscan TX as it was overwritten but here is the Solana transaction

https://explorer.solana.com/tx/3GdE2R6pSXwh1zJxefeuY3nJVPbDaZKsJkZAtsVqTBJQ2osaPp2kxSxQr7KW1ECS92s8hkW78fWbPbdzYZ7KHDLn

Please help

Thanks

KK

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 363bdc517f33fede2e519c50ad288e958b9b030fe9c30b164bb363316fc7ce62

Signed VAA bytes to submit to the contract:

> 0x01000000010d00e6ad68b1eb5afe1803631b43c336c7edb2fdc0dedd27b70f553218ee2e1725a53dd607090497ffbb05c8221767a27030e0a856ee4098c75dfd3e3b7050aa7b5300014b745c707bf8fc08b051ba030045267ac750ba2a505d9a00eb49b9c2ed00c4c951c019b5920d9002fbce8d4f796183de2bfe794685e804d26ef5a8e3c0965b3e0103bb0b256d93f6ba6f91b367e91bb280af32364aee93b2fe41482a444f79f364b80ecb4d3af6ad459b7a5c58b6200a00994870a7313e1cdb8d66a7aae163186fa40005f515f5cb0ec9086ee27ec7dc81bdb30766cb196fd85692bbde0b06fb8897686f6fc364df95811a7860bc3b417dacfcdea4e2eb3350d2e6764cd42196bb2e466300068292ca0d9c66764cf18443decae896ff711da49f24e16970c42214fba82a2c1c168e52b755a90a5c8352fa1f731f1c7822ef9f0837cd7466a0155d4e74874306010717cbd49f18ce492b6b6e5573f8e2dbe19bfa95d0a45953861c1d771dd0ab002260a6a71e7d9153d08b78b5e201fd750835778621eaadc0769406330b405b57d80008b02e561b4fbeb947aad8d7110bc92f5629149df74f16df2a99480409d3021c9c75350584aae7b5f62a25c749bbf063a9955b8f04908031788eb0cfe50551441d0009be0f03c8ad12b9b4213683d31962192732b27d98ab58e5114fc9835b5e4bba1217ea57e7f8ed5b12258221db9656779e99eca5a91255f0df7d488fd42cb1bb03010af6c5689df9480119657543ace5c2b484cff05ad3ca6256f2a95273b5e9376a76642bf8b7ec2a0783a305251d75e53dbe9ca4a4decbdbdad67d2264565286bdab000ba815ee292d27277e480ab4a095b159a3d22f0686f44bfddfc58c061607e1bb553c9691ef4f7dc38bc2dc75af2a3bf8c3d946e80e10e227f197c77d2d86a7efda000d8c02b56cac5a59128b87ede808a3ecda93903518837df79672bf56c1749ae4c362031c4810659836b634b17cf6b8304ae94e6d1e41e589278b2e7d76c568f4570011ffdf99caf5b5118fde6e8274559809fdb7fd53b1043485266fea59226fed14837170f146acbdc5f9db9688a50411db3febd3ce08f10fbfd704991b3a4d0db5c400127f2036e09dffb35bdc636ef1c15d5cd49fed277d8ab42af3352a98a9cc3f2f275cb2f61493bc670543f2136bbb2a328c6f7e9a1d1a2e3a2689e358bfa0a6cc1700613778131000001d250102a4fa6fab0f02c0dd3e741a0aa56989bb4e655a7a786cbc3cef9e96eef0600a51000000000000000000000000f3f5c252e8acd60671f92c7f72cf33661221ef42020000000000000000000000002260fac5e5542a773aa44fbcfedf7c193bc2c599080000000000000000000000000000000000000000000000000000000005f5e100

**Comment by KryptoKingz** [comment]
Reloading the page removed the transaction from the screen. 

I tried your alternate solution and was quoted 26k in gas.

<img width="512" alt="Screen Shot 2021-09-07 at 23 12 45" src="https://user-images.githubusercontent.com/90003668/132377752-607cf89c-d602-439a-a958-078a009a32d7.png">

**Comment by leoluk** [comment]
Looks like Etherscan misestimates gas sometimes :( Try a 250k gas limit.

**Comment by KryptoKingz** [comment]
Should I still proceed with it showing this error message?

<img width="376" alt="Screen Shot 2021-09-07 at 23 18 35" src="https://user-images.githubusercontent.com/90003668/132378347-946abcb6-83c8-4306-8d55-0274228f4761.png">

**Comment by KryptoKingz** [comment]
It came through on a previous transaction I did. Not sure what I did. Anyway its received. Thanks for your swift response.

Lucky this didn't happen for the 99 renbtc I sent on the previous wormhole transaction. Would of lost some hair
