### ISSUE TITLE
WETH  does not get back in my metamask wallet after sending it through wormhole. I sent it back from Sol to eth network.

### ISSUE THREAD

**Issue by jeta92** [solana-labs/oyster#273]
Transaction seems succesful but I do not see my WETH funds in my metamask. Please Help. 
BV1NRU5FQvxKgY2e4jL4JKB1hiDrrTYYfhhiJpUJVhkJ

**Comment by leoluk** [comment]
Please send transaction hash

**Comment by jasonwu112** [comment]
I was in the same situation. I was stuck. This is my wallet address: 2XQ4URWR7UNBaSoiCSc3GD1QvkY6F2WSTZtf2Yz9ajsf  this is my transaction hash:2kFVRG5hP7FGn74EhyU8wz6noC4St8XRciB7J7frhdeTJqb2Nw192c3iu8nV6Sh928CKqaB4LjUkwhWE2onMpCN9
 please find it for me！

**Comment by leoluk** [comment]
@jeta92 Please provide the transaction for the transfer
