### ISSUE TITLE
Wormhole WETH sent from Solana to WETH on Ethereum MISSING, data not loading on Recent Transactions

### ISSUE THREAD

**Issue by KikeKewl** [solana-labs/oyster#274]
I'm trying to complete the transaction from WETH (Solana) to WETH (Ethereum), tried reloading the page but no transaction history appears (it appears loading indefinitely). Please help in completing the transaction.

Transaction:

https://solanabeach.io/transaction/5EH6iQziU4yuJPbF5brBxGEaSoZxur1ii4HXacVCJt9QiwtSkmgA6juYDUYMKS5R7vLB1T2r9hK6gUzXugoAgzDh

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): c4c9f2e17d192e26f6cca801556a2d214b4684ff18fd6c448820eeadc841de9f

Signed VAA bytes to submit to the contract:

> 0x01000000010d00f7ed92dd52230c1fc92fb73d83c5e211bbbcfcf29b88e97c504bd876491523b03b72141a1cb02437760f2c39d81ad35745a80628a68090126a8a07eb74c560f90101549f8d2715885f0bc10db3c0c9c6c67d436fe3acacbaf9051713cf902d20785a718cc7114d3e963eebd3f98112b6724275531839969ad911a0de51e9a5ab1a5a0003b1816f302ca757a961a7f79519111a4a5d3523dc0b50a50072f3a8e03b3f9695771c8042cb41a17b6e0b7076b4e2836997c37281ad5c9b2d509f5c2be0497b0900051f9cb5eb3e296e6c2c12b0b4c6db7572fa4f74a133d1c53153d90f3cb3b1509d56c49ba3c63138ba8e7169fc8fac108256fedd78edab943108f1e78984fb5e7501068fb9fbac13d7f25d26309566895fc68bd95c7cc39a0ae0f768bd7f074ac3bfef76e4ec29fbfe63993853fb61d53401d571b2e0f6990c39397c10d48282136f1100074f16db2b5c37d8a45b334237c6871df9986befcbdbacc1d982927331164aaec817ca04c33789eca17f5376fc7c8168591029866fb50592eef2daeffe2bf2c18c00083aba63a7fe0fec28c2f62a5f23c87f79d0a4858a28795a2afe11e01bc91954287ce7f2f37529dcb235f500e05efb9cf6e88ba7a3c086ed4a9615de1ae0aed22b010942634afd256b3bf50817b859b17ed08bff36a6642b93aa2fa28933e2297c78c1325f38f04dd4b8f28018e437a827fc57b43bc4bf674b9a24cb13b983c21ec0d7000a950f975774a43172e40e049b170e6f8f3c101b487f3cdd8e2129423e895c41a53d3ddce6ecd7674eeeca127522313679520e709412f037ce48fc0c3d6eb95431000beecb718ba70291a19c5979cc05e4cbdfc1b7370acb07c3b88290e8bd4e70666d7372a728135ddb8b637e86bbef4678e45c0f76585b817cee2b43e41f80bd21ed000df6fb555316bee712a010ee0e5248f2d59187b7c1f0541d9dfae3012650e228126c688247df30da1f546e255b60e0403cd7264be00201b2160f5b2b28abebdd5e001135d0377f9cc490c6c610f4b6be74af75175b4d67498ee2de9e7662f50cce163528ebf3159596799e43409d391f2fe9315ecdaa1d7ff36e0b0fefa17047562550001242481a9b47501f373a9cab580f4ef45222a4556c482310c7e366762c553c939603e7c64377467b122992600105dc4c9fdabf22f63fe1ba788eda9d6f0e7e2e78016137be02100001608c01024f9e1a39c3fafa199d2b61856af113a6ad829713840951b2f400564e29aba031000000000000000000000000051abc20c0440af42181c1dc9ca4abfc74c07fe002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc209000000000000000000000000000000000000000000000000000000000ee6b280
