### ISSUE TITLE
weth stuck

### ISSUE THREAD

**Issue by jamycreates** [solana-labs/oyster#275]
tried to send weth from phantom wallet to metamask. it took the funds from my phamtom wallet but never got anything in metamask. https://explorer.solana.com/tx/cMGMBoHFUupND9iNd8nPJXKJPrgtuif7mumz67FVXYS5G1c6P4qGeivkURM21CmZXP525Nk5fvMaTHVpuRB2hcz

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 96b469867cc3032cb227d7be36d7b4740095a777626f3d1ca9bc93dd28d85834

Signed VAA bytes to submit to the contract:

> 0x01000000010d001933d8596205b17db8a15a29a90f1d10d52076648298a935486a1fbd6121619b2ab0684d43046f60ba6e2dc88df9a097e3cfa78cc4eb912e4a43ada25581b41401018710c76ada250d2222d289233ab73b7a6c0467005f078cb188c4afa491032c910ad044c4496acabe6a74516287ae920202bb38307adbde2fdc30fda71be41adc0102a62da67ba46ebe988e587cef2709468487dfaab3fb9f2af42844438720bf14056b0662950e60e80446216f5cc59e681c7f842333355b52a825bc83d778a789a70003c1818caa49000493e8be751e78444968099940bdacbe2af7ea6c0fa80938f51063b86c9951781b61d98d4811abe6822d2a0f6a9108c4a8a229b362aa84da4753000521e22cbc993d874b02499023c60de0a8e2b363fedd5f0371e1cc1120037f05c51995b487c04509e9c4baea5c42a1935fa68aff176407cf5e22f01eea16d92c980006ecc81d754b94a85a92a4e67f0be9006686122adc3db55cc2d159d544571583e502ab5018bbedc89142795fe49655391a3b246be5ea439b6246329018d9cf6230010756fe88bcc594a33afbdf6f3c17c41b5a8463b3a8e9b61055965258d80b6d0a1373ddc8dfaa1eaafc09a0a0e9d142aea5fa314ff2b006387fc62a88b29d4addd800088dd34e2f1a664d626a7d93bc4ec171bec400673a13afdcc8e5d7839991cee7516538206ff2d15fe406566d862a27e0660a0035cf4854a3b63b92659717560ff701095b6b70578cc2d7c973ca745c6978ada70ac0987184e1bf7399e4e90ff9e77857040bda54a8408476dfe5f6d608702f55fbb69eb48fcf0c780601b7685be1af25010bbc68e98c61e521824c43a23446f55998b13dd78be62894f9485f950899b841121b1d8a76419859c1874fff1dcd5e8678a516f7dd43eae51c16dd2aecae969cd9000d91618d2e3d09cf2feca344e15dab50e7a19a2ea026389d0ad4b38f7343c9f5580d350f5ef0525a35de769fd1678e57a069889823c29e6c1cce3e04a48b0e673f0111c4bec9b27921463deeff1cf35d084edadd84caefdb177ca993d8c2490c61b6f33c1deb3e2189ff51efdd5710d9248941dcdad8c0d04bed59bf93fa9a788f9f7e0112ee304f4f12564a1e8162f3bf3b93dc6d65dfc4c5a6d5d3562bb589760b2709dd18cb427b495c8115d032b354287d63a087ed1d91bb5af0fae630b5fef176d4a7006137e29b100000d0d201027aaece7469493fbceeb08dc33857607cff027fd6c29c539ec66e5f72af0d59e20000000000000000000000000a3458ab024d10b88eae1a7ea67272537387a84902000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2090000000000000000000000000000000000000000000000000000000074c3f7c0
