### ISSUE TITLE
wWETH -> ETH Limbo

### ISSUE THREAD

**Issue by jritossa** [solana-labs/oyster#277]
I was sending wWETH -> ETH via the Wormhole and rejected the transaction on the ETH side ($500 gas wtf). Alas my wWETH is in limbo. 

I believe this is the last Tx: https://explorer.solana.com/tx/4pcYrBzdzfxhqwiJQivTyivkb3yFM1KTxpdnnnUv5AZeKE8eaxgV6gt9NoNCQnnksCiBJZ6XKkozQHWBgCF9HJGx

ETH address: 0x66249043e695b063e0De19138544b702033e9Ef3
SOL address: Cmtt3Wp5Jn5v4SAsFKMQCd31uf2xysatkJMjpJtZXGxX

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): c639dfcc6e119263430530b8bd250b933031f0fbf784be89cd3570151a401ce8

Signed VAA bytes to submit to the contract:

> 0x01000000010d00457a48e2e7c114a659e9c5cb0a9e11af56d7dbe42bd5574bcb03c6e4501d5fa72b4c2b0f5e6859997b3e445f758d305fb696db9bb509105ede2238c1ff86ad8d0001f044eb14e7bb47599e17b78f3f3256e04d6b6647c7777c9d8eca27a8846320851b5390ce9893e09b8e5366143f1ad257d1d53602d2d36083b8f543835b5b61540102f47dbe8c837c9d0a9f99487c1ae5781cb4e9097c0aa9563eb8037c8fa072983531763e934a68a920ff0793043ecf80b4f7922df6daaae7c0d652bfcf4d26794d010336636762b7eb48927a1a91edbea386cb0878aa03bcd7aaac94b89a6276511c4433d461e75c89a829a24becc1447c27033fabb81df5b68db62b6b7c6afe80cd1001050b4cc651973f64df63fe2d18b456a4c90a32fe25dfb3e2df97144a74093d77dd2aa5b2529254a1dab382a7b68b9b0550ce06975d0ac6dc15cd92528fb3da5d5a01064bfb6c107f1130ee66dacfa41ec470d08d712b75bc51699b387a1c467fc3521d2108b317964be1f2ee85a64a48d71eb6f3dc690d20909b31bb8c0f192162dc93000718d35616244a64eb73b2382e184b95d752baac0bdbb4fd4d1e7863329c890be35fa6fb15edf9041a5936ce9a3732e332bfefcde4ec3c330242cb0824b9c0d34901083f29a84f73140a1f959406596c8cc0a7dbffbe0976f55ea2dd4107e6dfe9c953256b4cd3adba2e289427751ed89d412f0c60351bb0daff9c0d8f558b2d926f0f00093095de4f2e65a2346e2b0836a59cc8b46444e52b061c128c7e70771a35a255fa0f13a739c7cc091e6abeba5334b1c785abb262f6232ffb6bd9cf54ef30b0ca13000a8a27a8b1772d0d1ffc62323224f7a511d6336a2d05ad28259d18833480046ef45e96b50cf9590d4393f2a71851ad25dd91d9e338bae3375c52cc11d3486ee0fe010d082b91e6afb2aab776144185afb2be20e2fc76cda50a2e547d65df1884eb645e16b5ca2a86a02ddc8a5dfdf8036ab00f550d90c31bcb4de6a32c08ae01052a9d00119a83ba1cd8375f4f9a5a5b294fcc5c06928729b1aedd7471e3151815287eda4769568a52119f77392fb63f463c5935ce4c63033943a9855c5b721cc893fb17dc0012d4504ec7fb2ae35008ce36ace582f8943c1331920a1b1c0816b6f115ea84560f076382e4859314fcea23b055f9e20152e84f6a9996d482c633581f98d831a8bd01613817551000010beb010206e05ccdfdd11f48dd89e29bb898e7130c3dfdc05f447da37f8a644241cbe7b700000000000000000000000066249043e695b063e0de19138544b702033e9ef302000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc209000000000000000000000000000000000000000000000000000000003b9aca00
