### ISSUE TITLE
I requested to convert "wLUNA(Solana)" to "wLUNA(Ethereum)" using "Wormhole Solana Bridge", but it is not being deposited into my Ethereum wallet. 

### ISSUE THREAD

**Issue by sechangdong** [solana-labs/oyster#281]
https://explorer.solana.com/tx/2PnE8NwhwLH2ws4Hk3i3MqJVoBKvYYm7VzX7K6BUrPjqc6ospN4GDrXbDTFNEWWuDLApearbKqaWfDTyWZnDL7bW

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 0a9b52e4ca3c0834dcee814924a468d88d06747dc8568285a48bbd748a887122

Signed VAA bytes to submit to the contract:

> 0x01000000010d00d816ef8989fb34f6562ae0f916858dd2d53c391e481ade710dac404651078d9025c08a9bd1552f3ec1bd2b9db8423cd25b996c1d1edbbdae955caf4a5fe26b760101c178efb15ce6719de9394328f55e99e3a9a5be5950a0f4f6d8001ad644cc321c5f615ed9ca64d30584afb882b5d039f867cc32a693b2d192787e0cc5dc58b66b000316aa08827e66d99489cc890046541ae973704194b0eacfffb69475200ea2fd54274f2842b5935c8f429e98f15ae8a6dc5501d5d62f166bb5bac45d539f2b7d7101041542bfaa9efe7b2b1ae1c3ce7313c1e0683f9f5440382a8ad2c62a20325f986f7b07fbd346834db2b900f61760653563a7906e87bed6feb25d5bce721991002401056b93d2a16ff068ca0692dc609adf9df465dac3a1ea2666316da27862103dfe0058dbc6e2e388c041a7fcd5fb9f75f491341ca3ec8d0bcb73bb12d700d5f3478f0006e1574d01892033059915b8a9358256b86e463259570935e3e4e1c10494fa5c3e29494eca3af39b1c430ffa3d9ce06160a216d06b7864631e807c835d1f691ae8010760961a829cfe741786da3a8bbf7e8df4846e62c53acaedb65531db397ea0c2bd346031a1cb5f7b7aa2c0b7e0befbceeaf432e39001708c334559d8f6837accfa000838d6ad9a6cafe26ae259120c830e262f6d33af76082514841403b82bc8c85f074631e016efb1f4b2f079811d20d9734ea615a7f684f9af36770e8371d76353ab000a5a76cc5cb86d77d50818a2da97ac525484108b38235c7145c96eb5672a24b96b753a0f2d2f256b15f0134625e430327343209ec60b54c8a01b215fbce2b0bfb8000d67734cc6d9861505514a42d6b3a8defbf52c5890006d5797e26940604fd3799c45954662316fa1b39fdd6746bbb019102d642b88186886104290c023c8355d26000f03d9d689639e64aed34a92743ccf42c0cd59d2f7a5a32afc6b7645939ae7a8f833d0b16365f92a8c3c3af9188e510369cf885899436331539be610380e960f14011117c7e4e6381eb49c563845d6087673ee029ebd160efd49193ea700b9672b49f90b31b724f0b535f6ab7c5d77bab6c2b56ac532cde55213f2a0e072f4d13a8f650112d1b7f14e55b32e3d1444a26f2f3c06d54c124ec3091198e34eb87b8c47cba3d718302e2459a9ab93af6947be7ed710f1bee34410170870c5c29fb4826401523601613717b8100001141f0102107dabe5ffe1e8cdb33a5521b2d897de3e53c8d0f0fba2eba15124676c4d3cad000000000000000000000000d280f989164ee99793b5870835dac21fba1f5a3902000000000000000000000000d2877702675e6ceb975b4a1dff9fb7baf4c91ea9090000000000000000000000000000000000000000000000000000016336edd1e6

**Comment by sechangdong** [comment]
After connecting Solana and Ethereum wallet, I set the cash to "0" and clicked the transfer button. However, as shown in the attached picture below, it only loads and does not process.
![wormhole01](https://user-images.githubusercontent.com/90328592/132671090-ec768457-3213-4824-bccc-fbff2511eb5f.jpg)
![wormhole02](https://user-images.githubusercontent.com/90328592/132671096-ed54ec5e-9bd2-4477-8bc2-b3475ba60c38.jpg)

**Comment by sechangdong** [comment]
I clicked on the link you sent to connect, but I don't know how to write it. Please tell me how to write it.ㅜㅜ

**Comment by sechangdong** [comment]
I entered the VAA value you sent and processed it. Thank you very much.

**Comment by sechangdong** [comment]
Thank you~~ very much~~~

2021년 9월 9일 (목) 오후 7:12, Leopold Schabel ***@***.***>님이 작성:
