### ISSUE TITLE
wUNI stuck using Wormhole Solana Bridge 

### ISSUE THREAD

**Issue by alvarezgen** [solana-labs/oyster#282]
Hi friends, 

A few days ago I sent some UNI from the Ethereum network to the Solana network with no problem, I try sending them back from Solana to Ethereum but I cancelled the transaction on my Metamask because gas fees were too high at the moment so the wUNI are not showing up anymore on my Phantom wallet and of course they are not showing up either on my metamask wallet. 

Is it possible to recover these tokens? 

https://explorer.solana.com/tx/5RMqgjpLr5QVAZpAvXY9xPbqhMtVqsTphHScWdRKJc8uisGU2UGWzxky4JogATdq2YdKNm4AjT38vi2M7BpxcRNb

**Comment by yamijuan** [comment]
You can retry the tx, connect both wallets, select the token and look at the recent transactions table

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 25e4b2f25a32dc0925ad311cf4a93650dc3275999b72ed25d75381ac9b4b18d1

Signed VAA bytes to submit to the contract:

> 0x01000000010d00e805ca0a0015933a88135ec0ca23fa557e031bcecc9eabbdeb3a3311b13bdee90be88bf8a9a0b52e66039f4ce6777ee0b2571b490f90eeaeb36d49440bb9a7e001010d4af1949a88e41863de2d62107980bc26778028b5008f5da365a4660d2022e10aad346e47adc91241275fcee4ff1290b73243f1d87debd932c95fc8d1e7c9470003e5e86bcc990b5817263e13c2fff87f4d8069f2a4293703a17e1a237ff2ef559a0fd57762b17c69bd74dba2b9417b173e4411992d952fc438eb7ec4098fb25c3e01053c3c6e0ccb649ffa2331ec21db9f2ebaad877935a3e1a0bb90ec3eda89b515bd37e021cd2e5acb6fc220de40bc338cb47c113b8e06317e16958f57cf0b4ebc63010706dd26805cf60670193ef069c0f3dffd5c8fa9c2214dd9dc00b4239de9babc2175056f63ee76a2e88b123688a66463c8fd09a3f9d91e60b9f910dacc4d35270201085dad3f4bee613af9e07f27dd2f6033ece32180cbaf73ff8f5b3924756dd2cb4545bff998877d8cde0ea68cf358328ee7f8398e095a277233dc5452fe9444db430109108c8d3f7701f703b98a5ab0d70ee6cd1887911af153bc6896e1bbc5c4c6501259b179b84f8cf1bff4f29e1b03d7b1a8aba91f5d3f309b8f39abcf8533e72db8000a5af17c6f6818ba3276965562735a28fe50af0bc43401db1b4e2d6390ba24f1473e4bc3890ef8ce13b5f6a6cbfa5d2f4da6d15f5e9f08b9c9af7c379f16bd27f5000ba2578fcb7d383120c75865a71e793e04c1dc8ce1ff9e5ee2e25606b9155f95ab5de1b449173f60d9935259d102f161d9f05b6e75a456f5e0756b595acec3f3af010dd578f01f842bfb503da43264fd7a0b4ef3b056871f06e98dca8b1c4f08a2405179b0fad6b6718003cf137e3f481a5ec39f2ea2c7842b44eeaf3a81dceed1078f0010645b87638777736d0e087bbfae7bf63c2dfcbd02ebe1104611eaf009068b5c91178e423d7c3a182412bb06945a052eaef656b67d3f2f62c1551324850bfd0e230011759e3305cc564a29df6881cd851694a81e402f70cd723682d1855ba3b69ccea1172796748b4573aa168c762fc57ee24ff49c76e9a16520a8fdd2e77a589d43cd0012f0a92727ef46fe6692413a4d1aad7d848f412b27eb8151d70ae8674c2e5130442c56b6a855e25397b5943b5e7aecab14de02e9640171eebc227e7c7fb7552c4e016132430b100000b7b00102f930f36d63f658452bed97c65d54ff9d43f524f77dd43a3f0396b3b594a76540000000000000000000000000876182fe3e1874b3202ff88a8310ec70009afd78020000000000000000000000001f9840a85d5af5bf1d1762f925bdaddc4201f9840900000000000000000000000000000000000000000000000000000003b9aca000

**Comment by alvarezgen** [comment]
Thank you amigos, it worked. <3
