### ISSUE TITLE
WETH does not get back in my metamask wallet after sending it through wormhole. I sent it back from Sol to eth network.

### ISSUE THREAD

**Issue by jasonwu112** [solana-labs/oyster#283]
I was in the same situation. I was stuck. This is my wallet address: 2XQ4URWR7UNBaSoiCSc3GD1QvkY6F2WSTZtf2Yz9ajsf  this is my transaction hash:2kFVRG5hP7FGn74EhyU8wz6noC4St8XRciB7J7frhdeTJqb2Nw192c3iu8nV6Sh928CKqaB4LjUkwhWE2onMpCN9
 please find it for me！

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): eb09da0cd3b8262634a5dae9a530fbefe25fd4bf85bb4fc964095a297e0d0e55

Signed VAA bytes to submit to the contract:

> 0x01000000010d0037a09874aeb403b1fd4c66aab2dfc6603b05e4e0bce223908ec191abba325fc02a8e520a260409301ee93b2b207d5310d85123812a84a05f22c82b0724b65be10001871c3f5837bd91369e5721c73b1cc4928daba7d94e350730ed8adae50925553f24af895e7a0fd51d4f902301a2fce899628c429721a90dfccd0572d76716a5d70002c70e6dfd85913b67c36f278e4a857584c2c3f4bc07a527af6ea8fb3ad3950f6071237eac625e22e35f96e0997691dee6993dd7fe5ee7e4c75aef5c13dc639662010481dd358de1eb45a0b0e422d20f9e987f0fb340c77f7ea935876ea2a9a589bdb905ff9c8713fab777672150cf6895a49ad957a27b56c85ef0738b373dfab992c80105e3de8f5da0d9993110019efa4f938d380fad6818becb75d4f42eb47caf315d594ee004d48ff7ff5e50dd56b04f47f94ff5b459b5518ddd3e4294e906ec9f0ce20106959b5edc0baf15ff0fab7654e9bfc922914ae76109bfd6b7d9d6df7abc0f0d647deef735488b5a78fd3fe3b7cc6a0543490bd20b2a9c0f561f6dacf232e2d16400072d88c93e26905fb449b3c8790bb63784c6358a622622cc7891762639bdb2481c2c4c91ae836408f6e3d184580d695655b17809d7deb018d03d2f64ebec326336010895da53301cca83a8766a87edd72c1b7c1b62bb0f395944cfdacf027d222a230b4f72fbc1fe48cbac4ac733f9ab5691c20687e82451636adbeaa32b05feef93400109196d723e0f6a381f7ef6302de10e8d08b997910ebbf913b84a58bc6a79ec6945019f2ec728493afe8aff53791c5cfc6bea14621530eed36c438c0cb13472b0a4010a6be3a6c6667abcaa8ad2914071de4c37ab836ac9fd1e402ea24ae46a3a175fe5043bbfab8b1ce18d13bae7b05de5513788041ed407d39ea7a025d73e7f10844b010d1b1e5ccaf4f470b5bbe3e3dd471e25709596a2840db26c0929b6db9d744b95f033debf25ac959f64b89e02bb27a217229293418db07dca351ed10e6303dea4b30111cfbfab4218ff11a79c38d3c38f51d2de411301f7f03ee26061113cbcd139ddc912866f0c88c299f89b8cbd332983c5e7b572572e6e3e95ffec8b4030e51207960012490fcfd3388b6b0a3fe686e862e33c048821f58d125882983a1cc2989233b65d599d82f856d42aec4b713984aac2d6f7efa22f7eb0f32ec6903976ae14dc9134016138627510000101df0102089ce1edf367bcb23751562eb773c2b18ea67360fc4dfc970c468c1880fadc40000000000000000000000000b73a4132b0b30bae3573509b441a04adb3bb9d8e02000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2090000000000000000000000000000000000000000000000000000000016a65700

**Comment by jasonwu112** [comment]
what VAA?How do i find my vaa
