### ISSUE TITLE
Lost wRenBTC

### ISSUE THREAD

**Issue by Anne987651** [solana-labs/oyster#284]
I tried to send wRenBTC on Solana to RenBTC on ETH through Wormhole but I rejected on metamask because gas was high
Now I lost wRanBTC 

Transaction ID in Solana is 
4mSDEiL4Uj5nYRfzYYmYbFBneiKQevtz4SQgY4KBxfcLNKZhZxqW7iEAT69D5Kyj7BTLFEjE1466XUSjgkNF6Kx3

**Comment by Anne987651** [comment]
In Solana transaction
Result is Success
Confirmation Status is Finalized

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 2368058c7fd562ae19f8b0ed12e39d32a3074052789436416808c9cacd7bb917

Signed VAA bytes to submit to the contract:

> 0x01000000010d0069038236cc4a0d56c095f56439177806bb60da93152943203f9cbc30891d7ebd4ee424f6dbd428903e05e82228444d0a5b8ae9fcc59a183ef0328c510850f6c801010c8a35b1643839ffde89f21750e6edb07f279b5dc8a2b30bb8b70835a0e3e0803e90ddc039a4d0ea9e69f60114a18dd1676acd09b368d09ac9c23fdb6188d1ad01025b50f7796b9fada7a9b00dce304101bd919fa4bc9a721ffd23f48a56e4c3ae8d660c43df9e27d11bc61a63c8c290431b44c3086af5e795ece0a4445ecb5a05630003e1dfb558d763d9576d2493e59ff8dc31d70c6be1b6ace4761b3e2ab149252e8f2f74f282371cab34f35d64904fc52e4c8cb35abb984cb09dcb084b7de44a11c0010444c032d7a9dd1a59ddbd941431a070d9f9bd3709b57ce8c9a285e19761faa948055193062d4fcffbf23024b6063c24c262ddcc9e68043d9d1e4c896f077f7c0f0005826f40cd251c2619eaf715b20c7201d2d771c588c65f16287bcbc1d87910565731866f60a8109f09201b4ec3d8d907cca4e9aedde8c081fddf583ee0694a621400061cc844c4914a3f85ad2a2b850b51066b1e4b05d085e89d5bb534c871f4865fe438b8472b1a5fe13f07894d7cc45403f2c45f028b59a43723cc0b6d580946460900075277a86c47c3fe86dc699366de6944397a95a5a89fdcc5fd48b0b38a3c51b58723109d26fc68a23fb8deb8e68f834c3a06fb3c531c4aa4c36ff3d1300f0bb7f7000818e911d3f382e83067137ac365163bc2a1ba7dfcb7bd09be3ca788231f183c1a17983d7eca9da1fe6ee25f9ee16e1f955af1b5f0511f6389916c0dd92812d0e9000a29123963259533280effd862eced2bb8e56ad1611ff3515d4b1c7461674fe741268a4dded85c3c1828444c838ed4b0ed6d4483364f7776da4df574cce264b442000d808ff0dcceedff88158bb86d8bacafc3bf6abb33573f9ed0233873d379820b8e19cc6056d246f2b9946f9cfe620d5148348ea761ac7c19cd5efa834827320acf011129b33f280d45250319ee43206e7383b6f2d71abe4d790554aaa7be177d8163826409649708d5b0967e7c83242f3b033c42dae923e799d4d5242f0e81b9338d7a0012d9cf134b06653cf66e3529fa3cd7fa779431141d9a50d53d6e84148efd52094f54f5bb4611caafacdf59db979dac6415bc0a4b8bfb5e4e50112c29287c8b7b28006139e405100000a84c01020a03f325decfee390904cafb2c2b602a2be1ea06c8292773c0b833fc2d5a12c2000000000000000000000000d00124fbf72511f0b0b489503d699a153c87b16a02000000000000000000000000eb4c2781e4eba804ce9a9803c67d0893436bb27d080000000000000000000000000000000000000000000000000000000019ec49d0

**Comment by Anne987651** [comment]
Thank you for reply
Already I closed wormhole website
So should I open it again, connect two wallets, push Ctrl+f5, and check the wRenBTC balance again?

**Comment by Anne987651** [comment]
No data in my recent transactions in wormhole website

**Comment by leoluk** [comment]
Please follow the manual instructions

**Comment by Anne987651** [comment]
So I search this in web and allow contract in metamask?
https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

**Comment by leoluk** [comment]
And submit the bytes to the submitVAA method, yes.

Alternatively, you can try this third-party solution: https://www.interstellar.tk

**Comment by Anne987651** [comment]
in metamask, Connect web3 wallet, and click "submit VAA" ?

**Comment by Anne987651** [comment]
What is vaa(bytes)?
What should I write down?
Gas price gwei?

**Comment by leoluk** [comment]
Maybe try https://www.interstellar.tk instead

**Comment by Anne987651** [comment]
Thank you
I could settle

**Comment by grihanov** [comment]
interstellar just worked for me! thank you so much. It was scary moment
