### ISSUE TITLE
lost wrenBTC

### ISSUE THREAD

**Issue by grihanov** [solana-labs/oyster#286]
I tried to send wRenBTC on Solana to RenBTC on ETH through Wormhole but I rejected on metamask because gas was high
Now I lost wRanBTC

Transaction Signature in Solana is 
3M8aT6M1XJAJFRpLJpdwYRiyep4HxgXf8NBaEnSzFXaHWYjixuuahH99MwGj9zB8iV1x4b45swiySwwKV4J3YYng

please help

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): d5656dd103d4456225b6ff956247ff2de30c0371f016fb0f3277ac392bbd435c

Signed VAA bytes to submit to the contract:

> 0x01000000010d0052e0bee5dc164db86d03c3d8702c0533808bc80bdf7731a08f43fae77df53d87001385a31aba216e4de709159d8263e266894d6f9eac7a92dc54e8c82dafa8da000107913372b1de2e9ea93dc3305b25d3befb6a79672164bdb2efdb120a04968b1953437651155680dc955d0598224ba007b243a9a596f435887d9d46410bbf076b010210bdbb2c71a7878ab3fe05fed1ea98b98a7aae1ee6ae794d0583bfffb22311561e26568bfe8746fc8801faac5e98c3faad3f3520afca5d1fc4adad8f12099c910103944b19d52266ef38dacd37897dadc118f6ac8807ec5f512566a423bec887298d2524dc055fcbbddd06107b690f25c9a1da99fc9dcd353bfd170abb341a05975e00051a7072637856048b6974880b64c2f4a10bf01208347f06670fb2be127b3ff2c778ce1c95af3d4bc6d42a9c14cb16e0e201166305982d70fb40df848cd1f2e5a20006e61223a4f0eec330b97455c24df3b787e9c1cfbf11d9a714602962741ea873c26b0cdad762a7058395fa873b27755c72e113d35e5039e49613b7463635e18caa010719cc88e7e565d5106d716c3f8090c068ed0740ea406fd2ccffbc2742711ce36671f97ea53d31719baa5411478383fa32be0b0ed93d0cce0f944e1408572d59a10008b73d6654751b4ac7680da34a2b3dd048c51c20cbbf0ec9bccd5426c20674b002521211ff8e75ad46d67d44f655130b7fa396ad62d8142ad15a0db539e04e053c010aa8d3676ae834b683285835f4e5ac7ecbcb41f38c711c55ca5f541dd49fe644044a3538b3c44d4a06ff25ca0b2c876f49a53d24b9d7fcaaeb3d3ea5d108aba1fe010b9e21ffdca5772d622d0de08dfe7b317298de56a0296f4229245cc622787f8b0b37d0b3e0f5cdfada684c71eaabf430c1ee1846e22133edf7796ddbcfda12aece000dbdd997a461694e780efbb0873baaa3e11c74891b45bb57c424108785c279e76b4060b77d6490b3f042eec43b8e04d7e914246ff666e8b46b1227a54f0a590cfe0111bbf022b481252f9cd90a290d3486613592a68162923107b1920f48a95f8f41fa27a863ef9602f86af6b18ff774a97f5e07564abcad530fac3774f4875b059a410012376a6984f04deaf99dd3d78df9812bf0ca7be1e5c3aa499d18042f3fed8c1bdb426c276f9873501cec1538047417c1df8be5310f5c7c4a2b39874e09b42d77a1016139dd31100000a7930102e717b066d08c1dbe657e8ca1fd145f89d96d0d59368001ab01a4b99ef3c961aa000000000000000000000000d6a5664ca9182cbd5479fa3c7fd38dfdbb84ba0702000000000000000000000000eb4c2781e4eba804ce9a9803c67d0893436bb27d080000000000000000000000000000000000000000000000000000000000a006cc

**Comment by grihanov** [comment]
interstellar just worked for me! thank you so much.
