### ISSUE TITLE
Bridge renBTC ERC20 to SOL

### ISSUE THREAD

**Issue by grihanov** [solana-labs/oyster#287]
Please advice how to bridge rentBTC from ERC20 to SOL.
Using wormhole i receive wRenBTC on Solana but i cant really use it there cant swap either

**Comment by leoluk** [comment]
If you want renBTC on Solana, you want to use the Ren bridge itself.

The bridge doesn't know if there's a liquid market for wRenBTC on Solana. Maybe on Saber?

**Comment by grihanov** [comment]
thank you for help once again!!
