### ISSUE TITLE
UST stuck in wormhole

### ISSUE THREAD

**Issue by wannabeman1** [solana-labs/oyster#288]
I sent UST from SOLANA to ETH and it doesn't appear in my metamask.

Solana tx ID is https://explorer.solana.com/tx/33R2uJh8ignLi5hUjzbYtJdescVprbFyWn6tsqkJacpbUJHs4WDYkT5BypEhaJy8GPxx2kUC9VAo6QH42fZE5Yn3

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 712844eb8777733c0e124f41b56b3221ee6cb44bebba198a3ff6bcaf3df59ec8

Signed VAA bytes to submit to the contract:

> 0x01000000010d00562d761895bbd03cfc19158409a1717616deb235898601e1d74e9933eb51bca46ace463f330a47d615362bb7ee53a9ef5088e7248f356914c56c66139a6b7a0b000132196e2b32b1e43f65b37fc346ae0f5af8f52ddc468cf982a142986be9a683ed26cea54198dbc64080acc86ff0a3a91206e92be4f6a966ceab91ffd79fe535cf01033b866e0e80276de4ee80973bb13f58c6a551c9031174b33a1d931d87b9cf15c7718340fe858ff94ddd3db4ecf90368e5f166bc204406303ad72f67e2cc41c6cd0004dc87618ecafd8da02fbc6b192ae3bbc4bee900cf5fb6e9ff11b6f08fdcb0b3927be17ff8c1017f8960a3bb73ff049d83419a5389cdee4701197187867de8537b010559de25b73de1ab09462076aa53e6787a01e55b329ea46540bb59df163f0c38a308c97d04ad46ac1fb4499187eac59356bee53222edc9e37705e5f719975cd4680006d4ff32a2654b77151492b136cef28a6479ac68be7c976a9d18f2f499eb95e31a2c626340e2ca73a716bdc5eb9e71b84bde2fffe2f7d976d8e7628e5fa2447fa60007e553624a5828f269f3c99cf767580602cf631cd6cb2b2a80d60a707975133a48584fec6fb324fcc8097c8e88f82a25e7d0dda5f33dbda1177e0cfa8c222c9bba00080c933638fbd35dcbc90f4f9895342b9fd3b1228e1dc7456c692927d20043bf18167d4a5ecc21cfdd85e2e95f4636afdce30fdd0471c024a07f836c7ac47bb25a010a6bec418c325faecc22d2031ae6ebecbc1a2e61521a87114fe621fac7a69d640c23803853ec3ff97941a81320982d0df25028c5949f6eb8ed522cd0cd7778452a000b218b1c0aac6a959661f1eea1d5a6fd8d4aea934903fd2eae21a4f8c4ece7728306a1bcc4c22cb644b952494c0b90eaa7d23f56e1cbcc17c64df5314691345bd4010d3a3d158f634f064552edd25b89b644eb4aaa2c09eec7795a5c3dd24ccac3cf3768e13f25d38b36caa876e366db024779668f204e88eabe8b2f1d5b03d43c90b00011d4e6d2dafc68ea9235150709f48a718095b145dcc9b847b35f8811e66b6dede3649106d788e8908a87a7c90c6d967d7e15cda42d1db5aaa471571905d02e55b40012252eddd5beecb7169b3bbc295cc8936c920b9579f21ca72029724815c6cc22323973589f3bd7ed1f460ba918e825a75184d179bec7e8bbf4f3a3d041b87439fc006139e7e3100000870f0102f66a4f5cdcd127bee21bd4d427bd00c09984755dc5263e649289403046ac17160000000000000000000000005452aa87ba2bef2325632f94d97b85e4f40707d702000000000000000000000000a47c8bf37f92abed4a126bda807a7b7498661acd09000000000000000000000000000000000000000000000000000113e208164730
