### ISSUE TITLE
Failed Rebridging through the wormhole

### ISSUE THREAD

**Issue by PeteD8** [solana-labs/oyster#289]
hi team,
i bridged over 1000 Dai through the wormhole to find out that there was no liquidity at the other end.
so i tried to bridge it back but it never came through. they left my SPL token Wallet, but did not reach my metamask.
Recent transactions are showing nothing but four moving dots and solscan shows some errors??
Can you help me plz?

SPL Token Wallet main address A5V6fFMwotR5eh1r4p94FhZFZWjn9HwHmnGEcxcbHxmP
Metamask eth address 0x7B93B07351b361DbD2984E08e045e62F5a6F8097

**Comment by andydhancock** [comment]
Not sure if it's the same issue but I have done the same thing except with SRM (which I realised later I can just do in Sollet). 
Transferred over, couldn't see it in the wallet so tried to transfer back.

I'd changed the wallet in Metamask so when it got to "Finalizing transfer" and "Sign the claim..." I couldn't confirm it. 

Cancelled the popup, and now it's stuck in the wormhole!

Sol: BDicbWKdbSCYCdgnhoH5mZTtzvVFrA52fQCsehMEeP72 
ETH: 0x9575E331988058247F27ffcd1B9620F10DF028A8
Transaction: Psc6GDpEjW6Juf35VGKNLCgqeV8kp1iCauimGBWbzgWyaFdRAyjsb835z3SM6ZAJJaYKCmEbtbZcgqhe6PYvRz3

**Comment by leoluk** [comment]
Please provide the transaction that transferred the tokens out

**Comment by PeteD8** [comment]
https://solscan.io/tx/3gkHX4SddS98mGRGsmBNQ7KiQjwxAMxitq2fs6DEdb5pRiqQTtHpxhG7qvdMax1P8rbpAECyRG3CN78Bntk4Fb4H
This Transaction sent 1000 Dai through the wormhole

the two following transactions from the dai account 5BRyKFtgJuBBqTkUnJexapahAJXH6TiZrweEpkJobae9 (fees?) failed

**Comment by leoluk** [comment]
@PeteD8 please create a new issue
