### ISSUE TITLE
SOL to ETH lost transaction for more than 1.7 BTC

### ISSUE THREAD

**Issue by Jahaziel10** [solana-labs/oyster#291]
Hi, I have sent just over 1.7 renBTC from ETH to Solana, through the wormhole, I use the Phanthom wallet.

When it reached me, it was not in my renBTC balance, but in another asset called "renBTC (Wormhole)".

Then, wanting to pass that asset back to the Ethereum network, I confirmed the transaction in Solana but nothing happened, when refreshing the site, I see that I do not have the renBTC neither in Solana nor in Ethereum.

SOL Wallet: 2uA9dd32MsP1NqCQJUpoMuyfzE9JApR28AEVM6VgYMnR

ETH Wallet: 0xCabC51eF587e201825B8848F15c18ec151f72303

I'm not very familiar with how to look at the transactions, redo the failed transaction, and understand what the error was.

That is why I am in need of help.

Thank you very much in advance and sorry for my english.

**Comment by Jahaziel10** [comment]
Yea baby! I can recover my funds whith this: https://www.interstellar.tk/

**Comment by smehra** [comment]
> Yea baby! I can recover my funds whith this: https://www.interstellar.tk/

Amazing I used it too. It works!

**Comment by PeLaOs** [comment]
Exactly same problem here, did you fix it?

**Comment by leoluk** [comment]
Sounds like this is solved :)
