### ISSUE TITLE
sol wwETH to etherum blockchain disappeared

### ISSUE THREAD

**Issue by ajainwa** [solana-labs/oyster#292]
Hi, I sent over 0.1 wwETH from Solana to ETH through the wormhole using Phantom wallet. I confirmed the transaction in Solana but it gave an error at the approve transaction on ethereum section. Now I do not have my wwETH in Solana or wETH on ethereum. Please assist. My wallet address is below.

SOL Wallet: BRQ8CxT6845TakVEAMsX65togTU7XB9BTAKbW1dUJmPN

ETH Wallet: 0xfBFD1fb4Ae85F6932e4E64d14d9aF89Bb1A916c4

**Comment by leoluk** [comment]
Please provide the transaction which transferred out the funds

**Comment by ajainwa** [comment]
https://explorer.solana.com/tx/3A64FMSUrxxf4XtXLBrpZ7S6hadGF4TYuhB3161V9dnFFwZzJYS2WKnSitoXQekWDZcyLss9y5B75zBZbSFYDemJ

**Comment by ajainwa** [comment]
https://explorer.solana.com/tx/3A64FMSUrxxf4XtXLBrpZ7S6hadGF4TYuhB3161V9dnFFwZzJYS2WKnSitoXQekWDZcyLss9y5B75zBZbSFYDemJ

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): fa42a05719ec34759976da67ce2f70dd83cd73daf2825c883b7fb096d87aecb0

Signed VAA bytes to submit to the contract:

> 0x01000000010d00c39b269e08a4c1d557cccdedddb4d0c35db796148fc6b722c3cd73919b16ba9061eacfef919ef2e837e6b82bef1500a7c2e27839e41a166f20537f622c56031b01014dce68914a6269b6ac49d7f0901d93ac453cb9f5d034c5e1e39d833951d078e36da9f55e5755bda27113adb9ba54d928ebd7d0b956564f4fc4b5d9c7b3a8b96d0102dd4a93bd2c72d0af3237bbd2b300c9082370ea25d7b0da0fc57e3c7d63ffd7dc54eb2fb858cfb8ea4c7314d3254a44fbcba02a0b5cd3e56553a74bf33abc2f9d0003c7f5e798379b5fc0ae0c2ded5b8ff0d2d7d501ed7453f28a6419efa23f45fa5d74d73cfa23ad3a94f2528b80a03a857e9392f5a2ae9046883c31efcaffa9ebe60004fea83cc50d90e1e19c4110ed61644b77ce095353ea440817bc866be67e504a6a783681df04cf6847b58adf5129550728b627842f16c99009a5e2c41fb0e945d3010597d0cdb7506628b09d9e8f5d34927f2a48b5615929b097e98b7da3b33c9b4a540f32388f6f9e6407ab611c2b5d7c3461cd84f8660184e5aeefa985e419c4065900078a65b51c603d4e2e4dfea4bcc7faf39db8fdd9c3ca3c633c7141103e781a383d4282348d5103c5eecd6eaafeb7f4d558a860f60a0b7faddaa9b37dad4924c1180008d9742f7dfdcdeb9c0dbba4735cd3a2a734099d6e6d08fe63a0cc31abcbb7b2b17d2a0d143666816ebc19fc6257f71bdf56262ee97d9f063201616f5df52b4d0e000ac34b47c8ddd826418f9396b588cc1c8da1e8f3ac402b8a7f9d2921c8d26e3486143026ed14fd4a0454f830d991ce4a1c344a9e2d79cac2008f4ea58240d71bcd010bf69c13df0ff968c27443bad58bc7bbc304b9e727838959b5533cae8b6b10071a7af1fc1e31b2e41b320495601273b98f914af34481443c1a5841dbe07b461fec010d527f5b18ffb572d47f62abd63f0f9836061b3d54d618b1afdea7bdc77244a08b78b3ab2cca89f474e492b53e55b551efe72fdd6d8beb5248d504e04c3ebbda9c0011ad59e564596dd29323485a18e68f9af36dcd713263cacd41c27001218270489d4203ef3da9ea031f69893674d204ce5ff8852ab2e34d19e5e1a2945bb777846400127634fba8395beca76c9fdb2d3bc5a1ff71b5e538a64e2984d4fa744e79aad95f057567b9e456f237b361a6e1600e8dce9f5a5ce7c9d159937ad9e9ab62c1e7d700613a80551000014bba0102e882cfc674dee60a53ec80bc503fc26301458177a5f2724c237bb85f9351931c000000000000000000000000fbfd1fb4ae85f6932e4e64d14d9af89bb1a916c402000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2090000000000000000000000000000000000000000000000000000000005f5e100

**Comment by leoluk** [comment]
(you could also try using https://www.interstellar.tk if the above doesn't work)
