### ISSUE TITLE
Missing wBTC after bridge from Metamask

### ISSUE THREAD

**Issue by mattr121** [solana-labs/oyster#293]
Hi - I bridged wBTC from my Metamask wallet to my Phantom wallet.  The transaction shows as confirmed on Etherscan but the funds never appeared in Phantom.  Is there anyone that is able to assist me with this?? Thanks in advance.

**Comment by mattr121** [comment]
Here is the transaction hash on Ethereum:
https://etherscan.io/tx/0xc586d29f974b698297871dbc47215ec4c6395fe08bcc43151bf6457f705a499d

And here is the transaction on Solana:
https://explorer.solana.com/tx/5vEgYuwSkt6BNnN6qHdL6xJxcX5wzWG7t8fpneAE8nYyKhN63SiMt1zpzP8XuUTnBuxKe8RgC1zK2vs7Bxnc9TcV

**Comment by smehra** [comment]
Holy cow, this worked for me.
https://www.interstellar.tk/

**Comment by mattr121** [comment]
> Holy cow, this worked for me.
> https://www.interstellar.tk/

I think this only works if you're transferring from Solana to Ethereum

**Comment by leoluk** [comment]
> I think this only works if you're transferring from Solana to Ethereum

That's correct. This one needed a little shove: 
https://explorer.solana.com/tx/27BpPEPG5CavhxjQyiAZxdvSkLjb2WPS83CdYGsWsq31oXDWAXCWLwtfgxHtxVBnHuU1z4XxMw3D2RMHFcbCa1UL

It originally failed with this error:

> 2021-09-09T22:55:27.610Z	ERROR	wormhole.root.solvaa	solana/submitter.go:166	error submitting VAA	{"error": "rpc error: code = Internal desc = verify tx sending failed: ClientError { request: Some(SendTransaction), kind: RpcError(RpcResponseError { code: -32002, message: \"Transaction simulation failed: Blockhash not found\", data: SendTransactionPreflightFailure(RpcSimulateTransactionResult { err: Some(BlockhashNotFound), logs: Some([]) }) }) }", "digest": "8f286a4c72f5d3aa4e15a20e583588fd03454006d4ab5aacb1c8a28c2a68a52e"}

(might be https://github.com/solana-labs/solana/issues/16873 ?)
