### ISSUE TITLE
Transfer of WETH stuck in Wormhole as I rejected transaction on metamask

### ISSUE THREAD

**Issue by SMGithub11** [solana-labs/oyster#294]
HI there, 

Would appreciate some help. I transferred WETH through the wormhole bridge from Solana to Ethereum. It was successful on the Solana side but I stupidly rejected the transaction on Eth side as gas fees were super high.

It's now stuck somewhere. Is there anyway to get it back to my Phantom wallet please?

this is my transaction: 
https://explorer.solana.com/tx/3jJq5NYpb6eWfyMQnrs7aLaGQzxQWihWK77h9xRxsBKNmhsnsGsmyqd7AyU3S2gqj9jSQ7pUSdeYbmgu973QSkqC

Thank you for any help you can provide.

**Comment by SMGithub11** [comment]
there is no transaction hash on the ether scan as I rejected the transfer.

**Comment by smehra** [comment]
I have a similar problem with renBTC which is stuck in the wormhole as I tried to move it back from Solana to Eth. Please let me know if you find a solution

**Comment by andydhancock** [comment]
If you want to get it unstuck and onto ETH then https://www.interstellar.tk/ should get the metamask prompt up.
But then that costs much gas and ends up not where you want it. I'd also like to know if it can be reverted back to the SOL wallet!

**Comment by smehra** [comment]
I was just happy to get it in MM, happy to pay the gas

**Comment by SMGithub11** [comment]
> If you want to get it unstuck and onto ETH then https://www.interstellar.tk/ should get the metamask prompt up.
> But then that costs much gas and ends up not where you want it. I'd also like to know if it can be reverted back to the SOL wallet!

ok. thanks. will try.

**Comment by SMGithub11** [comment]
> If you want to get it unstuck and onto ETH then https://www.interstellar.tk/ should get the metamask prompt up.
> But then that costs much gas and ends up not where you want it. I'd also like to know if it can be reverted back to the SOL wallet!

I know this might be a stupid question but it interstellar.tk legit to use? I am so scared of all these scammers trying to get into my wallet - not that there is much in it. But it's precious to me...

**Comment by SMGithub11** [comment]
> I was just happy to get it in MM, gas no issue.

Did you use interstellar.tk? and was it successful?
 thanks

**Comment by andydhancock** [comment]
> > If you want to get it unstuck and onto ETH then https://www.interstellar.tk/ should get the metamask prompt up.
> > But then that costs much gas and ends up not where you want it. I'd also like to know if it can be reverted back to the SOL wallet!
> 
> I know this might be a stupid question but it interstellar.tk legit to use? I am so scared of all these scammers trying to get into my wallet - not that there is much in it. But it's precious to me...

It looked to do the right thing but as I say, I didn't really want to be spending all that gas to get it where I didn't want it to go so I haven't completed a test with it myself.
So all I've got to go on that it's legit is other people in the comments saying it is.

**Comment by SMGithub11** [comment]
> > > If you want to get it unstuck and onto ETH then https://www.interstellar.tk/ should get the metamask prompt up.
> > > But then that costs much gas and ends up not where you want it. I'd also like to know if it can be reverted back to the SOL wallet!
> > 
> > 
> > I know this might be a stupid question but it interstellar.tk legit to use? I am so scared of all these scammers trying to get into my wallet - not that there is much in it. But it's precious to me...
> 
> It looked to do the right thing but as I say, I didn't really want to be spending all that gas to get it where I didn't want it to go so I haven't completed a test with it myself.
> So all I've got to go on that it's legit is other people in the comments saying it is.

Ok. thanks for your reply. Appreciate the suggestion. I will see whether I've got the stomach to try it out... all these is giving me stress :)

**Comment by andydhancock** [comment]
Gas was a bit lower today so dared to test it as the wrapped SRM are useless on solana even if I could undo.
Worked:
https://etherscan.io/tx/0x71e8fd77e480a91d7487597e595b5da6199b874efde87d9824235f3d9856acee

Now I'm back where I started, less gas, plus a lesson!

**Comment by SMGithub11** [comment]
> Gas was a bit lower today so dared to test it as the wrapped SRM are useless on solana even if I could undo.
> Worked:
> https://etherscan.io/tx/0x71e8fd77e480a91d7487597e595b5da6199b874efde87d9824235f3d9856acee
> 
> Now I'm back where I started, less gas, plus a lesson!

wow - congrats. So you just connected to metamask - then put in your transaction has from solana and the transaction appeared for approval on metamask?

**Comment by andydhancock** [comment]
Yeah, box appears when you click submit.
That's the beauty of decentralised smart contracts; When the official interface denies you access to a function, you can still access it another way!

**Comment by smehra** [comment]
> > I was just happy to get it in MM, gas no issue.
> 
> Did you use interstellar.tk? and was it successful?
> thanks

yes, itworked

**Comment by SMGithub11** [comment]
> Looks like this is already resolved thanks to the community <3

No it's not. The link does not work.

**Comment by leoluk** [comment]
Try this then:

Manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 43f3cd0f2d6c4dd57a94c57aa607424957b025f270d063bfd7cc0913169fa555

Signed VAA bytes to submit to the contract:

> 0x01000000010d00736008bd4820313122ae727d6a4016c908a675bfd4a60bdee0b5de121a364d6b32c70350f69c67f2f11ad7ea6d28cea7d4e24e666963cbdf9be37efb8fd8f660000185715e46e5786ab4517b06970716bcdfba482495badbca80e6244fbf2f4b8e621d32fe2c4335c964dee8eed3cf784bb4f656b05223f0d326a6b0841cb5185c9801036ac169a2bb035889bba949019a90161542b9bbce8f9875090e9f85f45440bb7332e678530688f5b4241fab8eeb4f43166fc54878a112292d1bc2275cd81ab7f20004391fdbf170141cf2e5dd5a7e52643f87f223fb2b5bd5dfb2b65c29c083e53cda00e986d24974514894562f690b6a40f54be12afc724d3ffa78044c515d057fea0005357b01c14082afdc7beae206c62909a64aec06d1eaf09bc360c380976c8b4a310ce094f2e31fbaafe0325fa1cd299440e9d664f1fe09f5ddea51df03a9b3d4870006abac263a8e51f7d4a7c683ec5a38d8e94cb5718970af2cf9dbbb503a59fbc5ef39aff4472b132bc4645dfe8412c892de55606c4f343b4549221de71c0c7615050007a963a58af1bca8669d4f0ffd4a8d8e18cb960b285de3b5dcb6b97f6c04f60d22520dd3ba29c025cf38f7cbf24ed048296c39a20b81ad9c377d7130bc9afc0ca1010858bb8f0796b268cc794db8c44ff19c9b0bc3a20524fb300c3fe66830fd4e3cd77013ce53afd46aca87a9a027e2bb600f97a265cf899ca4311c26302a12c5c140000a7fdc8b3b50f1c048e488af1c24a4c2ad7ae3239b11da433b0a45ec2ae4edbcd755e650d011882f15a8a1d2624f1108a281a4d433c440b7c251b2859bbfb8881e010b0e73f646529b657a015f6fe128e45ae513b5e671fc36bbbfc204009e9782218a15a4927734377ac47c29ebeef0093400860214bca13ceb90cb7bd348c6a3a11e010dce43f51864149052cd80095c20758ccc502cb9b56a5d2caa18656d1396a3cfb70c2e7173f3772305ef6aaa9b1df6aeb2431d0e12ce73fcecdc6c5498068fdbc20011481c00b6f8f9ab15df91f712b9dae319efc960c4dd15cf5b7e04901facbf33ac72d72edb7e2d09ca629c22d76176877d974221f8e4707eaa92d4c86f88979e660112de133bb3dcb4c3871ac34c7f24d89d2a1fbec1d10eb56ac0487b144e8ff62161268464e15bb34b7988d5add7827cac26033de53ff728d6f99af0649eada8c8f100613ab83d10000106c00102473c7055121977a8cd250896a509fcc9e6664342bc44d8e6bb19da8238bbb65e000000000000000000000000f433bdbf45ae8396805f5882c9f395b246e62af802000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc209000000000000000000000000000000000000000000000000000000002faf0800

**Comment by SMGithub11** [comment]
thank you. that worked :)
