### ISSUE TITLE
Can't transfer ERC20 UST to Solana

### ISSUE THREAD

**Issue by mperegoo** [solana-labs/oyster#296]
Hi, I don't know why but I have 6 transtactions to approve the transfer (this means more than 60$ total) and also now I can't still finish the transfer itself.
It says:

Lock assets
Waiting for MetaMask transfer approval
Transfer failed!

Etherscan: https://etherscan.io/tx/0xf034a7a16667d2184ca98997aee3943ca0bb3f90da15942039ee9605cacadd55

How can I solve this? There's a way to have all those apporval fees back? I mean only 1 is necessary..

**Comment by leoluk** [comment]
What's the Solana transaction for the transfer?

**Comment by mperegoo** [comment]
Don't know how to find the exact one now.. this is my Solana Explorer link: https://explorer.solana.com/address/8wkZPEKuwGBLgryu3rfmEsfi3fE1aHyizwr6M846ymTW

Btw yesterday I solved this problem alone by just inserting manually the value of UST to move.. before this I was just clicking on my max to make it autofill.. 
But I still don't know why i had to pay more times the approval fee on ETH

**Comment by leoluk** [comment]
> But I still don't know why i had to pay more times the approval fee on ETH

Sounds like a bug in the UI - cc @yamijuan / @bartosz-lipinski. You should only need to pay the fee once.

> Don't know how to find the exact one now.. 

Go through the transactions one by one and find the "Wormhole Transfer Out" instruction.

**Comment by mperegoo** [comment]
Yeah sound like a UI bug now..

Usually every dapp make me pay once and I can't pay anymore. This time something gone wrong for sure and I had to retry.

Solana transtaction should be this: https://explorer.solana.com/tx/22UA3g6UokgqT1Zig6i7zUujHaYB5ueD4VCMbJGhPF2AT1F1aYRcNA88KKoNpT3LVLebdDpo3Gvw5QfqSNMCetYX

**Comment by leoluk** [comment]
No, this is not a transfer out.

**Comment by MARKO250851** [comment]
i have the same issues and doesnt look like a solution writen above anyone help please?

**Comment by leoluk** [comment]
@MARKO250851 you need to be more specific

**Comment by MARKO250851** [comment]
when trying to use solana wormhole bridge to move eth to sol i connect my metamask and phantom wallet however, very quickly with half second comes back, 
Lock assets
Waiting for MetaMask transfer approval
Transfer failed!
most occassions says this however sometimes it doesnt even say with prompt approve assets. im getting no where with this and have no idea how to fix, a couple of times its given me the explorer link below, but have no idea what this means if completed or not. also taken small deposits from my wallet , not good at this and have no idea whats going on. 
id appreciate your help thanks.https://explorer.solana.com/tx/2jVuB1oqCgkMJxbW15o2VnWFm7JW6We7kHsS3doEbWkLmGe29VQrj9ZY33Hoq1V5BUUN42q2DsvagXZsd9LL9agy
