### ISSUE TITLE
Issue: wWETH transfer from solana to ETH

### ISSUE THREAD

**Issue by honestnemo** [solana-labs/oyster#297]
Transferred 0.05 wWETH from solana to ETH and approval for solana took place but metamask pop-up for eth didn't open. Now the wWETH balance shows as zero on solana but no WETH received on ethereum. 

Also Tried https://www.interstellar.tk/. but seems this script has an error where it misses a character in the eth address and recognizes target address as 0X...... instead of 0X0....(my eth wallet is on a ledger).

Transaction for move-out of liquidity is :
https://explorer.solana.com/tx/5VxfEkmPVFa75AZNVvJaUXwA51UHyn9VoPLykfzsLfuzfdTwrSPY4Yzo3veTgwKMWVD8NYWJ8zg2zEDFqJYs66N8

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 67bcb50c583500aa62ee932e75ce5dc56d522b32ab1f162f88c541243ee16b1e

Signed VAA bytes to submit to the contract:

> 0x01000000010d00d28216de94f95eaa6c900baf3239bd6d3868f47f020b4edd7c02f76ed3fb968c781a1b0eafb2f6080dd0012f6c971ac084edfc6d47d3d36139588f9de0eda34001013ec215ecdc80a7fbe4ad62efa2dab643a813fb864b5e146b4e9995dd8a9a7dce3812e24a567683737c754beb170cd9e4b6a78b92441ea25f247e8c054e8ed3d501039599b50092ef6ef3052f7e8be22448287f86e3de33576fd853a00842c2fa9271609cb07bf11e603e7b13217b2f39eec4470d10a77433b2e2668a9316abc30abe00045fdedfac65a9f5a638bdf22f354bf6faac5677fffe5197d998ec8d1f521f572f306954a300f0283654b8c58fece4ca07d6346ef7e727761b094b74293ed0470d010513277beb6a15242904f1245a7f70e8f03eec9066cee1fb9c47c5fcf8e9ad7b691654cf69ba3ba2b62656df0926440396f799d59119af3019cb04b88b6d59e3f00007fbb87f3c335487430f953fe2c04d967bacb82251e14322a5ee097242e27ff17e081cfbee05b675c5b4c317d2101022887cd2901bcef3352e640692615ceb1d420008e0e79ca289b9be5b08c7980104b1fef3bc61ac2a7a217e13083a5599017583c414253fc750e08eb3edbf870b5202eb532c9835f32bb8ba39b19d16beaf31b9e701095a475ca6cdb07c21db950a618803be88fafaa42d92b1c3029f4c58aa6529bddb7c846fc7aa12152dd4746e926fdb3fb44c8ed3698905763b043f2874366810bd010ae3282515150e0171e8e8cda624a635ff23f091110f64bbd8985bc7d994da26632452db7f34b780c7812cf029cbb576715f318e57fa27165a508cdb6e7641d4f9000b0e56fc0dde55eab96a6b15a2c06b43206e80385147f028266396641279b274965241a117a270e3c55f082bf90b83207a0990c498a08365d4f23bf5746e6b7715000dfdb950eb3ff7715392a3db135303a620faa18cd6ec5929cf75eb659f3120ed0c77bbcd294bb217a6f6207c3dccc9d78056508435f4fb3ea829bf59b23e580e580011cbd00b1030de91b036c255df1fcf892ad74898e5aa66146c261668e18034d434442923ef85587259c2d40712b780d81bfb1ab7fab5c80481511019a4f2a19cf50112fece65eaaa1b93a6fd3e64f884314344c0ee22785582286b366cd6f2213836fa6817374fbc34e2e9db4693abbe9bee7ddb35b7e53393872a7c4e68be152d5ddb01613b091f1000009ec50102d70618f9a8c304961153a5aef041278eeb138e0e0d5af74f4b2ade3e77158b210000000000000000000000000656d8b7b1fcc09788f4a7b657b38a3a4eeb3f9b02000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2090000000000000000000000000000000000000000000000000000000002faf080

**Comment by honestnemo** [comment]
I am getting the following error while using Signed VAA bytes in submitVAA contract " Invalid transaction params: params specify an EIP-1559 transaction but the current network does not support EIP-1559', Do I need to use an older version of metamask to submit the transaction?

**Comment by honestnemo** [comment]
No worries, updating metamask fixed tht issue. Got my weth. Thanks
