### ISSUE TITLE
wBTC lost

### ISSUE THREAD

**Issue by cryptoUPnow** [solana-labs/oyster#298]
Hi I tried bridge my wwbtc solana tokent to EThereum network. But still didnt recive

**Comment by smehra** [comment]
Happened to me. I used https://www.interstellar.tk/ to retrieve

**Comment by leoluk** [comment]
@cryptoUPnow You deleted the tx hashes from your post, so presumably you wouldn't want me to publicly post your VAA hashes either?

Try using https://www.interstellar.tk
