### ISSUE TITLE
Missing 70HBTC from Solana to Ethereum using wormhole bridge

### ISSUE THREAD

**Issue by alexonemoretime** [solana-labs/oyster#300]
Hi 

I tried moving 70 HBTC from Solana to Ethereum using wormholebridge.com and I still do not receive it on the Ethereum side.

My solana txid
https://explorer.solana.com/tx/4oFHNWBSRNsatZDXWCJM2yUH9KwhqjydqZf9xikwvzfm1ewFMLPHUFyfRiLAWoQaKoyFbC7ucke5QVDvSuYidBM6

I tried to use https://www.interstellar.tk/ and i got the metamask popup but the transaction always fails (I am using metamask with ledger)

https://etherscan.io/tx/0xc5beb7129fad553ff0b5861fde8c6e20356e9ad21aef2960d974fec30a7b4561

Can somebody please please help me.

Below is the log from interstellar.tk

9/12/2021, 5:01:15 AM - Analyzing transaction "4oFHNWBSRNsatZDXWCJM2yUH9KwhqjydqZf9xikwvzfm1ewFMLPHUFyfRiLAWoQaKoyFbC7ucke5QVDvSuYidBM6"
9/12/2021, 5:01:15 AM - Fetch transaction info successfully
9/12/2021, 5:01:15 AM - Transfer Amount: 70.617572612
9/12/2021, 5:01:15 AM - Target Network: Ethereum
9/12/2021, 5:01:15 AM - Target Address: 0X6AEDA057364CC4AAD943CAC04A1C149D90E10A3B
9/12/2021, 5:01:15 AM - Extract VAA: 01000000010d0020f7c72f7c2d5153ff63e6ad310a56bff16b7dddcf8182138c17288c9b4548cb77392736471d441b335c706b064aa990711855b02238e0f208e74a1d563d375c01012b39b85bee93a68221e3ae670af61c0866d041c0931ef70ea459b0a7a6bf7a4e2ae84b4aca3ee19a00280b756f1ec8503819f45c7810c3d3d1847c4a7772341f0002726dc4b6d6e5f709d56a9331e281ae66b86ced000a43b4f2e31669c3716d7b25191be90039b218820bcd16114133ed68e02a60bc98efbc9c547f846d69070f070104a835b17ddb2af324bc714f9944273c064891b44ab27217391d7d50cb421b3e6c2375d3269dd6b3294438046615f4f24b677b0f9cc9ac622d9ec3c6cb54291ca80105af7cba4794d0ea6a019221a4d639b6897dcb690c132c3ded0b6e463812b3e4e41cbeb4075ec4e34b138c2dcb85e3b264cac1cd769404465cae8b7aa7d761e90b01060fd712ed5ea543b1b339c64bf2e2bf83fc246f6bf9cb09c5fb760a97a4b5a3d1186c140f02fef305b0f824a308d6ea809d03096f2786a6842f4dd487e00ea7400007e41402e407d807905767d90bbc8132a8951d5813046a3f19270f600398005b6631d7679b7167f91ea4ab62f72690516807997015472c50c75a4ab339017d1be10008fcb44f0095396f15e0535b879043dd848f05f856850c5cf008d5049019a116a17e3eeb2ab7c98b4f68292fac32b787742d68f4f4d61811af45f6b24aabe927ed000a041fe044dbddccacc07cc78fb0583c867f137da81fd71033fd30e8a8d1d000267bf44482fb76f93ba6758fa017d45cd7b60a8e421c960b8626b395b091e0ac93000d17161a014cae399074047bf557efd49fa73ae9875693e3d6ad87e1149b64993d49bad42f6d257c1d038751585b98b572ec4759e3e1af13ac205ebb520240f9b8010fef3c7a82b81de3e7905ccec5d9094166bbd86f5349a6c4e76f7112e0930d9f763b385f40cf72424a9a6657b8609dade4edc84e8e3a605a28732509be103d279a0011090ac2ae7068ba55fde00bfa9ec0adf5cb656c3a4797f49d33cb51729dc0ed426a8833a4f3ddeceac1ff5c1d9edbcb48eece5626d9b8119259a7f62d2f83631801129e74f97df235a14da81584db1c50ab404cf0153629b10ee749cd3228206f77906ddb83d01c35823371712649b30ce68f592d775c54506ed86ecb4edc997e1aec00613d05ac10000099770102ebb7f26e854c6e0b685ff3d78b9789fb32c084399087d61508363759593cbdd90000000000000000000000006aeda057364cc4aad943cac04a1c149d90e10a3b020000000000000000000000000316eb71485b0ab14103307bf65a021042c6d38009000000000000000000000000000000000000000000000000000000107122a504
9/12/2021, 5:01:15 AM - Creating TX to mint asset
9/12/2021, 5:01:41 AM - Waiting TX to be mint
9/12/2021, 5:02:19 AM - Error: transaction failed (transactionHash="0xc5beb7129fad553ff0b5861fde8c6e20356e9ad21aef2960d974fec30a7b4561", transaction={"hash":"0xc5beb7129fad553ff0b5861fde8c6e20356e9ad21aef2960d974fec30a7b4561","type":0,"accessList":null,"blockHash":null,"blockNumber":null,"transactionIndex":null,"confirmations":0,"from":"0x6aEdA057364cc4aaD943cAC04A1c149d90E10a3b","gasPrice":{"type":"BigNumber","hex":"0x2e90edd000"},"gasLimit":{"type":"BigNumber","hex":"0x03d090"},"to":"0xf92cD566Ea4864356C5491c177A430C222d7e678","value":{"type":"BigNumber","hex":"0x00"},"nonce":3878,"data":"0x3bc0aee6000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000003ed01000000010d0020f7c72f7c2d5153ff63e6ad310a56bff16b7dddcf8182138c17288c9b4548cb77392736471d441b335c706b064aa990711855b02238e0f208e74a1d563d375c01012b39b85bee93a68221e3ae670af61c0866d041c0931ef70ea459b0a7a6bf7a4e2ae84b4aca3ee19a00280b756f1ec8503819f45c7810c3d3d1847c4a7772341f0002726dc4b6d6e5f709d56a9331e281ae66b86ced000a43b4f2e31669c3716d7b25191be90039b218820bcd16114133ed68e02a60bc98efbc9c547f846d69070f070104a835b17ddb2af324bc714f9944273c064891b44ab27217391d7d50cb421b3e6c2375d3269dd6b3294438046615f4f24b677b0f9cc9ac622d9ec3c6cb54291ca80105af7cba4794d0ea6a019221a4d639b6897dcb690c132c3ded0b6e463812b3e4e41cbeb4075ec4e34b138c2dcb85e3b264cac1cd769404465cae8b7aa7d761e90b01060fd712ed5ea543b1b339c64bf2e2bf83fc246f6bf9cb09c5fb760a97a4b5a3d1186c140f02fef305b0f824a308d6ea809d03096f2786a6842f4dd487e00ea7400007e41402e407d807905767d90bbc8132a8951d5813046a3f19270f600398005b6631d7679b7167f91ea4ab62f72690516807997015472c50c75a4ab339017d1be10008fcb44f0095396f15e0535b879043dd848f05f856850c5cf008d5049019a116a17e3eeb2ab7c98b4f68292fac32b787742d68f4f4d61811af45f6b24aabe927ed000a041fe044dbddccacc07cc78fb0583c867f137da81fd71033fd30e8a8d1d000267bf44482fb76f93ba6758fa017d45cd7b60a8e421c960b8626b395b091e0ac93000d17161a014cae399074047bf557efd49fa73ae9875693e3d6ad87e1149b64993d49bad42f6d257c1d038751585b98b572ec4759e3e1af13ac205ebb520240f9b8010fef3c7a82b81de3e7905ccec5d9094166bbd86f5349a6c4e76f7112e0930d9f763b385f40cf72424a9a6657b8609dade4edc84e8e3a605a28732509be103d279a0011090ac2ae7068ba55fde00bfa9ec0adf5cb656c3a4797f49d33cb51729dc0ed426a8833a4f3ddeceac1ff5c1d9edbcb48eece5626d9b8119259a7f62d2f83631801129e74f97df235a14da81584db1c50ab404cf0153629b10ee749cd3228206f77906ddb83d01c35823371712649b30ce68f592d775c54506ed86ecb4edc997e1aec00613d05ac10000099770102ebb7f26e854c6e0b685ff3d78b9789fb32c084399087d61508363759593cbdd90000000000000000000000006aeda057364cc4aad943cac04a1c149d90e10a3b020000000000000000000000000316eb71485b0ab14103307bf65a021042c6d38009000000000000000000000000000000000000000000000000000000107122a50400000000000000000000000000000000000000","r":"0x5fd68559fbdf289c3e80ed7bb67c425b7453207e89928bf3cac7ee55dcc6f457","s":"0x3078837278841361e3c48f25387fbd12fcae202221ba874c4d408db5a2dc6f98","v":37,"creates":null,"chainId":1}, receipt={"to":"0xf92cD566Ea4864356C5491c177A430C222d7e678","from":"0x6aEdA057364cc4aaD943cAC04A1c149d90E10a3b","contractAddress":null,"transactionIndex":1,"gasUsed":{"type":"BigNumber","hex":"0x03d090"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0x5b3462b1a58fa58a0eb513b69429f2116935aea724be008aec74ab446c2e1b95","transactionHash":"0xc5beb7129fad553ff0b5861fde8c6e20356e9ad21aef2960d974fec30a7b4561","logs":[],"blockNumber":13206775,"confirmations":3,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x05633c"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x2e90edd000"},"status":0,"type":0,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.4.5)
9/12/2021, 5:02:19 AM - Progress exit early with error!

**Comment by caulinez** [comment]
i am not a support from wormhole but from the ether tx error seems like u are out of gas?

Warning! Error encountered during contract execution [Out of gas]

**Comment by alexonemoretime** [comment]
> i am not a support from wormhole but from the ether tx error seems like u are out of gas?
> 
> Warning! Error encountered during contract execution [Out of gas]
> 
> ![image](https://user-images.githubusercontent.com/7501144/132974073-c8517c67-1089-4836-a1d0-a466fb422e3e.png)

Hey thanks for replying, I don't think it is a gas issue, i tried 4 seperate times and I put the gwei really high, it fails like within 1 or 2 minutes. Really worried, somebody please help.

thanks

**Comment by caulinez** [comment]
did u change both the 
1. gas limit and 
2. gas price?

**Comment by alexonemoretime** [comment]
> did u change both the
> 
> 1. gas limit and
> 2. gas price?

I only changed the gas price, never changed the gas limit, what figure should i use for gas limit, i can try again now.

**Comment by caulinez** [comment]
normally the first digit for gas limit i doubled it. eg if the first digit is 2 i change it to 4. But i think there is no real play book for it. I'm just doing an estimation for it

**Comment by alexonemoretime** [comment]
> normally the first digit for gas limit i doubled it. eg if the first digit is 2 i change it to 4. But i think there is no real play book for it. I'm just doing an estimation for it

Hey mate, this is fixed now, i changed the gas limit from 250000 to 450000

Thank you so much, was so worried about it.

Cheers

**Comment by leoluk** [comment]
@caulinez Thanks :)
