### ISSUE TITLE
Renbtc missed from Solana to Eth using wormhole bridge

### ISSUE THREAD

**Issue by PeLaOs** [solana-labs/oyster#301]
Hello, first i sent renbtc from ETH chain to SOL using wormhole bridge and everything went fine. I tried to pool at Saber but i noticed that i chose the wrong renbtc(wormhole) instead of std renbtc and i could not stake it at saber...

So i decided to send it back to eth again. I use phantom wallet on SOL side and metamask on eth side, i connected both correctly at wormhole and did the transaction but i see 0 renbtc now at my phantom wallet and i dont have it at eth chain on my metamask neither.... it has dissapeared...

This is the transaction i have on my phantom wallet: https://explorer.solana.com/tx/3K2X3v6eDT96A3mKJLzzKomgAdxpTAbPUy4wMFyLVdgvqo6nPYdjnMynHtaywgCpe9UW4PdJECEo5XzVoS67CCJh

Please help. Im a bit desperate here.

**Comment by caulinez** [comment]
u probably need to retrigger the vaa again. there are several pple who got into the same situation as u, so u can browse around this github to see how they did it.

**Comment by PeLaOs** [comment]
any dev please?

**Comment by caulinez** [comment]
not a dev but i hit into the same issue previously. did a metamask popup happen for u on the screen? if no you might need to resign a vaa on ethereum

**Comment by PeLaOs** [comment]
hi caulinez and ty for your help, no, i think i did not get a metamask popup... and i dont have any transaction on metamask about this transfer... i have read on similar issues with other people that devs gives that VAA to resign, ill wait to a dev to see if that is the answer...

Anyway i dont know how to do this, could you tell me how to do it? ill have to wait to the vaa anyway... ty very much

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): e55f5a14aabb443157e93123362628dcd743b57bcdd7cb3cfadfcdd5ab11d215

Signed VAA bytes to submit to the contract:

> 0x01000000010d00b25dccc811c859ea73f1765965c91e4da188d1f9ff0c3884a09b61a0240382763ad19888f294ed478591470684997ed6466d88c6cdb3e832ec770d01ff19119600019f98e28216c2015e57be792f6238fc26ca8db042142a4bba4359d04bd1210be22864fbe3456af6ee51037c38a050c4058258101d4f64b23d155fe0ac084a767b0102aa0c94f5e6f7f517c2928265def692b44e9ae3b05402d476f6adfc7749c720157c0d6d1b72cac343dd831b88f3af458f4dcb336bdb8d165a4d52c8b027f7787b0103277a3fd63b8191501206f011fcea2b9b8309a55a75abc407b98e32a3183f28d2159ecdb1910cc0043b6312fafc0b846906ba61368c33f599333a4a753efe3a27010441ea0666793f0de70fa788f49c880ac8871d59e2c0abe2232f70cdc4116c33b62a0059ebf60aaff9d442a1f8f19a2b93ea6de612682fdae2a328ea15e954d47b00055fcfafa80cb9ebfbbfd900f23b3af71a429a137437dc592511079d1a8049fc65252d2c2905cc968106fbb2c3f6929b2d91c855460e96d5501b9d6d24158ae4e50106acbc6b154effc8fc959fdc491da51019d67eda1889cb328ec9d58c7f72ba82d4426d5cbd0dbef2a666888ba7f986ddff29b153af8ee6f3bfb3b255d3a158e2ca0107d6e59f482545ad7befe903cb8e723c94642008053795af3d57089b6aae66cbf80033af97e910d85e6cad90112b5966fbe58230e2f27ce8b778653f80e8e51bf50008d1c18994b8d43a55970222655a63a612761b269747a9d2eb3ab8bb6c4285416b3598f0e7c46a0b8bb6cbcaf5d31b10c836f487e61cf776ced49184cf22708b0f000a4ee6c18a06d07cd7f3acfa41687a2dce58c6903ee66ee0256fde49b6734b85bb3bf02deccaf694c47ced5937983f5a7e7ddd38f3d0a8dfb31e26f1284931dfc4000d6c4063b234ccc450405e86cf8ff17a1735f37dd8af43fb8a1325cb0de86ff2864f68e36e4df1a412a5f47ec6952251f315fe0e0a356fcc1298929d6c377d42e000118c9c6c1b426ee00aa5058b87864c349624b1353e4b3f30b0549a2e0082bb05606d9cecab38ed46f05a522e10d111305f0901d5d80d4cc57bc3a43be151919bdb01123efbb5aeaa2202aa40ee85121cf229ba5539e996e3aac6cfecf566bfafe17fef249d6392e36a40c398aeaf891c73c4b10655a74afef98ec5c4bb2c101068fc6801613cf565100000f01c0102529e0d315ddcf8ee47ad78c08e82f272a00b3163534ada4997fec227c03ce19600000000000000000000000024a577774274fc6de6e26a04862ade40c0960ea502000000000000000000000000eb4c2781e4eba804ce9a9803c67d0893436bb27d0800000000000000000000000000000000000000000000000000000000035ff09c

**Comment by PeLaOs** [comment]
Hello, i get this message when i connect to web3, and paste the VAA on submitVAA tab and click "write":  Invalid transaction params: params specify an EIP-1559 transaction but the current network does not support EIP-1559

I already tried yesterday to reload cache and relaunch wormhole but did not work.

Any idea? ty

**Comment by leoluk** [comment]
You can try the third-party https://www.interstellar.tk tool as well.

> Invalid transaction params: params specify an EIP-1559 transaction but the current network does not support EIP-1559

I never saw this error before. Are you sure Metamask is connected to Eth Mainnet?

**Comment by PeLaOs** [comment]
![Sin título](https://user-images.githubusercontent.com/90532444/133069560-61134844-9143-4cde-806c-4ddd62e60984.jpg)

Yes, it is connected for sure. So then i should try interstellar? i saw that link in a lot of posts here but i thought it was something that scammers were using to hack your metamask or something...

**Comment by leoluk** [comment]
We did a brief review of the source code of https://www.interstellar.tk and it seemed fine. A couple of folk used it successfully.

**Comment by PeLaOs** [comment]
great now i have it, interstellar worked, ty.
