### ISSUE TITLE
wBTC stuck in wormhole

### ISSUE THREAD

**Issue by mattr121** [solana-labs/oyster#302]
Hi - I bridged wBTC from my Metamask wallet to my Phantom wallet through wormhole. The transaction shows as confirmed on Etherscan but the funds never appeared in Phantom. I was told by the moderator that it is likely "stuck" in wormhole and one of the devs can assist with pushing it through.  

Here is the transaction hash on Ethereum:
https://etherscan.io/tx/0xc586d29f974b698297871dbc47215ec4c6395fe08bcc43151bf6457f705a499d

And here is the transaction on Solana:
https://explorer.solana.com/tx/5vEgYuwSkt6BNnN6qHdL6xJxcX5wzWG7t8fpneAE8nYyKhN63SiMt1zpzP8XuUTnBuxKe8RgC1zK2vs7Bxnc9TcV

Please help asap...thanks

**Comment by caulinez** [comment]
not a support from wormhole but from the tx seems like u are out of gas?

Warning! Error encountered during contract execution [Out of gas]

**Comment by leoluk** [comment]
https://explorer.solana.com/tx/27BpPEPG5CavhxjQyiAZxdvSkLjb2WPS83CdYGsWsq31oXDWAXCWLwtfgxHtxVBnHuU1z4XxMw3D2RMHFcbCa1UL
