### ISSUE TITLE
wYfi stuck in the bridge SOL-> ETH

### ISSUE THREAD

**Issue by d0xni** [solana-labs/oyster#303]
Hi , I have assets stuck in the bridge between 
Sol -> ETH 
https://explorer.solana.com/tx/28H6f393w6NHNuNFjE5VLjAozetZHuTvRsNbYaigNsj7SZPRGP5AvJEtHpMdgL9kEe3U1RFqmBPrigwD59fFnGFR
let me know if you need more infomartion other than the TX

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 108b2c36680dd4117ef581f6dccfbb9eebd2ddcf6307ae61b4c47d1f61144436

Signed VAA bytes to submit to the contract:

> 0x01000000010d00226b480d7a7e73d0bcd7bb763a27d64c77abc96cc006236096bf8ae5e7e3fec03b9c765d836e6a433fb343388b0cab9b9926ece4e047914cb620c319bdb51f6b0001e27db4269a71495fe5a65dcb43f550c2cb3b52ee9177cef6cf1138277e497c2d3e8fb3ca9cadd97a62465a1dac259af50d5deb596fd498ea4093ce21acdcf00d0103339b44d0d851f4f9e0efdff2674828f8fd42cc82f8c5667909df970aad71e43900de83266e3ffc987863212ced68dc34a4089486fa26b5d0c82b4e8eee0e5df1010447d22808f8b67589216499a7180516c17f27ab1450673284fe7a071fa71354892e3a160f2bb7e448a248c717ac017c6dd3bb742d249d1832ad2f5335728bb0cb0005c599cf9f7cc25aa0c8be0027ff809dd5a5f0ab5062d6d240292ed20a4a02a3470fc6dd2e97f6b88df888d786c67ba8fbfc176558b5613637e988588c593ac31e01062a19f6eff4a2c81c4677bede3b0e4c2abcedc3f4410e3c415716865bfe567dc0329fa4c46ee61a3f4f96660b449c096ac9b061426e7820c39d14a0118c48e8e80007200f7ff8c89cc831f3d89bd113b88a583f605578cad7cc76f105fa03516d6f2723708cf72761a4a2e474e161ca0aed6f8e1ed444cf1d206e9148ea5f37b4795b000802b1018ef93053d09b65666fddea0c0d9e6810d06dd55ca663c9b5bbd06a3fd67d3addd916e852073b2aece6603f7284dde32a6007ab5eb7986c8fb0ffaae10d0009512194bcfd01ef60f086050adfc69d76ff03506e9f65766d1bdb893e3d5702e73a7e3515d7ba8e61f0548ad6109bcf99cea199f91f653e68f62e902fa738a706010add545bbae85bc3c92a357f22e3a0f69e13841ac71112ff8f72dcbd2e0b8579166f28f1ee49798db56fd11462ee985bce03a81399d699321a61244302539b242d010dd71e92b3802343d728daf76e14fa15c4d030e9fcfeef1a70441018503f7e248a41e792e06cd46304e1f3f0dc412cee2394d60d89deef7569ede3b17571c459840011cd83b07ce65c7f146094e37e52a4093005d26c115ff4cd81f26ae3b7c35303fe3c1bac8509438cc87f581c0663a3c19edbed862ff1cdd638e0b55ded95dd3a0d01126624e9718e921b402760c95d5d9be2572962e171df60c515e9e25012ce875c09015f5b276ab5547e36ee9aaaf5b83ba45aacdff08c56a7f6bfa9bc3943c502f701613d96621000000e830102b585ac60891f21dd4a642395ddf3839103111f0d3b8787fee21cd674146dec44000000000000000000000000c102d21da143cb144bbdc4693553a850cf73ca5f020000000000000000000000000bc529c00c6401aef6d220be8c6ea1667f6ad93e09000000000000000000000000000000000000000000000000000000000ba5eef4
