### ISSUE TITLE
wEth stuck in Sol -> Eth

### ISSUE THREAD

**Issue by Lev-Stambler** [solana-labs/oyster#304]
Hello, I have an asset stuck un the bridge.

Sol -> ETH
https://explorer.solana.com/tx/2fyR7hgkuJ4xWbnaUwU5GtvoLEJj9BRnyZkiKCcRpzvuQoiGu9vVub4mfg7XceBW3DE2uEXgNyfCSNkPKzZcPbsA

let me know if you need more infomartion other than the TX

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 4370a4520ee2a404b64f44595db42d11c5d0cae7e5ea9bf40bf8e1d54138e841

Signed VAA bytes to submit to the contract:

> 0x01000000010d007cf926a3dc1b22f0c3acf51be3b956f2b31dd097f0dd36102c3cea7af2271605653d47f09eaf328cd202204c9fe5300f058803f273ffdab5f5821f82aab8e63e0001ee245d8d7143e1392c7a0525c1578c0561f3b8958663d51547d9fe69491c0ce961817a4024539b71ec873b0232c46854889bb24c8c7ec755a2fb79bf8688e67a0103f495f6c0cf56c738ed47ba30dcc7f0f128563abe187bf63afeaaadc89138af23163c84204eaeb0e4a9d7a9ac5df3a8bec8e82eeb9084e9697216426bb2fc950f010420bb150c7a30e09083aae5c923e10de21a78b5302d5d3bbd429bf57e6c78356d7cd7c306813678bb56391c60d03233739f0b98cd3d515fc3df619c4dd2c0ef0f01056baa40137ad226789b938a69fbf667ace0c7b9e136e626436aac756092ded1020db9071d86fc76286c4990b68478914f79f7830935c6965ebb038be5ae241df70106a9fe6e84fe69b2018d26e778d338afd709f6ab66279540785eebc713fb7906b805ce0bf17b0b738a5c7f889d406e2e8125c6a4326b6f3617c41bc9ba009d2b8d0007cbe8a5455b0b705ead879fc59215d1f28517ce5d4dcde9383a6bc754f23d7e937136beed16eb8d7b7c97fbe8cde8cff008b314a33e651fda6617686f1c50ad4500082b1dbb3b1ed2ffc48ac890c2deb33bd217075acaf8f6071f7f3a9a8a10143cb72d99620546813ceaf54cd604d13774b14d7b763bd80283abc8c82c1af09458ba0009b6c9e63b1e671db7436fe2817b20b85d09691fe5c273a03dfdbffcd995e050c271d8bb6e095523d62bc3bbb4a0cb1cbf875f90a278fedb2a0d3641fa93c669f3010a23883190ce7737a022712594cf7431c1c7c099bdbb53ce639835a219b3113a7d53d6485969376cec9971caf98724f99414b7a728c59fe90e60ae3ba43546f613010de66ca891291b8e3541e3b4779bef8d1963d951203b20ef1e849206126e9e3adf4d4f1fd65fde47202b33953c28adafe65e2cb94267de2c5abd15882acccbeee60011d78090a6c7a2bb40de3f6bf543651489f5f29111a83891515d4447810c5c13ba5019ad098562129de41fab30cda665ad3f66ba1dc9b14c3fdac411e540f3ab6f0112608bb399069ef207e6305db797dea71510bac988867fef55043a263005072f1479f71ace2dd027e93e0ce129e84c7832922e9ace3e677ab70b029c6a2387715c00613df3ff100000ca4201024b59ead4f8ed1c2a40413d87b74e9a617b11e13d4b7c5b5eabdfc954b1f5481e000000000000000000000000bd3dea21c4183b3462cb4af09900818ee5542efc02000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20900000000000000000000000000000000000000000000000000000000acda7d00
