### ISSUE TITLE
wLuna stuck ETH > SOL

### ISSUE THREAD

**Issue by Gitsomelearnsome** [solana-labs/oyster#305]
Hello,

I've tried to bridge wLuna from Ethereum to Solana. 
Tx's went through, UI got stuck on this screen:
![image](https://user-images.githubusercontent.com/40437233/132992556-8ef87279-c252-4dc6-bebe-43a2c1d22ffb.png)

Tx:
https://etherscan.io/tx/0x8254eabcc51b25034428ab587fac42833abc48dda74bf1bc34914f5b1bb0bfb1

wLuna on eth has been deducted, Solana account has not been credited with wLuna.

Fix appreciated. Thanks!!

**Comment by leoluk** [comment]
Looks like the token account is missing: https://explorer.solana.com/address/9LAQxpTY2Zi64c8epjBkDcC8uWgagwLZiUEe8MnSCx16

Please follow yamijuan's advice here to create the missing account: https://github.com/solana-labs/oyster/issues/196#issuecomment-909535731

**Comment by leoluk** [comment]
That worked! Here's the successful Wormhole tx: https://explorer.solana.com/tx/4ejiSy2XUyUVu8QiXQ9GGYjMx2x69ip9uTtwwF5PMs298vbKC47bWrE6Wxx55RDb3Lx22vC3xnz4bugb9fU1wUQt
