### ISSUE TITLE
wEth Stuck in Wormhole

### ISSUE THREAD

**Issue by Uranihoninvest** [solana-labs/oyster#306]
Hello, I recently bridged wEth from Eth-->Sol using the wormhole. I realized that there is literally nothing I can do with wEth on SOL (I cant unwrap it anywhere, I cant trade it.)

Tx is here.

https://explorer.solana.com/tx/5vzcknYxqNMaGADbvDF7AmjnLExrfNFxnEo6bbCkyodpufLm6zHwUR4PSmaji99yqHL7Q77sTVTCLvpYCCTE5SjM

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 64138d2e60547812f8766b7899b1f375b5a219e2a98042cc8b4653d736c437d3

Signed VAA bytes to submit to the contract:

> 0x01000000010d00848b15d190afce6647065bda0cb5f7a290dec03343fe6da4a02b03a6805b81df296e601a0d71a6f89989d321931f4a40bd208605222ba9297e8b2501dae4976e000147c570b6395e9a9fb3679fb3e99c1e335ae5ddf7ca60a10430fe2bddfce86c9c5b7066666f1daec10bc92b3222cc3a7b652d4b7fcf59cdf82e181c825f37d5de0002f75d34184714644f6e9c9163b5dc879bc325a1dbab4e8d31ff89b1ffc2b2faa026295d7f88ee693fa51b5f58897710916fef4c954696d0cfcc1aa4e33aad0f360103af087fd13ed1cd6126db3b1b4e923e691cfdd063650f75ab7c3e0e54eb79070b5e1434fcd1f92fec53c6175b257aa1edb26f95bfff609c734cdaa8367c577e630104e6b81bd8d450b095c3157f2a85b62234818e8d657023a5aec264a55d3d88ee56672c67ced5887b8a6d8b62e593695465aacb7ffec162f0140b5bf9e8cb8cd7d801055d461021c8b491f65b4c47925939c0bb901fbefb5a27b722921ed39ee16fb9d149656c4aef30a278deb910655d2f161af3c1e977e759b0db58303a73e316446e01076c3c83a72ab34d4e7aed606c96a243581696b27824ea9de98cc2b4b9fcae306e6480c4df7a0dc84713089c30b34e4cdfc01d1cf468d6a20363884121a129d5140008e2b47fbf3b2ffbd7930deab5ff833b596a15f1d6ab0cd784e23e709b82d272675ba4a974e0e220118ed7a3612d427b87d98e493268431e58284017c55ef84add000989fa73a98e64537c01279f2ae2a1e6089379b723bffb4df05c579685bb477c9e645eb34295283187b6c3595e4ebc9392ae8de0ee32e46f10a4eb8ce795e2ac9e010a766964cc4c1dada1c4331561f2b237691d0899787f22c079b0bbc1ff5b1ea6f131f0b1468c6268dfaca7b304bfee506c102e3393a7526da8406335a583297113010d78d3214c7b2ed399794a49d5459879d73fee02eb716766710dd2ecbacd7dc3954e8d07b00a01b03c8f33b2e99375088f4d754499e4fc413db99adef0b6c4820801119ad6e172e2fbc9b495808197ec90273b497bc3482291ee7c0d99fe49579f7fcb3c660370dfcffd5f67c80ad9a773d9e29f3cfdc76ebe36c0c5de97c5bce8837c0112a55ec3971b96ff84d97bba7adf6dd098eeb2ef9457d64d57c4438cba3ea9d1bb6f50443b94b1da67f958fa8d3855bb8299ce33278bd85f7c34c6941a4f7743fe00613a2599100000a8a50102e5af50443aa702bca9b93530bb45636909d52d3f1ab5c35c6d0d054123be7efe000000000000000000000000c853215b9b9f2d2cd0741e585e987b5fb80c212e02000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc209000000000000000000000000000000000000000000000000000000012ffbd300
