### ISSUE TITLE
Missing wEth funds from Phantom - Metamask transfer

### ISSUE THREAD

**Issue by subzand** [solana-labs/oyster#308]
Hi. Was transferring wEth from Phantom to Metamask, and didn't have enough Eth to transfer so it failed--any my funds never returned to my Phantom wallet.

https://explorer.solana.com/tx/32Y6XiDAXcKSHWtT4FTSv9DvvXuJfjpYc77RMrWRNqFLvWBiCAC72hGBQMJmTwfyTZDNGzUuxPwknS6jn4nCs1KH

Etherscan:

https://etherscan.io/tx/0xadd117ba7f0fd596e65c8f89f2f58e739611e56ffb9151be43cd993e60786867

Signature:

32Y6XiDAXcKSHWtT4FTSv9DvvXuJfjpYc77RMrWRNqFLvWBiCAC72hGBQMJmTwfyTZDNGzUuxPwknS6jn4nCs1KH

Phantom wallet:

BcakXFVCYiB3zvXSqkepyTnW95F7fy4n3iNQZGG76J4s

**Comment by subzand** [comment]
Would mean the world if you could help -- these are most of my funds and really need them :(

**Comment by leoluk** [comment]
It's not possible to cancel an in-flight Wormhole transaction (due to it involving two different chains - the first chain won't know about the incomplete transfer). You need to retry the Eth transaction from the "recent transactions" list on wormholebridge.com. Make sure both wallets are connected, and select both tokens from the picker.

**Comment by royyyk** [comment]
had the same issue for my wLUNA. now my wLUNA are nowhere to be seen.

**Comment by leoluk** [comment]
@royyyk please create a new issue with a detailed description and tx hashes

**Comment by subzand** [comment]
> ent transactions" list on wormholebridge.com. Make sure both wallets are connected, and select both tokens fro

I've been trying to find my recent transaction (have weth selected from phantom to metamask)

, but when I scroll down under "My Recent Transactions (selected token only)" it just is the loading icon in repeat. Does not show any past transactions.

What else can I do?
<img width="1044" alt="Screen Shot 2021-09-13 at 12 43 32 PM" src="https://user-images.githubusercontent.com/51518444/133146534-2d4f999f-e88b-4970-aa58-d1f2bfcd6c4d.png">
<img width="349" alt="Screen Shot 2021-09-13 at 12 44 04 PM" src="https://user-images.githubusercontent.com/51518444/133146597-b077b921-5276-4c33-bb01-aac29fbff17d.png">

<img width="1044" alt="Screen Shot 2021-09-13 at 12 43 00 PM" src="https://user-images.githubusercontent.com/51518444/133146466-38b325f6-aa5c-4ade-8173-52d03b8ad23b.png">

**Comment by leoluk** [comment]
@subzand new issue please with tx hashes included

**Comment by subzand** [comment]
> @subzand new issue please with tx hashes included

tx hash is included in my post above, why is this marked off topic? still trying to find a resolution to my post.

would mean the world if you could help, these funds mean a lot

**Comment by leoluk** [comment]
Oops, you're right - my mistake, too many issues :)

I think you provided the wrong tx, I guess this is the correct one? https://explorer.solana.com/tx/43ijHmGvehUPkih7MTG8o7K8eucJdxEyYFXf3ewYrKFRacY5jgEJMrqhLy7RmZMzKjQAeyWiDDnkQ6ww1fvWKxzg

The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): a00d552ad1c853c5c2bcb3cbb310e958a294006226f1750c723d6dd498b20646

Signed VAA bytes to submit to the contract:

> 0x01000000010d006db781076a1be29ca30f7ffbbf6dfeb059ac1ee1590491498a62b06e09b8ef3d7e6f761462e82156b980cc6da0145d51e3d324f0fb231e299c3ce03e44fed6dd01012c69c2823ba29ba4b38288882eae1458ede3993ab43183c2a505c01f5863ab943958ee5f4e2e1f757d3990aadc4f648a670b5d83349676607942fec9a9b895130003ebd3c8d9a2bb67d490d421584b81e570715134d0585896873c70235454166aeb534f40e5d605ed325b04b8c9d77333e28286c2878c68a8b50d56e017e73006e2000470345c5835aee0ab1738198dbab3eee493955d0fcbcbc0632d0ed0e27a929fdc720de148dcd9e8eae13bd06cbc797b38a24eb73f7c526f3271debde878a198660005eb0b7cb11be89148603284d1a76a2d8b60cc588d17f41f1b31f0a319be9fe643085dac8df3e9d5fd7e019b064d5c09d929fd7d1b8afdb4a79a0b964eed8f04e500064641c6ba8c651e76135e40180c7a806f2576a565697f3056a329d196c029cc3321b4dd0219da8a67ea11affddb08c2914f516779959642ec62d4ab612d0d801f000795a4cb53e8f1dfda37be3abfe5647c183df3c7cfb5a163b69332f9463662edec75bef2c29e918a5755ff0b3a4432747472364eb83790ecff96bae710782d48a9000858abe8c54edbe684a3790e8f7f73e387e4fd5ef5650edce4ad41df3a2a7fe9bd7bd7e8172d0429cc20777007507ea384fb24293b13b0b3044c4fd3e40568db5501099f42b441f4622cbe713d5ee8aa43579491e4d9f80d9079dc662ea3755ec3f70126abf7d1d2054a2d875520c318dd83874722a9082cdcf98dc6a3fc67363a2939010a95a3f34975f7fb02c2ee77b36642437842d10386a9ce3ff579be4f03f044ad0d7a480d7b21d188a3e1762dc7bb948f83f7025c62f4e72a6433c5df34616ea0ef000db25094f604834229af7bb58d804f96b388b45d8e4f7d92aa71671e9c52a8c9d660322b039078af05793f1880e6418921661cd087f7c12eb241caade38f1ea7e400118f8fd94b8afb78dc53a93c3dbe7281fdd7a1e8e51010131dd0f0994b695d6f70042015b4e1a5726e538954e425c9f4b234c068ecdf6976d4b7f1639cce85867b0012926365017bf67df5a03a7d10c21720347acdae7fb5cbf18cca76c847a596678c3ef8cf4803d5f86dbefc3e8c1232179e1649d043778adfbe64046d79f8b3615800613ae4be1000016113010208b1b280c67ea820097e0a5fea580287b0eaefe1138c15a3cba2dfe1ced8d6a2000000000000000000000000162e8a6213591dd1deffb42b24153cfb98a5529902000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc209000000000000000000000000000000000000000000000000000000001dcd6500

**Comment by subzand** [comment]
Thanks, cleared my cache--and same issue. Where would I find the bytes to submit at etherscan?

Is this website legit? https://www.interstellar.tk/ 
Asks for a $50 gas fee and will supposedly give my wEth back

**Comment by subzand** [comment]
<img width="1355" alt="Screen Shot 2021-09-13 at 2 20 59 PM" src="https://user-images.githubusercontent.com/51518444/133157993-fb871ff4-44e6-41b3-bd98-48b1bb075fda.png">
get this error

**Comment by leoluk** [comment]
Are you connected to Ethereum mainnet in Metamask?

Yes, Interstellar is legit

**Comment by subzand** [comment]
paid the fee after connecting to interstellar, thank you

**Comment by subzand** [comment]
i now have it

**Comment by leoluk** [comment]
🎉
