### ISSUE TITLE
renBTC lost, from Solana to Ethereum

### ISSUE THREAD

**Issue by Alvinhung** [solana-labs/oyster#309]
Hi I tried bridge my 0.558 renBTC from solana to Ethereum network. But failed to swap my token from Wormhole Wrapped Token on Ethereum to renBTC.

The Solana TX is here: 64oKhHR6U2mZnn5oeN3gwjPHsWog2Us9HWf2bHvHubSGMvenVccnDEqHLFwdkk2kYN8f7u9P5Mz5f2NtTfJZWdrt

My Solana address: 4kXYQPwYbzQN1ePZyweiEaUHdbTVwfpJfhm7i3gVQiJ4

My Ethereum address: 0x9325564ADe7683706107685Cf1993678B1163261

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 771b15779c196941e9f7a9b70042f75da8c4d418437eae0c4461e09fb18c43cd

Signed VAA bytes to submit to the contract:

> 0x01000000010d0097d81254490eb5ce5a914300ee90c0afe526ad426801a42a76f42c3d5b525d2a0e7d1c1005398a5efb8c6cb716064a4039f7275f75bde31a5a1c7a37a1c1d13b00011b683c467cc8ea71faf46dbedf9157814e0548429739236101945b33ed1aa38f7496ef1c240e9cfdf6235b5a6e50c6b349899c1dc6bb933ecbe3ac02a562208e0102b4efe6789feedaded8e2f203e5c87da4a9d27e6ddad3c594d3f80f2df75e315e2674c6bbb5d13ce83d902a574cfd2b0f66a226f72d0a5515375e3c9651a9650a00032ea5bd23842ac006c9c13da891bd978b376e35390152ccd9ddfb3d750058301816437ffcd1a59ff781afdd2976e98cff17eee05652e47b68d689a0b7c7d359e60004d8858b6328c53b9616c185e078da880dc09c06588cbf5e1bf31e60dd6d7d3a5d0e66a35bd6e0a137f953c02343b752eaf447eab9295ca27b1b541b50bd0638670005ef57e9c6ab23d04ba64a3f8fc47749f3131454ad2789b21f9141e784f7ea3fed3de3de6d689e8b543247a718a3c9b37b9be4de4bed2fd02e2948c835609fa2a70107c4e9c0e1bea6bb356f91090c21327610f08783b2631a8823d15206b620d1d41474652be5f6200c9f3760f681a24609b3c3869e0b17979ebbe10207a43d3848ef00086a199b619e4303fb4b811a27c3c401af1e066c2672f6e17e055a73d98fef9dd43bebb8a5e375127c975fd98c7f04783785653934a942c39f81218e646eeb5ab601096dcbba316912d256b83fab306ea81b21b0fa758bfe812d0dee064756776a4adf6e2672c420f16966644ad25e47cd9efcaf0307b36fefb1a1f3843dc6946801f9010a163511b8404c73f91a70a983f12e4b1e30707865e4e0c4840cc581119a317a573740570b4d79e16f33cd3da9e448bc54573f38892c8a3527c54ab2b1849b000c000d9cb956410cbafba015b57191da1cddb1e51de6176a156dc3f9659d3dfa3ef75e486cb7d012d4e5405e59f9321c57ca6b3cd4a1f9a72ab920f4a2a7f35b9641eb0111aba28e7ae60fa472083df9c10b39271830e4b5af0f53ae4c103872746f521dae37fdc3df675404451f0d4460fb32faf11965c8b0212b88dc9e959eaefab9dd250112d2eea83bbfc1af86f6d71bc5152e0c1bb03bf15493f16436e86cd94f4c760eef538152333a5c3dc7c25a0fb73ba112c702583028bcfde4a8612380fe6cd1f9d401613e38bb100000071f01022d106996b109daaa9944fd7ba0adafccc1d09ccb8661c8a61f20d642a3f31a3e0000000000000000000000009325564ade7683706107685cf1993678b116326101a6975293cf382d28589c7a079bb5e20e5676f222559bd0473e0ac011fc54e38008000000000000000000000000000000000000000000000000000000000354b7b4

**Comment by Alvinhung** [comment]
sorry @leoluk  may I know how to transfer my asset from Ethereum back to my solana address? 

many thanks

**Comment by leoluk** [comment]
Please follow the instructions above or try https://www.interstellar.tk
