### ISSUE TITLE
Wormhole Bug: BTC (ERC-20) to BTC (SOL) stuck on "Awaiting completion on Solana..."

### ISSUE THREAD

**Issue by misterbaka** [solana-labs/oyster#310]
My transfer has been stuck on "awaiting completion on solana" for a while now.

ETH:
https://etherscan.io/tx/0xc34696e4ab325f309b19e87dd511f325bb4951128f263504c040601476cb64c0

This usually doesnt take that long.

Please help its a large amount sent.

Thank you.

**Comment by leoluk** [comment]
https://explorer.solana.com/tx/4qPRQ2K6yEhSCGRGw2ewXTrAV3PW4dmzbfgQmFffVgV2uGoeCBihnbg6go3pFCyGHawbNKsF6QH7i8nq6jm8LKae

**Comment by misterbaka** [comment]
thank you.  glad it was just a delay.
