### ISSUE TITLE
Looks like this is already resolved thanks to the community <3

### ISSUE THREAD

**Issue by SMGithub11** [solana-labs/oyster#311]
Looks like this is already resolved thanks to the community <3

_Originally posted by @leoluk in https://github.com/solana-labs/oyster/issues/294#issuecomment-918035439_

**Comment by SMGithub11** [comment]
Hi there,

I'm afraid it's not been resolved. I could not use interstellar.tx.

Please help.

Transaction:
https://explorer.solana.com/tx/3jJq5NYpb6eWfyMQnrs7aLaGQzxQWihWK77h9xRxsBKNmhsnsGsmyqd7AyU3S2gqj9jSQ7pUSdeYbmgu973QSkqC

**Comment by SMGithub11** [comment]
To clarify

Would appreciate some help. I transferred WETH through the wormhole bridge from Solana to Ethereum. It was successful on the Solana side but I stupidly rejected the transaction on Eth side as gas fees were super high.

It's now stuck somewhere. Is there anyway to get it back to my Phantom wallet please?

this is my transaction:
https://explorer.solana.com/tx/3jJq5NYpb6eWfyMQnrs7aLaGQzxQWihWK77h9xRxsBKNmhsnsGsmyqd7AyU3S2gqj9jSQ7pUSdeYbmgu973QSkqC

there is no transaction hash on the ether scan as I rejected the transfer.

Thank you for any help you can provide.

**Comment by leoluk** [comment]
Replied in the original thread
