### ISSUE TITLE
Missing wLUNA after failed transaction on MetaMask

### ISSUE THREAD

**Issue by royyyk** [solana-labs/oyster#313]
While signing the transaction, my ETH was enough for the transaction so it failed and afterwards, my wLUNa went missing. I need help for it as the amount is not small

https://explorer.solana.com/tx/39k5F4VKjPXeHtgAvTWuFD8xPihzbQ3MkgeezyAmgQrkuG6mNVMs8DLYRs5wAibgYtaiy98c45iNDAuvSQCbRT76

Signature: 32Y6XiDAXcKSHWtT4FTSv9DvvXuJfjpYc77RMrWRNqFLvWBiCAC72hGBQMJmTwfyTZDNGzUuxPwknS6jn4nCs1KH

Phantom wallet: 7pffPqv3zLE9rdTk2Gri1fq8dCteBT2SQLCjUjUUBziC

**Comment by leoluk** [comment]
did you mean this tx? https://explorer.solana.com/tx/SqoJhYudt3PPyVjJE48yEZC8eTmftjKRtN5VJL1R2pW2T9dzBmoe8Ta2hmro6piwgDwF6k8zs8jKt9XfjucVd2k

The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 940acc208cbb50d73157ca01b1fd97fb3380b943691e8691b8640128ad0b73d2

Signed VAA bytes to submit to the contract:

> 0x01000000010d0004d05de5d94f4d3ac2bf5e78fc0c5102979e072c6debd97837719ca5212954ad7c6db468cdd6fd59091431131e1af4ca60284771483168e7764ce870680acc040101d444549115119dcf4ec63af6f7d49aea6bbee947e58a74e1de5f4ad4af6ca57a727784b3007dc5e33539cb5120ff91c508983335f8f357ffe1d723a60ffb3e040002e17634a4a4b5f4bf6720cb28845290b3cc4db4710cbeca5725d6bec1020aa1456e92b64a45d3cc04fce1782df26d155dc95864e817996d699badf39580108a300003e4a102c100bc27b8b6a42704dfa7192af78f1110f7d25c4b978dac9ece3fec1d053457dcbf274f9340946a2ac20096369933ed8318e6b7de2b0d0df7e58b8054000428defb27e4c1e0751c432777090cea9178ec3c41e947f4fa1032197c2cc885616ecc8fed36e71db4f53524bfc05ccfca3ff8a0a7d2af59436209dea0cc6375030105bcd4e2e0fb17e7431a4ff08515249420534f8987d512518830849fbec5b88f8c1473aef909d2268a9c097f51c3be08b20a005fb4f1776193928d0d6b50646cdf010662320c8bb25af9b63ffe02750975a8c193c8ad38ababecfc96e1c19d491f7db97d521e19ab09ddff8d83aa697e55574d2c969de9d9107cf6bbcd92c2647fe0cf010726085618dfd4d4116aa2ca80194c2bb8e3506485d7f33aa1432721494a8f019f425d4dd077a3035751da8b642f67cf8575e27136c0d7aff590f8ad30166f9ebf00089c44864dcd374948450636fc175b7b25a8fc2f7ffc7a9e8e2aada120cef90391249b5c494cee726de5d0ddc6f9f3d8b35566114f89422044d2244479298132a0000acae134c4b433a6c45e2d179391c84fb19658c55930e3d802e3c61fd020f8d358629687fa02b0af65586dca14118e862f03126a28f3cde6a2de91e798e036e127000dbc04cb91300e12be775c44655bd1f9fa362dfb592bac933b26e72823fc509e9734b617f087dd87598b2d6a5a97f06e860d83fb852d02bb7811ae827062d42c6f0011c57b9b55fb6b0866e181354068c796b8856e05795b38ce9b5ccfba22dbb624080e6b9eec76f954f3decdcaf98c4370eb6a355c1e000ebd2057ffe5ae7448e63c011231f6e39c696f0296645ccb30573e79f030514b1403d3f7a5483529cabbe1647173959d6b2359bc71199f8c1d439279e29b1d1d0893824b93b26eead43fa9913801613f569f100000550a0102fecc1ec2c63a3a836dadef4d151b9751a982093907f0e8da73cc8b01b9d409cc000000000000000000000000a89f22f5506247a74bd67300758c592e5a8e43f602000000000000000000000000d2877702675e6ceb975b4a1dff9fb7baf4c91ea909000000000000000000000000000000000000000000000000000001277bb52422
