### ISSUE TITLE
Wormhole Bridge Assistance - ETH side retrieval

### ISSUE THREAD

**Issue by Jasm72** [solana-labs/oyster#315]
Hello!

I transferred UST from Solana to ETH, but my UST is now stuck on the in-between contract (my MetaMask never popped with a transaction confirmation). Can I please receive the VAA bytes to write to the wormhole contract and retrieve my funds on the ETH side? Thank you!

Transaction: https://explorer.solana.com/tx/5JQdRT9TD5KrjEP2SQTpGQkN17oigm7JcxXvW8WqFJGUsErz6Udmm8tDUq6BxYrmRSAauK27t2PJWVMDk74ijDdt

**Comment by royyyk** [comment]
mine stuck in-between as well but the transaction failed. Do you have any idea what to do with that ?

**Comment by Jasm72** [comment]
> mine stuck in-between as well but the transaction failed. Do you have any idea what to do with that ?

Unfortunately I do not, sorry about that.
