### ISSUE TITLE
Incorrect TOKEN mapping for SPWN(Bitspawn protocol) 

### ISSUE THREAD

**Issue by anthowen** [solana-labs/oyster#316]
**Problem**:

The wormholebridge.com UI is presenting the wrong token pair for SPWN, and that results in moving funds from the OFFICAL SPWN ERC-20 address to the unofficial SPWN SPL address (compared with one in Coinmarkectcap) 

![image](https://user-images.githubusercontent.com/48500079/133146100-248d143b-eb37-40f4-a12f-f82fcde0e9a4.png)

the blurry token image(on Ethereum) is matched to the OFFICIAL address of SPWN ERC-20.
the clear token image (on Solana) is matched to the OFFICIAL address of SPWN on Solana.

Here are transactions:

https://etherscan.io/tx/0x1792f2c5a96ed3718f7109594a67b280571b985b247ba3ee6ecac3dfbd268c41

https://solscan.io/tx/4PPeZ8BDRKwfawjGcAToosdU6QEZYM7BYmxaTA9uFkjR5PbegnUHq1VDCwdYtWdbYqmXdkGdJmjm3d39LwwrQ6qC

I'm not sure if this is just a UI bug or contract bug, but I'd appreciate if you could look into this issue and fix asap. Thanks!

**Comment by leoluk** [comment]
Wormhole is not a swap pool - wrapping ERC20-SPWN gives you SPL-wormSPWN. Wormhole can't mint the "official" SPL-SPWN, this is up to pools like Saber.

**Comment by leoluk** [comment]
(let me know if I misunderstood the issue)

**Comment by anthowen** [comment]
I think you misunderstood. I didn't want to swap the tokens. I just wanted to move the ERC-20 SPWN token to Solana
![CleanShot 2021-09-13 at 16 04 26](https://user-images.githubusercontent.com/48500079/133149085-1c2d8bee-a8ce-40c4-b56d-afd28f4026af.png)

**Comment by anthowen** [comment]
![CleanShot 2021-09-13 at 16 04 51](https://user-images.githubusercontent.com/48500079/133149190-be3db691-501f-44fb-9c62-ee0d426592f1.png)

The bridge UI is populating the different address match. So when I select the ERC20-SPWN on Ethereum, it's pre-selecting the matched SPWN SLP on solana, but that's the incorrect address

**Comment by leoluk** [comment]
The wrapped assets addresses on Solana are derived deterministically from the Eth address, it's a fixed programmatic mapping - ETH-20 SPWN will always end up as wormSPWN on Solana.

**Comment by anthowen** [comment]
That's interesting. So wormSPWN is like a pegged SPWN on Solana? And as long as SPWN native token address is not the same as wormSPWN (according to Coinmarketcap), I need another pool to convert from wormSPWN to SPWN (on Solana)?

**Comment by leoluk** [comment]
Yes, Wormhole is just a bridge - it takes any ERC-20 and gives you a wrapped version of it.

**Comment by anthowen** [comment]
> Yes, Wormhole is just a bridge - it takes any ERC-20 and gives you a wrapped version of it.

Ah, that makes sense now... So probably Saber is like a platform for this kind of pool? Could you recommend any pool to swap wrapped asset to the native asset on Solana?

**Comment by leoluk** [comment]
Saber has been great for this - for example, they offer a pool that swaps wormSRM to native SRM.

**Comment by anthowen** [comment]
> Saber

yeah, that's perfect. Thanks for the explanation, it educated me a lot!
