### ISSUE TITLE
Failed Rebridging through the wormhole with transaction link

### ISSUE THREAD

**Issue by PeteD8** [solana-labs/oyster#322]
hi team,
i bridged over 1000 Dai through the wormhole to find out that there was no liquidity at the other end.
so i tried to bridge it back but it never came through. they left my SPL token Wallet, but did not reach my metamask.
Recent transactions are showing nothing but four moving dots and solscan shows some errors??
Can you help me plz?

SPL Token Wallet main address A5V6fFMwotR5eh1r4p94FhZFZWjn9HwHmnGEcxcbHxmP
Metamask eth address 0x7B93B07351b361DbD2984E08e045e62F5a6F8097

https://solscan.io/tx/3gkHX4SddS98mGRGsmBNQ7KiQjwxAMxitq2fs6DEdb5pRiqQTtHpxhG7qvdMax1P8rbpAECyRG3CN78Bntk4Fb4H
This Transaction sent 1000 Dai through the wormhole

the two following transactions from the dai account 5BRyKFtgJuBBqTkUnJexapahAJXH6TiZrweEpkJobae9 (fees?) failed

Thx in advance

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 5f57bf548aba721e10ffd13d5c48a2632f4d231c442594df2846ff81ccb663cb

Signed VAA bytes to submit to the contract:

> 0x01000000010d00c14f2b4ac8f396f3d55509a80e2a6382a360083c6d85290ecc22e7f5029d706721e42f0cc5a4b28aa1fe530b89598560254f6dafa6ecab85de98b137a5c35c450101e025c26e396a7579ab3ac6d2fe08072376dfccdf94114206445addddb324562a623df7431d6750212da04a590e8c4aa860cc484348bda843e36144af715927350003284d7c69ddf8295d2867988a7e8e73687fd21a5c20ac123b2555626c2a09a5ef1762b3180dcea25344dbb1ce92c9f6eff75ab84cae160f7426bf4a66268b23ec000446a4aeb54dc7ea67030dd2a3fdf984d701187f991602c9a96e8c1c2b56536473500f1f49db480cbcfb8b29c873c99a948bc93bfefbcbfa4f2af617dd37cf8df600055ac6ce20efa0eb0b1509bfeeacd5fc75ccd1fcd64aacff632e4417cb1f48497c52cfff9f82b5dd39c37ebb4045f6e8f587794c5bc1d19f2ae3471e3bbd9e29690006c77e06839ac3643c99260cf9c8084a142d62c9f0dd790341261083b657148eed413c27afabc7e91bf0f56e0ee6d0d40321fd7d273d354e9790d41871820182120107a4e89fa453e65d3035cc24d7453b13bb05ec6379d0cbd6781611b18a71512a856e0f79fd7af82afb9b3cb1679933df328489b6b3a99e2a6960010ef066f1d320010899c5948168fb5ea5c914d1d2ed06e441253c98e1c60d796bc294e1fd8c36ba4525bb14eb1e4b48f070a57e9280b5ba7b636439c2bbefaddd3d93791c9f380d6c000a98fb9960592295f95f44db0fde947a93ea789178332a158125d23846c24f669f33bcfcbbb98ba6403767b9cb2e038641cceb73d04263d8509da13272185c0e5d010bd13c9116af86317156e68e2b42151fefca7bd7e618d8f3b7543af6d4b24cd2d218b06b9737b515a74d82ffd145efcb54e530e03130b12611bd3b173fb57442da010d78f878beb71a6a90cc72783f9e2f53b6cd39626ce8197ba5a90849eb630899c46908fb800407e73a0908483b8737e55e1c8d68eb869ae75825ae4bd7488e01140111881acfeaf80fc140c125d31fb07f567815b32d029a2d35b002291c81382e006a55d49c716ca65b39bbdfbefcf3c92a474498093180498ec7027088425904ba9a011291c71bea035a1cbc9f4c5fae6ad3e62f47b24cd921ce86f57fa1c75c8cb1c21221859c1c2d41578bcdccaeaee9845cafac547d26c2ea45bf5b13075b3dde3660016139fd611000013a0c01023e1aca605dc49e53934b0e41ef3ec672e73385e9fb4705a3958c6a3fda6b051e0000000000000000000000007b93b07351b361dbd2984e08e045e62f5a6f8097020000000000000000000000006b175474e89094c44da98b954eedeac495271d0f09000000000000000000000000000000000000000000000000000000e8d4a51000

**Comment by PeteD8** [comment]
thx a lot i manually submitted the signed VAA and it worked!!
