### ISSUE TITLE
renBTC lost, want to transfer the wormhole wrapped token on ethereum back to the solana blockchain

### ISSUE THREAD

**Issue by Alvinhung** [solana-labs/oyster#323]
As I mentioned in the issue #309, I tried to bridge my 0.558 renBTC from solana to Ethereum network.

The Solana TX is here: 64oKhHR6U2mZnn5oeN3gwjPHsWog2Us9HWf2bHvHubSGMvenVccnDEqHLFwdkk2kYN8f7u9P5Mz5f2NtTfJZWdrt

My Solana address: 4kXYQPwYbzQN1ePZyweiEaUHdbTVwfpJfhm7i3gVQiJ4

My Ethereum address: 0x9325564ADe7683706107685Cf1993678B1163261

But I wanna transfer the wormhole wrapped token on ethereum back to the solana blockchain, please help me to fix it!

many thanks

**Comment by leoluk** [comment]
Duplicate of #309
