### ISSUE TITLE
Transaction stuck between Solana to Ethereum

### ISSUE THREAD

**Issue by zackyap** [solana-labs/oyster#326]
Was transferring from solana to ethereum, the confirmation of txn on metamask for ethereum failed.
I can't seem to continue with the transaction.

There's nothing listed under "My Recent Transactions".

https://explorer.solana.com/tx/55jYrtDQXfWsBjFbkuyTuwDniVZjpZLTdHxp3vFFBmd2fBVACNEpFfnNErnk634wJYnLRfyMnDKMr4fosxE1MkcM

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 7e3dcf7192f7a966d58898b58b76e821c53f2b05fc86ee1f3639346657d3635b

Signed VAA bytes to submit to the contract:

> 0x01000000010d003cc57242f58e8e833e1dba1001ec15c178a7f6980c09398b0e4734f6dd734715435aed92fb43542772f52a9e782d5f493379972bb22cae1fbfafdde9de02f886010149cdd5e3e9bd8130e7fd303dcc1b8f7cc4d98933a49cb3684ee5ecbc1eb2b7c45252797df2217137d027da882246c701ca357c049b8629c230daf66a62d6db810002c3b4a35af54cc147dcbdb74a75dd121766a780df813d224a4feb012b10583f7a15ba7a03001ad88ff679c753eabc57fbc56c56958696b36c6b522d55b2350f0500038eba48751ed13a77d75bb5764edd155f1cbc009eb7c76b624707d643bc83cbae28eaa5b3e9a0640db49376cb1c230b67a8c65c4f50a73c8f19a0b141a2e59e11010573a2a4c45c7902d19f4538ddcf722456766c9a498f96e97141aac2b10051225d00e8384aa77bebd8feff1ac0c4a2c8b0cbe70e4b4fdbe2e1b43760601d77f06800061402ef439ce5176acce305d2e89b3b240b09c40ef3aa73bf6c67c60b9ea0510157b233a4358955cb4ca99a24efdeba6a3bea899063ed78a6295872bdec1f886a00073089f0e3f4873bd019baf1f922ef2164ed2bf9d0c387dedb2d5741653af30a566d9eb67548f409073823adae366777a57c5a60b918d829fe82d30613bda4c03400081793d61684a025a5c2acb08d3d42194f14534332e5e01a62d8473ff0dea923f96f2cc241b7c4d07463b97d6497739c40e3bf473a74c202ff277a84a9225f53f2010a3590ab43978f53d28a99d6b2af5112a79f14e2936b06b437a5fceb37514856a21c24d97b2393586946d2aa941163eacb944b8b7e13313a5107058dc1e71a03b8000d9579e98aab9d3efcbd78c9c5e992ecbc2028d739f46f1cc3070cf35a052da5b77bd716444078e5c31ae4f1e0079d6813be340a3237c173fbbcc92ba097473160011041902d46f136b96f20698f5453211e85bb73516faf6996258c75b60ab92babd15f4d82c2fb95657ae885efc82ab3da251a3c304df7a7494815d0b730f141e63c011126dc7f599c739210785f5de839fab7cb88d04fee0df412bfa3b5dd96140d772f62e5068c366f0b9ed5f7f4833f91b1f8e4a6d555f97377f77ce7cd69d02b4d4f00128d87667d6b9b91cf69b311c799dc7f2fe3b0cdffb13319df28bc5283e2282d0a32c9b4c9963ba572a78e27cd8ecd4e86d7992d03276d969e2fd857bf3fb51b820161415e001000008314010266307f6823c40418eadb0b4729a80df47b5a16ed0dafb4ae3f0f7cc52c75201a000000000000000000000000d7f6548d398a0b6cbce01843027a0734ad18509002000000000000000000000000a47c8bf37f92abed4a126bda807a7b7498661acd0900000000000000000000000000000000000000000000000000000b9c4338e835

**Comment by zackyap** [comment]
Hey @leoluk , thanks for the follow up.

The transaction does not appear on wormholebridge.
It is perpetually loading.
![image](https://user-images.githubusercontent.com/346771/133469853-36c93f39-9eb0-4993-8bd7-8808d68c0dc2.png)


Have tried the method described and received this error.
![image](https://user-images.githubusercontent.com/346771/133469559-c481d2ce-4698-4587-93ff-21fc74f30fb2.png)

**Comment by leoluk** [comment]
Hm, looks like an Etherscan bug :/ Are you connected to Eth mainnet on Metamask?

You can give this third party page a try as well: https://www.interstellar.tk/
