### ISSUE TITLE
wLUNA sent from Sol to Eth hasn't arrived.

### ISSUE THREAD

**Issue by denisealg20** [solana-labs/oyster#328]
Hi there, 

I bridged some wLUNA from my SOLANA address [6F5SZkqdB4CMWsuRrC1QPjqgVJwjoF4dwBnZW8vCC9VH] to an ETH address [0xe385fA81138E777A7cE46E44c4f0aa10ad78e2DD] but it hasn't arrived in my ETH wallet. 

The transaction info can be found here: https://explorer.solana.com/tx/568jApetE6UzBnCYjkhvoTWmcy4RWMg8eE7fYnNmzAEKRDGFFfEWDfenbUyGdgDYZLWD13e9GA42ycpJ4J24b48a

Please can someone help me retrieve the funds. Thanks!

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 82461e742faf01d0dc4ca7a8a15dbcffd0a2fb3fb5f5e2f7c6b7c5d50d1a438e

Signed VAA bytes to submit to the contract:

> 0x01000000010d00d0e90c290a8599ae82ed8a6a8ba55ff80998b86cdbb8355e6b063842eefe094f5d1388b1b5e75a74a5727816731416e4054d8f37daa02037b601dc78ba83c6080001cf6c921a26ba7f5b2009e0e7aefef0b806f5d24c778582b506d12496ee74b8c6604acc960e0541843761ecd0e03d0cb15a122dceda9593b60c0a32f25fd093540102c2805417f002bb6ca4c68a0a5b6906c1e079d8c337fe115ece97118457212062494a035673b084b5538fc56b09e9e9076a1c07281842f12b80ef353dcb48a4090005c441ab8fa20308f74a00095b67aaf70d360ea06b0c01a690a515d366ec31c7b71a2ac621e7ef6a7e721cd65c171998f7b9ae94f9eb8c8f68e7ff1db49ce1c3fe000689c1551d23810f87078a64bf8db98d3a5b90ef42bd4ea2dddd8c0eabed87f63f0ec2f4dca74328fe160fffaf8f8d63fc21f31cc95ae841d1eb811ce9999328cf0107154ca566461924a4fe84d2e0771c11df4ae8d2c1dc3fc543d22d6ef794e8e2a42ca0cf7c81e778d118216facd8c4a1259f8dba84aa34585785d8565ad9f2863f0108841d4424b32a1fb3a2ad4cf4d19e20cb850cc5fc5385cd0e570dd04ddf4d64233e39f1285f442212ae6c96d3a99d4ca12e70d5a66b32aea8894c3d0f8ebe82c00109a0127c463e63ba5b2e6532d0b565d882415b5fe5994dfe9a8d7ebbc29bb6f384630d504c943edc484e33cb0edf8711b07d31656c11705529c75ec90e2d31ab40000c4bc317d28cd6fc7a525b8b08edde52f7a55feee5f00620ef03a179565215bdfd7fcc4ead43708b6672111bc57ad1112bdbd6db91cb1237a75329bf10c9dce54b000d209534c2ab7a556ea4f946ec8f87a1efcea84adaf858fd3b5160b108117471ec1c67205fd9be52f3d2e378394911cee44bb4c98f8bec7dd4adcd4021027faa7d00106fe19ad64b32fef4a0847156e9ba0ec914e078a421e9beb85132882b7eecd2651e6285f01e4a82757a96ce31779960e740a973cd0d52422d1cf657efbc9fa86801114669e70a74239575f374b71a308c3be50dc471689f916cae916e6c8d9dbe423d6738b57cd80353c6fc7eb4a36ea995a87a44c530f0e61d274b9774e14bddbaac0012402b2a9b1fa8f20f4b23307adba4f8fe2c0c4705e4fbe8bc0bd28c42928306355df468e2dee6c59a72aa1b7b1cc423411aa07354979f82aa416bdbb6b4066e70016142051c100001287f0102d8c5d4bdc50610f5707339bb0c99ccac043884cf19c94754c0d2cb7b50054e37000000000000000000000000e385fa81138e777a7ce46e44c4f0aa10ad78e2dd02000000000000000000000000d2877702675e6ceb975b4a1dff9fb7baf4c91ea909000000000000000000000000000000000000000000000000000000e51f8647eb

**Comment by tnathan94** [comment]
Hi @leoluk -- I am trying this process now for my Txn: https://explorer.solana.com/tx/2TJLamymrvNtZ9NaVkXvS1kotKnE4xUpCTusgqsUSzuZTGwHgcp5tEw6LngmqH756iUJKh7z6CNAYShpb8AwVRVx

It seems like it will cost ~3 ETH. Is that correct?
