### ISSUE TITLE
Sent Weth from Phantom to Metamask using Wormhole Bridge. 

### ISSUE THREAD

**Issue by Evenir1** [solana-labs/oyster#329]
I cant find the fund anywhere although the transaction was successful. The Metamask activity is saying "Lock Asset". Any suggestions on how I can retrieve my funds.

![Screen Shot 2021-09-15 at 7 45 48 PM](https://user-images.githubusercontent.com/25176157/133489263-fd64a9ad-b0fc-4cb2-88ef-fb56aa472e16.png)

![Screen Shot 2021-09-15 at 8 31 34 PM](https://user-images.githubusercontent.com/25176157/133489522-23baed10-5c1c-4fe1-9d24-30108dd9c84f.png)

**Comment by leoluk** [comment]
Please provide the tx hash as text so I can copy-paste it :)

**Comment by Evenir1** [comment]
0xbb931b089cbb1ce17b4d166260caf41c832e4ec897c2b2cd6494782c32930150

**Comment by leoluk** [comment]
It looks like you received the funds on Solana: https://explorer.solana.com/tx/36eX8fmZFotwgdKtpbkLKrhfJhQxp6QSqa3YFhgY7cK43FvaLc2X7fcvnZQBYakHgQQMZLC6Ts82K6WdEwPn2jQq

... and then sent them back to Eth: https://explorer.solana.com/tx/33M6crAXkT1CYVfdkY9VqQWX5kzx5Cy1nXvzEafjVyAHhAGaGnxswcVbwptuy1bKxAZ13cwZc5EMt3KyBiijsqTT

**Comment by Evenir1** [comment]
Correct, but I have received it in my Metamask. Its saying Locked Asset. 
![Screen Shot 2021-09-15 at 9 18 41 PM](https://user-images.githubusercontent.com/25176157/133495888-ec2215c5-ed89-4161-bf9f-e3a3aa47f88d.png)
![Screen Shot 2021-09-15 at 9 18 20 PM](https://user-images.githubusercontent.com/25176157/133495914-36e19b1f-daa5-4121-9aad-abcb950c500b.png)

**Comment by Evenir1** [comment]
Sorry, I havent received it in my Metamask wallet

**Comment by leoluk** [comment]
Try using https://www.interstellar.tk to retry the tx `33M6crAXkT1CYVfdkY9VqQWX5kzx5Cy1nXvzEafjVyAHhAGaGnxswcVbwptuy1bKxAZ13cwZc5EMt3KyBiijsqTT`

**Comment by Evenir1** [comment]
What is this number - 33M6crAXkT1CYVfdkY9VqQWX5kzx5Cy1nXvzEafjVyAHhAGaGnxswcVbwptuy1bKxAZ13cwZc5EMt3KyBiijsqTT

**Comment by Evenir1** [comment]
Sorted Thank you so much. Only cost me $93 gas fees. Geezz thats Ridiculous. But Thank you all the same.
