### ISSUE TITLE
wluna solana to metamask--not enough gas so I rejected.. now I can't find it..please help

### ISSUE THREAD

**Issue by patricknmt** [solana-labs/oyster#330]
Can anyone help.. I attempted to move wLuna through Wormhole to Metamask.  When the transaction prompted I didn't have enough ETH to cover the gas and so I rejected.  Now my Luna seem to be lost in space ..please help

it was transaction 24oxQKizr1xUnSJjVeELpaDdQhSp1gtusuqYL4ZcwMbcM3jy79QtGgDeqRPNcJZp1H66USJAxX4NQ7PyrDLUdouQ

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading https://v1.wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If v1.wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

Note that Wormhole v2 was recently launched on wormholebridge.com, which fixes the bug you encountered! You will still have to use v1 to complete your in-progress transfer.

You can also try using the third-party https://www.interstellar.tk site to retry your VAA submission.

---

Digest (for reference only): ebd2e1649ab4b92b29cfc7b31be69e652422a83fc6fc24b475edb71b14e57211

Signed VAA bytes to submit to the contract:

> 0x01000000010d00330591bec5c52ec2a5b86ae1636a9a592b1757d01807b881c79a6d3c329dce84039234c752b3282e03a2de83a0e69697117132e5da02d25d085d5d2ed707fbac00015ec0a325d4c33bd7648126201577965d183225a06aa3bb1d237e89bd5e2d02fc6950224a564d0e4f79e8b38bbca74b34e34d160cb40793cd854ce704313ef36601037448a3f56cf38840196d9abb9457406b19de3d059785780c29d2e6118f06acd0720775a1694e393cc71bcb1420a9fe98957501c7913577e4917d129efe464207010437d66152f09a331fc09869a7dd5ae227e3d7006e8ee5af21e415b83cffbdf8ed24301a790f32f148661fe3934592d43cf9090c4e9ab12f9e0ba64617d1d86400010522c8d80a9e94299f881195f397179450d18988bf83aa1a582f262602b45933cb21c29f537b0e12c6448ac8d3e848b1404eb7eea222e1dd30f655449bb07013740006ac9d1f79848e6dbb04cefad90d0356e03127eccd896700fb7b824c728e854a60117709b6b4f30770a868fea433f98d2fd01dc8b60646d0cac0e8acb74f327f3a01078cd5799c00c5e749d311b8f8162000f7911272cae01824d69a1a1f9f57b72e186c9fe8321c5cdc85d683996db2bdb81e886f53517baccb4a90b9af35d01f6ceb0009302ccbf804caa0a1914972f1a55c5f1e6dbc791e2a1f646aa65d5f98531830d953ce390a81407ea7a553e1abf9c731a84d6454984a02553aab6ae5e8ffa97cee000a33e60ff7522402f60bad7467f6490f1319957b20fff020cd68124674ae9022881f6b6a5a9ac6fe5ec515f0acc2850178e385293ab9493e792087413f3c698d25010d7b276fb201526a19897804eb64772cf0f2a2534e04215d6aafb4dd8cd83bff1679cc8853c2e8c559071164e89abdfb7fe952869156d81c03e77b208d92f2981b01105d1f1d8e432ad8e64e01f4c276d41692c47705ff0c86ae6a2e452777ea27213a438f3006d52a57e8cb3e94c24120dc4c8e11ed79729fe8338eac3239c290626d0011c5cc1aee34c8da8e9a3445a04e17bab6d6195c69ceeba75158eb93e07c83296a618ed579e6142711aafbaffa9c443ffd8c6b2e88f929fdecc08b7ef6e6daa1120112d573614b2ef48f2482b0afd9159dc40a51d4587f3475a2910fd7f90a346621dd038c501c64775e4efe7f86054952352c37d6bd8816402b5b0ee6543cd2cda077006141b949100000e0790102db237b9a8f5f47b1dcb9a85842b10ca00f194604dc1922c5b1909e378ab435f8000000000000000000000000e95d57aebf657dae7689410bd7aaadc32109534b02000000000000000000000000d2877702675e6ceb975b4a1dff9fb7baf4c91ea90900000000000000000000000000000000000000000000000000000002540be400
