### ISSUE TITLE
SRM stuck in wormhole bridge

### ISSUE THREAD

**Issue by dreamsia** [solana-labs/oyster#332]
Hi there!
I used the bridge to send SRM(Solana to Ethereum)
![image](https://user-images.githubusercontent.com/90447097/133568912-151ba458-3125-4412-bd41-d64da732bf13.png)
tx : 5NJhpXVQw2cpt5Xur8x96mromeACbyszZcGTzm3naUSfvd3CxLDrMDAndfC4pw5VyKHWiLbyAFiYUqWnVqt9BsEU

I guess approving to claim at the metamask is last stage.
But there's no pop-up. So I cannot approve
After I reconnected the wormhole bridge page again. I couldn't see approving pop-up and tx history.
![image](https://user-images.githubusercontent.com/90447097/133570728-b353251d-8774-43e8-b36c-9033d343e744.png)

Please help.

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading https://v1.wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If v1.wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

Note that Wormhole v2 was recently launched on wormholebridge.com, which fixes the bug you encountered! You will still have to use v1 to complete your in-progress transfer.

You can also try using the third-party https://www.interstellar.tk site to retry your VAA submission.

---

Digest (for reference only): 1c85098fadd85da94c0b3a887b64e36253059cc5534ad8f4beaf5ec7adc8b48a

Signed VAA bytes to submit to the contract:

> 0x01000000010d003649c079b4bb6c58480865b5bb796980a01463b0f61838652c81dfdea504e45b463b63b6c778718aefc5ddf7549a0c9422a533419c64e1f86631dae5b8af26b901021eba8d770aad55da62597dd47f1fbb7e41026424fc46e4a217ca8f3d0bdc29254f585afff9321bfc8777f626fdc1011e315c7e63db29f525da71b2a1819705a50104fcfab6f10bafd3dc261e5108afd3cc38ee4a019dc2c99f0a3f374303806c7bb166344fd9fcd441f894118b2232eb785ac3054c9ddaf30058e461032b4e6a641f01058a89bd78d325337c52bb4a9e8df475dec77f7c7ec2cf0b20c787d62d31d119ed2744f5878003ff52d65fda258d1af1dc3b5680c383ffbdbc94c0c43d8aaf75850106f18abed26112e5a7932e17c78a473c62f589c8666402d8577dafa8bcfc7c712018c387f492942bed27d49ef5b6daa4454dd27493704b2257d94e965fad72fdda0107a80dbe86f9f6b6551881f7ed18a8fe1dc5130cb89e83de20616c94b5c252f65b066f8ce93d98a4ce811164874ab4ed904c0fe7830901b014824b60a8112c126a01087f8c153efef6ca22e3357622237fc04e593438ac7dba5f2d8c5793d164cbb74e3400c4492cc41ac1a1c2e4a3f2f0c49728e4a26a3462a9b293fbd19c954d42f4010a6f9ac08b2180cfe344b527fb586d444a584afe4cbe8e05702af5825fd18a7b6e4627061726cdbd202d5c76ee3e2b0b8f611269afc968086d5d6fc8a69b4a2dcf000b583c5449b5aa13b148f3dc4b658f8a07f5398fbcfda2fdf24d3840f6a6d31c096b2182fb55a330876200f57507406cfc132df4dc00793ba5db234487b9a347f2000cd90759277e99848df1f3344a3ed92f3bc5488613a1c7c543a1b01e293595d4a73b3b4670e3c40481f205a9db3d694d189e384be9085c1f08137d40ced3ee7a0a000d2701d017e6445d8f20a179d320757b1389facd251c3657903d34d1e4ab89431937ca24d8c63bd4e158482989bb5225d65c8b364ad457b9f2ed0bdcb7607e99110010249778456d4dfa8901eb5555732a3b938f5c897564b323fffa75f916fbc6c38c402357aacc2cd05ace58fda8418229a5b31784003141c54a6b9d3671ead2db610012724bdc3dcfbe06befab0530d8d78c32511467a56e9708b89e91a9a223cce9bc2312a547ec1fb8f89f52a099c0211e91e8482308d0e7a822f756dc111f5380e74016142d401100000d6320102b0cb76895b4451ddf5bb121195bc638edcc108e627843ed3be7cd6d8188900c9000000000000000000000000fe10287fafdaf98df32e7ec137067ef03b3be86202000000000000000000000000476c5e26a75bd202a9683ffd34359c0cc15be0ff06000000000000000000000000000000000000000000000000000000009c7a4198

**Comment by dreamsia** [comment]
Hello!
I tried the v1.wormholebridege but solana-side SRM token is gone after
upgrading. Only Eth-side SRM token is accessible.
So, I want to try interstellar because it is more user-friendly than
manually submitting methods.
[image: image.png]
Which TX at the below should I put in the box? Sorry to bother you. I'm not
into technical things. Take care.

5NJhpXVQw2cpt5Xur8x96mromeACbyszZcGTzm3naUSfvd3CxLDrMDAndfC4pw5VyKHWiLbyAFiYUqWnVqt9BsEU

1c85098fadd85da94c0b3a887b64e36253059cc5534ad8f4beaf5ec7adc8b48a

0x01000000010d003649c079b4bb6c58480865b5bb796980a01463b0f61838652c81dfdea504e45b463b63b6c778718aefc5ddf7549a0c9422a533419c64e1f86631dae5b8af26b901021eba8d770aad55da62597dd47f1fbb7e41026424fc46e4a217ca8f3d0bdc29254f585afff9321bfc8777f626fdc1011e315c7e63db29f525da71b2a1819705a50104fcfab6f10bafd3dc261e5108afd3cc38ee4a019dc2c99f0a3f374303806c7bb166344fd9fcd441f894118b2232eb785ac3054c9ddaf30058e461032b4e6a641f01058a89bd78d325337c52bb4a9e8df475dec77f7c7ec2cf0b20c787d62d31d119ed2744f5878003ff52d65fda258d1af1dc3b5680c383ffbdbc94c0c43d8aaf75850106f18abed26112e5a7932e17c78a473c62f589c8666402d8577dafa8bcfc7c712018c387f492942bed27d49ef5b6daa4454dd27493704b2257d94e965fad72fdda0107a80dbe86f9f6b6551881f7ed18a8fe1dc5130cb89e83de20616c94b5c252f65b066f8ce93d98a4ce811164874ab4ed904c0fe7830901b014824b60a8112c126a01087f8c153efef6ca22e3357622237fc04e593438ac7dba5f2d8c5793d164cbb74e3400c4492cc41ac1a1c2e4a3f2f0c49728e4a26a3462a9b293fbd19c954d42f4010a6f9ac08b2180cfe344b527fb586d444a584afe4cbe8e05702af5825fd18a7b6e4627061726cdbd202d5c76ee3e2b0b8f611269afc968086d5d6fc8a69b4a2dcf000b583c5449b5aa13b148f3dc4b658f8a07f5398fbcfda2fdf24d3840f6a6d31c096b2182fb55a330876200f57507406cfc132df4dc00793ba5db234487b9a347f2000cd90759277e99848df1f3344a3ed92f3bc5488613a1c7c543a1b01e293595d4a73b3b4670e3c40481f205a9db3d694d189e384be9085c1f08137d40ced3ee7a0a000d2701d017e6445d8f20a179d320757b1389facd251c3657903d34d1e4ab89431937ca24d8c63bd4e158482989bb5225d65c8b364ad457b9f2ed0bdcb7607e99110010249778456d4dfa8901eb5555732a3b938f5c897564b323fffa75f916fbc6c38c402357aacc2cd05ace58fda8418229a5b31784003141c54a6b9d3671ead2db610012724bdc3dcfbe06befab0530d8d78c32511467a56e9708b89e91a9a223cce9bc2312a547ec1fb8f89f52a099c0211e91e8482308d0e7a822f756dc111f5380e74016142d401100000d6320102b0cb76895b4451ddf5bb121195bc638edcc108e627843ed3be7cd6d8188900c9000000000000000000000000fe10287fafdaf98df32e7ec137067ef03b3be86202000000000000000000000000476c5e26a75bd202a9683ffd34359c0cc15be0ff06000000000000000000000000000000000000000000000000000000009c7a4198


2021년 9월 18일 (토) 오후 7:08, Leopold Schabel ***@***.***>님이 작성:
