### ISSUE TITLE
wETH (ethereum) to wWETH (solana) 

### ISSUE THREAD

**Issue by 3thamphetamine** [solana-labs/oyster#335]
wETH left metamask wallet 15 confirmations. Spinning wheel still spinning for confirmation on solana. Funds never made it to phantom. explorer.solana.com says "success" and FINALIZED.

Signature(s): 

qXpxFcrogyqsYF79fXnmpoC9nw7S4qiKdvmTrMt6jmZ2ndMxGriQuvv4qK7WHJgprcxzZPid21wE5yX1njRUQoi

S3ubMXEvpHj31UJHckBfNrTNE8fdFpZgR7wnnRMZmpa96oFFLozXRLwy7amDGAAV1hfRpE9xpH5JXfgkuPqEH7j

Please let me know if there is any more info I can provide.

It's .05 wETH so not the end of the world but would like it back if I can.
xoxo

**Comment by leoluk** [comment]
https://explorer.solana.com/tx/3KhgsYTjPru3b823bzjZd6BP1vLBZP2yKcbxFNhZoSwu32z9SYkcbp5xswsEVPkkaaG4Y68Z5Xm2qLAY2Mg1SfSx
