### ISSUE TITLE
wETH from SOL to ETH mainnet through Wormhole stuck in a black hole :(

### ISSUE THREAD

**Issue by makorihi** [solana-labs/oyster#336]
Hi! New to here, but may have made a big mistake already...

I just made a transfer of wETH from SOL to ETH mainnet through Wormhole, but the txn failed because of insufficient gas (spiked crazy during that minute for some reason). So Wormhole got stuck and now my wETH is stuck in limbo somewhere.

I've put more ETH into my wallet, so now do I manually complete the contract? Wormhole isn't picking it up from where it left off unfortunately... But shouldn't there be some way to manually complete it?

txn: https://solscan.io/tx/5jRdzv2cB418kosVUFkPziYuFKEXeJvR5FU2JpTbcC1e5ecbB1ruR2n8V9wWpDdPhivbYxyTy4Mjq3nU9QzP6uAa

**Comment by leoluk** [comment]
All good, your funds are safe!

You probably meant this tx instead: https://explorer.solana.com/tx/5AouSugsDBEhweYzYoErSt2PnC7susAx1cvwrFjNE3pGEyV8WJwqzN3EXMnou1Z3YH28LmE4uDH8VXZuBWiRUM83

The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading https://v1.wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If v1.wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

Note that Wormhole v2 was recently launched on wormholebridge.com, which fixes the bug you encountered! You will still have to use v1 to complete your in-progress transfer.

You can also try using the third-party https://www.interstellar.tk site to retry your VAA submission.

---

Digest (for reference only): c81e3379e342b9d1064b18d599afff938167bf97d9f764851a935bff2d4201c4

Signed VAA bytes to submit to the contract:

> 0x01000000010d00f4647c6c4886c2ab72c54f423cf1587e585176689966a1026bdaf6a75884cbb76fe39cdf108810cc1492f3c9a7d5c2d76e8ff1e6c74cdd22369fb05b187cfe1800012ca3d6369a36412132a63c8b6692abe028ceb22ef4a329548713f00354ef863162c2707b033f834f4c489c12154d8d79dd4dc3e2ea1d8ef8a29bf942b344f18c00024327ca9e4260f402d00cce66fe9a3a38dcf54f7fa645b00592a3aa3630611a45572e072a696f69d6e7037c0ef681260bd381d0d5750160e380dabb6a5715761b0104e1e56966e0bd16d12a66037f1613fc6f5ed720acde23ccb96ce002ec7d63cbcd28a68df0bca47d58229007470d314c3daca7bcec1f52c9615d823952bede4db20105540a4f0bae9c5b5e7a7669d483c640a1b89c065f8d955f8bfa5eb4468498a79b0ec717ed52fd4edb33040ab6789dd7905c985a604622175cfdc1c02b44ae5bde01061ea0f0c322ca5d7d3bb6e19a51e8dc1f641127232cf1da70d6692acf3840b77a4ac891bdc87af62918f8e9e251f0b594602306a673a599633284ece7155b1ae1000785df81ea370a1582bbf005a1b405f0aa6dd06897d86d7369741791b6931fd6ab252c0a6016c0a2fe32bd8c94466c669290f0486f969f398ffd4b3783a7cac97c00081ff1f2bf6babe776c269f7c626f16b13984b0aad00fac3f4edf6ac44684d6bd744fef0154a63dd215e460e4c88b706a45ca27812063c408621d161390c384c92010ada1eceac9ae344f78efb08c2bba97e6b59bf07ae06e7a2188063f1771b8457e3071bc26ffd7ad9dd8c6523318043a841a9bb6682696c931cde3c2bf330f9bca0000ceedc7e1157e5fcba1ba7b1fbdf11e99a9a40f6badc23500dfe14b42ec49ff5d06f2fdd01339961feab92c7d444ccb9e6c76b239e1727925e6f75401808f793dd000d9e07a98b356eaed3666ebfaa9f3a4b25bff68e0f53861accda6e1c6aa508472e40b59e22b63ae203bb77d8a7c7f6937ecc90285a1cdd379eb72791dbee40a8f7011166dae7579e444fd243a76dd8b0792884ff57bc2d3361d2c042af08143098296e73d49db44bd1e55a01c2572dba63f473895a276d50fccc0c95118c1a20c20783011213be9903e04e41d574e2891324179f8dfebb52411d9741a2d2425c8e2f05336e530bca64c501a0effbd146969ae7b8bb098ece28cfcfcf4526bf3cdd81ce27db016143ef96100000e4c80102c2b58596bdeb0fe203b50ed4e98773786612e3e44a03213f066f0025ac697baa0000000000000000000000007152d4fa21c619497cf304755ffd4b40d7ab059d02000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20900000000000000000000000000000000000000000000000000000000055d4a80
