### ISSUE TITLE
wETH stuck in Wormhole going from SOL --> ETH

### ISSUE THREAD

**Issue by lilwhalo** [solana-labs/oyster#338]
I initiated a transfer of 1wETH from Solana back to mainnet and after confirming the Phantom wallet tx, I accidentally misclicked and hit 'reject' on the Metamask tx. Can anybody help me get the funds out of the bridge?

https://explorer.solana.com/tx/UkUmeFe7gZfKiPLM3p8PCK2Nrk4rz8kzGrbRwcjxkygpvyzCES9c7AAod4Dz2R26rhY38KojxLojNXjr9c7mVeF

**Comment by Bigbet420** [comment]
I’m having the same issue, did you get it resolved? Let me know if you come up with a solution !

**Comment by lilwhalo** [comment]
Haven't had it resolved yet, really hoping somebody will come and help me with this

**Comment by leoluk** [comment]
@Bigbet420 create a new issue please and include tx hashes so we can help you :)

**Comment by leoluk** [comment]
@lilwhalo 

The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading https://v1.wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If v1.wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

Note that Wormhole v2 was recently launched on wormholebridge.com, which fixes the bug you encountered! You will still have to use v1 to complete your in-progress transfer.

You can also try using the third-party https://www.interstellar.tk site to retry your VAA submission.

---

Digest (for reference only): 3ff6ca2cc21ca2d7950b7ae817e82176d487b819ffa6dba6d8ee4e5fc0297ab3

Signed VAA bytes to submit to the contract:

> 0x01000000010d00984da6d9205f670918d3a2a792a194a1f3b94d62effff9ededc9b7a8ec93996a5032910ea92428b355d38490df0fbbdcb318fb70463766a1ff153358f29faf350102da07867541e22279d22003aee97e64f334b891bf36c22cd590de4b682973c2024e4184ef81d40131768282acc8d4645c2f3b2cf202d13be10baf3a2f4c7257f200032c9b843685f523b9e8811fd2be6be87b3c31befb2827d0fb7c08547171fae4c409e0b6c5b34da6783c860aad2fc881be2721ed3f0713b8efc7ac7c17efa0e4cc01044f1f6708a728513b4c3f3eee0df2486268370ef795f0e509db617730ede1cfd905bc51c7fbc889bf472e2eff21374daceb098986a14734b714528aa463a68ede0005c9d4233cdd42a3a47d39520c9207b463e9ef7e7b64125d39848eca33854f030a258b16b222891a949d16da8d2baa0c7d5e486430bdc5a2e1307521075dc9f02601063edab6a9d007d7aecce6227629dc654d6bddd9f146d6df0db52d8dd46a65d27e30f66c24feeb59049b4c14bc9ff969a9af24cf0b7c32a9c0cc60f7931fd200270007b8ddb9c4ad04ce4e53231f12a72d6cb7c4e288fbbcf847023146a27623b4b5833957a83f90b85d42d03ed91e351ba9b24bd5dbd08d220d1ddc602f06bbf60d4800081bb8e27afdb1992c037adff061ec7b6e8c36937848336f00d3bb130f9cc98ebf66ad406d6b6de202fe9ee63471903ebf35a5199bd1abc72112dfddc71b60e57c010acc8c226102bca4fcfc4f368bf04e4c209ee2929a5298ac4486064a1daec2dd8456b95862b5f994f3cd5eb687be453abec617c82bb3277521315139e234417099010ce5d5193a82a4bc12bb980df866f0af5a7b8803ff977735a23b6ba0afb8349d6f59264b9a0c6208b10f9646b2fe1ae33c9614c0cb16e1785cf1286bfda58d2b6c000dca79f9bbbe311c039006b037c2226009f77a02088c09c26861a05903a508d79e35f4b61e414b7a190c030aab373762a05f8511c6b26520d0e8788cb498ecdb5300105b627f6e3de8cc2148dd7256550d40907510c9cbb8723ba1a52d7454757916a9218d7568446a412277a355a8d9534e2d22290ef1c36e0ebe326c80157ede3bde0012a8f3bf66db5dff39993045b23dfa23ad1c097967cbc727666022e6fd7f80fd0a042ac4122218ccd854b4463f87b7a30673d02420ca38dc22263b57a9452c881b01614437f2100001080e0102a66ca500fb0ef13494cc8f1e5222a9ba4c912e53e166199458f862e2459e1d080000000000000000000000004cc701125bade721695ab909ef4059b8a12be5de02000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc209000000000000000000000000000000000000000000000000000000003b9aca00
