### ISSUE TITLE
Coin stuck in limbo, rejected eth transaction

### ISSUE THREAD

**Issue by Bigbet420** [solana-labs/oyster#339]
I had approved Solana transaction to swap from sol to eth, when the coin was transferring I did not have enough eth for gas fees so I rejected it until I can do it later. Now I don’t see the coin in any of my wallets. Seems to be stuck in limbo, what do I do ?

**Comment by leoluk** [comment]
Either provide the tx here so we can fetch the VAA for you, or use https://www.interstellar.tk to recover the transfer.

**Comment by Bigbet420** [comment]
@leoluk Yeah I just used interstellar and it did not transfer my funds back and just drained my entire wallet of all of my ETH, wtf is going on ?!
