### ISSUE TITLE
550 Million Tokens stuck in transit.

### ISSUE THREAD

**Issue by techleadhd** [solana-labs/oyster#341]
Hi, I need some assistance with the wormhole bridge. 
Recently I bridged 550 Million tokens, which got stuck in transit.  
Can you please help return these to the original account?

https://solscan.io/tx/4nvcL9eKGkwfLBCb8P5rzS4iVfqQNYnpmToioRh45zHv6cDtLrJjVu5bEUpZCXeSc7oBwBtJXgV9xC8UHq5E8hy

Thank you.

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading https://v1.wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If v1.wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

Note that Wormhole v2 was recently launched on wormholebridge.com, which fixes the bug you encountered! You will still have to use v1 to complete your in-progress transfer.

You can also try using the third-party https://www.interstellar.tk site to retry your VAA submission.

---

Digest (for reference only): f9fc725978fac4d96678e2bdf1c588dae2b4e14ba45fafffe42a20b44d43c476

Signed VAA bytes to submit to the contract:

> 0x01000000010d00e45306fb70ca6dd03f56e6abbe47416c8e4c2bdbe1428f925a5b0186c38af5df528ce28e73440de8a3dcf4c6556056e2ad8e55a918b898720f14fe55bfaa5a4300028a1697b22129368ecc5d214434ab2bea60c675bff92656301dea7473da74ff012c23e0a74a21cbf152a7a256cb39fdadca745a9bd0c8cc0556fc577779c0994200034956f4d7ff4f554d0bff2ca7a34e9a625d9922d4163214ee3d4a3ad4a60b7bf80854c18756b9cd6dee437f4aeeca74d28afa0910c80cb59369a834dc784ab4900005997a3b4cd716002cd1fc4fa4ca81a60e9793cc77ec1f2d207669902a03caf98e48a8c49954f9c93da13db415b65b8f1512e14352016ccc37da36d19020209c4c0106cf13d3c0351f053b419993aec3d62721d033f7fcef229ae39db9b5c674926902414a3331507c0db2d24a2221117969358f6b73e3a50532c99f238bccdfb54efe0107f1858f926e7559f72393a5c2cacdc50ab99281b8ca8a569c18c78e1ba708a270647e183befdfbe4f04fd1cc27098831f8f476d15369d7dc4451d33621cd9f0d00008aef77b834fd67f7685d35f1ade16061f76db823a42f73e3305315073dfd2c352168126e6e11c9d78699e6400fac7c7d7d2e04f8d6e5df1c216da2443ceb36c620109bde2bc943069125ba7c046731003c7f26ba0bf8b5dee7e41357b136a556919c90f249bd29c8d64eef4810d96ddc1817538cf766fc7f6d1c1da288754dfd32173000ac9c640498564fd0bccc04a38d45d79447597da1c93eb8c66c36d5377f41c3e48211730be59249b80e3e3dedd8459b584316b96e09aa86e1c6ab7aa233bfb8fbf000c11a3ff1d3bcef02999dede6da242aeb74aaef0476e25d0c4e19cf0f0c730a94873257abfd9c85cb8e7e4ffaeb114baeb57d3363b3749e39c58b1cdf0a4e26ae2010d7f6c8c72cad018d84b7d5975a30d888f7cdc93acefa3265261f94365a0c628ec5666d935c07bdd3c1f879a987491be03e54dc39b10986bb31ac18f60656fcba40110599a51957ed457a1d011a0c754993ae3219b4ec7193e035dde00874022a92d806ca2ffab1349663fd95ba645b819a6f5e4095352796a61869ef3cc7213dfb5ca001102f4f7c7ba8ee729f62200e7daf1763b3eb982f7727d2c3a2eeabf34c8bbfc3447d88e52442e11ab8a6b8fa70ef3f2fbb1e10c196fdc13a590dabb264e000df901614394891000015c73010262eace491f78da96e7050d88f76b701b015db3339ef388ad8cacf0e3be85355d000000000000000000000000cab2a9983dde8ec9b1d0bf44c8ef297763ea9440020000000000000000000000006b4c7a5e3f0b99fcd83e9c089bddd6c7fce5c6110900000000000000000000000000000000000000000000000000000080164d3708
