### ISSUE TITLE
Wormhole bridge problem

### ISSUE THREAD

**Issue by Sandybeach25** [solana-labs/oyster#342]
Hi there,
Can you please help me with the following problem:
I (tried to) transfer USDT from the Solana chain to the Ethereum chain with wormhole (v2).
I used my Phantom wallet on the Solana side and my Trezor hardware wallet Ethereum address in my Metamask on the Ethereum side.
Al looked well, althought at the end i saw a button "disconnect Eth address" which i did not click.
I did click on REDEEM, and the transaction went through.
At least i   think it did, because i signed, and paid, for it in my Metamask.
Now at the end of all this my USDT is gone from my Solana wallet, and there is no USDT in my Metammask wallet.
I copy here the 2 transactions (from Solana chainn and Etherscan;

https://explorer.solana.com/tx/33L3CcKnAZshPotD1A72L7x1Tcsfg85HUQisuDSiGv6KWwuzdFjecc1tkv8h4HJyHP9zAtnEQ7UKnpuqqxtqbFcm

https://etherscan.io/tx/0x871d0c55abb37290bae1e964571bb8908895d68132f2eb675fda29c866367922

Please help me with this, i will be very grateful!!!
Best regards,
Marco
sandybeach@tutamail.com

**Comment by leoluk** [comment]
It looks like the bridge worked as expected - you received Wormhole-wrapped USDT on Ethereum. Chances are that those aren't terribly useful (no liquidity), so you might want to bridge them back to Solana.

**Comment by Sandybeach25** [comment]
How can i bridge my USDT back from Ethereum chain to Solana chain when they are not visable in my ethreum chain address???
Can you please help me by explaining that?
Thank you in advance!

**Comment by Sandybeach25** [comment]
![Pending bridge](https://user-images.githubusercontent.com/90960025/133893904-4620d49c-f6b2-4d57-8290-bb703f04c1af.jpg)
Also it is strange that the bridge transaction stil seems to be pending.
Which a connot stop...

**Comment by leoluk** [comment]
You should be able to use https://v1.wormholebridge.com to transfer the token back to Solana.
