### ISSUE TITLE
I used https://www.interstellar.tk/ .. it did not recover my funds and drained my wallet of all ETH to 0

### ISSUE THREAD

**Issue by Bigbet420** [solana-labs/oyster#349]
I had my TUSD stuck in the limbo of the wormhole and was told to use https://www.interstellar.tk/ to recover it. 
This was the sol to eth transaction ; 
https://explorer.solana.com/tx/gjcSYmCA6RUCVkSodYUFDg2S9Fy3LgtWBnCLEa2fRCTfKWpJWpf6fsYpMkUTvXX7UCyEUyj7USv4CMYucWU2WnJ
That above link is what I put into https://www.interstellar.tk/, I approved the gas fees but for some reason the transaction failed 
(I had right around $267 in eth, gas was only about $40) it should have gone through but after I noticed it failed, I checked my wallet and now I have absolutely 0 eth. I'm not sure what's going on or what to do but now I've lost money twice and have absolutely no clue how to recover it.
( https://etherscan.io/address/0xD50E1021f67520091f12b85Fc1BeCD434657f9dD )
The above link is my metamask wallet and the last 2 transactions were me putting the $267 eth into my account, and then immediately after, it somehow got sent to here , to the link below
 (  https://etherscan.io/address/0x5fae299c4eda1b1b9d9e47e4229ccc09195cef91 )
So now I have 157$ lost in wormhole and $267 somehow lost to ( https://www.interstellar.tk/ )
To clarify, this is my trust wallet address that I used to send the 267$ to my metamask address : 
( 0xe2da92C4705cC29e5399751e974b5e2503a0EA39 )
This is my metamask wallet address that received the funds from my trust wallet:  
( 0xD50E1021f67520091f12b85Fc1BeCD434657f9dD )
and this is the wallet that somehow received my funds from metmask after using https://www.interstellar.tk/ : 
( 0x5Fae299C4edA1B1b9d9e47E4229cCc09195CEF91 )
also metmask shows no transaction of the $ being sent out, but when I looked up my wallet address on etherscan you can see it gets sent to some unknown address, Im guessing the address has something to do with https://www.interstellar.tk/

**Comment by leoluk** [comment]
We took a look at your transactions – none of them were generated by interstellar.tk, including the one transferring your tokens. Metamask would've prompted you to approve a transfer, rather than a Wormhole contract interaction.

If you didn't initiate this transfer, it sounds like your computer or seed phrase was compromised.

---

As for the Wormhole transaction, try manually submitting it using these instructions (after putting some Eth back into your wallet to pay for fees):

Manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

Note that Wormhole v2 was recently launched on wormholebridge.com, which fixes the bug you encountered! You will still have to use v1 to complete your in-progress transfer.

You can also try using the third-party https://www.interstellar.tk site to retry your VAA submission.

---

Digest (for reference only): f1aebb67cc28fb3b55d5c1598cf0b247733c05d10218f869b4bd1d306f7d0ab3

Signed VAA bytes to submit to the contract:

> 0x01000000010d004cc25ce7586c90686a0bdc401b7795bf82ec3876fcf35e11a88f7f81dd0cc4ce4c2e21cf9a13b10e1d587e23933c4b40959137e2a0bfbdd4473b255331daf4fc0101cb14584e20afb7d1896ae0df0ecdf31a66fb5200ef59f671ffbe2f205907fc9f64b159f775af78acf19bf4efad1a72d5895053786605b8109f8cb15c32fe20e30004faa9746a67086e793f3c8fce9bcd1a7613931b7810845815ce76445e4971458e64121afd5f0359857927ab12bea904236d92c4deb78e5744a726eb3df64b4695010534e3eedb5423685f4f30e5f051f7a845e7fbe6eb6b0f9b5a1317497be3070efc0264bdef8155e56f2c3f7834aa0c402adff1742b7c735e77718bae4b15d2eda70106e2e7ebcab5b3c94c15a13d087102adfde955155fda2b15000335b6b3250b7b976d4a5aa37ebc381a2c51081d8822b6d7c9f43efacdbb965263d05d860421fd810107efb0cb38638b865dace5d4a49a31b83f66e2eaa569caf3bd0d17e24f32b904e748afc3e50f2c9f7f2679e53a83adcab5ec398aaed452fc095c068c6225654dcc0108168354ae7e5f5a99bd00ee70f6335a172f438786fcb836251341eced213dd38a5005ecac3e5fa994d34bcdac61919f8c0c8c5d1335d442ba3fa5b1949ffcafb6000a99e37352a38497cf77e3324f55fdff3c7cd563bbafa37b69747b66c6491038983519678562e405e1b8e529655cd281787b7a87b37a2d9ee16ef2be218779f1df010c7aa7978da8f108447ab4394cc6a222faa3aaa92a4ee70956a9a962081f7bf29e7efd239c5e2a012e2765f31e7aa2bf115f9b0ad7498a77d58aa20e7f02f27c14010d7644d4923d81d116e2964af9754fdea873a5f5b5746f6f2ecbdc61760cfa845e0734b54e8857402c359b97df17007e558ecb75ffd7b606b53f6b891dce7ccf06011059cd26038d2365fd20ecbf8701843e7a2980cf26712d2c5378ca7fd91f1e2d5d3c92ee7b26c19d72dfbaf3ea191a6c866e2abac04f00d832c8554ecaa529350000112b402021597dc2cdf5b8a8885011697f2c29500b6c8ee7e6ea6970bf33b8a28b51cf1bd27396a76921bcd0de41ee9c7fd9a13bf91d81d2179fc08f743d1c900200125a595ba2ef058f6fd6c2de24bf58d9b451a53d11ed72ac0450e69a9d43df06f319c9a25fe36902db2dbd277af78038d8c5c2b22f01b9161a4f8d059de350149c016144d0fb10000125c801024f4382dbedd8ca10ad9a3ae645ea861cec6772f04ddab1e069251f12876499a7000000000000000000000000d50e1021f67520091f12b85fc1becd434657f9dd020000000000000000000000000000000000085d4780b73119b644ae5ecd22b3760900000000000000000000000000000000000000000000000000000023e2fbdbe0

**Comment by Bigbet420** [comment]
My metamask also does not show any transaction actually sent out of my wallet. But as soon as I hooked it up to Interstellar and went through with trying to recover my funds all my money was gone. It did not recover my funds, and drained everything from my wallet. There is no chance my seed phrase was leaked, I keep it written in paper.

**Comment by Bigbet420** [comment]
I had initiated to pay for the gas fees on interstellar, every bing was processing and then all the sudden there was an error and after trying to do it again my account had been drained to zero. There is absolutely no chance it was a problem on my end.

**Comment by leoluk** [comment]
> There is no chance my seed phrase was leaked, I keep it written in paper.

The seed phrase is also kept your computer, assuming you entered it in Metamask vs. using it with a Ledger.

Metamask prompts you to confirm every transaction it sends and a website like Interstellar can't just do arbitrary transactions through it. If Metamask doesn't show the transactions, they weren't done through Metamask.

**Comment by Bigbet420** [comment]
The last transaction metamask shows is through interstellar it says failed and then all my eth disappeared, I’m starting to think it’s a leak within you’re site. Because something is definitely not adding up to me and my computer has not been compromised

**Comment by leoluk** [comment]
Interstellar is a third party website not operated by or affiliated with us. It did work for dozens of users without stealing their money and we've been in touch with the author—whatever happened to your money, it wasn't related to Wormhole.
