### ISSUE TITLE
Luna Stuck in wormholeV1

### ISSUE THREAD

**Issue by Deflucky** [solana-labs/oyster#350]
I just tried to send 5 wLuna to metamask using wormholeV1. I approved the Solana transaction but when I saw the metamask approve/reject prompt, I noticed the gas fee was higher than I expected and rejected it to see how much eth I had in the wallet. But now it looks like my funds are stuck. I would like to just have my funds sent back to my Solana wallet if possible. The transaction id: 24pQH7B4z2HNBTTeXiRq2sCx6VWsdrSgRyez7LXp9xeT7Xn5PJww4rL28PQ38gbwd9bh4v4WGP5Xj5mj1CiuCEDc
Any help would be appreciated.

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading https://v1.wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If v1.wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

Note that Wormhole v2 was recently launched on wormholebridge.com, which fixes the bug you encountered! You will still have to use v1 to complete your in-progress transfer.

You can also try using the third-party https://www.interstellar.tk site to retry your VAA submission.

---

Digest (for reference only): 9e647789dbf370cab215cbda359910e4d9a3f301cf13e20a1e6e62d932272a4b

Signed VAA bytes to submit to the contract:

> 0x01000000010d005022075ed5d7ac6c869f23822e7b07797ce16cc2db8df36b88b8d1f6278e36760e92956e5c6a8cc0809fe89154372488f2b6c83542b486b99c94ec12d88e8615000164ecdfb59c8cf679d3e1354440472994cbf355f237335a86c53d5bee8598f5675a4f03f67707273637c1dbeaa958bbcb49e622124520653fecf793872fb7837900023f903717f7f98fcb4fc7870c1bb58da2e9d655d88ebb9e84fee00f73fc392d912a345983acd0eb8800c4e89d18d2d8af3cf2bb07997dbbfe5bbdbc9a67eb359a00058f1268d15d72dfd1ef057e9726abe9f436df6967f34eb9d3088a803729cd51f1519824d4e954d646da95e71832280b4144d99cd3c54552e8b2c3ef713b3b82670006c4ad69c1abfde95c879409d21794cff4d43e517fd3713f2b89a32f9ee205d7d71853312134f3b8dc8553d7148eafe4e8abafef7779f744b695d93f9dfbd879a20007f739677e7195d0efea18ffb21c804c7b5ab8103d7f139f85a372c27611a280654bce2558954c0b2c0d7da5e204a064362e52bc69999ebd485280033837a94e57010a437c56f10519d266f11da890d863f5a9660275cc225c862243ec738c51e38019377c8523d1c5e9f890ceea417f5f242764206ecc5d8b8d1c854f585cba35351e010b5a353d355f3efd36ceb2ef6749edb39e58229c6a9308a1c17002707e51c3447167dda8f63788ecd964dec79299cdc9a1e178abba7b453c27d4bcc7564afb8062010c27d137e0ced245556c53b723acaea669754ac6cdc17c71b823227f504264186008e96824b00e4aa4dd659f241104687a97dfaa3e0976458618ef329b3e9fe670000d418f5a35c0c7122f0db6f34fd95c2af91b0f12c4cd915eef5ad6643031069ed0609b59fdfabaafa024087db78cc8168d9b32c2ee8eb9626122c4e7c2b3da1b53011004320984d543871ac741a131a7d2f584565c601de9cba1dba6b4f54fd8bfe6611f79d8f2a810a9f70a90c7ec7b1ef4de9c1daf09be892a2087ffd063751113fb0011332d307d3c592c781b258ee49832e812ea8dab748af61d5e4d618719ab2dd9f93e5cf5cb43b9ec0bdc38b0f0d8a9b4d28049c95c2c9c7eca1067ccbca4ecafe80012f6f50d5f337f9901a2b9157200f981ed97f1f02999ad128ce8b7973aba04f264058f9472da55348e86e6f8ad79f751bfdd027aeaec5d68f3abd48a4481e9a8b60061479ecc100001365e010217d5a56c6a0e8989b9ca566294d05cb46e2c4ac38b66bdf9aaa49875ad30504b0000000000000000000000003996c69288e1464c8d23823ddb7e72743021154c02000000000000000000000000d2877702675e6ceb975b4a1dff9fb7baf4c91ea909000000000000000000000000000000000000000000000000000000012a05f200
