### ISSUE TITLE
Attestation Failed

### ISSUE THREAD

**Issue by JimZorn** [solana-labs/oyster#355]
I'm trying to transfer my Raydium ERC20 to the Solana blockchain, and when I get to the point of transferring it, I'm told that the "Target Asset is unavailable. Is the Token registered?" I proceeded to click "Register Now", and after providing the "Source", "Target" and clicking "Attest", the transaction went through as seen on Etherscan here (please see link https://etherscan.io/tx/0xfd75c3d332085a1ff9141fc1481a7e9905ac2c872c922e653f65b4f6053358e0).

However, it was indicated that Raydium was still not registered, making it not possible to bridge my Raydium from Ethereum to Solana. Please see attachments.

<img width="1440" alt="1" src="https://user-images.githubusercontent.com/69160031/134041474-b4d0c354-1bb2-43c8-8c4b-c8fd451ca587.png">
<img width="1440" alt="2" src="https://user-images.githubusercontent.com/69160031/134041485-431c5bd1-0b0f-4e8e-b21e-2567607b5800.png">
<img width="1440" alt="3" src="https://user-images.githubusercontent.com/69160031/134041489-ede88ede-e33b-4d97-b6dd-bb4bb3735bf5.png">

**Comment by yamijuan** [comment]
please refer to this Github https://github.com/certusone/wormhole

**Comment by leoluk** [comment]
(the oyster repo is for the v1 wormhole UI — please create a GitHub discussion here for v2: https://github.com/certusone/wormhole/discussions/new)
