### ISSUE TITLE
Wormhole Bug: BTC (ERC-20) to BTC (SOL) stuck on "Awaiting completion on Solana..."

### ISSUE THREAD

**Issue by misterbaka** [solana-labs/oyster#358]
It’s happened again..My transfer has been stuck on "awaiting completion on solana" for a while now.  it’s been over 8 hours now (last time this happened it cleared in about 4 hours)

ETH:
https://etherscan.io/tx/0xc3f5d7df58cdce90d4c68e4832d9d9e067299eadd64c8d46f8152f8c74a583bb

This usually doesnt take that long.

Please help.  Thank you.

**Comment by leoluk** [comment]
There you go, gave it a nudge: https://explorer.solana.com/tx/5a7Bj9KHpydWnAro7DkXAWna7DgnnctEGZw838UdvoyfPZqA7yw4Nm57NGjk66GnvozqUXgYaeAVGF6EY3d4FuL

**Comment by misterbaka** [comment]
thanks alot!!
