### ISSUE TITLE
Reply to last post

### ISSUE THREAD

**Issue by raaanaj** [solana-labs/oyster#359]
You closed the last message, before I was given an option to reply, so I will do so here:

You wrote:

> Note that Wormhole v2 was recently launched on wormholebridge.com, which fixes the bug you encountered!

It is my understanding that I cannot use Wormhole V2 to move wWETH (Wormhole Wrapped Ether) from the Solana chain to the Ethereum chain, so I don't know why you would suggest this.

I was told on the Wormhole DIscord to not transfer my wWETH back to Ethereum last week, and to wait until Wormhole V2 was released.    Now Wormhole V1 doesn't work either, and there is no use for wWETH on the Solana chain.

Are there any plans to fix Wormhole V2 to be able to transfer wWETH from Solana to Ethereum mainnet?    

What do you suggest I do to reclaim my funds and convert back to ETH or some other token that is usable and has some value?

**Comment by raaanaj** [comment]
You also wrote:

"You can also try using the third-party https://www.interstellar.tk site to retry your VAA submission."

That site says "when you trying to send cryptos through Wormhole from Solana to Ethereum, but accidentally rejected the signature request on metamask"

However, I didn't accidentally reject my signature request on metamask.

**Comment by leoluk** [comment]
> It is my understanding that I cannot use Wormhole V2 to move wWETH (Wormhole Wrapped Ether) from the Solana chain to the Ethereum chain, so I don't know why you would suggest this.

Correct. The message simply acknowledges the bug and notes that it won't occur with v2.

> I was told on the Wormhole DIscord to not transfer my wWETH back to Ethereum last week, and to wait until Wormhole V2 was released. Now Wormhole V1 doesn't work either, and there is no use for wWETH on the Solana chain.

The v2 UI has swap pools for some tokens and automatically offers to migrate them. If there's no pool for wWETH, you need to use v1 to transfer the tokens back, which should work.
