### ISSUE TITLE
USDK not come up on V1

### ISSUE THREAD

**Issue by iwanami10** [solana-labs/oyster#364]
USDK does not come up on V1.
How to bridge back using v1?

USDK token address: 
2kycGCD8tJbrjJJqWN2Qz5ysN9iB4Bth3Uic4mSB7uak

![210926_144100_737](https://user-images.githubusercontent.com/3964558/134795570-09fadfc4-15e4-46f8-8c04-518b2d508210.jpg)

Only SOL come up.
![210926_144553_740](https://user-images.githubusercontent.com/3964558/134795557-15ea1b26-e275-41c8-a1bd-16e087097a0c.jpg)

My phantom wallet
![210926_144129_739](https://user-images.githubusercontent.com/3964558/134795585-ebf899d2-1fce-4427-86ec-09a0180bc98f.jpg)

**Comment by evan-gray** [comment]
@yamijuan perhaps a similar issue to #353 ?

**Comment by yamijuan** [comment]
similar to #354

**Comment by yamijuan** [comment]
@iwanami10 can you try in https://app.saber.so/#/swap and see if the token shows up?

**Comment by iwanami10** [comment]
I am sorry, but I have no USDK(v1) now.
I accessed the following URL directly by inputting to the browser address bar, and could bridge back.
https://v1.wormholebridge.com/#/move?from=SOL&token=USDK
Thank you for investigation.
