### ISSUE TITLE
Can't make claim on v1.wormhole.com

### ISSUE THREAD

**Issue by bagz11** [solana-labs/oyster#377]
I make transfer UST from Solana to Ethereum. **trans hash:**
3UA7R3gK5dxjDw73zQbwpFbayc2Zr2TJ6QMLdPWEyyjDdbWXLQrdEgBFtrZzyar5Wx1bS95i6Wjd9G9ve1io2mjh

Transaction was approved on Solana, but window with claim via Metamask not appear. Previously, in such a situation, one could find the transaction in the list "My Recent Transactions" and make claim again. But now it does not load.

<img width="1385" alt="Снимок экрана 2021-10-07 в 09 59 56" src="https://user-images.githubusercontent.com/92082860/136518731-106ad3a0-ff0d-46d7-b128-06e80c7b7133.png">
<img width="496" alt="Снимок экрана 2021-10-08 в 08 18 15" src="https://user-images.githubusercontent.com/92082860/136518744-8da3248a-2eb6-4583-9862-dc094c028bdd.png">

I guess that I can make claim via web3 on etherscan, but I do not know what to enter in the field **vaa (bytes)**

<img width="358" alt="Снимок экрана 2021-10-07 в 17 13 20" src="https://user-images.githubusercontent.com/92082860/136518936-70c68e9a-75b1-4e7e-86bd-c05ce9e035c7.png">

Please help, make claim or return it back to solana. Thanks!

**Comment by fr33fly** [comment]
I have the same problem, just opened a new issue about it.

Would be great to find out how to get the correct signed VAA (bytes) for transactions that are stuck in the Wormhole.

I have seen various people having a similar problem, hopefully we can get some help.
