### ISSUE TITLE
Wweth lost while transferring back to metamask through wormhole

### ISSUE THREAD

**Issue by 2sharkk** [solana-labs/oyster#386]
I was transferring wweth through v1 bridge back from phantom (solana) to metamask. As v1 did not had any liquidity. Initiated the transaction , got it processed through solana network and since eth gas fees was very high. didn't finish the transfer to metamask through wormhole. after some time when I opened there was no wweth to be found. 

Sol transaction hash # HkMuM68vgTrnpNGBeMjatvzm5EFpRRjwJb7iLuoTGQap
address # 6QcZoyCg4n2WhmjxHtW15xSnPZDxkRMtP6fNDWUqm8Aj

**Comment by 2sharkk** [comment]
> The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading https://v1.wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.
> 
> If v1.wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract
> 
> Note that Wormhole v2 was recently launched on wormholebridge.com, which fixes the bug you encountered! You will still have to use v1 to complete your in-progress transfer.
> 
> You can also try using the third-party https://www.interstellar.tk site to retry your VAA submission.
> 
> Digest (for reference only): 2008517f32a5fe97052a7dfbf499d2158107f82749cbff9732790eb8727f8218
> 
> Signed VAA bytes to submit to the contract:
> 
> > 0x01000000010d00ec93c86f4a81c710e8ff7090be1af86a7cc3305ae410a0379e0cce64db67cfb960ac01577e751006562a1ca047847ee58f30e85c81a092c5ab84d104bb465f7901030ac48b5b598fd18f99d6e03f3b1c69d93f4d3cb8c17b72c7dc3160d6121afbe855362742dc5dacf8acfdd3dd59b930714d2aa80c7461dabbd0abaee368868578010436ef858ced197da80530d412c5254b721cc431a6e4ec0d1806658d93647c79ef024639bd1fb137920b0e50dd561ccfa8a2ea2db9eac284ec73e7496a72f6f27901051fae20fc585d4d652fa5a8b3ef7e1ffc009142f3555db4f6aad92efcaa10348e2862b64912b20766885934ce4c69e61ba9dd3659aaaababdd1966ca52b1b2dde0006cd0346db63db8385f6cfa7911a191fd67a6fe83f9a924e5eaf5a89fd2caa491153bdef91f428922d48642c20b8b9f8e9cdc3e825620d9c65260b334ba89b8cbb0107270eb95eb81fe24f1c566130ef7d05749730c05394cc766992fb426fd3ee06c93900aab2b43d99e7b476ee1857b4c8447c9a103c7cdda2035f899ed9c954bfeb0108ca0ae3a6fba272f2833c22b11b119184f673b55b72d112b397520553b9f211c526d7befc4cafe1cf557df13ddb49bf670798fc6ed535ca352351924863458ef3010988e1108ca75e3e300263d7e274805c0cc53e75154913354d820f612ef5b6d6511e164aa906162669dd8bca70b0dad30eeba61015efd94f9e5c7d08d7a233a8df000a2d50ef97f0b86e8e6ff8570f359f04b4e8960d44c3cdcce8611a9ce1b25f41f70c8235d781dddfb7ad6fd126bd57fd0a0921680440099f04be10e86551311439010c1003376ff293c1fd29ce2b81ee92281542a749af66029b30f9636683cf6839ec0cd444d96c805b8a4136336f9b06ddf55b5e4fc79cfeaf27c990f7d0a1c3713a000d1cba855ba44c2f44ac995cfbc468481b6eaf1d9446f03a7d728fd080b2f62dfc565179c42d74e8f986a5d62d0cfc48fc6c018d46679fed087498d740ad78ab8201106b4df013b680d1008f052182f76a517e7ee43db9195f2ba9d62fc761e2d16b881efc4945ed1ad7b4c85975cd95b85d8b1ff30a08061836763bf818bc487b0a81011290d9c3655a7c978b83074fa3115e60525d898acc15e54cd1279825284e5080d6689645cb5520c10543d6a0b1aa848f9dcd584c9872f21eaca9a37b9012d82af0016164530a100000c0a0010289b3feb352976edeb594d6aad02c1eec8b1825ccec565134a6573c64d0a726b10000000000000000000000001d9cf76b4b2d1208b267fc62cd7bcc3fe6964b2402000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc209000000000000000000000000000000000000000000000000000000000aff3f20

Hey the interstellar.tk is asking me to transfer the weth to this address: 0xf92cD566Ea4864356C5491c177A430C222d7e678

**Comment by leoluk** [comment]
We can't help with interstellar.tk issues - it's a third party tool.

Please follow the manual instructions above if you're concerned about Interstellar. It shouldn't ask you to transfer tokens, only to submit a Wormhole transaction.
