### ISSUE TITLE
I want to find my StarAtlas NFT poster (wrapped wormhole token)

### ISSUE THREAD

**Issue by keepgoing2021** [solana-labs/oyster#401]
I've been having problems since May.

problem occurred in the process of using wormhole v1 (sol -> eth) 

please check my tx and help me 

https://explorer.solana.com/tx/2YCPREAubdzzFvyBMmhqsCLJzh9ZrajKmn4TySDZrxAfvxiqY3nACFS7PbZYQryQX69Ur4YAbPd1GvxxPCUATHa9

https://etherscan.io/token/0x945f8c700d51f0a97c4d860435d63d8eed96edde?a=0x13b41f81A71D7adB19A971B58501eff3048f3070

![IMG_20211013_223042](https://user-images.githubusercontent.com/89294486/137960514-62fd8c73-3870-40fb-a0d0-9b135a5eccbb.jpg)

**Comment by leoluk** [comment]
The Solana transaction you posted is a `PostVAA` transaction, which is an inbound transfer TO Solana. Please provide the correct outbound transaction.

**Comment by keepgoing2021** [comment]
> You sent details for a successfully completed Wormhole transaction. What do you need help with?
I can't use my NFT poster just wrapped and stucked ..

want to solve wrapped wormhole token -> solana NFT

**Comment by leoluk** [comment]
I don't understand - please reach out on Discord: https://discord.gg/xsT8qrHAvV
