### ISSUE TITLE
V1 Wormhole Error - Insufficient Gas

### ISSUE THREAD

**Issue by chrishoskins7** [solana-labs/oyster#409]
I attempted to send WETH from Solana to ETH via the V1 Wormhold last month, but the gas had risen and I didn't have enough to receive it through the other side. I tried clearing the cache, but the transaction will not continue. I appreciate any assistance. The transaction hash is H4otTHWr3J7ecxEmeTcsjTEx9Xudrau5BULT6xHZMHN17v9k9EBqLpgLVL59uGyFn5zBonfvcu1iG3xBTCP4TYRi2

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading https://v1.wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If v1.wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

Note that Wormhole v2 was recently launched on wormholebridge.com, which fixes the bug you encountered! You will still have to use v1 to complete your in-progress transfer.

You can also try using the third-party https://www.interstellar.tk site to retry your VAA submission.

---

Digest (for reference only): 6e9ceb6cb0eee334d093d7b7643eddce269acafeac2594a42a164fe4634bbf3b

Signed VAA bytes to submit to the contract:

> 0x01000000010d0046df2b9f74bcf3d0daf75e0d18b86029ff6b8ebc3e957b709d48c18ae72bbe7420376f03f78d555985224096603d585c0574ad624df5601e8ece6aedb90391520102df1a89d1463f592062577ca98497a75672065255afdb5a39b91a917359b6e0c12955798a123d617f0cad29d92a5d98d7620bff48146f5ba6e78154f2e75098c400037c19a9c30e1ddf546b1f888d7fdf225e35db048bc7e1842a0082e000c1e6b75c735d18e16af2025f4fb073a2d6fccff1faf10e3ab3fd4ba7ef23c9a6d3712d2300053327abf60ea4dae6ded88c8ca4ba6e40043c170c590f8e055a71b13a3b02f0d82d5cc9f6cad83636d7d7700d6992eccd0148529b92078125ce39c68c5b0a5c6a01061408bf6c47187a85339d4c10ffea58ad6d49b7167f523466e28cfc690984da8c665c4db5cdef63333ca1919ca594673073185efd3691110dd637abf1e938de890007cf841ae3c5044afd4ed93e831a71ef044cf08eb7d35bb08fab662ac84c2165cb14f27c7fece7824968dc636eb4c4e42fdf4b0b199919dc4ecc51bf3612d0666f0008fff6ea3ccddff8b64ee378ff809c23825892af71cce6f55b912a137d5c63b37b31325500960a3e792295445d0fefaff33486b4695792345c09d56a343b1b5f9a000adb366b295de3d92c0cd28a7ae372bdc0f05e933dc3c207a5c924dd3d573077aa4c734d9b48062f95cae8bc88cf8174af3f74ca57d4505126a0b61bee8c0e75a4010bd658429deca8db14116d3f511e07d0f8f2d2234d6fb50e385ad39bf2cef87653029871315ffb4554e44d612bb8d5f5cb4050084d81fc9aa3e91fd65e3e5c6984010d5ac3323a9adbf23f4f1713b6541e3f105fbf7aa8763d7c791ddcc0ddbd4341da72996c028277c9bab6bbfecbb2d1a008e2c1e312e9a0c1fc9a47a8e3479982be0010fc98c892a803864b86e6b8428238ab2b9010c7034273fb6660aec808511456e66f9544af01749912bb6d60e9156217ed5305af1ec378a474fbae4ce90b82a628011167003c3e6b46fb46ae325b1f981281ad73d29826838dfedc18c64016605b769552a99feb2c1a867d0e391c5a0ad5c0f153b26f54a671c4257dff453905086b390112162f55f69d3ce08af1ded1d74d8bf2743067406ca1f047567d23fc2b04725eb500bb5540303480eb78d2fbcc0d4324251bb5b584ebb34425e7aa74baf013643d0061300f0410000038290102fe8b1c3b8e88ad8350c7ab176bd40d5076a9916e456641189fddf61ce1ec79ad00000000000000000000000055d2cd3d39478e815d2ba1ef6bc1fb6b96bb22f502000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20900000000000000000000000000000000000000000000000000000000042c1d80

**Comment by chrishoskins7** [comment]
Thank you! This is resolved. I submitted the VAA bytes.
