### ISSUE TITLE
Stuck wWETH in Wormhole v1; Transaction not going through

### ISSUE THREAD

**Issue by auerlone** [solana-labs/oyster#410]
Hi,
Over a month ago I transferred WETH to Solana through the Wormhole v1 and now I am stuck with wWETH and cannot re-transfer it to the Ethereum network, as the transaction approval loads for hours just to fail in the end. I have tried several times over several different time periods. The amount is only 0.0599 so there should be enough liquidity left but I don't know to be honest. Please find some screenshots attached to this post. I would be thankful for a solution or other approaches to tackle the problem. Thanks in advance!

<img width="1386" alt="Screenshot 2021-10-25 at 19 34 44" src="https://user-images.githubusercontent.com/93151999/138743120-f1991060-969a-42d9-9d1d-f6513ebdb6cb.png">

<img width="1386" alt="Screenshot 2021-10-25 at 19 33 09" src="https://user-images.githubusercontent.com/93151999/138743100-d8bef400-ad70-417c-bc5d-9bffaa4baba2.png">

<img width="1386" alt="Screenshot 2021-10-25 at 19 34 33" src="https://user-images.githubusercontent.com/93151999/138743118-6235c7a6-04d4-4893-a3c4-536e403e4bc3.png">

**Comment by auerlone** [comment]
Hi,

I recently contacted you for help with regard to a transaction stuck
because of insufficient ETH for gas fees. Now the gas fees are low so I
would like to retry the transaction. However, when clicking on the link for
the third-party interstellar and also when manually inserting the VAA
bytes, in Metamask it says the transaction is worth 0.00$. Please find a
screenshot attached to this email. Can and should I still approve the
transaction or what are the next steps?

Thanks in advance,

Am Do., 18. Nov. 2021 um 01:31 Uhr schrieb Leopold Schabel <
***@***.***>:

**Comment by justinschuldt** [comment]
@auerlone That is normal, no reason for concern. The mint happens after you submit the VAA, metamask is not aware that submitting the VAA will result in tokens being minted, which is why it shows $0.
