### ISSUE TITLE
Stuck FOUR in Wormhole v1; Transaction not going through

### ISSUE THREAD

**Issue by PTModra** [solana-labs/oyster#412]
Hi,
I have tried to bridge tokens using V1 back to ETH and process stopped. I have noticed that tokens are gone on SOL wallet but they never came on ETH wallet - now it is over 12h from pressing transfer

Transaction:
https://explorer.solana.com/tx/4Z8G3dh56Gy7CTtE17KC8GR8jhbUGfiXnVrj2qNztMzsycY6DJHJvqycfq3hS3y8dR5KvCN5yxKTL4RcetheXQoX

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading https://v1.wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If v1.wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

Note that Wormhole v2 was recently launched on wormholebridge.com, which fixes the bug you encountered! You will still have to use v1 to complete your in-progress transfer.

You can also try using the third-party https://www.interstellar.tk site to retry your VAA submission.

---

Digest (for reference only): 99f1299a0e59bae991fa24c9976b00b5936a02bb4149f060d8d7d34c92a58b64

Signed VAA bytes to submit to the contract:

> 0x01000000010d00476dda80bc6e0c2ea4e7c8fc6d5d7e77b40917ad653eb155eb86ef7fb5ea7a0a0db5802f0073ba644727837629c281150168d92e47b996fa1d9f71a78a077542010173ba2e167e45349bd095c3b5983abc47787ac7fe81ce33f7d538dba172f869205e58c2afb2e79b612c7a4ed17cef93c85828f372167b1585be2749d0a0747f93000370d1cbc7b9c396268fe9b26271659a7025e3200aecf4871b2fe60c6e2d0e3e6e6deeeff48dab6dfd470522fe7729f8d6e877d2aa717bbb3554ac267926af46da0004a9bfb824a18fab338468b9b1f2c2dfd26bbc6da826dbef6e72d8da05d0201a31290a885bed4be39f9deb1d1cd408f0bd872e4847fbd83d285ffc8e2d8e273a320005ac03850cda343b2d63015fcc3eb314ce48817de439455c9f7b3e9bb37766db445c3e58cfb2d1b6d3fb516cc692b1edc8537635bcc68642337bd73643ad70d8f8010656fb5f38798ef23f158d046c394e5908f83e216f46881df5874f6ce3e29eec061ce4b19ac6e07cd15db9b544b6259ccdb57fba13b18eba368faf6fbd33b3a8c3010780f4da4f3af7d9194f5906843b91ee4b2395c407b7e5d932b64af71a087c59544a8ba23cb4e9a81b821a8444c1fb2a035a4b57dc33bf8a6ee8962341b16ad19f0008c1c39840fcc0ff1d35e1eab04b4e5cbea20d6a9fc3ad4692684f24cce466cdfe7c4bb1c8e71cf3eb3ed90736b0ead7a3a49592ebffd83bb38ea777145ded4c37010a317c8187ea2f1e309477b864b316b30a3d54717ac496b8c68d0cae7945f8a2e43dd6184b520174594eeb097499ef31b05a4ad3611fc11dddad6026f87ad755c1000ce62b035187ddb368e709d2ee019e75567580f689200759695d16be15c87f3f1d3e24a2c0a296241c1283956160ca1388ddfb8deb4019d4cdb20587c5319f848c010db4b8c5b46928d471278a047b5ec4bcc51f61c00f1e8cce08bc3cb8c35941536b36686081e6548b7e0cd40ece9fd21e2c026648338f307905f12fb0508a64c4f3011009ba5d97b94d2c4127cfbdc87ff14ab96a917c9d8130f618031a0cedd9d24e0742859fe1344e8473da6258efa9aff69d141068c6daf7a08630acebc7f7547fa50012a49a81ac9c741803189928a95e34e7bca8cfc406666826e9c52fe7b8866028d953378aef3b5acb2e63555d9ec98e58f7853b62cc7ed9a39ead4f77faaaf28690016178078e1000007ff60102419a0a1d89cf9cc7f04f3e26bc95f5754e640024ca8a19433ac9e530dddb235100000000000000000000000032403c0cac25e86bf89acbc1fed1dfcf9434117a020000000000000000000000004730fb1463a6f1f44aeb45f6c5c422427f37f4d0090000000000000000000000000000000000000000000000000000024616979880
