### ISSUE TITLE
V1 Wormhole Error - Insufficient Gas (corrected hash)

### ISSUE THREAD

**Issue by chrishoskins7** [solana-labs/oyster#414]
I attempted to send WETH from Solana to ETH via the V1 Wormhold last month, but the gas had risen and I didn't have enough to receive it through the other side. I tried clearing the cache, but the transaction will not continue. I appreciate any assistance. https://explorer.solana.com/tx/4otTHWr3J7ecxEmeTcsjTEx9Xudrau5BULT6xHZMHN17v9k9EBqLpgLVL59uGyFn5zBonfvcu1iG3xBTCP4TYRi2

**Comment by leoluk** [comment]
Replied in #409
