### ISSUE TITLE
i cant find the selection of math wallet on V1 wormhole

### ISSUE THREAD

**Issue by arthurOmanko** [solana-labs/oyster#416]
i cant find the selection of math wallet on V1 wormhole.
when i try to use math wallet on V1,
i cant use math wallet because of not shown about math wallet.
please fix this problem ASAP.

**Comment by arthurOmanko** [comment]
why you developers changed about wallet selection code???

**Comment by leoluk** [comment]
I don't know why Mathwallet is no longer supported, but you need to use any of the other supported wallet providers:

![image](https://user-images.githubusercontent.com/859697/140508964-c3c55135-b19d-48fe-a20e-39d8e9dbd770.png)

For non-trivial amounts of tokens, we recommend using a Ledger hardware wallet.
