### ISSUE TITLE
error while using v1 wormhole bridge

### ISSUE THREAD

**Issue by dhterra** [solana-labs/oyster#418]
I was transferring v1 wrapped Luna from solana to eth via v1 wormhole bridge, but the transaction has stopped while "finalizing transfer" for more than 1 hour. I can't find any pop-up for signing on either solana or metamask wallet.

Please find tx on solana side below.
https://explorer.solana.com/tx/5Uwoj6o8TgFMRqaKp6koFe4FyYdMEPPdQZCaWxK51WmuiSK42YdWWSwZd4THdenwg13h31diG8QjRSbSoDWQPKj1

How can I claim my wrapped Luna on eth side?

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading https://v1.wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If v1.wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

Note that Wormhole v2 was recently launched on wormholebridge.com, which fixes the bug you encountered! You will still have to use v1 to complete your in-progress transfer.

You can also try using the third-party https://www.interstellar.tk site to retry your VAA submission.

---

Digest (for reference only): 5d57f58db6372f17a20317da0264f48f05dd41e956fe7a18dd8c908e5852a89f

Signed VAA bytes to submit to the contract:

> 0x01000000010d0005abe7ea593d1f67a3a52891e76b40995114c4b26a2e85d7bf5015ab06ac17482a369df02c4b3a999000f3aa7e99fcc78db62f86220b4666ff73921a08e31ac700015b9857f53e2420dca6cef2689c4aa965f90192b7fe49db4de6b3439a81110c6e0d9b11498f4337f72859466e3ed6b8a475f6160d76804b026f8b2e271836b3b60103f825bec1b4dc87907bb5534c955d19faed8dcdd95d0047d8a0998597735d25db6ec9821f69dce8bd8200836f999a11a09a1140814b84c1ad735d8c11c051f8330004af5ddd277d04c4fbf3f075e7e4a530dcd34c4261318693d04a14c0ce58e50bb91ce5c6ad8d2e4c56e13f251089ff53975199ee9efa705f89b4d1446247c3106100053f907f985218cb366ea030295cba862af644f2aa7c08634a2408cd5505b44f8f43052b16d4adf934ef83d5af971a10250a1d31409baa68ec9adf48d2923c6f640106cd46364001de968021cedb9a3dd75b7eb689f46f34aff24ee72e1b6d400101ec1feb8a93f105b505404e8775cf33948495dcc8db4349ab131b74234ea67e9e500007a4401aafbb5b58eb4d9f7377419e7f4622896024a0bef6709b561fed18da049a571a4036b4018475f4467c892f7bda3e6d23aeed612d6f685b29227bfc0332b9010ae7d6b8c8fda6ea97c7697b9272b02d3c3bde0d8cc7d4e2cbab128e5289f653a555780935d3717a37f96409abd1bc7b7fb0348ebc0e0e14740631f790acb97a8a010caf190a648d284e7bb692f926a0a2530e3b28e11528cb9e9fe68e9e7a32770156033d038c5dcdd785774fbb317e8c1900123323533132d6fe2b1793dbfce26394000db77fccff0244785608ec068bebd9f2499476b0fbf1e374c6cfb58934fe9f34d47d225ee9253fff1a312a3875ce310635cfe1f8c6a0eff048e8925e08e234db480110ae2bce161243cbdc99e1223e5c2c61efc45aac2538fdd2ca5e9574d40a3f2ca85750fc3d28473b952a40546edf0cca55df87c0360a32c25882626931228725c801116f8ad09989ec9b5180881d1eca01f4852551239f7ca1db0a0b9d83774b971166217bbaa038d4f6d06e84b86efa3fd8d1bb153aa1523047d0aec9771296ba41620012a0a5870a2629f462343a941e0b134b555873e3f9f161d9e49c8441aea4b8fe523b1352277dc04947eb7a3fbadf35ec5e3f9a53b29376a42e9d0b077589fe31ff016181e460100000d7740102e6c9ddeef0113252f459a95a0426362c9c15e36ce325904eb4bdf4a3eb1204c1000000000000000000000000447f95026107aaed7472a0470931e689f51e0e4202000000000000000000000000d2877702675e6ceb975b4a1dff9fb7baf4c91ea90900000000000000000000000000000000000000000000000000001b2244f8e400
