### ISSUE TITLE
wLuna seems to be stuck in Wormhole. Sollet -> Metamask

### ISSUE THREAD

**Issue by dwilliams619** [solana-labs/oyster#419]
Hello,

I sent wLuna from Sollet -> Metamask via v1 wormhole about a month ago. ~71 wLuna.

I was looking and asking in wormhole discord and they referred me here. Tx: 2YDLzqtM5UhohBPHsQJtPfaiH9xz9movGKZKPWAeBt6FK8RcBqSbtpaTY1aejMfmCoT96MM4zhQscvFzQTXAVDaf

If i remember correctly it was stuck on first step of tx, and never moved on to next portion. Thank you for help.

**Comment by leoluk** [comment]
2YDLzqtM5UhohBPHsQJtPfaiH9xz9movGKZKPWAeBt6FK8RcBqSbtpaTY1aejMfmCoT96MM4zhQscvFzQTXAVDaf is not a Wormhole lockup transaction.

Please provide a successful transaction transferring out your tokens, and we'll be able to help you :)
