### ISSUE TITLE
wETH stuck in v1.wormholebridge.com

### ISSUE THREAD

**Issue by sbue** [solana-labs/oyster#420]
Hello Admins,

I sent 0.1 wETH from SOL to ETH in V1 wormhole. I want the ETH in Solana but was told I needed to send it back bc wrapped ETH v1 != wrapped ETH v2.

Can someone help me get it back: 
- TX_ID: 65Gc7VZZRR26gYb3KLNvvrdBBQtqGJQLRAvMzsXHTjK8qYeo5LxajMQc4NLhpvw9pivF6CMUyeixVEG3C5KLFE1F
- https://v1.wormholebridge.com/#/move?from=SOL&token=WETH

**Comment by leoluk** [comment]
The transaction you provided is not a Wormhole lockup transaction. Please provide the transaction that actually locked your funds and we'll be able to help you :)

**Comment by sbue** [comment]
I'd liek to re-open this @leoluk 

Here are the transactions:
- https://explorer.solana.com/tx/65Gc7VZZRR26gYb3KLNvvrdBBQtqGJQLRAvMzsXHTjK8qYeo5LxajMQc4NLhpvw9pivF6CMUyeixVEG3C5KLFE1F
- https://explorer.solana.com/tx/3EJEA8upSFtzNJTseiWQcNrMpPDuvd2ZPeqGXuD7TRfGCtVTfwRATfF6fQ6ZTZPJvzS5W9kbs5m1UG1EHtQfEyos

Thank you 🙏

**Comment by sbue** [comment]
Bump please 🙏

**Comment by sbue** [comment]
Bump 🙏

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading https://v1.wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If v1.wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

Note that Wormhole v2 was recently launched on wormholebridge.com, which fixes the bug you encountered! You will still have to use v1 to complete your in-progress transfer.

You can also try using the third-party https://www.interstellar.tk site to retry your VAA submission.

---

Digest (for reference only): 1cc41bf743d87f3678f9ea9916dc2d15b1f036517bc349d2c75f2f84afe6cd99

Signed VAA bytes to submit to the contract:

> 0x01000000010d00821cbcf7842058910502ce40aea9f82d42a25b3c67f53bb1f1e39f8436e8f0f914932b19438673af6139cf76319acc703248ace5cd94dbb451283ab651e0cd6701017db19b836210243e270d09a7e4b73a2cd4d98b56f1252c0807cd3320ae20dce8335257f3e4808a75983710451a32df32030333e7faaa1c645a647ef96195e2df0103a9bdb2485607f572d2f173158f626cc69b4b2e8e5098b7c0677ad9a5c9f208f40fe7da71cf4dddcdca5ab7e28249f15fc22d29b570dab39bcb37d3ec2023429e0105bbefee58e2ad609c21f7031265f1d4b0e526a7cd878ebf9ee44d9d8f118802db66a8f5ea9a64c8b5e244f3d8a57053dbf2e2a9bfd10dc47348121e9081913679010686ac843aff646e4f53c927a05f7ae029a39c98732c79c8854ca63ff62ae4873b1edf2cd1ad2ed93703ce21cc4094047028a9c2c3bb1e88a448cb822aa1d906f20107f0814ed2df65a3de3fd93cde30d2d595a029aa27882ce3caebf3a88a25519deb2e88171767b4ba542bc3aeaaa06300c9c707266d44c43891f99953c56d41bbb30108b2550776324a7dc5a4ee57c1b6bcb5f2f2467afa7e84d362919493de482c72fe3137884138b16bbad6acd937b43f5b5f67429716f844c5497eeba76c40e1fc13010a80b4495bc0f58b5c45e4cf3a14f5fe022ec6a2f28ad12ab6a59e3aaba5bdd45101a75b12c1c6a67de6422a8f1bbedeadd3e72320110bfb8d4ace395701098ad8000caf8b27c827570bc384fb0d5a0d7a0c168588479d5018220869f5a77a374c0fb90c35f983a08a0cd91681807858423e8dbac3d0060e0c606fa942cd5bf55bceb2010de4d64620f6a9a9e42026b7bd2b8a8c58c2ddcbf2de258d3683de6f26f2312ae570d3f3e7e4e8e28a9c503a84f02f1d1ea31cb48b991f444ba80e955be0b7f24c011014433a308a31b03624334b8b28ba8596c1c951b3fbce722db573b264f2229b2e4e18b61aafb72319a5a774a809a918553c34917ca752e6c0a9aea1401e90c64d00112b9e1e52cf69f004fc2612c04b1aa96fa5e661959706c5ea94061dc0bb233d113dbd3a2cb0cb69d1bdb63f269d11a8ef56492ba55c213155b9fb25e767b06ad2001275d9705ccd269b0066c759234dc7cbaa57781025f4a620a68c85e93adfc986ff22c671ac17293d36e756efc9f089db35585968cf29062ada29c6846eb4a8828401618499d91000002a2301023856e74c808fa55700565b2f356c7876d080abb3681d2df1613d1aa998854d2e00000000000000000000000063d5c7d63a67c00903856910fab9f9540140cfbc02000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2090000000000000000000000000000000000000000000000000000000005f5e100

**Comment by sbue** [comment]
Executed the VAA but never got the ETH deposited into my address (0.1 ETH)

https://etherscan.io/tx/0x6d782e6d92c27955f6f50476e0553211ea26d9fd549af1ecee6f115eba8a6ab7

Tried with https://www.interstellar.tk recently but got this error: `Fail with error 'VAA was already executed'`

**Comment by sbue** [comment]
Friendly bump here @leoluk

**Comment by sbue** [comment]
Bump please @leoluk
