### ISSUE TITLE
V1 wormhole. CATO on solana to CATO on ETH. Cannot redeem tokens

### ISSUE THREAD

**Issue by cryptodaddyangel** [solana-labs/oyster#423]
Hello, Im tryign to complete this transaction now that Eth prices have calmed some. If possible, cancel the TX and keep my CATO on solana. When I look in the history/pending transaction, the loading animation is just spinning.

tx: on solana: 5E7Na1Q3f9C2ucN34weNV9ZGfPnWmio8UqtqgGWBvs24NjdKJnVYhBhFRFqpQJfYXFUZvoQEDKPzZbyQ7ararFX

![cato](https://user-images.githubusercontent.com/82098072/141662341-2234ef6b-b423-443b-88ab-d2dccafbdf93.JPG)

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading https://v1.wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If v1.wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

Note that Wormhole v2 was recently launched on wormholebridge.com, which fixes the bug you encountered! You will still have to use v1 to complete your in-progress transfer.

You can also try using the third-party https://www.interstellar.tk site to retry your VAA submission.

---

Digest (for reference only): 3a781a2c9ac410aa0887d53e4b387d9572aec31c6fc9e70829dadc0ea42f2108

Signed VAA bytes to submit to the contract:

> 0x01000000010d006ac9ea465d6e259070a5e8f8af54fb07848ea842f1bfb750d27e3f483d7ccd416c976432c4e0b0fd5f882d2b96a282d72a3ca65ac0a54441ccd5b79e24cf9d440101cc7cda3e3e9fa3b0118af0df568d640aea4e2921bf6894b49324c5ddcd09d18413926ee1cab7c2c07ff805a82b6d0563a89bed469749293a4a71bcfc15a61488010374271517c1c255e0cf55cccd784c73b40762b23bf16b7d47093818240339f3e95a61f7295b39752ddbcae54260b157c7f546b38255a2ff395cd26299ebb0271001045d8d694a398bb2337b0a16d45061342b3910316351744f493627692897cb01e830de3670d37e52b78ff1ddb0d50beef3969d9b79b247b11c74519ee8f5f850ad00058001759267738b216cb6ba7b61aec074cddf9183631667308f6a7388ddadeae334de8576d2c7cd1498ed033dfe8d16bfbeb9ee5ad3d5618b015e2bf3815bd9f30007aec56b57c57693bd9e20896225ed70fd455080ba7fa346069b91d2f29587b48b3449052e8d18286d857b0b62a25b77af90c2fd716d10fd1e57633b4d68ed7ae9000857568119df1034bd16e5c286882e8365af679bab08bf83b3ee511bfd9984a7ca6011b790538c2bc59934eb575f28e620e107d2e7260ad65c6e86c135d92f3b6400091e3d5ad273f93a5b0b8908d67e36a28df124ebc34501c43714b754b1bcc38dc22ac762b59e96b49c1daee604fb7c15afce1ac71896945bab8588156df7e60d0d000c1dbf0a0b029d9fc1878cb7fe2e6de1d334f7ce0253a1066ececcd097e2ca19c419f88fed248a864a5fc4d06e68b23c4b81df07e147941dfba1bac7b8be19a0f8010d8d69c7bbb1babf8e494dd276eb625d983f300e084d51f50c2f8cb483c30dd7dd0e5d104edcee09d7c8dbfd5987e554ec6e8b6577794d3caf6a5b412c4ea74b7b010f59661fba7bd1690959b2a31e3b5fae6458cb1b45a016ed3affb903ed8c870a5656c5cc96010fc39a469df6025424eed9d13a8fbaa01007e86dc1e49b8aaa7fa5001091a7815df101a76b6fbe811f0d28996226ed6fd222a28e7a6e47a084c29631992710e0e35edcafef296d18a1d447eed0d9c9698dd87dc7e5e1de21bab8bba7bf0012a2c99a96f6166ee7936298a7c50ff1266a5d9f31f3968095ea48eec2365303531e2a95b3301802f0a3f5b48ebb38929b2390c2c6218187b84453d6d935d834fc01610ca87c10000075f301023698a9e345ba747806b56d02989a5cd9f5d8c2673a5f7a0cd27304115d8585270000000000000000000000000c6c5340cf09b9d362f29bb695a1aee5cfcce81d01477b4d5287f20780541f4182f1c6cfb2b54153633d41a2e63ebffef94bc7d34e09000000000000000000000000000000000000000000000000000011a8df633a00
