### ISSUE TITLE
Tokens stuck in wormholebridge

### ISSUE THREAD

**Issue by llouis123** [solana-labs/oyster#424]
Hi,

I sent USDC on Sol to BSC, which turned into wormhole tokens.

Went to send them back and it doesn't look like they've gotten back into my Sol wallet?

https://bscscan.com/tx/0x2be21ff11e40a6728fefa0bf21d1e135dd50cb57028fd990c14a5879ad3cd1c8

Thanks,

**Comment by leoluk** [comment]
This repo is for Wormhole v1's UI, which does not connect to BSC.

See here for Wormhole v2: https://wormholenetwork.com/
