### ISSUE TITLE
v1.wormholebridge transfer error

### ISSUE THREAD

**Issue by barducci** [solana-labs/oyster#425]
https://explorer.solana.com/tx/5KSPQW4RMdCjr68gHCnJru8S9Cg7vamMW2Zk6Cr4jCMiBmrLQyghEGZCd3QMKwUuJCJXvYQoPtC6WdfWC1ZnNHAb

**Comment by leoluk** [comment]
It says `Error: insufficient funds` so presumably you do not have enough SOL to pay for fees?

**Comment by barducci** [comment]
This is not the issue since 900 USD worth of SOL is in the Phantom wallet. Also, if this had not been enough then DAI would have stayed in the wallet. The situation now however is it is somewhere I cannot access.
