### ISSUE TITLE
v1 wormhole problem - Tokens vanished

### ISSUE THREAD

**Issue by kennitfarseer** [solana-labs/oyster#426]
Transferred V1 MM tokens from Sol (phantom) to Metamask, but rejected the transaction after seeing the fees. After that my MM tokens have vanished from any wallets.
Tried the pinned post method but didn't really understand. 

Transaction: https://solscan.io/tx/2rJWY1PE5Wjdpx7JSWE7cmZZFTkX2WzZAneGjsZunpH6TnkgtjPRvHK1hgPKiRZSzcrG3aJgQqA2cShnB5ha5wyG

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading https://v1.wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If v1.wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

Note that Wormhole v2 was recently launched on wormholebridge.com, which fixes the bug you encountered! You will still have to use v1 to complete your in-progress transfer.

You can also try using the third-party https://www.interstellar.tk site to retry your VAA submission.

---

Digest (for reference only): 2862f3e460fc177cb46ae150f953fd7e60a2fc817c2c67fb541efdafa5180dac

Signed VAA bytes to submit to the contract:

> 0x01000000010d00d58095197660a8d2c1a4c406767e4bde0c4de739868eef323f25d0e6e33c99d97c1a806b0f0db734e709b00aa1e35d0948287fe3b261965c5926290b762a0eb90001d25a51df7ca2994dac25a304299ab039b3fc6e006616f5f71dae52320cf8433132a18effdf1efb28d9e291fe3887b105e48e82c20d4ea984a1c084c2343ad3d400033d45b0fc62689a97633ad072140ee18626d4261d9e41e719d191282cd62357d16d721f06ff900f52001f22d8b7cef4c5c74b79eb54acf8a63ba2a51a76ca240b0005a43e5f4dc97ff3f36e8a01d808da6d9cd5499efab0e90a2aeaf55eb512d749af2f8efb6dd3edc81a18221ac4b06346dfb3c8e9f3032fe045ffbd3770485ea1870106fb933668d39dbc6ab636160e298871ad720d6759bb33f0b082f05d235dddb36f67b570d4698bfe14d7be30b8fd3966710530809390b9e9af9758ea5f7692bf180007212d093f1803756db502fb8c38cdb1c0d21406bf01c3d8b4a0ae2a1694cc15a5265f89f26e6223b7ac3cd157e6bf00344daee54850903386e6355009acc63133010ad88c48b540257120d139b6ca581a4c1c5f8af2c9d7ffe5e43324611d32df991d7a054a0b459260c6c26ca7ba49dc66cce12d5d8a468e1068783888ea5f1bb5b0000b400bcc0838419bd551984f340ab9a111e613b1233e5313817b0a835bef7d64f070cc4e8ec42b64d115c4cba621523ca0f085ca49ceef53d4d8ceb408aaa4f34c010c2fb242d9e6168af7fe7fae302dca26ec7e72f7baaf9fa2884a8f11813e0928646ff6a96971f43730760a8194d0e81dcf3aaaabf9ed84538431c164b42ba955b9010d08f8a95ddeb602510d870507acc90ca7bae63fd1b3aa795bd0cf30eafa82d65163a1c1f710a648c3cb993be802e652078af411d07a298a4db045ed91ad5f26f400104f57befef4942004498e609b037c787a1f6dd5c6efdab9f53a25ec3785a10e910dec41c94d6966b2fb7b7fbac48e0f143133385b8141ae61cea547c4bed634c400117c49a0809e5962f142b404c313c27791eab0278f94d4a3559b397160ced8247817cedf1bfe336357856edc1ee665f4c4b38089b36644c60b0c22e03206dfe60400122317b59277d87f770e1ffedd43c84a02b4ff3c13bef05951f52178915219877b20211584b787bed28fe0115c0402876d28289dfe91515b7b5623334daf251bbe006192b36f10000040c6010292002562d5a6563cd3aeaee4254377d4e90986c56bbc191796f875ab4bd9b742000000000000000000000000b2c7a4056f9297bee96330f2c03c37096afe5bfb020000000000000000000000006b4c7a5e3f0b99fcd83e9c089bddd6c7fce5c6110900000000000000000000000000000000000000000000000000000004fdec7000
