### ISSUE TITLE
v1 wormbridge problem

### ISSUE THREAD

**Issue by bagz11** [solana-labs/oyster#438]
I made a trans from Solana (wUST_V1) to ETH (UST)

**TX:**
`5ATSSMD2Dy8PUoiorQzDrrtrGguDozDSNJMvTFZoqWaNqFMfWoMzdoMtnqYdXV4ca2qzYUEyZfaKZkhtZZYxsja3`

but I cannot complete transaction. Status on worm v1:
`Executing Solana Transaction`

<img width="284" alt="Снимок экрана 2021-11-25 в 19 12 53" src="https://user-images.githubusercontent.com/92082860/143486880-9d090718-55c7-45b1-bc3a-64a4b7aa48fc.png">

i tried using **intersellar.tk** many times, but VAA not valid.

<img width="1349" alt="Снимок экрана 2021-11-25 в 19 12 09" src="https://user-images.githubusercontent.com/92082860/143486799-ea8c6aac-eb0b-4e2c-989c-92a30206192e.png">

<img width="313" alt="Снимок экрана 2021-11-25 в 19 14 21" src="https://user-images.githubusercontent.com/92082860/143486990-00bb21ed-033a-4e1d-ad6a-349614707ac1.png">

**Update:** 
I researched this issue with a familiar Solana programmer. He said that **VAA code was not generated** in this part transaction:
[https://solscan.io/account/BdYnEy25r3WvMDJbbjejosyvWHDDgPe1ERMifsrVi8HW](https://solscan.io/account/BdYnEy25r3WvMDJbbjejosyvWHDDgPe1ERMifsrVi8HW)

There should be a second transaction, which serves as: **posting VAA**

For example, other successful transaction:
[https://solscan.io/account/5U57pCe66Q6bHAzJ14orePZXERQSrTyCxTUj1QvyPskX](https://solscan.io/account/5U57pCe66Q6bHAzJ14orePZXERQSrTyCxTUj1QvyPskX)

![Снимок экрана (3)](https://user-images.githubusercontent.com/92082860/143677718-dca489c5-c899-4ed5-9b8d-0c3a13d355ea.png)

Admins, pls help!
 @leoluk @yamijuan @bartosz-lipinski

**Comment by bagz11** [comment]
I think if you wrote a guide, how and where find VAA, it would be useful for many users Worm_V1. thanks!

**Comment by leoluk** [comment]
> 2021-11-27T17:19:15.642Z        INFO    wormhole.root   processor/observation.go:221    aggregation state for VAA       {"digest": "e3d73bb65c39f5ac1b42c07866a10f55831637ce90e7b76aeeb6296e4266c9e1", "set": ["0x187727CdD17C8142FE9b29A066F577548423aF0e", "0xE4276d2Ef965B37A492C5F0f85e9A558f82895BD", "0x854E8bE1eE471e70a152b3FBB093057efBb9e20F", "0x43f98818f1f0e93A921C2A74ED868213946A3580", "0x79071C82011B4a542C7d67f290Ef4181CE6B2b0f", "0x7580aA7e036dC199bF0E152C71004716AE0AA747", "0xe7aF00E4B5F69B8E8e49adBE7b1A2b6BDd81f346", "0xc155a290149Bb2f58332abA8DC31217df483501e", "0xF73c0e6f9A242B3564F9e65Fbd94Fcbc332a0deB", "0x1Fca1307C7BeEf596f209cf393f3d50d41e4a0F9", "0xf51a742452E9c2B4bD131a934C10f97b80455669", "0xe0718fca4Dc271f4EF43Ff624a6b730A339eF104", "0x1bb88a04DDa307Bc4f5e97c4856c068D1A4182a8", "0x5cF8ca288D9077160Ff9D6583b63aa20EFF40B7d", "0xDe2E046412ebcc6563831AA7A9B2104E0c58B351", "0x4ed7ABB1408F91058BFeDac3CAeCB03F8ec22C1b", "0xE3727bBc8342F631eC9A20d8A6FB44fe97C6dFcd", "0x9F09C8E49757486e98887b49373620290D963729", "0xe263fDFeDF000121046578253312861e83f28bD5"], "index": 1, "aggregation": [true, true, true, true, false, true, false, true, false, false, true, true, false, true, false, true, true, false, true], "required_sigs": 13, "have_sigs": 12}

Consensus failure, will require network upgrade to fix.

**Comment by bagz11** [comment]
> 

Leopold, many thanks! I used interstellar.tk again, after your actions. And now i was able to generate valid VAA and get the transaction on ETH network. problem solved.

P.S. Guy in issue #437 have a same problem.

**Comment by leoluk** [comment]
Yep these two transactions got stuck - credits to the guardians who promptly responded yesterday :)

**Comment by xiaowang158** [comment]
@leoluk PS Guy in issue https://github.com/solana-labs/oyster/issues/511 also have the same problem
