### ISSUE TITLE
weFTT stuck in Wormhole, would like to put it back into Solana (Phantom Wallet)

### ISSUE THREAD

**Issue by PragmaticMoose** [solana-labs/oyster#441]
Looking for assistance.  I was trying to convert my FTT on my phantom over to ETH so I could get it on an exchange.  After seeing what the ETH fees would cost to redeem, I changed my mind and would like to put it back on Phantom.  

Signature:  FbBaEa6qExuBozdgDZi8uxcvG5PLa2tnAHAYvYGBej1hiLz4W5JtGcSR1VUgjBaFosPAYNHJsbRfUhrjtnvgsCs

Block #: 108815643

**Comment by suzzax** [comment]
Hello, 
This is a Wormhole V2 enquiry - once you send the tokens to the target chain, it is not possible to cancel the transaction. You'll need to redeem the tokens on Ethereum by following the redeem process outlined here: https://docs.wormholenetwork.com/wormhole/tutorial-recovery-workflow . Please feel free to reach out to the wormhole discord if you have any v2 support enquiries: https://discord.gg/wormholecrypto . Thank you!

**Comment by suzzax** [comment]
I can see the tokens have been redemed, issue can be closed, thank you!
