### ISSUE TITLE
v1 wormholebridge: wBTC transfer from SOL to ETH lost after rejecting eth gas fee 

### ISSUE THREAD

**Issue by milensinan** [solana-labs/oyster#442]
Hi team,

I used V1 to send back wBTC that I had originally sent from ETH to SOL.

However, when sending back to ETH, gas prices were momentarily quite high (surprise) and I had to reject the transaction on Metamask, afterwards the wBTC was nowhere to found.

Here is the transaction:
https://solscan.io/tx/2rVBAp1Xrf99A9LpnemxtLk8zHA1VGnNUHDQx1i7pbWykvYKWpXG3pYD1Uw5fwZr5Q4dpxXbUmXytM7jwmFA4k1r

Please let me know how can I resolve this.
Already contacted Wormhole support, but they couldn't help.

This is my original from ETH to SOL transaction: which has worked as expected.
https://etherscan.io/tx/0xc406ec313923bfe25bbe139dcdc962e164e25d31e7918b1716bf276eeef3f72d

**Comment by Zer34** [comment]
Try https://www.interstellar.tk/ that helped me with similar issue

**Comment by milensinan** [comment]
> 

thank you so much, that sorted me : )
