### ISSUE TITLE
My tx stuck at "sign the claim": wormhole v1 ImBTC token from SOL to ETH

### ISSUE THREAD

**Issue by Zer34** [solana-labs/oyster#445]
I used https://v1.wormholebridge.com/#/move?from=SOL&token=IBBTC
To move IBBTC from Solana to Eth
https://explorer.solana.com/tx/4sNgbUDNjKpkXfyM9RZhYJTJMkvtbNTLbnk1nsfxUDKuShKxdK7BQjvvwXQjL1GLg6hZNFn39JR32ndDSceGopT7
Everything was going fine
But when I received messages "sign the claim"  on the network Eth
I found out that my metamask was connected to another network, I changed network to Eth in metamask
but window with a transaction to receive coins did not appear on metamask...
after that I refresh the site, but it didn't help either
At the moment, I do not see my transaction anywhere on the site, and accordingly I cannot make the claim tokens in the Eth network or return them back to the Solan network.
Thank you for your help.

**Comment by Zer34** [comment]
Also I tried to clear cache and reloading v1.wormholebridge.com, it didn't help

**Comment by arthurOmanko** [comment]
if yet not solved, you can see past closed tickets on this issues.
a solution has been provided by also developer.
i hope your fortunate.

**Comment by Zer34** [comment]
> if yet not solved, you can see past closed tickets on this issues.
> a solution has been provided by also developer.
> i hope your fortunate.

Thanks bro. It helped
