### ISSUE TITLE
Bridge from Solana->Ethereum

### ISSUE THREAD

**Issue by m4t123** [solana-labs/oyster#455]
Hey there ! 
I tried to bridge wwt/rin from solana to ethereum via the v1 wormhole and the transaction got stuck. Happened already a few months ago, but no problems after your help. Now it happened again, and interstellar doesnt work to get the VAA ( transaction errors with "invalid VAA") . Clearing cache also doesnt help.

Help is very much appreciated, i hope its not lost. I wont do it again, i ´m too anxious now :) 

The transaction is 31ysPNmE6s54Pcu6EDEsPVbUJS75U64wzjqBWiuVTAbZGrvRP5MGXk24diBtvv46cEfsAVLxgAWpXyRcHVP6eNAv

https://solscan.io/tx/31ysPNmE6s54Pcu6EDEsPVbUJS75U64wzjqBWiuVTAbZGrvRP5MGXk24diBtvv46cEfsAVLxgAWpXyRcHVP6eNAv

**Comment by m4t123** [comment]
interstellar finally worked for me . closing it

**Comment by Rachit2323** [comment]
Hi , did you completely done bridge from solana to eth?
