### ISSUE TITLE
PLEAE HELP ARE MY TOKENS LOST

### ISSUE THREAD

**Issue by cohenemc** [solana-labs/oyster#458]
Was my first time using wormhole i did not wrap my USDC or anythign i just connected phantom and meta mask without wrapping the usdc and sent it to my ehtereum address. I quickly realized this was a mistake so i did not click the redeem button yet. What is the next best step? Did i lose my tokens forever? Please help

**Comment by leoluk** [comment]
Wormhole v1 or v2?

**Comment by soup24** [comment]
V2, I think.
