### ISSUE TITLE
Trying to recover tokens

### ISSUE THREAD

**Issue by soup24** [solana-labs/oyster#460]
I need help.  I used sollet wallet to send 3,000 USDC to an erc-20 address.  My metamask popped up, but I did not have enough gas, and I canceled the transaction.  The USDC isn't in my wallet.  Is there any way for me to recover the tokens?  I have tried entering the transaction id on the redeem tab in the wormhole, but it says, Cannot read properties of undefined (reading 'replace')

I don't know enough to know what I'm doing.  I think the transaction was through: https://wormholebridge.com/#/
because that is the site my metamask connected to.  Maybe this is wormhole V2 because Interstellar doesn't seem to work.

I should have enough gas in my wallet now, but don't know how to proceed.

Transaction:
https://explorer.solana.com/tx/4MUVaTQj2ctpUbDj65PPKqKJvPvTUKjJQkUVDWTvx2oyrnWKEuyWEz8mzzZrniaocMU9hiuSMYAq2mQHURbJWvQ9

thanks.

**Comment by soup24** [comment]
Can someone help me?  We need this money to live on.

**Comment by suzzax** [comment]
This transaction was not done using Wormhole, you'll need to contact Sollet/serum to resolve this. Thank you!
