### ISSUE TITLE
Wrapped Sol Stuck in the Wormhole

### ISSUE THREAD

**Issue by robintanner** [solana-labs/oyster#467]
Hey there my wrapped sol is stuck in the wormhole and I cannot redeem on wormholebridge.com

Wrapped sol - https://finder.terra.money/columbus-5/address/terra190tqwgqx7s8qrknz6kckct7v607cu068gfujpk
Transaction ID - 65PYsQQZ56hi2WCK7WafZnJ5oRDbWomeZfDYwrVApodYnnXCASMNEFUwKaPSpmUmRBz3ZdWExB5JC2rPMoPjCGdr
phantom (source) = 63219BXbqpr5Vpv4ToE4d6Hm4ZbPUaCmMyBu9TQMpMLc
terra station (dest) = terra1hkm7cdwnuxzstl0udk350q8vthps645lthape4

This is the error I get on the wormhole site. 

rpc error: code = NotFound desc = rpc error: code = NotFound desc = account terra1hkm7cdwnuxzstl0udk350q8vthps645lthape4 not found: key not found

**Comment by suzzax** [comment]
Hey @robintanner  
You'll need to have both ust and luna to fund the transaction on Terra. Once you have the funds, you can follow the redeem process here: https://docs.wormholenetwork.com/wormhole/tutorial-recovery-workflow

**Comment by leoluk** [comment]
Assuming this is fixed - please complain otherwise.
