### ISSUE TITLE
Unable to redeem tokens

### ISSUE THREAD

**Issue by blackgoblin7** [solana-labs/oyster#469]
I sent WETH from AVAX to ETH, and the tokens have been stuck in ETH bridge, unable to redeem. 

Source TX: 0xd9030677a28d12a428af868873338f5ea54b7b53bdfe205db90e055e84ef5f05

I am unable to redeem the tokens from the ETH side.

**Comment by suzzax** [comment]
Hello! Would you be able to try the redeem process using the transaction :)  https://docs.wormholenetwork.com/wormhole/tutorial-recovery-workflow . Please feel free to reach out to us if you have any further support enquiries on our discord : https://discord.gg/wormholecrypto

**Comment by leoluk** [comment]
Assuming this is fixed - please complain otherwise.
