### ISSUE TITLE
Unable to redeem Wbnb tokens from bridge

### ISSUE THREAD

**Issue by YMEIJER** [solana-labs/oyster#474]
Hi,

I cannot redeem my Wbnb tokens from the wormhole bridge. The TX hash is: 0xe5cc379b1c6679146510f07229d1ce8b4245f858e7477653199967e2e35b4938. 

Amount is 0.25 BNB. I tried everything, all transaction are going fine, until te last transaction to put WBNB to my Solflare wallet.

Kind regards,

Youri

**Comment by leoluk** [comment]
IS this for Wormhole v1 or v2?

**Comment by suzzax** [comment]
I can see these tokens have been redeemed. Issue can be closed, thank you!

**Comment by shimbannft** [comment]
How did you do it? I can't redeem my token

**Comment by shimbannft** [comment]
@leoluk can your help me with my 5 BNB missing in wormhole token ERC20 here's their contract address in etherscan 0x418d75f65a02b3d53b2418fb8e1fe493759c7605

**Comment by VFMCCrypto** [comment]
I can not redeem tokens from Osmosis to BSC. Qt: 0.1WBNB. Tx: a39701a1d66db901c200731ab8570079ad0a77e56117b051f4c5a138caf03091
