### ISSUE TITLE
Hi.  I'm sorry to ask again.  

### ISSUE THREAD

**Issue by soup24** [solana-labs/oyster#475]
I think what I am looking for is the VAA for this transaction.  I have tried interstellar, but I think I was using V2 of the wormhole.  It was the first time I've tried transferring USDC from Solana to Coinbase and messed up.  It is a lot of money for us, and it is stuck in limbo or lost forever.  Is there anyone who can help?  Thank you.  

https://explorer.solana.com/tx/4MUVaTQj2ctpUbDj65PPKqKJvPvTUKjJQkUVDWTvx2oyrnWKEuyWEz8mzzZrniaocMU9hiuSMYAq2mQHURbJWvQ9

**Comment by soup24** [comment]
Hi.  I'm sorry for bothering you guys.  SS on Discord helped me.  My transaction went through Serum not your wormhole.

**Comment by suzzax** [comment]
Hey guys, please close this issue. thank you!
