### ISSUE TITLE
UST Stuck At awaiting completion on solana Via V1

### ISSUE THREAD

**Issue by amol3335** [solana-labs/oyster#497]
https://etherscan.io/tx/0x58bfaac91b9f764f9e2b47f3ea09d7f16281da64982e665f8fd9095c9c96ba8f
Please resolve the issue.

**Comment by leoluk** [comment]
Seems like the network failed to submit this one due to Solana timeouts. Retried manually: https://explorer.solana.com/tx/4zNdUbjaiCc5x5aDC9WGN2y969Zp4Zx7HCbjXyNA5QzYZpo2Ewpc6fsiURDaXzofC3sXFT183aQdZRpHy2ET422z
