### ISSUE TITLE
tuUSDC (Solana) to USDC (Ethereum) v1 transfer stuck, interstellar drops first "0" after "0x" address, please help!

### ISSUE THREAD

**Issue by joelyer** [solana-labs/oyster#499]
Hello, I used the v1 bridge in error to move USDC from Solana to Ethereum.

The funds are just sitting in the wormhole v1 contract.  How to I get them sent to my ETH address or sent back to my Solana address?

The transaction id is 5iZrDmUxwTmRUwTPWE9SgzR6GVezD5rwyKfspkX5sCuMuajEY9LzH2uV9KzbjZGtWgj66Nj6DLMRHD6FDdUvP87K

I tried interstellar.tk but did not work.  On interstellar, it is saying my target address does not match my ETH wallet address.  The target address that interstellar is producing starts as 0x2CD1 but my wallet starts with 0x**0**2D1, with a 0 right after the x which is why it probably doesn't work.

Thank you.

**Comment by joelyer** [comment]
@leoluk  Hi, I believe you mentioned that something was in the works a few weeks ago about recovering funds stuck on v1...is it ready now?  Been stuck for almost two months now.  Would love to continue using your lovely platform but all my money is stuck.  Please and thank you in the most respectful manner.

**Comment by leoluk** [comment]
We recently went through all old Sol -> Eth transactions and submitted them (even paid for gas!). Was yours not included?

**Comment by joelyer** [comment]
> We recently went through all old Sol -> Eth transactions and submitted them (even paid for gas!). Was yours not included?

Nope, just checked, still sitting in the wormhole v1 contract...and no wallet activity in my ETH wallet.  I see some "out" transactions in the wormhole v1 contract 8 days ago but nothing relating to what I was transferring.

**Comment by leoluk** [comment]
There's no liquidity for v1 wrapped USDC. You need to reverse the transfer by bridging back to Solana.

**Comment by joelyer** [comment]
> There's no liquidity for v1 wrapped USDC. You need to reverse the transfer by bridging back to Solana.

Fair enough.  I assume i use the v1.wormholebridge.com again?  Will it get stuck again?

If successful, I assume I will have my original funds back on Solana to which i can use the correct portal bridge?

**Comment by joelyer** [comment]
I kicked it back to Solana and it worked! You are a GOD leoluk! Thank you much!
