### ISSUE TITLE
Wormhole Solana to Terra VAA issue / Network Consensus

### ISSUE THREAD

**Issue by ndankajapa** [solana-labs/oyster#502]
Hi there,

My transaction got stuck at "waiting for wormhole network consensus" when I was transferring UST from Solana to Terra. The tokens are stuck in between networks.

When I try to redeem from the transaction signature, Wormhole says "requested VAA not found in store"

Any ideas to retrieve my tokens? Thanks.

Here's the signature: 

https://explorer.solana.com/tx/5k1XLh4X2YcmCH3Q8aijhFdjKbYhPZgjqErxLjFSqY3bfPQTFryPHejtFAnny4ZLD2nf7ppQUyxrSdKHLULifh8u

**Comment by leoluk** [comment]
See Discord linked on https://wormholenetwork.com for v2 support, this repo is for the v1 UI only
