### ISSUE TITLE
USDC (Solana) to USDC (Eth) Wormhole stuck, Please help!

### ISSUE THREAD

**Issue by J-Hunta** [solana-labs/oyster#527]
So ive tried to swap USDC from my Solana wallet to metamask using wormhole website
Now I cant see USDC in either wallet, and not sure what to do next
this is the solscan link
https://solscan.io/tx/DPUDvFJzhwDQo1cEncPEB5tVkUnuNFKGCziEE4w3Sx2Mt7ztawtaJGEgeDc3zJUUWPHAS74YUYKbVJQSM1YbNZD

Phantom wallet:  2zAUFDBQDj6GeD4YRutsLk3qCN5dWPoKSJZmsVpDGMBC
supposed to end up at this metamask address:  0x1f78D430A5005a72ab45f4E32f619Ea02eA1aC67

any help is apricated! cheers

**Comment by J-Hunta** [comment]
I've tried using Interstellar but was unable to recover anything

**Comment by ckeun** [comment]
can you try to redeem again?
