### ISSUE TITLE
USDC token bridge problem from SOL to ETH

### ISSUE THREAD

**Issue by WilliamTheWhale** [solana-labs/oyster#531]
I have a tx that is stuck. I was sending usdc from SOL to ETH and the bridge transferred it out of my SOL wallet rj7U  but never to my Metamask Eth wallet 8B80. 

My tx id is 3VLgffQjffXW3Ue467wy5DbeocZ777HSpv18yGTDuBM7KBi391ahdvXowUtP63Q6RwYq2N9mNirdyvSyYLcJ9Z5p 
The wormhole wallet that has it is 9zyPU1mjgzaVyQsYwKJJ7AhVz5bgx5uc1NPABvAcUXsT

**Comment by ckeun** [comment]
can you try to redeem it again using interstellar.tk?

**Comment by WilliamTheWhale** [comment]
I tried and it submitted VAA tx. on ETH network here is the tx 0xa1a333d7b06a331b8484a88e787addf17b1674580c2e5764e7cc36ad1189bc4c

**Comment by WilliamTheWhale** [comment]
Hello again, I now have a WWT token considered to be a V1 wormhole token for my USDC. I am having trouble converting it to regular USDC.  Where can I convert?

**Comment by ckeun** [comment]
it looks like you have v1-wrapped **native solana USDC**. so if you want an unwrapped version of USDC, you have to send it back to solana through the v1 wormhole... 

if your ultimate goal is to get ethereum native USDC then once you send the v1 wrapped USDC back to solana.... you can try using this tutorial: https://docs.wormholenetwork.com/wormhole/tutorial-how-to-send-usdc-from-solana-to-ethereum

and the [portalbridge.com](https://portalbridge.com/#/transfer)

**Comment by WilliamTheWhale** [comment]
I just did. I read it on Wormhole discord. Thanks and I'll close the ticket.
