### ISSUE TITLE
soSushi stuck bridging solana-> eth, Interstellar.tk transactions won't go through 

### ISSUE THREAD

**Issue by nodeseek** [solana-labs/oyster#537]
I have a series of failed transactions trying to bridge sushi from solana to eth. I originally bridged the tokens last year from solana to eth using the v1.wormholebridge. The transactions successfully completed on solana, but never executed on ethereum. I tried to use interstellar.tk several months ago, with failed transactions. Then I recently tried using interstellar.tk again today, with the same failed results. Each time, interstellar.tk successfully detects the solana transaction and proposes an ethereum transaction which I unsuccessfully try. 

My failed transaction history can be seen at 
https://etherscan.io/address/0x505d416cc681a5c9a72b8de33e943e8be2c26510
The most recent failed transaction was at https://etherscan.io/tx/0x70816625d4749eeb952796f1c2ad6d91202d2ffa362bb7df822ebea985527ec3

I'm a worried about losing the tokens with the upcoming bridge deprecation and would greatly appreciate any pointers on how to proceed. Please help!

**Comment by ckeun** [comment]
what was the original solana transfer transaction id?

**Comment by nodeseek** [comment]
hey thanks for taking a look! the tx id was [JhNkkxUFqNLvAQge9nC7KYAHjcpiDhKcXEuejNbBzRGSMRY5C9yzh7crsmdfeY3hc22ueaKyqRLAXoEvFpPGeSD] (https://solscan.io/tx/JhNkkxUFqNLvAQge9nC7KYAHjcpiDhKcXEuejNbBzRGSMRY5C9yzh7crsmdfeY3hc22ueaKyqRLAXoEvFpPGeSD)

**Comment by nodeseek** [comment]
Ah okay, in that case I still need to complete the failed transactions on Ethereum, before I have access to the wrapped tokens to then send back to solana. Would you have any thoughts on how to complete the failed ethereum transaction https://etherscan.io/tx/0x70816625d4749eeb952796f1c2ad6d91202d2ffa362bb7df822ebea985527ec3? I tried interstellar.tk a couple times but none of them worked. Is there another transaction I can send to the wormhole contract on eth to get access to my wrapped tokens?

**Comment by ckeun** [comment]
yeah wasn't sure why you were getting an "out of gas" error. it looked like you had plenty of ETH in your wallet. anyway, i ended up redeeming it for you when i tried to debug your issue. https://etherscan.io/tx/0x3f2da12639debcd5167ede65ef801b7f2fbc844cd190cf7d3c1fb172c6f00968
so you should have the v1 wrapped token in your wallet now.

**Comment by nodeseek** [comment]
Wow thank you so much ckeun!! That's incredibly generous of you, really appreciate the help (and gas).
Just to make sure I don't mess up bridging again, would I send WWT back to Solana through https://v1.wormholebridge.com/#/move?from=ETH&token=SOL? The bridge UI form correctly shows my WWT balance as soSushi

**Comment by ckeun** [comment]
Yup, exactly. 👍

**Comment by nodeseek** [comment]
Thanks again man, transfer just went through!
